### ISSUE TITLE
CSS targeting for tables no longer works (or not as easily)

### ISSUE THREAD

**Issue by Jellby** [sphinx-doc/sphinx#1720] opened 2015-02-12 17:01 UTC
With version 1.2 I was using some specific CSS rules (using table#label selectors) to target selected tables and style them (adding rules, setting column widths, alignments...).

I've now updated to 1.3b2 and my trick no longer works, because what used to be, in the HTML output:

```
<table id="label">
```

is now:

```
<table id="id1">
<span id="label"></span>
```

I realize this needed if there are several labels, and I can only modify my CSS selectors to use "id1" instead of "label", but then I'd have to change everything if I move a table. Moreover, this code seems to be not quite valid, I don't think you can have a naked span inside a table, and at least Firefox moves the span before the table... Could something be done to have static and predictable ids for tables (and everything else).

**Comment by shimizukawa** [comment] 2015-02-13 04:33
It depends on the change 7cd470f59a0710f7ad4d5a94c10cd907aa135af0 for numref feature.
`self.document.note_implicit_target(node)` for a table node causes this behavior.

@tk0miya do you have any idea to keep previous html output?

**Comment by shimizukawa** [comment] 2015-02-20 14:26
@Jellby the behavior is not only caused by numfig feature. It will happen on several cases.
I recommend that you would use `:class:` option to assign class attribute to tables.

```
.. csv-table:: title
   :class: label

   1, 2, 3
```

Or use rst-class directive to assign a class attribute to the next element.

```
.. rst-class:: label4

=== === ===
1   2   3
=== === ===
```

**Comment by Jellby** [comment] 2015-02-20 15:19
Thanks, that could be a workaround, although it's not as convenient (now I'd have to add a label and a class, for what is essentially the same information). For the invalid `<span>` inside `<table>`, see #1733.

**Comment by shimizukawa** [comment] 2015-02-20 22:27
>  For the invalid `<span>` inside `<table>`, see #1733.

Indeed, it's a invalid output. I commented about it to #1733.

**Comment by shimizukawa** [comment] 2015-02-22 14:01
@Jellby you can provide id for each type of table as:

```
.. _label1:

.. table:: simple table
   :name: simple

   === === ===
   1   2   3
   === === ===

.. _label2:

.. table:: grid table
   :name: grid

   +--+---+---+
   |1 |2  |3  |
   +==+===+===+
   |1 |2  |3  |
   +--+---+---+
   |1 |2  |3  |
   +--+---+---+

.. _label3:

.. csv-table:: csv table
   :name: csv

   1, 2, 3
```

In this sample, `labelX` is not assigned to table element as ID. However all tables have ID that provided by `:name:` option.

see also:
- http://docutils.sourceforge.net/docs/ref/rst/directives.html#name
- http://docutils.sourceforge.net/docs/ref/rst/directives.html#table

IMO, behavior of label becoming ID had just happened in your use case.
The `:name:` option is proper way to provide ID for table (and other elements).

**Comment by Jellby** [comment] 2015-02-22 19:29
Ah, I didn't know about the `:name:` option. Yes, that's probably what I should use, thanks for pointing that out.

**Comment by shimizukawa** [comment] 2015-02-22 23:20
Thanks for your confirmation!

**Closed as completed by shimizukawa** 2015-02-22 23:20 UTC
Labels: closed:wontfix, builder:html, internals:environment

**Comment by Jellby** [comment] 2015-02-25 10:19
`code-block` does not support `:name:`, and how would I use it for a simple table with no caption like this?:

```
.. _label:

=== === ===
1   2   3
=== === ===
```

EDIT: It seems in this case the label is simply used as `id`, so nothing to change here.

**Comment by Jellby** [comment] 2015-02-25 10:49
And a `:name:` in `figure` results in (1): the `id` being applied to the `<img>` rather than the `<div>`, and (2): undefined label warning from sphinx.

**Comment by shimizukawa** [comment] 2015-02-25 15:23
simple table has the ability, please see a comment I posted.
https://github.com/sphinx-doc/sphinx/issues/1720#issuecomment-75436709

For the `figure`, I need more inspection.
@Jellby if you have a time, please create another ticket for that.

**Comment by Jellby** [comment] 2015-02-26 07:55
With "simple table" I mean a table that does not use the `table` directive, as in my example above. But I noticed that in this case the standard label works as I want, so that's OK. For the figure (and code-block), I've created #1742

**Comment by shimizukawa** [comment] 2015-02-28 01:29
@Jellby docutils documentation says the "table" directive is used to create a titled table, to associate a title with a table. It also associate id and class. IMO, it's only way to provide ID to simple table.
http://docutils.sourceforge.net/docs/ref/rst/directives.html#table
