### ISSUE TITLE
'ascii' codec can't decode byte 0xe5 in position 0

### ISSUE THREAD

**Issue by sonymoon** [sphinx-doc/sphinx#3908] opened 2017-07-04 08:03 UTC
Subject: make html  cause exception

### Problem
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)

#### Procedure to reproduce the problem
```
.. figure:: test.png
    :scale: 40 %
    :align: center

    figure caption

that was my script, when I add a caption after a blank line, I couldn't make it

type make html 

```

#### Error logs / results
```
- call trace
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/Sphinx-1.6.2-py2.7.egg/sphinx/cmdline.py", line 306, in main
    app.build(opts.force_all, filenames)
  File "/Library/Python/2.7/site-packages/Sphinx-1.6.2-py2.7.egg/sphinx/application.py", line 339, in build
    self.builder.build_update()
  File "/Library/Python/2.7/site-packages/Sphinx-1.6.2-py2.7.egg/sphinx/application.py", line 339, in build
    self.builder.build_update()
  File "/Library/Python/2.7/site-packages/Sphinx-1.6.2-py2.7.egg/sphinx/builders/__init__.py", line 328, in build_update
    'out of date' % len(to_build))
  File "/Library/Python/2.7/site-packages/Sphinx-1.6.2-py2.7.egg/sphinx/builders/__init__.py", line 394, in build
    self.write(docnames, list(updated_docnames), method)
  File "/Library/Python/2.7/site-packages/Sphinx-1.6.2-py2.7.egg/sphinx/builders/__init__.py", line 431, in write
    self._write_serial(sorted(docnames))
  File "/Library/Python/2.7/site-packages/Sphinx-1.6.2-py2.7.egg/sphinx/builders/__init__.py", line 440, in _write_serial
    self.write_doc(docname, doctree)
  File "/Library/Python/2.7/site-packages/Sphinx-1.6.2-py2.7.egg/sphinx/builders/html.py", line 555, in write_doc
    self.docwriter.write(doctree, destination)
  File "/Library/Python/2.7/site-packages/docutils-0.14rc1-py2.7.egg/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/Library/Python/2.7/site-packages/Sphinx-1.6.2-py2.7.egg/sphinx/writers/html.py", line 57, in translate
    self.output = visitor.astext()
  File "/Library/Python/2.7/site-packages/docutils-0.14rc1-py2.7.egg/docutils/writers/_html_base.py", line 247, in astext
    + self.body + self.body_suffix)
```
- <public link of unexpected result if you have>

#### Expected results
<Describe what to actually do>

### Reproducible project / your project
- <link to your project, or attach zipped small project sample>

### Environment info
- OS: macOs 10.12.3
- Python version:2.7.10
- Sphinx version:1.6.2
- <Extra tools e.g.: Browser, tex or something else>

**Comment by tk0miya** [comment] 2018-03-18 04:30
Sorry for late response. I tried to reproduce this problem now. But I can't.
Can you still reproduce this issue? If you can, please let me know in detail.

Thanks,


Note: my procedure to reproduce:
```
# with python2
$ sphinx-quickstart -q -a author -p project test
$ cd test
$ (edit index.rst)
$ curl -L -o test.png http://via.placeholder.com/300.png
$ make html
Running Sphinx v1.7.1
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1 source files that are out of date
updating environment: 1 added, 0 changed, 0 removed
reading sources... [100%] index
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index
generating indices... genindex
writing additional pages... search
copying images... [100%] test.png
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded.

The HTML pages are in _build/html.
```

I guess the error is related with content because it was raised on generating HTML.

**Comment by tk0miya** [comment] 2018-06-16 15:44
I'm closing this now because unreproducible.
Please feel free to reopen if you still in trouble.

Thanks,

**Closed as completed by tk0miya** 2018-06-16 15:44 UTC
Labels: type:bug
