### ISSUE TITLE
the search results only display the file where the result is found and not the link

### ISSUE THREAD

**Issue by ArezkiT** [sphinx-doc/sphinx#6616] opened 2019-07-30 13:58 UTC
Hello everybody,

I use Sphinx v2.1.2 for the (offline) documentation of our software, when I do a search the result page only displays the pages in which the searched word is found, I absolutely need to display a link to redirect to the exact place where the word is found.
The expected result is similar to this one: https://docs.pylonsproject.org/projects/pyramid/en/latest/search.html?q=project=project.

Please help me with this.

**Comment by tk0miya** [comment] 2019-08-01 16:06
Please mark up your keywords with these roles and directives.
http://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html

Sphinx create hyperlinks for registered keywords only. It does not work for keywords in plain text.

**Comment by ArezkiT** [comment] 2019-08-02 08:31
Hello,

Thank you for you return, I'll test your solution and get back to you as soon as possible.
Thank you again!

**Comment by tk0miya** [comment] 2019-08-02 13:39
I'm closing this now. Because this is not a bug of Sphinx.
Please post sphinx-users forum in next time.
https://groups.google.com/forum/#!forum/sphinx-users

Thanks,

**Closed as completed by tk0miya** 2019-08-02 13:39 UTC
Labels: type:question, html search
