### ISSUE TITLE
4.1.0 regression: HTML logo or Favicon specified as file not being found on output

### ISSUE THREAD

**Issue by ViktorHaag** [sphinx-doc/sphinx#9438] opened 2021-07-12 21:26 UTC
### Describe the bug

If you specify `html_logo` or `html_favicon` values in `conf.py` as files (not URLS), then they won't be found properly in the generated HTML output unless you place the files in the configuration root of your source.

For fuller explanation, refer to merged https://github.com/sphinx-doc/sphinx/pull/9381.

### How to Reproduce

Place a logo for your HTML docs in a subdirectory below the configuration root of your source files (like `_static/logofile.png` for example).

Build your docs as normal. Your `logofile.png` will get copied into the output tree's `_static` subdirectory as expected, but your generated HTML will refer to it as if it were in `_static/_static/logofile.png`.

**Workaround**. Placing your project's logo image and favicon file into the configuration root directory so that your `html_logo` and `html_favicon` config variables have no file path to the files is a workaround until a fix is merged.

### Expected behavior

When referring to your logo or favicon files by file path in configuration, the generated HTML output should seek to find them directly in the `_static` subdirectory in the output tree as expected.

See attached test.zip project.

[test.zip](https://github.com/sphinx-doc/sphinx/files/6804457/test.zip)

### Your project

See Test project attached in Expected behaviour

### OS

MacOS 11.4

### Python version

3.9

### Sphinx version

4.1.0

**Comment by tronical** [comment] 2021-07-13 06:53
I've submitted a merge request (#9440) to try to fix this, along with a regression test. Could you try and see if this fixes your setup as well?

**Comment by PhilipMay** [comment] 2021-07-13 08:42
I have the same issue with the 4.1.0
@tronical I tested your fix. It works for me. Thanks.

**Comment by ViktorHaag** [comment] 2021-07-13 13:12
> I've submitted a merge request (#9440) to try to fix this, along with a regression test. Could you try and see if this fixes your setup as well?

Yep -- works with my project. Thanks!

**Comment by tk0miya** [comment] 2021-07-13 16:18
Fixed by #9440. I'll ship a bugfix release within a day.

**Closed as completed by tk0miya** 2021-07-13 16:18 UTC
Labels: type:bug, builder:html

**Comment by tupui** [comment] 2021-07-13 17:49
Thank you @tk0miya and @tronical!

**Comment by tupui** [comment] 2021-07-14 18:06
@tk0miya would it be possible for you to yank 4.1.0 on PyPi? This way we don't need to exclude this version from all the requirements around there.

**Comment by tk0miya** [comment] 2021-08-01 15:44
IMO, yanking is not needed. If we'll remove all past packages contains bugs or regressions, there are no old packages on PyPI.

**Comment by tupui** [comment] 2021-08-01 16:39
> IMO, yanking is not needed. If we'll remove all past packages contains bugs or regressions, there are no old packages on PyPI.

@tk0miya I disagree here as the previous version is breaking a lot of us, which other versions are not doing. You had to re-release another version just for this bug, yanking was introduced especially for that. To circumvent it, we now all need to do this: `Sphinx>=3, !=3.1.0, !=4.1.0`. IMHO adding more of these is not advisable...

**Comment by tk0miya** [comment] 2021-08-01 17:28
>I disagree here as the previous version is breaking a lot of us, which other versions are not doing. You had to re-release another version just for this bug, yanking was introduced especially for that.

We release bug fix packages (ex. 4.1.Z) only when the latest stable version (ex. 4.Y.Z) contains critical bugs. It means all bug fix packages should be yanked when newer one is released, right? Is it really the correct usage of the "yank" feature?

Note: 4.1.1 is not only for this bug. It also contains another bug fix.
https://github.com/sphinx-doc/sphinx/milestone/111?closed=1

**Comment by tupui** [comment] 2021-08-01 17:37
The PEP for yanking is here https://www.python.org/dev/peps/pep-0592/. The line is often blurry to say "this release should not be used at all". Here it's just my opinion to yank the release because it broke something which was not supposed to break. In the end it's on you to decide 😃 In any case, I appreciate that you were fast to fix the issue 👍 The rest is details.
