### ISSUE TITLE
Autodoc includes "self" as argument for class methods

### ISSUE THREAD

**Issue by fladd** [sphinx-doc/sphinx#6769] opened 2019-10-24 23:19 UTC
**Describe the bug**
Autodoc includes "self" as argument for class methods.

**To Reproduce**
Have code with a class and class methods, run autodoc.

**Expected behavior**
"self" should not be listed as the first argument, and has not in the past (don't know which version though).

**Screenshots**
Current behaviour:
<img width="746" alt="image" src="https://user-images.githubusercontent.com/2971539/67532050-23230a80-f6c5-11e9-9c01-82f1afbf087a.png">

Previous behaviour:
<img width="744" alt="image" src="https://user-images.githubusercontent.com/2971539/67532153-801ec080-f6c5-11e9-9e65-8cad5ec01e99.png">

**Environment info**
- OS: MacOS
- Python version: 3.7.4
- Sphinx version: 2.2.0
- Sphinx extensions: ['sphinx.ext.autodoc',
              'sphinx.ext.autosummary',
              'sphinx.ext.doctest',
              'numpydoc']

**Comment by tk0miya** [comment] 2019-10-26 06:47
Note: The original source of this document is located at
 https://docs.expyriment.org/_sources/expyriment.design.Experiment.txt

It seems `.. automethod:: __init__` is used to render it.

**Comment by tk0miya** [comment] 2019-10-26 06:51
Hmm... "self" is not shown with simple example on my local:
```
# index.rst
.. autoclass:: example.Foo
   :members:
   :inherited-members:

   .. automethod:: example.Foo.__init__
```
```
# example.py
class Foo:
    def __init__(self, foo, bar):
        """The init function of Foo."""
```
result:
![スクリーンショット 2019-10-26 15 50 18](https://user-images.githubusercontent.com/748828/67615504-56ba7d80-f808-11e9-9f2b-862da8fe221f.png)

And I failed to build your document because of dependency failed. Could you make a minimal reproducible example please?
Thanks,

**Comment by fladd** [comment] 2019-10-26 09:31
Could it be related to our usage of numpydoc? I saw that the official Numpy documenation also has "self" included (e.g. https://numpy.org/doc/1.17/reference/distutils.html).

**Comment by fladd** [comment] 2019-10-26 09:35
Apparently it is: https://github.com/numpy/numpydoc/issues/220

**Comment by tk0miya** [comment] 2019-10-26 14:51
I reproduced the error with numpydoc. All I did is adding to numpydoc to my extension list.

With `-vvv` option, it seems some extension (maybe numpydoc) handles `autodoc-process-docstring` event and rewrite the signature of `Foo.__init__()` like this.
```
[app] emitting event: 'autodoc-process-docstring'('method', 'example.Foo.__init__', <function Foo.__init__ at 0x110163e18>, {}, ['The init function o
[autodoc] output:

.. py:method:: Foo.__init__(self, foo, bar)
   :module: example


   The init function of Foo.
















   ..
       !! processed by numpydoc !!
```

Without numpydoc, I got this debug output. It does not contain "self".:
```
[app] emitting event: 'autodoc-process-docstring'('method', 'example.Foo.__init__', <function Foo.__init__ at 0x10590e598>, {}, ['The init function o
[autodoc] output:

.. py:method:: Foo.__init__(foo, bar)
   :module: example

   The init function of Foo.

```

From my sight, this is a bug of numpydoc. So I'm closing this.
Please reopen this if there is something we can do.

**Closed as completed by tk0miya** 2019-10-26 14:52 UTC
Labels: type:question, extensions:autodoc
