### ISSUE TITLE
Latex build should remove existing output files when it starts

### ISSUE THREAD

**Issue by jfehrle** [sphinx-doc/sphinx#6898] opened 2019-12-07 23:17 UTC
If you get certain severe errors from `sphinx-build`, the output files (including the pdf file) are not updated if they're already present in the build directory, whereas if the output files didn't already exist (and you get the same error) you do get useful output.  This is confusing.

In my case, I'm running on Windows/WSL, which AFAIK always fails when it tries to run `xindy` because of WSL limitations (i.e., it doesn't run a Linux virtual machine).  Even with this error, if the output files aren't already present in the directory, I get a useful pdf, albeit with some of the indexing missing.

```
Latexmk: calling xindy( -L english -C utf8 -M sphinx.xdy -o CoqRefMan.ind CoqRefMan.idx )
Cannot map memory to address 0x800965be3000 .
```

I'm told that running the build on Linux with the output files already present and without the error will indeed update the output files as expected.

**To Reproduce**
I believe this will work on Linux:
1. run sphinx on your favorite project that builds a pdf
2. rename the `xindy` binary so it won't be found
3. run sphinx again, I expect you will get the same failure behavior

**Your project**
I expect you don't want to download all of Coq's dependencies and build all of Coq.
See https://github.com/coq/coq/pull/11232 and https://github.com/coq/coq/issues/11218.

**Environment info**
- Windows 10 with WSL (Ubuntu)
- Python version: 3.6.8
- Sphinx version: 2.2.2

**Comment by jfbu** [comment] 2019-12-07 23:46
not addressing the main issue, but can you try at your locale with <s>``-D latex_use_xindy=False``</s> (edited) ``-D latex_use_xindy=0`` (I don't know if quoting is needed on Windows). As you are using xelatex, it is possible that the build will succeed despite the fact `makeindex` creates `idx` file which is not valid as UTF-8 encoded file. At least that is what I said at https://github.com/sphinx-doc/sphinx/issues/5132 when I reported using lualatex was not even possible (when some indexed word starts with a multi-byte letter; the problem is that `makeindex` picks up the first byte thinking it is a full letter to make a "big letter")

**edit**: sorry I made an error in the above the boolean value [should be set](https://www.sphinx-doc.org/en/master/man/sphinx-build.html#id2) via ``-D latex_use_xindy=0``.  But currently it does not work.   There appears to be possibly  a bug but I need to examine more. (#6900)

**Comment by jfehrle** [comment] 2019-12-08 00:53
@jfbu Not sure what you have in mind.  There is no `-D` option for make or latexmk:

```
$ latexmk CoqRefMan.pdf -pdf -dvi- -ps- -D latex_use_xindy=False
Use of uninitialized value $ENV{"LATEXOPTS"} in concatenation (.) or string at (eval 10) line 1, <GEN1> chunk 1.
Use of uninitialized value $ENV{"LATEXOPTS"} in concatenation (.) or string at (eval 10) line 2, <GEN1> chunk 1.
Use of uninitialized value $ENV{"LATEXOPTS"} in concatenation (.) or string at (eval 10) line 3, <GEN1> chunk 1.
Use of uninitialized value $ENV{"LATEXOPTS"} in concatenation (.) or string at (eval 10) line 4, <GEN1> chunk 1.
Use of uninitialized value $ENV{"XINDYOPTS"} in concatenation (.) or string at (eval 10) line 5, <GEN1> chunk 1.
Latexmk: -D bad option
```

Our makefile just uses `sphinx-build`, which sets up its own Makefile.  Not keen into digging deeper into the Makefiles since you suggest that it's not related to my issue.  FWIW, I believe our index has only USASCII characters.

**Comment by jfbu** [comment] 2019-12-08 08:36
@jfehrle As the conf.py  of your project which I had checked quickly last night 

https://github.com/coq/coq/blob/756d2f4db5eae51c8c01a40550b8c4553bd30f53/doc/sphinx/conf.py#L343

sets up `latex_engine` to ``'xelatex'``, Sphinx sets up Latexmk configuration files and a Makefile in the LaTeX build repertory to use `xindy`. As you reported a problem with `xindy` I indicated that it is possible to have rather `makeindex` in its place:

- the [``-D`` is a documented option of ``sphinx-build``](http://www.sphinx-doc.org/en/master/man/sphinx-build.html#id2). which you can use to override some `conf.py` setting in particular those acquiring default values as they are not explicitly set.

- [`latex_use_xindy` is a documented configuration variable](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-latex_use_xindy).

**edit** I should actually read the documentation :smile:. A priori the correct syntax should be `-D latex_use_xindy=0` but it fails (#6900)

If you invoke `sphinx-build` with `-b latex` and <s>`-D latex_use_xindy=False`</s> `-D latex_use_xindy=0` Sphinx <s>will</s> *should* (but it does not) prepare in the LaTeX build repertory a `latexmkrc` configuration file telling `latexmk`to use ``makeindex``. Hence if you call manually `latexmk` in this directory   it should pick up that information and use ``makeindex``. As you indicated the index (I am meaning here the general index, not the module index) contains only US-ascii characters, then your project should be able to use ``makeindex`` with no issue. 

If your project does not use Unicode, `'xelatex'` is not needed and slower than the default `'pdflatex'`; the conf.py of your project sets to nil string `'fontenc'` key and your configuration is not broken only because `polyglossia` loads by default `fontspec` thus the default font setup will be ok (assuming you use Sphinx 2.0.0 or later) but for example recently merged #6888 works around some intrinsic upstream `xelatex` problem and you will lose that fix if you set manually `'fontenc'` key to nil string. By the way if you stop using `'xelatex'` do not set to nil string the `'fontenc'` key.

This being said, it does not address your initial report. I did not understand what is meant by "latex auxiliary files" (in the latex world, this has a specific meaning). You say they break the build but then you say your system does not have xindy and this is what breaks the build.

**Comment by jfbu** [comment] 2019-12-08 08:47
> Hence if you call manually `latexmk` in this directory it should pick up that information and use `makeindex`

Sphinx puts in the latex build repertory a Makefile which is matched to the way it configures Latexmk. From initial report it is not clear if the last step involves executing `make all-pdf` in that repertory or manually using latexmk, I assumed the latter but I now suspect actually the former applies.

**Comment by jfbu** [comment] 2019-12-08 09:27
1. sorry first about having made an error in saying how to configure from command line the `latex_use_xindy`. It should have been `-D latex_use_xindy=0` but this fails for a reason to investigate

2. but going back to your reporting
I currently don't see a bug here. When working on a project and building to PDF after a change, the build via latexmk is faster if latex build directory has some files from previous build still present.

    If previous build ended up badly, I recommend to do `make -C  _build/latex clean` (where I am assuming here `_build/latex` is the path to the latex build directory) prior to a subsequent `make latexpdf` or `make latex; make -C _build/latex all-pdf` (edit: or rather in your use case direct `sphinx-build` invocation)

**Comment by jfehrle** [comment] 2019-12-08 19:02
> As you reported a problem with xindy

Not quite.  Yes, there is a problem running xindy on Windows/WSL but that is not the point of my issue report.  I expect the xindy/latexmk problem will only be fixed by planned WSL improvements.

>  I indicated that it is possible to have rather makeindex in its place

I already have a workaround, which is in coq/coq#11232.  I don't have the knowledge or experience to justify swapping out `xindy` to the other Coq developers.  I have a little experience with Sphinx and almost none with latex.

> I did not understand what is meant by "latex auxiliary files" (in the latex world, this has a specific meaning).

The last 7 files listed in https://github.com/coq/coq/issues/11218#issuecomment-560021680.  Note the older modification times compared to the other files and CoqRefMan.tex in particular.

> you say your system does not have xindy

No, didn't say that.  I do have xindy.

> 2\. I currently don't see a bug here. When working on a project and building to PDF after a change, the build via latexmk is faster if latex build directory has some files from previous build still present.
> 
> If previous build ended up badly, I recommend to do `make -C  _build/latex clean`

The behavior is confusing and unlike other build processes.  How would a user know what qualifies as "badly" and that they should do a particular make clean before the next run?  I wasted many hours over several days trying to tweak the latex output when Sphinx was not even updating the pdf file--until I noticed the stale modification time.

The issue is that upon certain errors, the directory is not left in a good state for the next build.  Removing the files upfront is a simple way to fix it.  A better fix is to detect when such an error has occurred and then ensure that the directory is left in a clean state.  (The faster latexmk could still be used when there's not such an error.)

FWIW, Coq builds its documentation with "make refman-pdf" (in https://github.com/coq/coq/blob/master/Makefile.doc), which then invokes the Sphinx makefile.

**Comment by jfbu** [comment] 2019-12-08 21:45
> I already have a workaround, which is in [coq/coq#11232](https://github.com/coq/coq/pull/11232). I don't have the knowledge or experience to justify swapping out `xindy` to the other Coq developers. I have a little experience with Sphinx and almost none with latex.

xindy is used because latex_engine is set to `'xelatex'`, it is not explicitly asked for by the Coq conf.py. If no indexed terms contains characters outside of US ASCII, then adding `latex_use_xindy = False` to the conf.py is reasonable thing to do if the contributors to Coq project have issues with xindy dependencies. I suppose there is some reason the Coq developers opted for `'xelatex'`, thus I expect that documentation does contain Unicode letters and that using default latex engine is not an option. Using the default (`'pdflatex'`)  would also let Sphinx, if not instructed otherwise, replace usage of xindy by usage of makeindex.

**Comment by jfbu** [comment] 2019-12-08 22:01
>  I have a little experience with Sphinx and almost none with latex.

I hope you will be happy with Sphinx...

> The behavior is confusing and unlike other build processes. How would a user know what qualifies as "badly" and that they should do a particular make clean before the next run? I

The `make` in latexbuild directory will report if Latexmk exited with an error. Any such case qualifies as "bad" output. (*) The normal thing is not to ignore the error but to clean the latex build directory from auxiliaries: these are *not* the files added by Sphinx to the directory, but the numerous files created by the latex engine because latex is a multi-pass system, typically 3 or 4 passes . To get rid of them `make -C <latexbuilddir> clean` and then try again using `make -C <latexbuilddir> all-pdf LATEXOPTS=--halt-on-error` (Unixen syntax with GNU make) in order for the latex log and console output to stop at the first latex error if one arises. Does it arise on first latex run? or after the index is build (via makeindex or xindy)? this is the kind of information needed to better understand the context. Ideally if an error arises during latex engine execution, examine (the line number is given) the latex file near that line, and identify the origin in the reST or markdown source to understand if some kind of mark-up generated that error.

(*) even if  no error arises, maybe the latex log contains warnings. For example typically warnings that such or such Unicode character is not available in the font. It would be much of a burden to check that, fortunately Latexmk gives a summary of such problems. Sometimes they are "trivial gripes" one can ignore. But one should not ignore Latexmk exit status indicating failure.

**Comment by jfbu** [comment] 2019-12-08 22:15
Latex is a multipass system. For example on first pass a .toc file for the table of contents is produced. On second pass that file is input and actually typesets the TOC. This may shift all pages numbers hence offsets all page references, from example page numbers in the index. Typically a third pass is needed. Long tables may need 2 or 3 passes until they stabilize. If I am working on a project and I change some part of the documentation and want to build the PDF, cleaning entirely the build directory will cause the process to be re-done in its entirety. It is not possible to simply let this become the default because for some project something goes wrong but nevertheless some partial PDF is produced in the first run and that if one does not clean the directory next time the PDF build process will crash.

For example I often test changing from pdflatex to xelatex and back or changing language for reasons of testing and it is quite often the case that babel LaTeX package auxiliary files from previous run will break the next latex pass. I thus typically do make clean before make latexpdf for these small projects. I would not do it lighthearted when a project documentation runs into thousands of pages.

I am thus closing this issue, because we can not make default the asked-for behavior and each Sphinx user can very easily force the desired behavior either manually or via a script.

**Closed as completed by jfbu** 2019-12-08 22:15 UTC
Labels: type:question, closed:wontfix

**Comment by jfehrle** [comment] 2019-12-08 22:21
> maybe the latex log contains warnings

More than 10000 lines of warnings.  The vast majority appear to be like these:

```
LaTeX Warning: Reference `language/gallina-specification-language:coq:warn.iden
t-is-declared-as-a-local-axiom-local-declaration-scope' on page 648 undefined o
n input line 58711.


Underfull \hbox (badness 10000) in paragraph at lines 58711--58712
[]\TU/FreeMono(0)/m/n/10 ‘ident’ is declared as a local axiom

  Reference `addendum/extraction:coq:cmd.extraction-implicit' on page 635 undefined on input line 57713
  Reference `addendum/extraction:coq:cmd.extraction-inline' on page 635 undefined on input line 57714
  Reference `addendum/extraction:coq:cmd.extraction-language' on page 635 undefined on input line 57715
```

**Comment by jfbu** [comment] 2019-12-08 22:24
@jfehrle the warnings you see are the normal thing for the first latex pass. If latexmk did not abort for some reason it would execute at least twice (in fact thrice usually) xelatex and the vast majority of these warnings ideally all will in the end disappear. Latexmk ends its job by printing a summary of remaining warnings.

**Comment by jfehrle** [comment] 2019-12-08 22:29
> I am thus closing this issue, because we can not make default the asked-for behavior and each Sphinx user can very easily force the desired behavior either manually or via a script.

Removing the existing output files is just a suggestion from someone who hardy knows the system.  To avoid user confusion, it would be good to ensure the directory is left in a clean state regardless of any errors that occur.  Thanks for explaining things, though.

**Comment by jfbu** [comment] 2019-12-08 22:31
I see your point but cleaning the directory is removing all hints to what went wrong. The expected thing is that the PDF build succeeds. If it fails some Hercule Poirot human intervention is needed, unless Coq software itself in the future handles it :smile:

**Comment by jfehrle** [comment] 2019-12-08 22:41
> I see your point but cleaning the directory is removing all hints to what went wrong.

Huh?  I just agreed with you on this point, that removing the files may not be the best thing to do.

A few minutes ago I was about to say that I would follow your instructions below sometime tomorrow, but there's not much point in that if the issue is closed.

> To get rid of them `make -C <latexbuilddir> clean` and then try again using `make -C <latexbuilddir> all-pdf LATEXOPTS=--halt-on-error` (Unixen syntax with GNU make) in order for the latex log and console output to stop at the first latex error if one arises. Does it arise on first latex run? or after the index is build (via makeindex or xindy)? this is the kind of information needed to better understand the context. Ideally if an error arises during latex engine execution, examine (the line number is given) the latex file near that line, and identify the origin in the reST or markdown source to understand if some kind of mark-up generated that error.

**Edit** BTW, our CI system (Linux-based) builds the pdf without difficulty, which would seem to rule out a mark-up issue.
