### ISSUE TITLE
LaTeX: "math" directive + ":nowrap:" swallow surrounding paragraph breaks

### ISSUE THREAD

**Issue by mgeier** [sphinx-doc/sphinx#5503] opened 2018-10-02 14:46 UTC
### Problem

In LaTeX mode, when using `:nowrap:` in a `math` directive, the preceding and following paragraphs are not separated anymore, all becomes part of a single paragraph.

#### Procedure to reproduce the problem

```
Previous paragraph.

.. math::
   :nowrap:

   \(a\)

Next paragraph.
```

#### Error logs / results

LaTeX output:

```latex
Previous paragraph.
\(a\)
Next paragraph.
```

#### Expected results

There should be empty lines around the math stuff:

```latex
Previous paragraph.

\(a\)

Next paragraph.
```

### Environment info
- OS: Debian Linux
- Python version: 3.6.7
- Sphinx version: `master`

**Comment by jfbu** [comment] 2018-10-06 18:08
The ``:nowrap:`` means user has responsability of choosing math display structure. For example here it could be `\[a\]` or `\begin{equation*}...\end{equation*}`.  Such constructs should **not** be preceded by a blank line in LaTeX file. They are designed to be parts of paragraphs typographically, the paragraph is interrupted by a math display. That's how Knuth designed TeX to start with.

Thus I don't think this is a bug, although it may be surprising if as in your use case no display math is actually coded in the source.

**Comment by jfbu** [comment] 2018-10-06 18:35
Notice that with

```rest
Previous paragraph.

.. math::

   a

Next paragraph.
```

you get

```latex
Previous paragraph.
\begin{equation*}
\begin{split}a\end{split}
\end{equation*}
Next paragraph.
```

in latex file, which is correct. No empty line should be before `equation*` environment.

Currently if you decide to use

```rest
Previous paragraph.

.. math::
   :nowrap:

   \begin{equation}
   a
   \end{equation}

Next paragraph.
```

you will get

```latex
Previous paragraph.
\begin{equation}
a
\end{equation}
Next paragraph.
```

which is correct. There should be no empty line before, at any rate. One after could be perhaps, but this means equation closes paragraph. In math typography however equations are not paragraphs of their own.

**Comment by jfbu** [comment] 2018-10-06 18:47
Additionally Sphinx uses `parskip` package which adds spacing between paragraphs. Making equations their own paragraphs will add inappropriate whitespace.

Perhaps documentation of Sphinx should be clearer that `:nowrap:` expects user chooses a display math environment (or `\[..\]` at least), and that if inline math `$..$` or `\(..\)` markers are used, the math will be typeset inline. And without any marker it will not be handled as math by TeX and will probably raise error.

**Comment by jfbu** [comment] 2018-10-06 18:48
Closing as this is not a bug. Please reopen if you disagree :)

**Closed as completed by jfbu** 2018-10-06 18:48 UTC
Labels: closed:wontfix, builder:latex

**Comment by mgeier** [comment] 2018-10-09 12:02
Of course you are totally right! I didn't completely realize that "display" equations don't create a new paragraph in LaTeX.

But, just out of curiosity, how could I force a new paragraph before or after the `math` directive if I wanted to?

For example, the displayed equation could be the end of a sentence and the next sentence should start a new paragraph. Something like this:

```rest
... and finally, the result is

.. math::

    a^2 + b^2.

In the next step, we will look at something completely different, namely ...
```

I know I could do this with a `raw` LaTeX directive/role containing `\par` but is there a more Sphinx-like way to do this?

BTW, this issue is not a problem anymore for me since I put (with your gracious help!) those "nowrap" equations into framed boxes on their own in https://github.com/spatialaudio/nbsphinx/pull/218.

**Comment by jfbu** [comment] 2018-10-09 13:00
Does

```rest
... and finally, the result is

.. math::

    a^2 + b^2.

\

In the next step, we will look at something completely different, namely ...
```

work for you ?

It creates an empty `<p></p>` in html output and forces a new paragraph in LaTeX output. This seems coherent (to me...). From brief testing with classic theme the `<p></p>` does not modify spacing in html output (on Firefox)

**Comment by mgeier** [comment] 2018-10-09 14:34
Yes, thanks, it works! I didn't know that a single backslash can do that!

For the record, the RTD theme creates additional vertical space for the empty paragraph.

**Comment by jfbu** [comment] 2018-10-09 15:30
@mgeier you can do this

```
Next paragraph.

... and finally, the result is

.. math::

    a^2 + b^2.

|LaTeXpar|\
In the next step, we will look at something completely different, namely ...

.. |LaTeXpar| raw:: latex

              \par{}
```

which leaves output in html exactly identical and inserts the `\par` token in LaTeX output.

(fixed typo in edit but anyhow it seems name of substitution is lowercased)
