### ISSUE TITLE
autodoc import error even after inserting source path to the system path

### ISSUE THREAD

**Issue by keunwoochoi** [sphinx-doc/sphinx#3834] opened 2017-05-31 12:29 UTC
Subject: import error on my package 'kapre'

### Problem
https://github.com/keunwoochoi/kapre/tree/master/ is the package, and in `docs/`,
`conf.py` [here](https://github.com/keunwoochoi/kapre/blob/master/docs/conf.py#L46)
```python
sys.path.insert(0, os.path.abspath('..'))
```

and I got this warning with the html file without content.
```
WARNING: /Users/gnu/Gnubox/kapre/docs/augmentation.rst:4: (WARNING/2) autodoc: failed to import module u'kapre.augmentation'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/gnu/anaconda/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 657, in import_object
    __import__(self.modname)
RuntimeError: sys.path must be a list of directory names
WARNING: /Users/gnu/Gnubox/kapre/docs/time_frequency.rst:4: (WARNING/2) autodoc: failed to import module u'kapre.time_frequency'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/gnu/anaconda/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 657, in import_object
    __import__(self.modname)
RuntimeError: sys.path must be a list of directory names
```

#### Procedure to reproduce the problem
```
$ git clone https://github.com/keunwoochoi/kapre.git
$ cd kapre
$ cd docs
$ make html
```

### Environment info
- OS: MacOS, but also on Readthedocs server
- Python version: 2.7
- Sphinx version: 1.6.2

**Comment by tk0miya** [comment] 2017-06-03 07:32
I got another warning message. something wrong?
```
$ docker run -it --rm tk0miya/sphinx-html bash
root@0a4891bda819:/docs# pip3 install sphinx==1.6.2 sphinx_rtd_theme
(snip)
root@0a4891bda819:/docs# git clone https://github.com/keunwoochoi/kapre.git
Cloning into 'kapre'...
remote: Counting objects: 572, done.
remote: Compressing objects: 100% (134/134), done.
remote: Total 572 (delta 120), reused 123 (delta 55), pack-reused 378
Receiving objects: 100% (572/572), 1.08 MiB | 697.00 KiB/s, done.
Resolving deltas: 100% (344/344), done.
Checking connectivity... done.
root@0a4891bda819:/docs# cd kapre/docs/
root@0a4891bda819:/docs/kapre/docs# make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.6.2
making output directory...
Generating grammar tables from /usr/lib/python3.5/lib2to3/Grammar.txt
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Skipping optional fixer: buffer
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Skipping optional fixer: idioms
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Skipping optional fixer: set_literal
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Skipping optional fixer: ws_comma
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
------------------------------------------------------------
['/usr/local/bin', '/usr/lib/python35.zip', '/usr/lib/python3.5', '/usr/lib/python3.5/plat-x86_64-linux-gnu', '/usr/lib/python3.5/lib-dynload', '/usr/local/lib/python3.5/dist-packages', '/usr/lib/python3/dist-packages']
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 2 source files that are out of date
updating environment: 2 added, 0 changed, 0 removed
reading sources... [100%] time_frequency
WARNING: /docs/kapre/docs/time_frequency.rst:4: (WARNING/2) autodoc: failed to import module 'kapre.time_frequency'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sphinx/ext/autodoc.py", line 657, in import_object
    __import__(self.modname)
ImportError: No module named 'kapre.time_frequency'
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] time_frequency
generating indices... genindex
writing additional pages... search
copying static files... WARNING: html_static_path entry '/docs/kapre/docs/_static' does not exist
done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 2 warnings.

Build finished. The HTML pages are in _build/html.
```

**Comment by tk0miya** [comment] 2017-06-03 07:41
I also installed dependencies, but the message is not changed.
```
# pip3 install -e .
# pip3 install tensorflow
# make html
(snip)
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 0 source files that are out of date
updating environment: 0 added, 1 changed, 0 removed
reading sources... [100%] time_frequency
WARNING: /docs/kapre/docs/time_frequency.rst:4: (WARNING/2) autodoc: failed to import module 'kapre.time_frequency'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sphinx/ext/autodoc.py", line 657, in import_object
    __import__(self.modname)
ImportError: No module named 'kapre.time_frequency'
(snip)
```

**Comment by bendnorman** [comment] 2017-08-08 18:42
I am also trying to use autodoc to document a project which is dependent on tensorflow but I continue to get an ImportError.  Did you ever find a solution?

**Comment by tk0miya** [comment] 2017-11-01 16:50
I'm closing this now because I can't reproduce the error.
Please feel free to reopen if you still have this problem.
Thanks,

**Closed as completed by tk0miya** 2017-11-01 16:50 UTC
Labels: type:question, extensions:autodoc
