### ISSUE TITLE
TypeError: 'type' object is not iterable

### ISSUE THREAD

**Issue by Lucky-coding** [sphinx-doc/sphinx#3521] opened 2017-03-06 09:31 UTC
I make a class like this:

```
class item(object):
    def __init__(self,ID):
        self.id = ID
        self.match = []
        self.replacement = []
        self.title = []
        self.category = []
        self.buyer = []
        self.buy_date = []
        self.img_data = []
        self.match_counter = []
        self.replace_counter = []
        self.also_buy_counter = []

def get_item(items,item_id):
    return [obj for obj in items if obj.id == item_id][0]

print(get_item(item,3074908))
```

After run ,it is:

```
Traceback (most recent call last):
  File "F:/PyCharm/Apply/Day 0305/data processing.py", line 170, in <module>
    print(get_item(item,3074908))
  File "F:/PyCharm/Apply/Day 0305/data processing.py", line 98, in get_item
    return [obj for obj in items if obj.id == item_id][0]
TypeError: 'type' object is not iterable

Process finished with exit code 1
```

How can I solve this problem? Thank you.

**Comment by tk0miya** [comment] 2017-03-07 01:24
Hmm? How is this relate with Sphinx?
It seems simply a bug of your script.

**Comment by tk0miya** [comment] 2017-03-20 16:17
Now I close this because it seems not a bug of Sphinx.
Thanks,

**Closed as completed by tk0miya** 2017-03-20 16:17 UTC
Labels: type:question
