### ISSUE TITLE
[autodoc] please avoid evaluating default function arguments

### ISSUE THREAD

**Issue by mitya57** [sphinx-doc/sphinx#2844] opened 2016-08-11 18:36 UTC
Currently if Sphinx encounters a function like this:

``` python
def age(self, now=datetime.datetime.utcnow()):
```

It generates output like this:

```
age(now=datetime.datetime(2016, 8, 5, 7, 33, 8, 845335))
```

I think it is confusing and should be avoided.
(Originally reported at [Debian #833820](https://bugs.debian.org/833820).)

**Comment by peterjc** [comment] 2018-09-24 15:48
This looks like a duplicate of #759 to me.

**Comment by tgandor** [comment] 2020-02-12 10:35
@mitya57 - this example is cool, however the function is wrong ;) The default `now` would be only evaluated at time of function definition.

**Comment by mitya57** [comment] 2020-02-12 10:42
I know, I said exactly that in the linked downstream bug.

**Comment by tk0miya** [comment] 2020-02-13 06:17
I made a super experimental extension for this.
https://gist.github.com/4279adc2d6ff4da52ea73c18cfdd229a
![スクリーンショット 2020-02-13 2 04 31](https://user-images.githubusercontent.com/748828/74406653-94a0e780-4e73-11ea-8ac2-95b5ddf387b2.png)

I'd like to know side effect to enable this by default. So it might be needed to add a new option to enable it.

**Comment by tk0miya** [comment] 2021-03-06 10:59
Will be fixed by #8771. Closing.

**Closed as completed by tk0miya** 2021-03-06 10:59 UTC
Labels: extensions:autodoc, type:proposal
