### ISSUE TITLE
Autodoc regression in Sphinx 1.6.6 (all work fine in Sphinx 1.6.5)

### ISSUE THREAD

**Issue by makhomed** [sphinx-doc/sphinx#5143] opened 2018-07-03 18:31 UTC
Sphinx 1.7.5 fail with exception when I try to generate documentation 
for https://github.com/makhomed/fabrix project.
Sphinx 1.6.5 work fine.

### Problem
Autodoc from Sphinx 1.7.5 fail with exception.

#### Procedure to reproduce the problem
```
# pip install Sphinx
# cd /opt
# git clone https://github.com/makhomed/fabrix.git
# cd /opt/fabrix/docs
# make html
```

#### Error logs / results
```
Exception occurred:
  File "/opt/fabrix/fabrix/config.py", line 59, in __iter__
    return self.__super__getitem__(env.host_string).__iter__()
KeyError: None
The full traceback has been saved in /tmp/sphinx-err-txDvuK.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```
Full traceback:
```
Traceback (most recent call last):
......
  File "/usr/lib/python2.7/site-packages/sphinx/ext/autodoc/__init__.py", line 1252, in add_directive_header
    objrepr = object_description(self.object)
  File "/usr/lib/python2.7/site-packages/sphinx/util/inspect.py", line 243, in object_description
    sorted_keys = sorted(object)
  File "/opt/fabrix/fabrix/config.py", line 59, in __iter__
    return self.__super__getitem__(env.host_string).__iter__()
KeyError: None
```
Buggy code:
```
  File "/usr/lib/python2.7/site-packages/sphinx/util/inspect.py", line 243, in object_description
    sorted_keys = sorted(object)
```
Buggy code in context:
```
def object_description(object):
    # type: (Any) -> unicode
    """A repr() implementation that returns text safe to use in reST context."""
    if isinstance(object, dict):
        try:
            sorted_keys = sorted(object)    # <=== line 243, bug is here
        except TypeError:
            pass  # Cannot sort dict keys, fall back to generic repr
        else:
            items = ("%r: %r" % (key, object[key]) for key in sorted_keys)
            return "{%s}" % ", ".join(items)
```

#### Expected results
Expected normal run without errors/exceptions and documentation generated 
like it was generated with Sphinx 1.6.5: https://fabrix.readthedocs.io/en/latest/

### Reproducible project / your project
- https://github.com/makhomed/fabrix

### Environment info
- OS: CentOS Linux 7.5
- Python version: Python 2.7.5
- Sphinx version: 1.7.5

**Comment by tk0miya** [comment] 2018-07-05 15:33
Sorry for inconvenience. I made a fix for this in #5131. So it will be fixed in next release.
Please wait a moment.

Thanks,

**Comment by tk0miya** [comment] 2018-07-12 15:40
Fixed by #5131.
Thank you for reporting.

**Comment by tk0miya** [comment] 2018-07-12 17:04
Oh, my last comment was not correct. #5131 is not related with this.
I have to investigate this again.

**Comment by makhomed** [comment] 2018-07-12 17:21
@tk0miya, can you please reopen this issue #5143
because now it marked ad closed and it is now not display
in the list https://github.com/sphinx-doc/sphinx/milestone/47

**Comment by tk0miya** [comment] 2018-07-14 13:46
It seems Sphinx-1.6.6 failed to build the document of fabrix. It might be a regression of Sphinx-1.6.6.
```
FROM tk0miya/sphinx-html

RUN apt update; apt install -y python2.7 python-pip build-essential
RUN git clone https://github.com/makhomed/fabrix.git
RUN pip2 install -U pip setuptools tox
WORKDIR /docs/fabrix
RUN python setup.py install
WORKDIR /docs/fabrix/docs
RUN pip2 install -U Sphinx==1.6.6
RUN make html
```

**Comment by makhomed** [comment] 2018-07-14 17:54
@tk0miya, sorry, I test only 1.6.5 and 1.7.5 versions, 
1.6.5 works fine, but 1.7.5 fail with exception.

BTW, looks like fix for this bug is trivial:

```diff
--- /usr/lib/python2.7/site-packages/sphinx/util/inspect.py.old 2018-07-03 20:06:20.243907000 +0300
+++ /usr/lib/python2.7/site-packages/sphinx/util/inspect.py     2018-07-14 20:41:03.341835263 +0300
@@ -241,7 +241,7 @@
     if isinstance(object, dict):
         try:
             sorted_keys = sorted(object)
-        except TypeError:
+        except (TypeError, KeyError):
             pass  # Cannot sort dict keys, fall back to generic repr
         else:
             items = ("%r: %r" % (key, object[key]) for key in sorted_keys)
```

after this patch I can successfully build documentation for fabrix with sphinx 1.7.5

is my patch ok and it can be included in upcoming 1.7.6 version of sphinx?

**Comment by makhomed** [comment] 2018-07-14 18:03
> It seems Sphinx-1.6.6 failed to build the document of fabrix. It might be a regression of Sphinx-1.6.6.

@tk0miya, yes I confirm, sphinx version 1.6.6 also fail with exception 
in file ```/usr/lib/python2.7/site-packages/sphinx/util/inspect.py``` 
in function ```object_description()``` in line ```208```.

**Comment by tk0miya** [comment] 2018-07-15 05:19
Finally, I found this bug is caused by #4181.

**Comment by tk0miya** [comment] 2018-07-15 05:21
@makhomed Thank you for your patch. I will apply it in next release. Please wait a moment :-)

**Closed as completed** 2018-07-15 09:10 UTC
Labels: type:bug, extensions:autodoc
