### ISSUE TITLE
Sphinx exception : AttributeError: 'dict' object has no attribute 'env'

### ISSUE THREAD

**Issue by DuyguKeskek** [sphinx-doc/sphinx#3871] opened 2017-06-17 08:53 UTC
When I run the project I'm getting this exception
`Exception occurred:
  File "/home/duygu/.local/lib/python2.7/site-packages/sphinx/transforms/__init__.py", line 90, in apply_transforms
    self.document.settings.env = self.env
AttributeError: 'dict' object has no attribute 'env'
The full traceback has been saved in /tmp/sphinx-err-pbYwUh.log, if you want to report the issue to the developers.
`
How can I resolve it ?

**Comment by tk0miya** [comment] 2017-06-17 13:25
Did you read our issue template? I can't reproduce your problem from this issue.
Please let me your problem in detail.

**Comment by DuyguKeskek** [comment] 2017-06-17 13:33
I have a custom Sphinx project using bootstrap theme and I want to import Ablog into it.-It is a blogging engine for Sphinx- When I do that, it always gives this error message. I tried uninstalling and reinstalling Sphinx many times but nothing has changed. When I extract Ablog implementation my Sphinx project works perfectly. But this is not a bug of Ablog that's why I'm confused. What do you think ?

**Comment by triparno** [comment] 2017-06-22 20:26
I am facing the exact problem,
```
 File "/usr/lib/python3.6/site-packages/sphinx/transforms/__init__.py", line 90, in apply_transforms
    self.document.settings.env = self.env
AttributeError: 'dict' object has no attribute 'env'
The full traceback has been saved in /tmp/sphinx-err-_4b0ncup.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!

```

**Comment by tk0miya** [comment] 2017-06-24 04:27
I need to know your problem in detail to resolve your problem.
Could you share your document or reproducible example?
And could you paste the full stacktrace saved on your computer.

In addition, I don't know about ablog. So I can't answer your question.

**Comment by tk0miya** [comment] 2017-09-06 15:39
Finally, I've not been able to  reproduce this. And it seems this is a bug of ablog.
So I close this now. Please feel free to reopen this if you still get same error.
We need to an additional information to reproduce this.

Thanks,

**Closed as completed by tk0miya** 2017-09-06 15:39 UTC
Labels: type:bug
