### ISSUE TITLE
Napoleon: numpy array class attr

### ISSUE THREAD

**Issue by jrkerns** [sphinx-doc/sphinx#2036] opened 2015-09-11 16:31 UTC
I'm using python 3 and sphinx 1.3 w/ napoleon and if I use the new `sphinx.ext.napoleon` my `make html` build breaks for classes with numpy array class attributes. [class example](https://gist.github.com/jrkerns/aa19bb48ce8f2e7f7ee8)
Exception:
`Exception occurred:
  File "D:\Python\Miniconda3\lib\site-packages\sphinx\ext\napoleon\__init__.py", line 362, in _skip_member
    cls_path, _, _ = qualname.rpartition('.')
AttributeError: type object '__qualname__' has no attribute 'rpartition'
`

If I use the old `sphinxcontrib.napoleon` it will build without error and properly identify the attr as a numpy array.

Any help is appreciated; thanks!

**Comment by RobRuana** [comment] 2015-09-11 17:24
Thanks for the report! I'll take a look

**Comment by RobRuana** [comment] 2015-11-18 05:05
Hmm... I have not been able to reproduce this issue. The exact example class you provided works with the source from the sphinx repo.

The sphinxcontrib.napoleon extension actually has the most recent source code, because I am able to release it as soon as it is patched (unlike the mainline sphinx extension, which must wait for a new sphinx release).

Thus, I believe this may be a bug that has already been fixed in the repo, but not yet packaged and released.

If the sphinxcontrib.napoleon extension is working for you, then go ahead and keep using it – you won't be missing out on anything.

**Closed as completed by RobRuana** 2015-11-18 05:05 UTC
Labels: extensions:napoleon

**Comment by jrkerns** [comment] 2015-11-18 14:46
Okay, thanks for looking into it!
