### ISSUE TITLE
Parsing error for returns when using google style docstrings

### ISSUE THREAD

**Issue by rothnic** [sphinx-doc/sphinx#2085] opened 2015-10-13 16:35 UTC
It appears that [this issue](https://bitbucket.org/birkenfeld/sphinx-contrib/commits/79535b22d5df75e978aba22587fcb018862c8ef9) still exists for google style docstrings.

You can see the issue manifested on our 0.10 documentation: http://bokeh.pydata.org/en/latest/docs/reference/charts.html#id1

Screenshot for reference:

![image](https://cloud.githubusercontent.com/assets/452052/10461338/7cc21974-719e-11e5-887f-071dd0133d23.png)

**Comment by RobRuana** [comment] 2015-10-13 18:14
Thanks! Just for future reference this is the docstring that exhibits the bug:

```
def Bar(data, label=None, values=None, color=None, stack=None, group=None, agg="sum", xscale="categorical", yscale="linear",
        xgrid=False, ygrid=True, continuous_range=None, **kw):
    """ Create a Bar chart using :class:`BarBuilder <bokeh.charts.builder.bar_builder.BarBuilder>`
    render the geometry from values, cat and stacked.
    Args:
        values (iterable): iterable 2d representing the data series
            values matrix.
        cat (list or bool, optional): list of string representing the categories.
            (Defaults to None)
        stacked (bool, optional): to see the bars stacked or grouped.
            (Defaults to False, so grouping is assumed)
        continuous_range(Range1d, optional): Custom continuous_range to be
            used. (Defaults to None)
    In addition the the parameters specific to this chart,
    :ref:`userguide_charts_generic_arguments` are also accepted as keyword parameters.
    Returns:
        a new :class:`Chart <bokeh.charts.Chart>`
    Examples:
        .. bokeh-plot::
            :source-position: above
            from collections import OrderedDict
            from bokeh.charts import Bar, output_file, show
            # (dict, OrderedDict, lists, arrays and DataFrames are valid inputs)
            xyvalues = OrderedDict()
            xyvalues['python']=[-2, 5]
            xyvalues['pypy']=[12, 40]
            xyvalues['jython']=[22, 30]
            cat = ['1st', '2nd']
            bar = Bar(xyvalues, cat, title="Stacked bars",
                    xlabel="category", ylabel="language")
            output_file("stacked_bar.html")
            show(bar)
    """
```

**Comment by RobRuana** [comment] 2015-11-18 18:09
I can't reproduce this issue with the docstring quoted above.

I am assuming this has been fixed in the repo, but a new version with the fixed code hasn't been released yet.

You can try using the sphinxcontrib-napoleon package ('sphinxcontrib.napoleon' instead of 'sphinx.ext.napoleon' in conf.py). You'll need to pip install sphinxcontrib-napoleon or add sphinxcontrib-napoleon to your requirements.txt.

sphinxcontrib-napoleon usually has more up-to-date fixes.

**Closed as completed by RobRuana** 2015-11-18 18:09 UTC
Labels: extensions:napoleon
