### ISSUE TITLE
raw directive trims newline character from the last line of its contents

### ISSUE THREAD

**Issue by yulin-li** [sphinx-doc/sphinx#3594] opened 2017-03-30 14:02 UTC
Subject: <what happen when you do on which document project>

### Problem
When I built my project to latex, an error occurred that \begin{itemize} didn't start with a new line. So, the ``item`` can't display correctly in PDF.

#### Procedure to reproduce the problem
Here's my source code:
```rst
hello
=====

some code

.. raw:: latex

	\begin{OriginalVerbatim}[commandchars=\\\\\\{\\}]
		hello too
	\end{OriginalVerbatim}
	
	
* item1
* item2
```
And the result:
```latex
\chapter{hello}
\label{\detokenize{test::doc}}\label{\detokenize{test:hello}}\label{\detokenize{test:welcome-to-my-test-s-documentation}}
some code
\begin{OriginalVerbatim}[commandchars=\\\\\\{\\}]
        hello too
\end{OriginalVerbatim}\begin{itemize}
\item {} 
item1

\item {} 
item2

\end{itemize}
```

#### Expected results

```latex
\chapter{hello}
\label{\detokenize{test::doc}}\label{\detokenize{test:hello}}\label{\detokenize{test:welcome-to-my-test-s-documentation}}
some code
\begin{OriginalVerbatim}[commandchars=\\\\\\{\\}]
        hello too
\end{OriginalVerbatim}
\begin{itemize}
\item {} 
item1

\item {} 
item2

\end{itemize}
```

### Environment info
- Windows
- Python version: 3.6
- Sphinx version: 1.5.3

I have ever thought it was a nbsphinx's bug: 
https://github.com/spatialaudio/nbsphinx/pull/106

**Comment by tk0miya** [comment] 2017-03-30 15:04
The latex writer of Sphinx expects block level elements should have a following empty line. So it outputs `\begin{itemize}` without a newline.
But, in this case, `raw` directive generates a inline node. It does not have the empty line.

It seems the combination of them causes this issue.

As a quick look, docutils handles a raw node like following:
```
    def visit_raw(self, node):
        if not 'latex' in node.get('format', '').split():
            raise nodes.SkipNode
        if not self.is_inline(node):
            self.out.append('\n')
        if node['classes']:
            self.visit_inline(node)
        # append "as-is" skipping any LaTeX-encoding
        self.verbatim = True
```
It inserts a newline if the node satisfies `not self.is_inline()`. It might help this situation.

Note:
The handler for bullet_list nodes outputs `%\n` before the itemize environment. Is it related with this?
```
    def visit_bullet_list(self, node):
        if self.is_toc_list:
            self.out.append( '%\n\\begin{list}{}{}\n' )
        else:
            self.out.append( '%\n\\begin{itemize}\n' )
```

**Comment by jfbu** [comment] 2017-03-30 15:43
Note that (at least since Sphinx 1.4 and presumably earlier versions as well) Sphinx by itself always adds a `\n` after the closure of a `Verbatim` environment.

So this issues arises from `.. raw:: latex`. I use this directive often myself for matters of quick testing and I am aware it does not add a new line character. I usually simply add a `\relax` additional line to the contents of the `.. raw:: latex`  directive.

In case text follows, it appears in my brief testing that a `\n` is inserted anyhow. Hence we do not get `\relaxFoo`  possible problem. Here we get `\relax\begin{itemize}` which is fine mark-up.

If your use-case is only from such  ``raw`` directives then I suggest you simply use the ``\relax`` additional lines.

**Comment by jfbu** [comment] 2017-03-30 15:49
@Harlan-pku side note, one should not escape backslashes in raw directive. This should be

```
.. raw:: latex

	\begin{OriginalVerbatim}[commandchars=\\\{\}]
		hello too
	\end{OriginalVerbatim}
	\relax
```

Besides: since Sphinx 1.5, you don't need `OriginalVerbatim`. Just use `Verbatim` if you want the un-modified environment from `fancyvrb`.

**Comment by jfbu** [comment] 2017-03-30 16:02
The `\begin{itemize}` does *not* have to start on a new line. But the `\end{Verbatim}` should be on a line of its own, that's typical of verbatim environments. And of course, Sphinx latex writer does it.

There is no bug of Sphinx here, but only a  problem of mark-up in usage of `raw` directive.

During recent developments of Sphinx latex writer attention has been paid whenever it made sense to start (and end) LaTeX environments on a line of their own, using `'\n\\begin{foo}\n'` and `'\n\\end{foo}\n'` type of Python strings, for environments corresponding to block level constructs ("vertical mode" in TeX parlance). But we have hundreds of lines of tests, and it requires quite some time to update them all, we don't have much time for these things which aer purely aesthetic and not required by LaTeX mark-up.

I am downgrading this to a question, because I don't see a bug  of Sphinx here.

Also: note that `raw` directive should *not* systematically end with a new line. There might some LaTeX code we want to test without newline.

**update:** *yes, but if user ends the last line with a `%` for raw latex output this will compensate in the overwhelming majority of use cases an automatically added `\n`.*

**Comment by jfbu** [comment] 2017-03-30 16:11
@tk0miya regarding the bullet list handler, I am confused: the code your comment is the one from Docutils latex writer, not the one from Sphinx latex writer ...

ah, probably you meant that as Docutils inserts `%\n` for bullet list it could fit with `raw` not inserting a final `\n` on its own. But, I want to point out that `\end{Verbatim}%` is not legal and would cause failed PDF build, so even with Docutils latex writer behaviour for bullet list, this would not change the fact that the use of `raw` directive as in @Harlan-pku example creates non compilable LaTeX source.

**Comment by jfbu** [comment] 2017-03-31 06:16
A substitution declaration can use `raw` directive allowing to insert inline raw LaTeX code. Then, we do not want that Sphinx adds systematically a `\n` because this could mean an extra space in horizontal mode. We can not use `%\n` because in the context of @Harlan-pku's example this would mean `\end{Verbatim}%` which causes failed PDF build.

In conclusion for `raw` directive in LaTeX, it is important that it *not* be systematically followed by a newline. Hence closing this as this is not a bug of Sphinx, but a non-appropriate contents in `raw` directive.

**update** I have later changed my mind about this, because space problems in TeX from an added `\n` can be prevented if user ends the raw contents with `%`.

**Comment by mgeier** [comment] 2017-03-31 08:07
@jfbu OK, that makes sense. But how can I insert a trailing `\n` in the LaTeX output if I want to?

Or is the `\relax` work-around really bullet-proof?

**Comment by jfbu** [comment] 2017-03-31 13:09
@mgeier I see no way to insert a trailing `\n` from use of `raw` directive. I also see no way to insert an ascii character 32 (space) after `\relax` to be sure `\relaxFOO` problem does not arise. But,

1. a character after the raw directive will start a new paragraph hence the `\n` will be inserted avoiding the `\relaxFOO` potential problem

2. but if you do need systematic use of these raw directives, possibly immediately one after the other, you should make sure any raw latex contents not starting with  a macro is done this way:

```
.. raw:: latex
   
   %
   contents 

```
In this way you avoid `\relaxcontents` bug.

Generally speaking though `\relax` is ok, because issues can come only from abuse of raw directives, and an extension patching sphinx latex writer has the direct means to output what it wants without raw directive.

Still, keeping with raw directive, there are some more or less exotic other possibilities on the TeX side.

- you could use `{}`. But again that depens of circumstances, is this in vertical mode (good) or in paragraph mode (not good perhaps if spaces come after that)? what may follow ? what is on previous line ?

- you could use `\1` rather than `relax` with `\let\1\empty` in the preamble. The point is that `\1` can be immediately followed by letters.

- you could use `^^20`. For TeX this is for all intents and purposes like a space character (ascii code 32). If the TeX source end up being like this:

      foo
      ^^20bar

  it will be handled like

      foo
       bar

  i.e. it is as if the space was not there (it doesn't double the one from the end of line after foo).

  And if you have

      foo
      ^^20
      bar

  It is really as if the intermediate line was an empty one, which creates a `\par` token.

I see advantages (theoretically) forLaTeX with the raw directive not adding a trailing `\n`: raw contents may be genuinely inline and we may not want any whitespace in-between.

**Comment by jfbu** [comment] 2017-03-31 13:24
> you could use `\1` rather than relax with \let\1\empty in the preamble. The point is that \1 can be immediately followed by letters.

Note that this is `\1`  (the digit 1, or any other digit) not, `\l` (the letter ell). Saying this in case your fonts make the difference not clear.

**Comment by tk0miya** [comment] 2017-04-01 03:51
Sorry. the bullet list handler is docutils'.

`rst2latex.py` (docutils) generates following LaTeX code.
```
$ cat test.rst
hello

.. raw:: latex

   Sphinx

* world!
```
```
$ rst2latex.py test.rst
...
%%% Body
\begin{document}

hello

Sphinx
%
\begin{itemize}

\item world!

\end{itemize}

\end{document}
```

The writer inserts
* a newline after raw node
* a line contains only `%` before itemize

I don't know the second one help this case, but it might help similar case.

BTW, I prefer to docutils' approach which switches the style of raw nodes from inline element to block one automatically. Indeed, inserting `\relax` will resolve this case. but inserting it is very tired and forgetful work for me.
In another point of view, reST notation basically considers a directive as a block level element. Actually, docutils considers a raw directive generates block element. So it would be better to do that in Sphinx too.

**Comment by jfbu** [comment] 2017-04-01 08:41
I don't know what is the exact scope of the discussion here: the raw directive should be only for end user, right? an extension should have better means of modifying latex output than using raw nodes, shouldn't it directly write to the latex output? Regarding raw directive, scattered remarks:
 
1. currently we can do

   ```
   abc\ |x|\ ghi

   .. |x| raw:: latex

          def
   ```
   with the effect to produce ``abcdefghi`` in LaTeX and ``abcghi`` in other builders.

   Of course, this is perhaps very rare construct, but at least we can do it currently.

   If raw directive inserts a trailing `\n` we have an extra space. To get rid of it the user could do:
   ```
   abc\ |x|\ ghi

   .. |x| raw:: latex

          def%
   ```
   Here I am assuming `\n` will be inserted by LaTeX writer.

   So we see that here again we force upon the user some awareness of underlying issues.

   I agree that the situation with an automatic `\n` to follow, which in some cases might mean user must end raw contents with `%`, is less problematic than the situation with no automatic `\n` and in some rare cases a `\relax` workaround, which have its issues previously commented upon.

   But honestly, how many times will Sphinx user need by itself to insert  a `Verbatim` environment via a `raw` directive ? Doesn't have the extension better means to do that than using `raw` directive ?

   Again, there does not exist in LaTeX environments which must start or end on a line of their own in TeX source, apart from the verbatim family of environments. So the `\begin{itemize}` does not _have_  to start on a line of its own. It is arguably more pleasing to the eye if it does though.

 
2. in LaTeX, lists behave differently if they are separated by empty line or not from previous paragraph: if separated by empty line in source, they will insert `\partopsep` space above themselves, and also below themselves (the latter even if no empty line separates in source the `\end{..}` from next paragraph; for me, this is a LaTeX design bug). I guess this is why Docutils takes care of using `%\n` in preference to `\n\n` before `\begin{itemize}`. But, there is almost no difference between `%\n` and a single `\n` in this situation, because the end-of-line space created by TeX during tokenization will be discarded by the closure of paragraph before itemize. Exception: user has loaded `enumitem` package and is using `\begin{itemize*}` for an "inline" list. Then it would actually  be better not to do `%\n` but only `\n`.

The `%` in `%\n` in Docutils, if before `\begin{itemize}`, has thus no functional importance, in overwhelming majority of cases. I use these kinds of things myself when I write directly LaTeX markup, but this only for visual comfort in looking at file, so that the `\begin{foo}` is better seen. I do this for footnotes in particular, so that in my Emacs buffer, `M-x fill-paragraph` will affect only the footnote, not the thing before (I use hard wraps in all my TeX files; early TeX would choke if an input line had more than 1000 characters, by the way).

My opinion is that ``raw`` directives, like ``image`` directives, should not be morally considered to serve only for block level elements, because it does make sense to use them for insertion of inline contents via substitutions.

However, without treating them as block-level, LaTeX does allow that they be systematically followed by a trailing `\n`, and user can always use a `%` to suppress preventively an end of line space, in the rare cases they could influence pdf output.

**Comment by jfbu** [comment] 2017-04-01 08:55
In brief, it is ok with me if raw directive appends a trailing `\n` to the last line of its contents. This may fit better to user expectation, independently of builder, that raw contents are inserted "as is", and the last line of contents morally should have a `\n` at its end. (I understand trailing spaces are trimmed, but that's other thing).

On the other hand, I would be more reluctant to raw directive prepending `\n` to before insertion of its contents.

**Comment by mgeier** [comment] 2017-04-01 09:37
@jfbu Thanks for your detailed explanations!

I've added `\relax` in https://github.com/spatialaudio/nbsphinx/pull/107 and I've added `%` in the beginning of raw LaTeX directives in https://github.com/spatialaudio/nbsphinx/commit/f0a40072acf157b9334be1f1a5ab37e43374301f.

This seems to work without problems now, thanks a lot for your help!

> the raw directive should be only for end user, right? an extension should have better means of modifying latex output than using raw nodes, shouldn't it directly write to the latex output?

Not in my case, since my extension [nbsphinx](http://nbsphinx.readthedocs.io/) provides a source parser and therefore it's not directly writing to LaTeX.
Currently, it creates an intermediate `.rst` representation which is parsed by the built-in RST parser, but in the future it may write directly to the docutils document structure. Latter will probably make it easier to add newlines here and there, but it will still use raw directives.

> In brief, it is ok with me if raw directive appends a trailing `\n` to the last line of its contents.

Yes, that sounds good. I guess this would avoid the whole issue I had!

Thanks also to @tk0miya for bringing this up.

**Comment by jfbu** [comment] 2017-04-01 10:28
@mgeier yes I looked now at https://github.com/spatialaudio/nbsphinx  and how you use the raw directive for various outputs. I had in mind only a LaTeX extension, as the raised issue looked like a pure LaTeX one.

Ok, glad the patches you added fixed your issues. I was hesitant but @tk0miya and you have now convinced me that indeed the Sphinx implementation of the `raw` directive should insert trailing `\n`. I recall I had been surprised when I first encountered the problem but I had grown used to it. With an ending `%` inserted by user, an additional trailing `\n` makes no change to previous situation. Except in extreme cases like a raw directive which would insert contents inside a verbatim block of course, which (afaict) could not arise without some rather significant modifications to the handling of nodes (one can also imagine abuse of raw directive to start and end verbatim like environment, to self-display verbatim the enclosed LaTeX mark-up produced by Sphinx...)

From what I understand of your issues, I confirm they would not have arisen if raw directive had inserted a final `\n`.

**Comment by tk0miya** [comment] 2017-04-02 09:41
@jfbu I think you are mistaken about the interpretation of raw directive.

Docutils; the original implementation of reST processor, recognizes a raw directive both in-line element and block-level element (especially in LaTeX writer).
For example, with substitution syntax, it behaves as in-line as you said:
```
$ cat test.rst
abc |X| ghi

.. |X| raw:: latex

   def
```
```
$ rst2latex.py test.rst
...
%%% Body
\begin{document}

abc def ghi

\end{document}
```

But, it behaves as block level element without substitution:
```
$ cat test.rst
abc ghi

.. raw:: latex

   def
```
```
$ rst2latex.py test.rst
...
%%% Body
\begin{document}

abc ghi

def

\end{document}
```

Note: The image directive also behaves as same as above.


The difference comes from the structure of doctree.
In the first case, the raw node is appeared under paragraph. So LaTeX writer renders it as inline element (even if it is at the end of paragraph).
```
$ rst2xml.py test.rst
...
<document source="test2.rst">
  <paragraph>abc <raw format="latex" xml:space="preserve">def</raw> ghi</paragraph>
  <substitution_definition names="X"><raw format="latex" xml:space="preserve">def</raw></substitution_definition>
</document>
```

On the other hand, the raw node is placed outside of paragraph, and the writer renders it as block level element.
```
$ rst2xml.py test.rst
...
<document source="test.rst">
  <paragraph>abc ghi</paragraph>
  <raw format="latex" xml:space="preserve">def</raw></document>
```

So what I said is LaTeX writer of Sphinx should be render the raw node as a block level element if it is placed outside of paragraph (because it behaves as block level!).

**Comment by jfbu** [comment] 2017-04-02 14:34
@tk0miya thanks for clarifying. Am I correct : your analysis is that in the [nbsphinx](https://github.com/spatialaudio/nbsphinx) case the raw node was placed outside of a paragraph in reST source, hence it should have been treated as block level, and if it had been so it would not have been trimmed in latex output of the newline character of its last line, and @Harlan-pku would have had no issue to report ? The case of raw nodes inserted by substitution needs no such consideration and my long argument about pros and cons of a trailing `\n` also with them is interesting as a kind of long political digression but  basically not what this whole thing is about ? ;-)

**Comment by tk0miya** [comment] 2017-04-02 15:37
No, what I told is the case of docutils. As reported, Sphinx does not treat the non-substituted raw nodes as block-level. It **always** treats them as inline level elements.
docutils is a reference implementation of reStructuredText processor. Hence the behavior of Sphinx is a kind of bug, i think.

**Comment by jfbu** [comment] 2017-04-03 16:22
@tk0miya I think you misunderstood my misunderstanding ;-) and that I tend to agree with you that non-substituted raw nodes should be treated as block-level.

**Closed as completed** 2017-04-08 19:52 UTC
Labels: type:bug, markup, builder:latex
