### ISSUE TITLE
Include directive: wrong relative path

### ISSUE THREAD

**Issue by kynzie** [sphinx-doc/sphinx#6805] opened 2019-11-10 09:31 UTC
**The bug**
Here is the project tree:
```
test/
├── build
├── exo
│   ├── main.rst
│   └── test.rst
├── make.bat
├── Makefile
└── source
    ├── conf.py
    ├── index.rst
    └── part1.rst
```
`index.rst` has the following content:
```
Include problem
============

.. toctree::
   :maxdepth: 2
   :caption: Contents:

   part1
```
`part1.rst` has the following content:
```
.. include:: ../exo/main.rst
```
`main.rst` is correctly included.
But `main.rst` has the following content:
```
.. include:: test.rst
```
The `test.rst` content does not really matter. At build time, `sphinx`, report the following warning:

```
exo/main.rst:1: WARNING: Problems with "include" directive path:
InputError: [Errno 2] No such file or directory: 'source/test.rst'.
```

**To Reproduce**
Described above.
```
$ make latex # for example
```

**Expected behavior**
Regarding [`docutils` documentation](http://docutils.sourceforge.net/docs/ref/rst/directives.html#include), it says:

```
The directive argument is the path to the file to be included, relative to the
document containing the directive. Unless the options literal or code are given, the
file is parsed in the current document's context at the point of the directive.
```
As no option are given, no warning should raise and ``test.rst`` must be found and included relatively to `exo/main.rst`

**Environment info**
Tested with on:
- OS: Linux
- Python version: 3.7.4
- Sphinx version: 2.2.0 and 2.2.1

**Comment by tk0miya** [comment] 2019-11-17 02:31
As you quoted, include directive considers the file is a part of the current document. In this case, the content of `../exo/main.rst` is inserted into the location of include directive in `part1.rst` (current document). In accuracy, it is not inserted, but processed as a part of `part1.rst`. Anyway, this is expected and formal behavior.

**Comment by tk0miya** [comment] 2019-12-01 16:48
I'm closing this because of not a bug.
Thanks,

**Closed as completed by tk0miya** 2019-12-01 16:48 UTC
Labels: type:question, markup
