### ISSUE TITLE
Newline ('\n') in docstring drops words until end of line

### ISSUE THREAD

**Issue by syutbai** [sphinx-doc/sphinx#4251] opened 2017-11-20 22:02 UTC
### Problem
Docstring in pdb.py has a '\n' followed with "exit".  
<pre>
1106     def do_quit(self, arg):
1107         """q(uit)\nexit
1108         Quit from the debugger. The program being executed is aborted.
1109         """
</pre>

The resulting Sphinx-generated web document does not show the "exit" part:  https://docs.python.org/3/library/pdb.html.  Snippet of document shows option "exit" is missing:
> q(uit)
>    Quit from the debugger. The program being executed is aborted.

PDB CMD help shows:  
> q(uit)
> exit
>    Quit from the debugger. The program being executed is aborted.

Bug discovered through IPython docs for PDB: https://github.com/ipython/ipython/pull/10911.  Warning is:
<pre>
WARNING: Unexpected indentation
</pre>

### Environment info
- OS:  CentOS 7.4
- Python version:  3.6.3 
- Sphinx version:  1.6.3
- <Extra tools e.g.: Browser, tex or something else>  Chrome

**Comment by jzf2101** [comment] 2017-11-20 22:21
According to https://github.com/ipython/ipython/pull/10911

> Making changes in PDB:
> PDB has Docstring formatting that drives help file formatting.
> Docstring triggering the message below contains a '\n': Q(uit)\nexit . Pdb functions do_quit() and do_exit() is aliased so the resulting help file for this formats the "exit" word elegantly beneath the "Quit".
> Making changes in PDB by removing the '\n' uglifies the Docstring, where the word "exit" starts on column 1.
>
> Making changes in IPython debugger.py:
> Escaping logic can be added to the docstring wrapping function to handle '\n'. This will likely make the code ugly.
>
> Making changes in Sphinx: 
> Where "WARNING: Unexpected Indentation" is thrown, handle docstrings with '\n'. Code needs to be investigated in more details.

**Comment by tk0miya** [comment] 2018-02-19 02:03
>Snippet of document shows option "exit" is missing:

The original python doc is marked up like following:
```
.. pdbcommand:: q(uit)

   Quit from the debugger.  The program being executed is aborted.
```
(at https://github.com/python/cpython/blob/master/Doc/library/pdb.rst)

It seems docstring is not used (or converted by another tool).


```
1106     def do_quit(self, arg):
1107         """q(uit)\nexit
1108         Quit from the debugger. The program being executed is aborted.
1109         """
```
This docstring is interpreted as below:
```
q(uit)
next
        Quit from the debugger. The program being executed is aborted.
```

As a result, the third line (starts with "Quit from ...") is treated as indented suddenly.
Please update your docstring to correct one.

Thanks,

Note: You can check how the docstring is interpreted using `inspect.getdoc()`

**Comment by tk0miya** [comment] 2018-03-06 16:07
I'm closing this now because this is not a bug of Sphinx.
Thanks,

**Closed as completed by tk0miya** 2018-03-06 16:07 UTC
Labels: type:question, extensions:autodoc

**Comment by jzf2101** [comment] 2018-03-07 17:52
I believe we looked at this but found cpython couldn't fix it? @douglatornell
