### ISSUE TITLE
Disable italics in :doc: link

### ISSUE THREAD

**Issue by nicoco007** [sphinx-doc/sphinx#2194] opened 2015-12-25 06:22 UTC
I have a bunch of `:doc:` references in my documentation, but all the links that are created this way are italicised. Is there a way to disable this? I tried using different themes and they all have the same problem.

**Comment by tk0miya** [comment] 2015-12-26 03:57
Sphinx represents `:doc:` references as `<em>` elements in HTML.
But, Sphinx does not define any styles for `<em>` elements.
So your problem is caused by default settings of your browser.

If you want to change the styles for them, please setup user stylesheets.

(1) Create stylesheet under `_static` directory in your Sphinx project (ex. `_static/custom.css')

```
/* show <em> items as normal fonts */
em {
    font-style: normal;
}
```

(2) Load the stylesheet. Append following lines into `conf.py`.

```
def setup(app):
    app.add_stylesheet('custom.css')
```

(3) Regenerate HTML by `make clean html` command.

I think this is not a bug, so I'm closing the issue.
if you have any problem about this, please reopen it.

Thanks,

**Closed as completed by tk0miya** 2015-12-26 03:57 UTC

**Comment by nicoco007** [comment] 2015-12-26 07:51
I see. That's somewhat annoying, but your fix works. I feel a bit stupid for not thinking of this earlier. Thanks!
