### ISSUE TITLE
After upgrade to 1.5, primary_domain errors

### ISSUE THREAD

**Issue by h4ckninja** [sphinx-doc/sphinx#3215] opened 2016-12-09 22:26 UTC
I had 1.4.8 installed and a project used `primary_domain = 'php'` without problem. However, when I upgraded to 1.5, the same project produces the following error:

~~~
WARNING: primary_domain 'php' not found, ignored.
~~~

If I change `primary_domain = 'python'`, I get python not found.

What can I provide to help debug this?

**Comment by shimizukawa** [comment] 2016-12-11 12:52
phpdomain works fine in my environment.
I attach logs and a sample project.
```
root@5bc6bb625767:/opt/3215# python -V
Python 2.7.12

root@5bc6bb625767:/opt/3215# sphinx-build --version
Sphinx (sphinx-build) 1.5

root@5bc6bb625767:/opt/3215# pip install sphinxcontrib-phpdomain
Collecting sphinxcontrib-phpdomain
  Downloading sphinxcontrib_phpdomain-0.2.1-py2-none-any.whl
Requirement already satisfied: sphinx>=1.3 in /usr/local/lib/python2.7/site-packages (from sphinxcontrib-phpdomain)
Requirement already satisfied: requests in /usr/local/lib/python2.7/site-packages (from sphinx>=1.3->sphinxcontrib-phpdomain)
Requirement already satisfied: babel!=2.0,>=1.3 in /usr/local/lib/python2.7/site-packages (from sphinx>=1.3->sphinxcontrib-phpdomain)
Requirement already satisfied: imagesize in /usr/local/lib/python2.7/site-packages (from sphinx>=1.3->sphinxcontrib-phpdomain)
Requirement already satisfied: Pygments>=2.0 in /usr/local/lib/python2.7/site-packages (from sphinx>=1.3->sphinxcontrib-phpdomain)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python2.7/site-packages (from sphinx>=1.3->sphinxcontrib-phpdomain)
Requirement already satisfied: docutils>=0.11 in /usr/local/lib/python2.7/site-packages (from sphinx>=1.3->sphinxcontrib-phpdomain)
Requirement already satisfied: alabaster<0.8,>=0.7 in /usr/local/lib/python2.7/site-packages (from sphinx>=1.3->sphinxcontrib-phpdomain)
Requirement already satisfied: Jinja2>=2.3 in /usr/local/lib/python2.7/site-packages (from sphinx>=1.3->sphinxcontrib-phpdomain)
Requirement already satisfied: snowballstemmer>=1.1 in /usr/local/lib/python2.7/site-packages (from sphinx>=1.3->sphinxcontrib-phpdomain)
Requirement already satisfied: pytz>=0a in /usr/local/lib/python2.7/site-packages (from babel!=2.0,>=1.3->sphinx>=1.3->sphinxcontrib-phpdomain)
Requirement already satisfied: MarkupSafe in /usr/local/lib/python2.7/site-packages (from Jinja2>=2.3->sphinx>=1.3->sphinxcontrib-phpdomain)
Installing collected packages: sphinxcontrib-phpdomain
Successfully installed sphinxcontrib-phpdomain-0.2.1

oot@5bc6bb625767:/opt/3215# pip list --format=columns
Package                 Version
----------------------- -----------
alabaster               0.7.9
Babel                   2.3.4
configparser            3.5.0
docutils                0.13.1
enum34                  1.1.6
flake8                  3.0.4
funcsigs                1.0.2
html5lib                0.999999999
imagesize               0.7.1
Jinja2                  2.8
MarkupSafe              0.23
mccabe                  0.5.2
mock                    2.0.0
nose                    1.3.7
nose-timer              0.6.0
pbr                     1.10.0
pip                     9.0.1
pycodestyle             2.0.0
pyflakes                1.2.3
Pygments                2.1.3
pytz                    2016.10
requests                2.12.3
setuptools              28.6.0
six                     1.10.0
snowballstemmer         1.2.1
Sphinx                  1.5
sphinx-rtd-theme        0.1.9
sphinxcontrib-phpdomain 0.2.1
SQLAlchemy              1.1.2
termcolor               1.1.0
virtualenv              15.0.3
webencodings            0.5
wheel                   0.29.0
Whoosh                  2.7.4

root@5bc6bb625767:/opt/3215# make html
Running Sphinx v1.5
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1 source files that are out of date
updating environment: [config changed] 1 added, 0 changed, 0 removed
reading sources... [100%] index
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index
generating indices... genindex
writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded.

Build finished. The HTML pages are in _build/html.
```

* project example: [3215.zip](https://github.com/sphinx-doc/sphinx/files/644437/3215.zip)

@micheal  can you please check your environment?

**Comment by jeromegamez** [comment] 2016-12-26 20:50
I had the same issue, and I "solved" it by removing the `primary_domain` line from the `conf.py` file and making sure that all my code blocks are set up correctly.

**Comment by tk0miya** [comment] 2017-01-02 06:13
Any updates?

>If I change primary_domain = 'python', I get python not found.

BTW, the python domain which sphinx provides is named as "py".
So please configure like following:
```
primary_domain = 'py'
```

**Comment by tk0miya** [comment] 2017-01-08 04:37
We could not reproduce the problem, so I close this now.
Please reopen if you still have the problem.

Thanks,

**Closed as completed by tk0miya** 2017-01-08 04:37 UTC
Labels: type:question, domain

**Comment by pinepain** [comment] 2018-02-26 19:37
After carefully reading `conf.py` what @shimizukawa provided in the project example, I noticed that you have to add `sphinxcontrib.phpdomain` to the list of extensions. It looks like quite common misunderstanding for newcomers, so I'd like to cover this case with pointing at it:

In case you hit the same issue like I did, having something like 

```py
primary_domain = 'php'

extensions = [
    'sphinxcontrib.phpdomain'
]
```

in your `conf.py` should help.

**Comment by tk0miya** [comment] 2018-02-27 01:51
Hmm... it seems the document of phpdomain does not mention about `conf.py`.
http://pythonhosted.org/sphinxcontrib-phpdomain/#install

I guess it was reason of this issue.
