### ISSUE TITLE
module anchor incorrect in objects.inv

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#951] opened 2015-01-03 01:19 UTC
I use sphinx.ext.intersphinx to print out objects.inv in the official python 2.7 and 2.6 doc and their anchors differ.

py2.7:

u'zlib': (u'Python', u'2.7', u'library/zlib.html#zlib', u'-')

py2.6:

u'zlib': (u'Python',
          u'2.6',
          u'library/zlib.html#module-zlib',
'-')

If you look into library/zlib.html in py2.7, you will find no anchor "zlib".

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/951
- Originally reported by: [leo2007](https://bitbucket.org/leo2007)
- Originally created at: 2012-06-22T13:51:04.343

**Comment by shimizukawa** [comment] 2015-01-03 01:19
_From Daniel Neuhäuser on 2013-04-02 17:29:25+00:00_

This causes the linkcheck builder to always fail with Sphinx 1.2.x if intersphinx is used.

**Comment by francoisfreitag** [comment] 2020-11-22 19:47
I cannot reproduce this issue. I tried the following:

```console
$ python -msphinx.ext.intersphinx https://docs.python.org/3/objects.inv | grep zlib
```

The result lines contain the `#modules-zlib` anchor, and do not contain `#zlib`.
```
        zlib                                     library/zlib.html#module-zlib
```

Has it been fixed since? If you can reproduce, can you precise the steps to reproduce?

**Comment by tk0miya** [comment] 2020-11-25 15:56
This is an issue created 8 years ago. It seems resolved at present. So I'm closing this now.
Thank you for your investigation :-)

**Closed as completed by tk0miya** 2020-11-25 15:56 UTC
Labels: type:bug, extensions:intersphinx
