### ISSUE TITLE
UnicodeDecodeError during make html

### ISSUE THREAD

**Issue by sevaader** [sphinx-doc/sphinx#2335] opened 2016-02-18 11:09 UTC
> # Sphinx version: 1.3.5
> # Python version: 2.7.0 (CPython)
> # Docutils version: 0.12 release
> # Jinja2 version: 2.8
> # Last messages:
> # Running Sphinx v1.3.5
> # loading pickled environment...
> # not yet created
> # building [mo]: targets for 0 po files that are out of date
> # building [html]: targets for 18 source files that are out of date
> # updating environment:
> # 18 added, 0 changed, 0 removed
> # reading sources... [  5%] CondorBDD
> # Loaded extensions:
> # sphinx.ext.todo (1.3.5) from C:\Python27\lib\site-packages\sphinx\ext\todo.pyc
> # sphinx.ext.autodoc (1.3.5) from C:\Python27\lib\site-packages\sphinx\ext\autodoc.pyc
> # alabaster (0.7.7) from C:\Python27\lib\site-packages\alabaster__init__.pyc
> # sphinx.ext.viewcode (1.3.5) from C:\Python27\lib\site-packages\sphinx\ext\viewcode.pyc
> # sphinx.ext.doctest (1.3.5) from C:\Python27\lib\site-packages\sphinx\ext\doctest.pyc
> 
> Traceback (most recent call last):
>   File "C:\Python27\lib\site-packages\sphinx\cmdline.py", line 244, in main
>     app.build(opts.force_all, filenames)
>   File "C:\Python27\lib\site-packages\sphinx\application.py", line 266, in build
>     self.builder.build_update()
>   File "C:\Python27\lib\site-packages\sphinx\builders__init__.py", line 251, in build_update
>     'out of date' % len(to_build))
>   File "C:\Python27\lib\site-packages\sphinx\builders__init__.py", line 265, in build
>     self.doctreedir, self.app))
>   File "C:\Python27\lib\site-packages\sphinx\environment.py", line 618, in update
>     self._read_serial(docnames, app)
>   File "C:\Python27\lib\site-packages\sphinx\environment.py", line 638, in _read_serial
>     self.read_doc(docname, app)
>   File "C:\Python27\lib\site-packages\sphinx\environment.py", line 791, in read_doc
>     pub.publish()
>   File "C:\Python27\lib\site-packages\docutils\core.py", line 217, in publish
>     self.settings)
>   File "C:\Python27\lib\site-packages\sphinx\environment.py", line 128, in read
>     self.parse()
>   File "C:\Python27\lib\site-packages\docutils\readers__init__.py", line 78, in parse
>     self.parser.parse(self.input, document)
>   File "C:\Python27\lib\site-packages\docutils\parsers\rst__init__.py", line 172, in parse
>     self.statemachine.run(inputlines, document, inliner=self.inliner)
>   File "C:\Python27\lib\site-packages\docutils\parsers\rst\states.py", line 170, in run
>     input_source=document['source'])
>   File "C:\Python27\lib\site-packages\docutils\statemachine.py", line 239, in run
>     context, state, transitions)
>   File "C:\Python27\lib\site-packages\docutils\statemachine.py", line 460, in check_line
>     return method(match, context, next_state)
>   File "C:\Python27\lib\site-packages\docutils\parsers\rst\states.py", line 2726, in underline
>     self.section(title, source, style, lineno - 1, messages)
>   File "C:\Python27\lib\site-packages\docutils\parsers\rst\states.py", line 327, in section
>     self.new_subsection(title, lineno, messages)
>   File "C:\Python27\lib\site-packages\docutils\parsers\rst\states.py", line 395, in new_subsection
>     node=section_node, match_titles=True)
>   File "C:\Python27\lib\site-packages\docutils\parsers\rst\states.py", line 282, in nested_parse
>     node=node, match_titles=match_titles)
>   File "C:\Python27\lib\site-packages\docutils\parsers\rst\states.py", line 195, in run
>     results = StateMachineWS.run(self, input_lines, input_offset)
>   File "C:\Python27\lib\site-packages\docutils\statemachine.py", line 239, in run
>     context, state, transitions)
>   File "C:\Python27\lib\site-packages\docutils\statemachine.py", line 460, in check_line
>     return method(match, context, next_state)
>   File "C:\Python27\lib\site-packages\docutils\parsers\rst\states.py", line 2726, in underline
>     self.section(title, source, style, lineno - 1, messages)
>   File "C:\Python27\lib\site-packages\docutils\parsers\rst\states.py", line 327, in section
>     self.new_subsection(title, lineno, messages)
>   File "C:\Python27\lib\site-packages\docutils\parsers\rst\states.py", line 395, in new_subsection
>     node=section_node, match_titles=True)
>   File "C:\Python27\lib\site-packages\docutils\parsers\rst\states.py", line 282, in nested_parse
>     node=node, match_titles=match_titles)
>   File "C:\Python27\lib\site-packages\docutils\parsers\rst\states.py", line 195, in run
>     results = StateMachineWS.run(self, input_lines, input_offset)
>   File "C:\Python27\lib\site-packages\docutils\statemachine.py", line 239, in run
>     context, state, transitions)
>   File "C:\Python27\lib\site-packages\docutils\statemachine.py", line 460, in check_line
>     return method(match, context, next_state)
>   File "C:\Python27\lib\site-packages\docutils\parsers\rst\states.py", line 2299, in explicit_markup
>     nodelist, blank_finish = self.explicit_construct(match)
>   File "C:\Python27\lib\site-packages\docutils\parsers\rst\states.py", line 2311, in explicit_construct
>     return method(self, expmatch)
>   File "C:\Python27\lib\site-packages\docutils\parsers\rst\states.py", line 2054, in directive
>     directive_class, match, type_name, option_presets)
>   File "C:\Python27\lib\site-packages\docutils\parsers\rst\states.py", line 2103, in run_directive
>     result = directive_instance.run()
>   File "C:\Python27\lib\site-packages\sphinx\ext\autodoc.py", line 1469, in run
>     documenter.generate(more_content=self.content)
>   File "C:\Python27\lib\site-packages\sphinx\ext\autodoc.py", line 788, in generate
>     self.analyzer = ModuleAnalyzer.for_module(self.real_modname)
>   File "C:\Python27\lib\site-packages\sphinx\pycode__init__.py", line 212, in for_module
>     obj = cls.for_file(source, modname)
>   File "C:\Python27\lib\site-packages\sphinx\pycode__init__.py", line 195, in for_file
>     obj = cls(fileobj, modname, filename)
>   File "C:\Python27\lib\site-packages\sphinx\pycode__init__.py", line 232, in **init**
>     self.code = self.source.read().decode(self.encoding)
>   File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
>     return codecs.utf_8_decode(input, errors, True)
> UnicodeDecodeError: 'utf8' codec can't decode byte 0xe0 in position 17587: invalid continuation byte

**Comment by tk0miya** [comment] 2016-02-19 16:58
It looks like encoding problem of your python code.
Could you show me your sphinx project including python scripts or reproducible minimal project?

**Comment by tk0miya** [comment] 2016-04-27 03:37
It seems not a bug of sphinx. So I close this now.
Please reopen if you get more information about this.

Thanks,

**Closed as completed** 2016-05-02 02:55 UTC
Labels: extensions:autodoc
