### ISSUE TITLE
Coverage fails on metaclasses

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#911] opened 2015-01-03 01:10 UTC
Trying to generate code coverage on a metaclass fails with the traceback given in the attached file.

I confirmed that it is a problem with metaclasses as such:

Python 2.6.5 (r265:79063, Apr 16 2010, 13:09:56) 
[GCC 4.4.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > import inspect
> > > class Test(type):
> > > ...     pass
> > > ... 
> > > inspect.getmembers(Test, inspect.ismethod)
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/lib/python2.6/inspect.py", line 252, in getmembers
> > >     value = getattr(object, key)
> > > AttributeError: **abstractmethods**

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/911
- Originally reported by: Brett Ponsler
- Originally created at: 2012-04-09T20:42:47.882

**Comment by shimizukawa** [comment] 2015-01-03 01:10
_From Georg Brandl on 2014-10-18 07:29:33+00:00_

Removing version: 1.0.1 (automated comment)

**Comment by birkenfeld** [comment] 2015-07-25 09:50
I can't reproduce your example with Python 2.7 - I suppose it was fixed in Python since.

**Closed as completed by birkenfeld** 2015-07-25 09:50 UTC
Labels: type:bug, extensions
