### ISSUE TITLE
Cannot I disable constant expansion in default argument values?

### ISSUE THREAD

**Issue by Felix-neko** [sphinx-doc/sphinx#1806] opened 2015-03-25 14:29 UTC
I have some functions like

```
f(x, propagation_speed=scipy.constants.c)
```

I run `sphinx-apidoc` to generate documentation on them and them `make html` to get final HTML data.

Alas, Sphinx expands the constants and gives me something like

```
f(x, propagation_speed=299792458.0)
```

Cannot I somehow disable the default values expansion in docstrings? Could I add something to `conf.py`?

**Comment by Felix-neko** [comment] 2015-03-25 14:48
P.S. Also, even if I write

```
f(x, propagation_speed=3e8)
```

Sphinx gives me
    f(x,  propagation_speed=300000000.0)

It's extremely annoying to count the number of zeros.
^__^

**Comment by Felix-neko** [comment] 2015-04-03 22:45
P.P.S. If you're importing the modules, it's possible to get their path by `__file__` attribute and them parse them as text files. So it's possible, for example, to pass the full **text** of function or method signature to `autodoc-process-signature`.

**Comment by danielshahaf** [comment] 2016-08-11 06:18
Duplicate of #759 ?

**Comment by tk0miya** [comment] 2018-03-06 14:58
We'll track this issue in #759.
Thank you for reporting

**Closed as completed** 2018-03-06 14:57 UTC
Labels: closed:duplicate, extensions:autodoc
