### ISSUE TITLE
roles lost in text of a handwritten directive

### ISSUE THREAD

**Issue by JulienPalard** [sphinx-doc/sphinx#5554] opened 2018-10-19 13:06 UTC
### Problem

This directive https://github.com/python/cpython/blob/514bbfc7fc4dcb868d4364632ad14c0533af154f/Doc/tools/extensions/pyspecific.py#L136 works with html builder but breaks with gettext builder. More specifically the roles inside the directive are lost.

#### Procedure to reproduce the problem

(Tarball of following setup availabe here: https://mdk.fr/bugsphinx.tar.bz2)

Given the following `conf.py`:
```
import sys, os

sys.path.append(os.path.abspath("./"))
extensions = ["pyspecific"]
```

Given the following `foo.rst`:
```
Pouette

.. availability:: :func:`len`

Pouette
```

Given an empty `contents.rst` file.

Given the following `pyspecific.py` file:
```
from docutils.parsers.rst import Directive
from docutils import nodes


class Availability(Directive):

    has_content = False
    required_arguments = 1
    optional_arguments = 0
    final_argument_whitespace = True

    def run(self):
        pnode = nodes.paragraph(classes=["availability"])
        n, m = self.state.inline_text(
            ":ref:`Availability <availability>`: ", self.lineno
        )
        pnode.extend(n + m)
        n, m = self.state.inline_text(self.arguments[0], self.lineno)
        pnode.extend(n + m)

        return [pnode]


def setup(app):
    app.add_directive("availability", Availability)
    return {"version": "1.0", "parallel_read_safe": True}
```

Running: 
```
rm -fr build/; sphinx-build -v -b gettext . build/po
cat build/po/foo.pot 
```

gives:
```
[...]
msgid "Availability: len()"
[...]
```

I expected:

```
[...]
msgid "Availability: :func:`len`"
[...]
```

### Diagnostic already done

In `gettext.py` in `write_doc`, the call to `extract_messages` gives "Availability: len()", (the "wrong" one).

so I went to check in `extract_messages`:
```
(Pdb) print(node.pformat())
<paragraph classes="availability">
    <inline classes="xref std std-ref">
        Availability
    : 
    <literal classes="xref py py-func">
        len()
```
this looks OK, but node.rawsource already contains role-stripped text, which looks bad as it's what's returned.

Not sure if it help :(

### Environment info
- OS: Debian Buster
- Python version: 3.6.6
- Sphinx version: 1.8.1

See also: https://bugs.python.org/issue35015

**Comment by tirkarthi** [comment] 2018-10-19 13:49
I tried with Python docs and on every node there is `astext` method where in case of ":func:`len`" then `node.astext()` returns `len()` . There several places where `node.rawsource = node.astext()` is done. I tried putting print statements there but couldn't help. `write_doc` gets a `doctree` which is then passed to `extract_messages`. `doctree` itself has the `len()` version instead of role. I don't know if it happens inside the `read_doc` . I searched for sphinx issues but nothing. I don't know if mine is the right approach. I will wait for Sphinx experts to get some input since internals are little hard to debug for me.

Thanks much for the small reproducer that I can use for further debugging instead of building Python docs that is time consuming even with cache enabled :)

**Comment by JulienPalard** [comment] 2018-11-06 08:35
I don't really understand why it works this way, but I fixed it:

https://github.com/python/cpython/pull/10360/files

Am I hiding a sphinx bug, or am I just doing it right? I have no idea at the moment.

**Comment by tk0miya** [comment] 2018-11-25 02:50
Our gettext builder expects all `paragraph` node has its `rawsource` to translate the node. If none, Sphinx calls `astext()` of the node. So your hack is good!

**Comment by JulienPalard** [comment] 2018-11-25 21:42
Nice to hear þ

Is it documented somewhere?

**Comment by tk0miya** [comment] 2018-12-25 16:01
No, it is the behavior of reST parser of docutils, not documented.

**Comment by tk0miya** [comment] 2019-01-13 14:18
I'm closing this because of not a bug.

**Closed as completed by tk0miya** 2019-01-13 14:18 UTC
Labels: type:question, internals:internationalisation
