### ISSUE TITLE
Search is broken in 1.5

### ISSUE THREAD

**Issue by Blendify** [sphinx-doc/sphinx#3203] opened 2016-12-07 18:08 UTC
After upgrading to sphinx 1.5 the search is not finding any results.

Searching "blender" on https://www.blender.org/manual/search.html gives accurate results (built with 1.4.9).
However, if you build it yourself using 1.5 doing the same thing will fail, it will just search endlessly.

The project is located here: https://developer.blender.org/diffusion/BM/

**Comment by LindsayHill** [comment] 2016-12-08 19:09
We saw something similar with github.com/StackStorm/st2docs / docs.stackstorm.com. For now, we have pinned sphinx to 1.4.9,  which works for us.

**Comment by erik-sn** [comment] 2016-12-11 03:57
Digging into the chrome debugger a little, it seems the `DOCUMENTATION_OPTIONS` object is missing the `SOURCELINK_SUFFIX` field. This is giving an unhandled exception in searchtools.js.  This object looks like it is initialized through templating [here](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/themes/basic/layout.html#L87). 

Here's a screen shot of my debugger with variable values:
![image](https://cloud.githubusercontent.com/assets/17732472/21077974/e8111bd6-bf2b-11e6-905d-86e76f92dc71.png)
![image](https://cloud.githubusercontent.com/assets/17732472/21077976/1310b85a-bf2c-11e6-82b6-e82a92dfea7f.png)

**Comment by tk0miya** [comment] 2016-12-11 12:35
Did you use sphinx_rtd_theme? If so, It's a bug of the theme.
https://github.com/snide/sphinx_rtd_theme/pull/346

**Comment by erik-sn** [comment] 2016-12-11 14:03
Yep that's it, thank you for pointing me to it.

**Comment by tk0miya** [comment] 2016-12-11 14:25
For now, it seems not a bug of sphinx.
So I close this now.
Please reopen if you still have same problem with bare sphinx.

Thanks,

**Closed as completed by tk0miya** 2016-12-11 14:25 UTC
Labels: html search
