### ISSUE TITLE
Error with Make PDF

### ISSUE THREAD

**Issue by Seif-Abaza** [sphinx-doc/sphinx#6901] opened 2019-12-08 09:52 UTC
# Sphinx version: 2.2.1
# Python version: 3.6.9 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/Sphinx-2.2.1-py3.6.egg/sphinx/cmd/build.py", line 275, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/usr/local/lib/python3.6/dist-packages/Sphinx-2.2.1-py3.6.egg/sphinx/application.py", line 236, in __init__
    self.setup_extension(extension)
  File "/usr/local/lib/python3.6/dist-packages/Sphinx-2.2.1-py3.6.egg/sphinx/application.py", line 395, in setup_extension
    self.registry.load_extension(self, extname)
  File "/usr/local/lib/python3.6/dist-packages/Sphinx-2.2.1-py3.6.egg/sphinx/registry.py", line 475, in load_extension
    mod = import_module(extname)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/keratos/.local/lib/python3.6/site-packages/rst2pdf/pdfbuilder.py", line 129
    except Exception, e:
                    ^
SyntaxError: invalid syntax

**Comment by jfbu** [comment] 2019-12-08 10:26
This is a duplicate of #6828 
> This is caused by rst2pdf extension you added. Unfortunately it still does not support python3.
Thanks,

Thanks for reporting

**Closed as completed by jfbu** 2019-12-08 10:26 UTC
Labels: closed:duplicate, type:question
