### ISSUE TITLE
type hints is not complete in "Return type"

### ISSUE THREAD

**Issue by lester-wu** [sphinx-doc/sphinx#8676] opened 2021-01-10 19:43 UTC
**Describe the bug**
Self-defined type hints can not display completely in `Return type` but in `Parameter`

**To Reproduce**
```
import typing
import pydantic


ResponseContent = typing.Union[
    None,
    pydantic.BaseModel
]

RequestHandler = typing.Callable[
    ...,
    typing.Awaitable[ResponseContent],
]


class DemoClass:

    def demo_method(self, arg1: RequestHandler) -> RequestHandler:
        """This is demo method."""
        pass
```
After generating docs, I got the following behavior. The `Parameters` column displays the complete type hints, but not in `Return type`.

```
Return type: BaseModel]]]

Parameters: arg1 (Callable[[..], Awaitable[Union[None, pydantic.main.BaseModel]]])
```

**Expected behavior**
```
Return type: Callable[[..], Awaitable[Union[None, pydantic.main.BaseModel]]]

Parameters: arg1 (Callable[[..], Awaitable[Union[None, pydantic.main.BaseModel]]])
```

**Your project**
No

**Screenshots**
![image](https://user-images.githubusercontent.com/68556491/104133408-63e86b80-53be-11eb-8c43-7596b7d22e86.png)

**Environment info**
- OS: MacOS Catalina 10.15.7
- Python version: 3.9
- Sphinx version: 3.4.3
- Sphinx extensions:  sphinx.ext.autodoc, recommonmark, sphinx_autodoc_typehints==1.11.1
- Extra tools: No

**Additional context**
No

**Comment by tk0miya** [comment] 2021-01-11 16:03
I can't reproduce the bug. Could you make an example project for this case?

Note: On my local, `Union[None, ...]` is rendered as `Optional[...]`. I don't understand what is happened in your environment. I doubt this trouble is related to sphinx_autodoc_typehints. If possible, please try again without it.

**Comment by lester-wu** [comment] 2021-01-13 16:46
Thank you. After removal of `sphinx_autodoc_typehints `, it can display the complete signature of self-defined typing. There might have a conflict between `sphinx` and `sphinx_autodoc_typehints`.

> Note: On my local, Union[None, ...] is rendered as Optional[...]

This is weird. But I think the `Union[None, ...]` is also correct, since I declare to use `typing.Union`

**Comment by tk0miya** [comment] 2021-01-16 13:00
The python interpreter considers `Union[None, T]` equals `Optional[T]`. Internally, they are completely the same.
```
$ python
Python 3.9.1 (default, Dec 12 2020, 22:52:49)
[Clang 11.0.3 (clang-1103.0.32.62)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from typing import Optional, Union
>>> Union[None, int]
typing.Optional[int]
>>> Optional[int]
typing.Optional[int]
```

Anyway, it seems this trouble would be caused by sphinx_autodoc_typehints extension. So I'm closing this now. Thanks,

**Closed as completed by tk0miya** 2021-01-16 13:00 UTC
Labels: type:bug, extensions:autodoc
