### ISSUE TITLE
Exception sphinx-automodapi (dll load failed)

### ISSUE THREAD

**Issue by ninafiona** [sphinx-doc/sphinx#5759] opened 2018-12-11 16:59 UTC
Exception occurred:
  File "C:\ProgramData\Anaconda3\lib\site-packages\sphinx_automodapi\utils.py", line 78, in find_mod_objs
    __import__(modname)
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden. (Module not found)

**Comment by tk0miya** [comment] 2018-12-15 09:41
I guess you need to set up DLL files before running sphinx_automodapi. Unfortunately, the extension does not output logs so I can't understand what happened in the process.
Anyway, this is not a bug of Sphinx-core itself.
So I'm closing this now.

Thanks,

**Closed as completed by tk0miya** 2018-12-15 09:41 UTC
Labels: type:question
