### ISSUE TITLE
Not able to generate search index file while make html

### ISSUE THREAD

**Issue by marimuthum** [sphinx-doc/sphinx#6566] opened 2019-07-08 21:38 UTC
**Describe the bug**
Not able to search the text.
while generating html file using make command it gives the below error.

dumping search index in English (code: en) ... 
Exception occurred:
  File "/usr/lib64/python2.7/site-packages/sphinx/search/__init__.py", line 379, in freeze
    docnames, titles = zip(*sorted(self._titles.items()))
ValueError: need more than 0 values to unpack

using python 2.7
Sphinx v1.8.5

Please help me to resolve the issue

**Environment info**
- OS: RHEL 7
- python 2.7
- Sphinx v1.8.5
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.doctest',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.ifconfig',
    'sphinx.ext.graphviz',
    'sphinxcontrib.redoc',
    'sphinxcontrib.exceltable',
    'sphinxcontrib.plantuml',
    'sphinx_git',
    'sphinx_markdown_tables'
]

**Additional context**

- [e.g. URL or Ticket]

**Comment by tk0miya** [comment] 2019-07-09 17:10
Could you provide us a reproducible example? We need to reproduce the error to resolve the error. It's first time to me to see such error message.

**Comment by marimuthum** [comment] 2019-07-18 14:22
Thanks. when i run make html it gives the below error

**Comment by tk0miya** [comment] 2019-07-21 11:05
Thank you for comment. But I still can't reproduce the error from your comment. If it is hard to provide a minimal reproducible example, I'll close this issue because of not reproduced. Please share your project or give us a minimal reproducible example.
Thanks,

**Comment by jayaddison** [comment] 2024-03-14 11:24
Closing as this bugreport does not provide sufficient details to replicate the problem.  If there is still a problem here, please re-open and provide more information, and we'll investigate.

**Closed as completed by jayaddison** 2024-03-14 11:24 UTC
Labels: type:bug, html search
