### ISSUE TITLE
HtmlFormatter: dynamic CSS styles with incremental builds

### ISSUE THREAD

**Issue by blueyed** [sphinx-doc/sphinx#7258] opened 2020-03-06 06:16 UTC
I would like to use dynamic CSS styles/classes, based on content being used.
In particular it is a lexer that parses RGB true color ANSI escape codes, and generates tokens for them, e.g. `Token.Color.RGBff0000` for red foreground color.

This is based on https://github.com/chriskuehl/pygments-ansi-color, which only handles 256 colors though, and generates many classes for them.  This approach is not feasible for RGB, and I think it makes sense in general to only output classes that are actually being used.

My current hack uses a custom HtmlFormatter via `PygmentsBridge.html_formatter` (which is documented), and then stores the requested CSS classes (for token types) on its class (since new formatter instances are used for every code block).

When a new formatter gets requested I'm adding the previous dynamic token types / styles via the following (so that they end up all in the stylesheet in the end).
```python
        for ttype, style in PytestDocHtmlFormatter._update_dynamic_styles.items():
            name = formatter._get_css_class(ttype)
            formatter.ttype2class[ttype] = name
            formatter.class2style[name] = (style, ttype, len(ttype))
```
(based on what is done in `pygments.HtmlFormatter._create_stylesheet`)

Then in the formatters `get_style_defs` (which gets called from `sphinx.highlighting.get_stylesheet`) I'm saving the `super()`s return value in a file, and merge it with successive runs. (stored in `os.path.join(app.doctreedir, "dynamic_styles")`)
(I've tried to use the env's pickling, but that happens before any formatting apparently.)

What can be improved in this regard?
Is there a better method to store the state from/with formatting?

(I think this might be a nice feature to have in general, since it appears to be known what classes are used via/for highlighting (if it can be remembered/stored somehow in a better way).)

(Also note that this is not so much a problem with full/clean runs, of course, but only when there are changed files / incremental builds.  With regard to that it seems that "toctree contains reference to excluded document '…'" always triggers highlighting of module's code and "copying static files".)

**Comment by tk0miya** [comment] 2020-03-30 14:07
The highlighter module is called only on writing phase. So it is called only for modified documents on incremental build. To know what kind of literal_block is used in your project, you need to scan all of doctrees on the doctree-read event.

**Comment by tk0miya** [comment] 2020-11-12 18:06
I'm closing this now because this is not a bug.
Thanks,

**Closed as completed by tk0miya** 2020-11-12 18:06 UTC
Labels: type:question
