### ISSUE TITLE
circular references when processing "TOC tree" causes failure in Sphinx v1.3

### ISSUE THREAD

**Issue by alexjch** [sphinx-doc/sphinx#1787] opened 2015-03-17 18:33 UTC
This seems a regression (I discovered by accident)

Sphinx v1.2.3 ignores circular references (from log):

```
[13:46:00]C:\wrk1\9f333d9351f7b918\p4\assets\docs\branching\source\index.rst:: WARNING: circular toctree references detected, ignoring: branching/source/index <- branching/source/index

Sphinx v1.3 fails (from log):

[16:13:20]writing output... [ 10%] branching/source/index                                
[16:13:20]
[16:13:20]Exception occurred:
[16:13:20]  File "C:\wrk1\9f333d9351f7b918\tcpython_27_x64_v1.1\lib\site-packages\sphinx\writers\html.py", line 353, in depart_caption
[16:13:20]    node.parent.traverse(nodes.image)[0], _('Permalink to this image'))
[16:13:20]IndexError: list index out of range
[16:13:20]The full traceback has been saved in c:\tcag1\temp\buildtmp\sphinx-err-blw08i.log, if you want to report the issue to the developers.
[16:13:20]Please also report this if it was a user error, so that a better error message can be provided next time.
[16:13:20]A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Comment by alexjch** [comment] 2015-03-17 18:35
The offending file is index.rst  (notice line # 15)

```
 10 Contents:
 11 
 12 .. toctree::
 13    :maxdepth: 2
 14    
 15    index
 16 
 17 Version |version|
 18 
     ...
```

**Comment by lehmannro** [comment] 2015-03-17 21:57
I must miss something here — the error and corresponding source code looks like this is related to a `figure` instead?!  Your example properly builds in Sphinx 1.3.1 (and I cannot find any traces that such an issue could've been fixed from 1.3 to 1.3.1.)

**Comment by lehmannro** [comment] 2015-03-18 07:22
Indeed, it seems this is a duplicate of #1788.  Could you confirm you're using `graphviz`?

**Comment by alexjch** [comment] 2015-03-18 14:08
Correct graphviz is in the mix

**Closed as completed** 2015-03-19 23:36 UTC
Labels: closed:duplicate
