### ISSUE TITLE
Bug: Image translation code uses full filename incorrectly

### ISSUE THREAD

**Issue by doctorlard** [sphinx-doc/sphinx#3061] opened 2016-10-19 03:08 UTC
The `process_images` function in `environment/__init__.py` calls `search_image_for_language` in `sphinx/util/i18n.py` with the full image filename instead of the relative filename. `search_image_for_language` will always return the original file, since it will try to append the full filename to the `env.srcdir` directory, which doesn't exist.

For example, passing in `/usr/share/my-user-manual/images/screengrab.png` as an argument will test if `/usr/share/my-user-manual/images/usr/share/my-user-manual/images/screengrab.png` exists!

I'm not sure what the correct behaviour should be. We could modify `search_image_for_language` or its dependent function, `get_image_filename_for_language`, to handle absolute paths correctly, or we can modify the callers (as far as I can tell only `process_images` and `ext/graphviz.py`) to pass in only relative paths, as the function expects.

**Comment by doctorlard** [comment] 2017-06-01 03:13
Hi @tk0miya - can you tell me what the correct behaviour should be here? I'm happy to contribute a patch. This is related to (resolved) issue #3028

**Comment by tk0miya** [comment] 2017-06-01 14:53
Sphinx treats an absolute image path as a relative path from srcdir. So `/usr/share/my-user-manual/images/screengrab.png` is considered as `$SRC_DIR/usr/share/my-user-manual/images/screengrab.png`.
This behavior is not related with `search_image_for_language` setting.

I don't know where the behavior came from. But AFAIK it is already implemented at v1.0.

**Comment by tk0miya** [comment] 2017-06-25 12:42
I close this because I believe this is not a bug.
Thanks,

**Closed as completed by tk0miya** 2017-06-25 12:42 UTC
Labels: type:question, markup, internals:internationalisation

**Comment by doctorlard** [comment] 2017-09-05 09:48
@tk0miya - It is indeed a bug; process_images incorrectly tries to translate the **full path** of the image instead of the path relative to the source.
