### ISSUE TITLE
Introduce :mindepth: for TOC tree

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1606] opened 2015-01-03 11:39 UTC
It would be nice if one could define the minimum TOC level that should be displayed.

Use case: I have a page where I document multiple named tuple types where each named tuple has its own heading. Now I want to link to this page from a parent page where I'd like to have a heading "Named Tuples" and under that I include the TOC tree. Currently I have no way to get rid of the duplicated "Named Tuples" heading of the first TOC level.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1606
- Originally reported by: Maik Riechert
- Originally created at: 2014-10-26T22:57:05.490

**Comment by AA-Turner** [comment] 2022-05-23 19:48
Closing as a duplicate of #2790.

A

**Closed as not planned by AA-Turner** 2022-05-23 19:48 UTC
Labels: type:enhancement, internals:toctree
