### ISSUE TITLE
jinja2.exceptions.TemplateNotFound: toggle-primary-sidebar.html

### ISSUE THREAD

**Issue by AlexanderJuestel** [sphinx-doc/sphinx#11315] opened 2023-04-11 14:13 UTC
### Describe the bug

Referencing from https://github.com/executablebooks/sphinx-book-theme/issues/719

I would be happy to provide more information if needed. 

### How to Reproduce

The creating of the docs fails --> https://readthedocs.org/projects/gemgis/builds/20023049/

### Environment Information

```text
-
```

**Comment by adam-grant-hendry** [comment] 2023-10-18 21:38
See the root cause analysis in [`pydata-sphinx-theme` #1511](https://github.com/pydata/pydata-sphinx-theme/issues/1511) and the corresponding fix in [`sphinx-book-theme` PR #770](https://github.com/executablebooks/sphinx-book-theme/pull/770).

**Comment by adam-grant-hendry** [comment] 2023-11-02 15:53
@AlexanderJuestel You have `sphinx-book-theme` in [`extensions`](https://github.com/cgre-aachen/gemgis/blob/4311a97ac54b44fc997f5350435a0c2a2892a0bc/docs/conf.py#L43C21-L43C21) as well as `html_theme`, but it [should only be added to `html_theme`](https://github.com/executablebooks/sphinx-book-theme/pull/770#discussion_r1379425399). Remove it from `extensions` and it should work.

**Comment by picnixz** [comment] 2023-11-07 08:53
Since this issue is not related to Sphinx itself, I will close it here. Feel free to reopen it if it persists when applying the suggested fix.

**Closed as not planned** 2023-11-07 08:53 UTC
