### ISSUE TITLE
Bibliography crashes on latex build with docclass 'memoir'

### ISSUE THREAD

**Issue by ajgpitch** [sphinx-doc/sphinx#3315] opened 2017-01-08 09:42 UTC
Subject: Bibliography crashes on build with docclass 'memoir' in qutip/qutip-doc

### Problem
The latexpdf build of our document fails. To date it seems we use the 'memoir' docclass. I don't know why, this is my first attempt at building the docs (about 3 days into it now!). The problem does not occur with the 'manual' docclass, but I have to ditch our preamble (which does not bother me so long as everything works and looks ok)
Problem does not occur in v1.4.6, which is how I tracked it to a potential issue with sphinx (after about 20 hours of trying :)

#### Procedure to reproduce the problem
```
make latexpdf
```

#### Error logs / results
```
! LaTeX Error: \begin{bibitemlist} on input line 1547 ended by \end{sphinxthebibliography}.
```
#### Expected results
Create pdf including the bibliography

### Reproducible project / your project
This is not our project doc, it's the smallest reproduction of the problem I could make.
[sph1_6test-qutip-doc.tar.gz](https://github.com/sphinx-doc/sphinx/files/692010/sph1_6test-qutip-doc.tar.gz)

### Environment info
- OS: Linux mint 17
- Python version: 3.5
- Sphinx version: 1.5.1 (conda) and 1.6dev (pip)
- <Extra tools e.g.: Browser, tex or something else>

**Comment by jfbu** [comment] 2017-01-08 10:27
Thank you for the report and sorry for inconvenience!

Thanks for the small project displaying the problem.

This should fix the issue. Add these lines at the end of your file `latex_output_files/latex_preamble.tex`:

```latex
\ifdefined\endsphinxthebibliography\else
\def\endsphinxthebibliography{\endthebibliography}
\fi
\ifdefined\endsphinxtheindex\else
\def\endsphinxtheindex{\endtheindex}
\fi
```

Memo: this problem is caused by an oversight in 1a540247b which was merged in 1.5. The bug will be fixed in 1.5.2. Then the above lines are not needed but they cause no harm either.

**Comment by ajgpitch** [comment] 2017-01-08 11:07
Wow, that was quick.

Actually, I am thinking of it as serendipitous, as the whole thing looks
much better with 'manual' docclass. The preamble does not seem to be missed.
I learned a lot these last few days :)

Good to have a solution though, just in case my fellow team members point
out something I missed that makes the 'memoir' essential.

Thank you

**Comment by jfbu** [comment] 2017-01-08 12:16
Glad it worked!

Part of your `latex_preamble.tex` (the definition of `\maketitle`)  looks like an old version of `sphinxmanual.cls` from which use of the `titlepage` environment has additionally been removed  (memoir has no such environment).

But more relevant possibly is that at top of the `latex_preamble.tex` you have some use of `tikz` package for chapter titles. But this is overruled from the fact that `fncychap` key is left to default in your `conf.py`. If you want to see the effect of the TikZ code, you should add 

        'fncychap' : '',

to `latex_elements` in the conf.py. Else, there is no need to load package `tikz` in `latex_preamble.tex` as `\chapterstyle{box}` will remain without effect due to package `fncychap` which is loaded by default by Sphinx (and somehow does not create conflict with memoir but overrides its config for chapter titles)

(http://www.sphinx-doc.org/en/1.5.1/config.html#confval-latex_elements)

**Comment by jfbu** [comment] 2017-01-09 14:58
fixed at https://github.com/sphinx-doc/sphinx/commit/c9204ea95ad1ad377054526edd9533d20d783622

**Closed as completed by jfbu** 2017-01-09 14:58 UTC
Labels: type:bug, builder:latex
