### ISSUE TITLE
latex "Undefined control sequence \\hlineSomeText" for make in latex output

### ISSUE THREAD

**Issue by rpuntaie** [sphinx-doc/sphinx#4431] opened 2018-01-14 15:04 UTC
The reason is in line 1476 of writers/latex.py:

```
            self.body.append('\\hline')
````

A space needs to be added to ``\\hline``.

**Comment by jfbu** [comment] 2018-01-14 15:22
Thanks for reporting. Usually text in first cell of new row starts a new paragraph hence a ``\n`` is automatically inserted. Can you show us how rest sources are for this table and which version of Sphinx you are using?

**Comment by jfbu** [comment] 2018-01-14 15:24
We can use ``'\\hline '``  but this requires tests update, hence I would like to know concrete case needing this.

**Comment by rpuntaie** [comment] 2018-01-14 16:57
```
.. list-table::
   :name:
   :widths: 10 8 8 8 8 8 8 8 8
   :header-rows: 1

   * - SLOT
     - 0
     - 1
     - 2
     - 3
     - 4
     - 5
     - 6
     - 7

   * - Coded
   
       output
       
       state
       
       (binary)
     - 0000100
     - 0001100
     - 1011100
     - 0101100
     - 0001100
     - 0001100
     - 0000100
     - 0000000
```

**Comment by jfbu** [comment] 2018-01-14 17:24
Thanks! I will add the space as workaround, but this seems to reveal some deeper lying bug.

Indeed from

```rst
.. list-table::
   :header-rows: 1

   * - S


   * - A
   
       B

       C
```

I get this pseudoxml

```xml
        <table>
            <tgroup cols="1">
                <colspec colwidth="100">
                <thead>
                    <row>
                        <entry>
                            <paragraph>
                                S
                <tbody>
                    <row>
                        <entry>
                            <paragraph>
                                A
                            <paragraph>
                                B
                            <paragraph>
                                C
```

which looks fine but creates the  `\hlineA`  in latex output. On the other hand, from

```rst
.. list-table::
   :header-rows: 1

   * - S


   * - A
   
       B
```

I get similar 

```
        <table>
            <tgroup cols="1">
                <colspec colwidth="100">
                <thead>
                    <row>
                        <entry>
                            <paragraph>
                                S
                <tbody>
                    <row>
                        <entry>
                            <paragraph>
                                A
                            <paragraph>
                                B
 ```

which gives a non problematic ``\hline\nA`` in latex output.

@tk0miya can you look at this?

**Comment by jfbu** [comment] 2018-01-18 09:28
@tk0miya I have identified the root cause at https://github.com/sphinx-doc/sphinx/blob/1.6.6/sphinx/writers/latex.py#L1481

This then causes removal of `\n` at https://github.com/sphinx-doc/sphinx/blob/1.6.6/sphinx/writers/latex.py#L1502

I recall that https://github.com/sphinx-doc/sphinx/blob/1.6.6/sphinx/writers/latex.py#L1481 survived big refactoring of table handling by latex writer, but here it affects multi-paragraph cells which are not merged. I don't recall offhand the reason for `\n` removals done by [LaTeXTranslator.departentry()](https://github.com/sphinx-doc/sphinx/blob/1.6.6/sphinx/writers/latex.py#L1494).

I will re-examine that later (I need to review past history of changes), but it we should fix it for 1.6.7 and at time for 1.7.0.

**Comment by tk0miya** [comment] 2018-01-18 15:06
I think it is better to fix this on 1.7.x if big refactoring needed.
Anyway, I'll take a look later.

**Comment by jfbu** [comment] 2018-01-18 15:10
@tk0miya it appears it was caused by my oversight, I kept two lines unneedlessly at #3435. PR at #4452

**Comment by jfbu** [comment] 2018-01-20 09:24
Fixed at https://github.com/sphinx-doc/sphinx/pull/4452/commits/9aca29a7816c8989a7d67356f270c255cca3c2bb. Thanks for reporting!

**Closed as completed by jfbu** 2018-01-20 09:24 UTC
Labels: type:bug, builder:latex
