### ISSUE TITLE
HTML infers copyright date instead of using today from conf.py

### ISSUE THREAD

**Issue by nmattia** [sphinx-doc/sphinx#3451] opened 2017-02-24 09:46 UTC
Subject: <what happen when you do on which document project>

### Problem
- The HTML builder doesn't not seem to rely on `conf.py`'s  `today` value for setting the date. This is apparent when the copyright is displayed at the bottom of the page. Not only might the user not want to use the current system date for the copyright notice, but some systems (like [nix](https://nixos.org/nix/)) hard code the `SOURCE_DATE_EPOCH` environment variable (used indirectly by the HTML builder) to allow for reproducible builds. In this case, copyright will be stuck in the year 1970.

The use of `SOURCE_DATE_EPOCH` comes from the [`util/i18n.py`](https://github.com/sphinx-doc/sphinx/blob/029e9908c0114fe74df5c1cbf3342dd5205bcac5/sphinx/util/i18n.py) module.

#### Procedure to reproduce the problem

In a nix-shell with `python35.withPackages (ps: with ps; [ sphinx ]);`, build documentation with sphinx's generated makefile:

``` shell
$ nix-shell --pure --run "make html"
```

#### Error logs / results

The HTML shows a copyright notice from year 1970.

#### Expected results

The HTML shows a copyright notice with the current year _or_ the year defined in `conf.py`'s `today`.

### Environment info
- OS: Linux with nix package manager
- Python version: 3.5 (nix: `python35.withPackages (ps: with ps; [ sphinx ]);`)
- Sphinx version: 1.5.2 (nix: `python35.withPackages (ps: with ps; [ sphinx ]);`)
- Nixpkgs commit `deec3c1dae62e8345451cd8c4ad41134ab95e88d`

**Comment by tk0miya** [comment] 2017-02-24 14:50
Sorry, I don't know about "nix". But Sphinx does not use `today` for the last updated.
`today`  is used only for the substitution in reST notation.

>These values determine how to format the current date, used as the replacement for |today|.
>http://www.sphinx-doc.org/en/stable/config.html#confval-today

I think your expectation is wrong.

**Comment by tk0miya** [comment] 2017-03-03 15:11
Any updates?
I think this is not a bug of sphinx.
So I'd like to close this.

**Comment by nmattia** [comment] 2017-03-03 15:54
Not relevant to me anymore, happy to close. Thanks for your input.

**Closed as completed** 2017-03-03 15:53 UTC
Labels: type:question, builder:html

**Comment by chreekat** [comment] 2017-06-02 20:00
In case someone else ends up here, this probably *was* a nix-specific issue. [Nix sets SOURCE_DATE_EPOCH to "1"](https://github.com/NixOS/nixpkgs/blob/ad7bee4eb406b88c77cb53edbe9d4de44e7e692d/pkgs/stdenv/generic/setup.sh#L219) (1970-01-01T00:00:01Z) so that the nix goal of "totally reproducible builds" is met. One must explicitly set SOURCE_DATE_EPOCH to something more relevant.

**Comment by Balletie** [comment] 2018-03-16 13:09
One can set it in the generated Makefile like this:

```diff
@@ -7,3 +7,4 @@ SPHINXBUILD   = sphinx-build
 SPHINXPROJ    = InventoryAdministration
 SOURCEDIR     = .
 BUILDDIR      = _build
+SOURCE_DATE_EPOCH = $(shell git log -1 --format=%ct)
```

**Comment by dbeecham** [comment] 2018-03-18 13:55
Came here from Google to say thank you @Balletie, worked perfectly - you're helping Nix-users everywhere.

**Comment by Balletie** [comment] 2018-03-18 21:21
thanks :)

**Comment by cpitclaudel** [comment] 2021-07-11 13:38
Making a note here for the future: while the original OP was about automatically inferring dates, there *is* a problem in Nix with copyright years, and that's due to a surprising feature of Sphinx: 

https://github.com/sphinx-doc/sphinx/blob/4a2f5df9ba277f6ce2ad77812a57133a822758e9/sphinx/config.py#L394-L404

If a SOURCE_DATE_EPOCH is set, then Sphinx greps through the "copyright" option in conf.py and changes any mention of the current year to SOURCE_DATE_EPOCH.  This was a source of lots of head-scratching for us at https://github.com/coq/coq/issues/7378 (and apparently other projects, too, given this thread).  What confuses me is that this code doesn't do anything for reproducibility: the point of a reproducible build is that building twice should produce the same results, and this feature doesn't help with that. (Consider this: if the copyright string of a project is "2007-2021" in a given commit C, then two separate builds of that same commit will produce "2007-2021" both times, so reproducibility isn't harmed).

The behavior was introduced in https://github.com/sphinx-doc/sphinx/commit/7a89015a5466412597b9a0157c0ab1af1914a81a , (in PR https://github.com/sphinx-doc/sphinx/pull/2503) and was even discussed in a reproducible-builds blog post: https://reproducible-builds.org/blog/posts/53/ .  It was discussed here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=820895

Apparently, the point is to work around reproducibility bugs in other packages that have code like this:

```
copyright = u'2006-%s, Author' % time.strftime('%Y')
```

But that's a bug in those packages, not one that Sphinx should have to work around: it's trivial for these packages to use `sphinx.util.i18n.format_date` instead of `strftime` or even check the `SOURCE_DATE_EPOCH` variable.

I can propose a PR to revert 7a89015a5466412597b9a0157c0ab1af1914a81a , but not before we hear from Alexis, the author of the patch.  I have emailed him.
