### ISSUE TITLE
latexpdf figure numbering "0.1", "0.2" "0.3" when using "howto" documentclass

### ISSUE THREAD

**Issue by gm6** [sphinx-doc/sphinx#2598] opened 2016-05-30 06:11 UTC
Hi,
How to change the figure numbering from "0.1", "0.2" "0.3" ... to "1", "2" "3" ...
Any idea? Thank you!

**Comment by tk0miya** [comment] 2016-05-30 15:35
Really? In my environment, I can't reproduce that. Could you share your project or small examples?

**Comment by gm6** [comment] 2016-05-31 07:51
Hi, I should mention that I am using Jinja2-2.8 MarkupSafe-0.23 Pygments-2.1.3 docutils-0.12 sphinx-1.2.3, since I am testing https://github.com/jterrace/sphinxtr. It doesn't work with Sphinx 1.3.x or newer versions. Any suggestions?

**Comment by tk0miya** [comment] 2016-05-31 12:29
I try to reproduce using bare sphinx-1.2.3. But it works fine.
It seems this is not a bug of Sphinx, and might be a bug of sphinxtr.

**Comment by gm6** [comment] 2016-05-31 15:29
Thank you for your time! I agree. I'll dig the "sphinxtr" deeper later :)

**Comment by tk0miya** [comment] 2016-05-31 15:34
Now I close this once.
Please reopen if you get more information.

Thank you for reporting.

**Closed as completed by tk0miya** 2016-05-31 15:34 UTC
Labels: builder:latex
