### ISSUE TITLE
Sphinx's autodoc is not producing output when module has nested classes

### ISSUE THREAD

**Issue by jsabater** [sphinx-doc/sphinx#7656] opened 2020-05-11 20:52 UTC
When your module has nested classes, the `automodule` directive from the `autodoc` extension does not seem to be parsing them correctly, thus not producing any output (and not producing any errors or warnings during build).

This is an [example module](https://github.com/jsabater/genesisng/blob/master/src/genesisng/services/login.py). Any of the classes in it follows this pattern:

```python
class Name(Service):
  class SimpleIO:
  def handle(self):
    pass
```
I detected the error when upgrading from Sphinx 1.7.5 to Sphinx 3.0.3 (both cases with [rtd](https://github.com/readthedocs/readthedocs.org) theme version 0.4.3). I tested with different versions:

* 1.8.5 seems to be working fine (no warnings, correct output) with both `rtd` and `classic` themes.
* 2.4.4 works fine with the `rtd` theme but produces a [warning](https://github.com/readthedocs/sphinx_rtd_theme/issues/739) and works fine with no warnings with the `classic` theme.
* 3.0.3  does not produce the warning with the `rtd` theme but the generated content is blank with either of the themes.

I found this [issue with autosummary](https://github.com/sphinx-doc/sphinx/issues/1441), which may be related to this.

I am using Python 3.6.9 on Ubuntu 18.04. You can check my Sphinx configuration [here](https://github.com/jsabater/genesisng/tree/master/docs).

**Comment by tk0miya** [comment] 2020-05-13 12:48
On my local, the nested class is shown correctly as following:
<img width="177" alt="スクリーンショット 2020-05-13 21 44 54" src="https://user-images.githubusercontent.com/748828/81813897-fd772900-9562-11ea-8a20-a78d34479bb9.png">
I used Sphinx-3.1.0dev and alabaster theme.

Please let me know what happened in your environment. I still don't understand your problem

Note: It seems the rtd theme was fixed, but not released yet. So the warning is not an issue now.  All I can say is installing it from GitHub directly.

**Comment by tk0miya** [comment] 2020-05-13 12:51
Note: As a trial, I built genesisng with following Dockerfile. But contents are shown (not blank) on my local.
```
FROM tk0miya/sphinx-html

RUN git clone https://github.com/jsabater/genesisng
WORKDIR /docs/genesisng
RUN apt update; apt install -y `cat requirements.Debian`
RUN pip3 install -r requirements.txt
RUN pip3 install -U Sphinx
WORKDIR /docs/genesisng/docs
RUN make html
```

**Comment by jsabater** [comment] 2020-05-13 16:45
Hello, Takeshi.

Indeed, the issue seems to be fixed in what could become rtd 0.4.4, but what made me post this issue was that it was also happening with the classic theme.

So I created a virtualenv with Python 3.6.9 and cloned the sphinx and rtd repos. I built and installed the latest versions of both but, when running `make html` I got this error:
```
# Sphinx version: 3.1.0+
# Python version: 3.6.9 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 3.0.0a1
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/usr/lib/python3.6/configparser.py", line 1138, in _unify_values
    sectiondict = self._sections[section]
KeyError: 'metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jsabater/venvs/sphinx/lib/python3.6/site-packages/Sphinx-3.1.0.dev20200513-py3.6.egg/sphinx/cmd/build.py", line 279, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/jsabater/venvs/sphinx/lib/python3.6/site-packages/Sphinx-3.1.0.dev20200513-py3.6.egg/sphinx/application.py", line 244, in __init__
    self.setup_extension(extension)
  File "/home/jsabater/venvs/sphinx/lib/python3.6/site-packages/Sphinx-3.1.0.dev20200513-py3.6.egg/sphinx/application.py", line 398, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/jsabater/venvs/sphinx/lib/python3.6/site-packages/Sphinx-3.1.0.dev20200513-py3.6.egg/sphinx/registry.py", line 402, in load_extension
    mod = import_module(extname)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/jsabater/venvs/sphinx/lib/python3.6/site-packages/readthedocs-5.0.0-py3.6.egg/readthedocs/__init__.py", line 19, in <module>
    os.path.join(os.path.dirname(__file__), '..', 'setup.cfg'),
  File "/home/jsabater/venvs/sphinx/lib/python3.6/site-packages/readthedocs-5.0.0-py3.6.egg/readthedocs/__init__.py", line 14, in get_version
    return config.get('metadata', 'version')
  File "/usr/lib/python3.6/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.6/configparser.py", line 1141, in _unify_values
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'metadata'
```
I take it that you didn't get this message, did you?

I see that just yesterday rtd 5.0 was tagget, and I noticed from your post that sphinx is getting its 3.1 release some time soon, so maybe it will all be gone before I've managed to reproduce your steps, heh.

Finally, with that Docker experiment I must admit that you got me. There obviously must be some differences. Since I only have some basic knowledge of Docker (I used it, I am just no advanced used), could you please provide me with the files you used and I'll give it a try myself?

Thanks for your help anyway.

**Comment by tk0miya** [comment] 2020-05-16 13:42
Ah, sorry. It's my mistake. I've misread you that you're using "sphinx-rtd-theme", not readthedocs package. I did not check how it works.

BTW, it seems your case is a lack of configurations. I feel it is better to report it to rtd project. I'm not an expert of the package. I've never used it.

**Comment by tk0miya** [comment] 2020-12-27 15:12
Now I'm closing this because the error has not been reproduced yet.
Please file a new issue with the detailed procedure or example source if you're still in this problem.

Thanks,

**Closed as completed by tk0miya** 2020-12-27 15:12 UTC
Labels: type:bug, extensions:autodoc
