### ISSUE TITLE
unknown node type ifconfig in sphinx 5.0.0

### ISSUE THREAD

**Issue by djhoese** [sphinx-doc/sphinx#10496] opened 2022-05-31 01:35 UTC
### Describe the bug

My project's CI just switched to sphinx 5.0.0 and I'm unable to generate my documentation that depends heavily on `ifconfig`. In this particular case there seems to be an issue with doing an `.. include::` of a file that uses `ifconfig`.

```
source/overview.rst:46: WARNING: unknown node type: <ifconfig: <comment...><paragraph...><paragraph...><paragraph...>>

Exception occurred:
  File "/home/davidh/miniconda3/envs/polar2grid_py310/lib/python3.10/site-packages/docutils/nodes.py", line 2068, in unknown_departure
    raise NotImplementedError(
NotImplementedError: <class 'sphinx.writers.html5.HTML5Translator'> departing unknown node type: ifconfig
```

### How to Reproduce

```
$ git clone https://github.com/ssec/polar2grid
$ conda env create -n polar2grid -f continuous_integration/environment.yaml
$ conda activate polar2grid
$ cd doc
$ make html
```

### Expected behavior

No error.

### Your project

https://github.com/ssec/polar2grid/

### OS

Ubuntu

### Python version

3.10

### Sphinx version

5.0.0

**Comment by djhoese** [comment] 2022-05-31 01:39
I removed the `.. include` and still had issues with other `ifconfig` usage so the `.. include` isn't important.

**Comment by AA-Turner** [comment] 2022-05-31 10:22
Hi David,

Is there a single file minimal reproducer? I assume this worked on 4.5.0?

A

**Comment by djhoese** [comment] 2022-05-31 11:58
Yes it worked with older sphinx. I'll try to make a single file reproducer today.

**Comment by djhoese** [comment] 2022-05-31 15:12
`source/index.rst`:

```
Home
====

.. ifconfig:: config_bool

    .. only:: not html

        `Google <https://www.google.com>`__

    `GitHub Repository <https://github.com/ssec/polar2grid>`__


.. ifconfig:: config_bool

    .. only:: not html

        `Google <https://www.google.com>`__

    `GitHub Repository <https://github.com/ssec/polar2grid>`__
```

`source/conf.py`

```
def setup(app):
    app.add_config_value("config_bool", False, "env")

extensions = ["sphinx.ext.ifconfig"]
```

Build command:

```
rm -rf build/*; sphinx-build -b html -d build/doctrees source build/html
```

It seems my use of `.. only` is maybe a problem. I noticed that if I removed the second `ifconfig` then it was fine so something about having them back to back mayber?

**Comment by AA-Turner** [comment] 2022-05-31 15:14
Thanks David! I'll look into this now.

A

**Comment by djhoese** [comment] 2022-05-31 15:15
If I put a comment `.. a comment` between them then it works too so that is at least a workaround if this is a difficult to fix bug.

And thanks for looking into it so quickly. Appreciated.

**Comment by AA-Turner** [comment] 2022-05-31 15:37
Note for future self: self-contained script:

```python
from pathlib import Path
import shutil

from sphinx.cmd.make_mode import run_make_mode

Path("conf.py").write_text('''\
extensions = ["sphinx.ext.ifconfig"]

def setup(app):
    app.add_config_value("config_bool", False, "env")
''', encoding="utf-8")

Path("index.rst").write_text('''\
.. ifconfig:: config_bool

    `GitHub Repository <https://github.com/ssec/polar2grid>`__

.. ifconfig:: config_bool

    `GitHub Repository <https://github.com/ssec/polar2grid>`__
''', encoding="utf-8")

shutil.rmtree("_build", ignore_errors=True)
run_make_mode(["html", ".", "_build"])
```

runs as `python reproducer_10496.py`

A

**Comment by AA-Turner** [comment] 2022-05-31 16:05
The problem is in 

https://github.com/sphinx-doc/sphinx/blob/873d9f6fdababb96f0763f538e85921f7d332b70/sphinx/ext/ifconfig.py#L54-L69

specifically when the condition is false. Normally mutating a Docutils node tree whilst iterating (`doctree.findall`) is fine, but as we replace with an empty node, the second `ifconfig` node is skipped and not evaluated. The fix is to replace with a placeholder node, such as `addnodes.meta`.

A

**Comment by tk0miya** [comment] 2022-06-02 17:18
Fixed by https://github.com/sphinx-doc/sphinx/pull/10502.

**Closed as completed by tk0miya** 2022-06-02 17:18 UTC
Labels: type:bug, extensions:ifconfig
