### ISSUE TITLE
typing.TYPE_CHECKING conditonal circular imports break sphinx doc generation

### ISSUE THREAD

**Issue by henryJack** [sphinx-doc/sphinx#4072] opened 2017-09-19 09:05 UTC
Subject: typing.TYPE_CHECKING conditional imports break sphinx doc generation

### Problem
- When using the `sphinx-autodoc-typehints` extension with commented custom typings, in this case I get the following error:

#### Procedure to reproduce the problem
```
from typing import TYPECHECKING
if TYPE_CHECKING:
    from mymodule import MyClass

class B:
    def __init__(my_object `MyClass` = MyClass()):
        self.object: `MyClass` = myclass
```

#### Error logs / results
```
WARNING: error while formatting arguments for mymodule: name 'MyClass' is not defined

Exception occurred:
  File "<string>", line 1, in <module>
NameError: name 'MyClass' is not defined
```

#### Expected results

It straight up breaks the docs generator. Could it not just render as a string?

### Environment info
- OS: Windows 10
- Python version: 3.6.1
- Sphinx version: latest

**Comment by tk0miya** [comment] 2017-09-24 07:08
Thank you for reporting, but it seems your examples is not a correct python script.
Could you share the correct one for me please?

In addition, is it a bug of Sphinx? not `sphinx-autodoc-typehints`?

**Comment by henryJack** [comment] 2017-09-27 13:13
Hi, I've created a dummy repo highlighting my issue. There is a python module called `mymodule` and a `README` explaining my full step by step issue...

 https://github.com/henryJack/sphinx_issue/blob/master/README.md

**Comment by jenshnielsen** [comment] 2017-10-28 07:29
I can confirm that the Sphinx only issue exists with 1.6.5 but it appear to be fixed in Master. 

A quick bisect indicated that https://github.com/sphinx-doc/sphinx/pull/3870 fixed it.

With master the type is reported as `_ForwardRef['MyTypeName']` 

I did not try `sphinx-autodoc-typehints`

**Comment by henryJack** [comment] 2017-10-28 10:20
The issue only occurs when I use `sphinx-autodoc-typehints`, see issue here https://github.com/henryJack/sphinx_issue/blob/master/README.md#issue

**Comment by jenshnielsen** [comment] 2017-10-28 10:46
@henryJack In your example the warning `C:\dev\local_spinx_test\docs\source\mymodule.rst:10: **WARNING: error while formatting arguments for mymodule.class_a
.AClass: name 'B' is not defined**` is triggered both with and without `sphinx-autodoc-typehints` 
Without `sphinx-autodoc-typehints` I am just get the warning but the function signature is also missing from the output. If you only care about the error you are correct that the issue is with `sphinx-autodoc-typehints` but if you actually want correct output there is an issue without it too

The changes in #3870 fixes the warning and corrects the function signature without `sphinx-autodoc-typehints` unfortunately it does not fix the issue with `sphinx-autodoc-typehints`
but that issue should really be reported here https://github.com/agronholm/sphinx-autodoc-typehints

I used a cleanup version of your example here https://github.com/jenshnielsen/sphinx_issue
where I fixed the non related warnings and removed the output from git so I can do a clean rebuild

**Comment by jenshnielsen** [comment] 2017-10-28 16:10
Ok I realised that you did report it there too but did not put in a reference here. The relevant bug report is here https://github.com/agronholm/sphinx-autodoc-typehints/issues/22

**Comment by tk0miya** [comment] 2017-10-29 12:24
Eventually, is this a bug of Sphinx? If none or already resolved, I'd like to close this.

**Comment by jenshnielsen** [comment] 2017-10-29 13:24
@tk0miya IMHO there is a bug in sphinx 1.6.5 since the signature is formatet incorectly but that is fixed in Master. So I think it’s safe to close this

**Comment by tk0miya** [comment] 2017-10-29 13:35
@jenshnielsen Thank you for confirmation!

**Closed as completed by tk0miya** 2017-10-29 13:35 UTC
Labels: extensions:autodoc
