### ISSUE TITLE
make[3]: *** [ecto-sphinx] Error 2

### ISSUE THREAD

**Issue by Abduoit** [sphinx-doc/sphinx#5137] opened 2018-07-01 16:29 UTC
### Problem

I am trying to use sphinx with object-recognition-kitchen project from this [link](http://wg-perception.github.io/object_recognition_core/install.html#building-the-documentation)

When I run last command, I get the following error:

`abdu@grasp-uoit:~/ws/build$ make doxygen`

#### Procedure to reproduce the problem
```
<abdu@grasp-uoit:~/ws/build$ make doxygen>
```

#### Error logs / results
```
<abdu@grasp-uoit:~/ws/build$ make sphinx-doc
Running Sphinx v1.7.5
SYS.PATH=== ['/usr/local/bin', '/usr/local/lib/python2.7/dist-packages/Sphinx-1.7.5-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/typing-3.6.4-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/sphinxcontrib_websupport-1.1.0-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/packaging-17.1-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/requests-2.19.1-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/imagesize-1.0.0-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/alabaster-0.7.11-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/Babel-2.6.0-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/snowballstemmer-1.2.1-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/Jinja2-2.10-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/certifi-2018.4.16-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/urllib3-1.23-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/idna-2.7-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/chardet-3.0.4-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/MarkupSafe-1.0-py2.7-linux-x86_64.egg', '/opt/ros/kinetic/lib/python2.7/dist-packages', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/python2.7/dist-packages/wx-3.0-gtk2', '/home/abdu/ws/src/ork_tabletop/doc/source']
/usr/local/lib/python2.7/dist-packages/requests-2.19.1-py2.7.egg/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
WARNING: sphinx.ext.pngmath has been deprecated. Please use sphinx.ext.imgmath instead.
WARNING: unknown config value 'ecto_docs_dir' in override, ignoring
building [mo]: all of 0 po files
building [html]: all source files
updating environment: 1 added, 0 changed, 0 removed
reading sources... [100%] index                                                                                                         
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index                                                                                                          
generating indices... genindex
writing additional pages... search
copying images... [100%] example2.png                                                                                                   
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 2 warnings.

The HTML pages are in doc/html/object_recognition_tabletop.
Built target object_recognition_tabletop-sphinx
Running Sphinx v1.7.5
SYS.PATH=== ['/usr/local/bin', '/usr/local/lib/python2.7/dist-packages/Sphinx-1.7.5-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/typing-3.6.4-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/sphinxcontrib_websupport-1.1.0-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/packaging-17.1-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/requests-2.19.1-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/imagesize-1.0.0-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/alabaster-0.7.11-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/Babel-2.6.0-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/snowballstemmer-1.2.1-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/Jinja2-2.10-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/certifi-2018.4.16-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/urllib3-1.23-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/idna-2.7-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/chardet-3.0.4-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/MarkupSafe-1.0-py2.7-linux-x86_64.egg', '/opt/ros/kinetic/lib/python2.7/dist-packages', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/python2.7/dist-packages/wx-3.0-gtk2', '/home/abdu/ws/src/ecto/doc/kitchen', '/home/abdu/ws/src/ecto/doc/kitchen/../../ecto/python']
/usr/local/lib/python2.7/dist-packages/requests-2.19.1-py2.7.egg/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
WARNING: sphinx.ext.pngmath has been deprecated. Please use sphinx.ext.imgmath instead.
WARNING: unknown config value 'ecto_docs_dir' in override, ignoring
loading intersphinx inventory from http://plasmodic.github.com/ecto_ros/objects.inv...
intersphinx inventory has moved: http://plasmodic.github.com/ecto_ros/objects.inv -> http://plasmodic.github.io/ecto_ros/objects.inv
loading intersphinx inventory from http://plasmodic.github.com/ecto_opencv/objects.inv...
intersphinx inventory has moved: http://plasmodic.github.com/ecto_opencv/objects.inv -> http://plasmodic.github.io/ecto_opencv/objects.inv
loading intersphinx inventory from http://plasmodic.github.com/ecto_image_pipeline/objects.inv...
intersphinx inventory has moved: http://plasmodic.github.com/ecto_image_pipeline/objects.inv -> http://plasmodic.github.io/ecto_image_pipeline/objects.inv
loading intersphinx inventory from http://plasmodic.github.com/ecto_openni/objects.inv...
intersphinx inventory has moved: http://plasmodic.github.com/ecto_openni/objects.inv -> http://plasmodic.github.io/ecto_openni/objects.inv
loading intersphinx inventory from http://plasmodic.github.com/ecto_pcl/objects.inv...
intersphinx inventory has moved: http://plasmodic.github.com/ecto_pcl/objects.inv -> http://plasmodic.github.io/ecto_pcl/objects.inv
building [mo]: all of 0 po files
building [html]: all source files
updating environment: 43 added, 0 changed, 0 removed
program-output about to run /home/abdu/ws/src/ecto/doc/kitchen/ecto/overview/./cell01.py                                                
Unable to run '/home/abdu/ws/src/ecto/doc/kitchen/ecto/overview/./cell01.py ' returned 1stdout: Traceback (most recent call last):
  File "/home/abdu/ws/src/ecto/doc/kitchen/ecto/overview/./cell01.py", line 2, in <module>
    from ecto.ecto_overview import Printer01
ImportError: No module named ecto_overview
/home/abdu/ws/src/ecto/doc/kitchen/ecto/overview/cells.rst:73: WARNING: 4 column based index found. It might be a bug of extensions you use: [('single', u'Cell; NopCell (module ecto.ecto_overview)', 'index-0', u'Cell; NopCell (module ecto.ecto_overview)'), ('single', u'NopCell (ecto cell in module ecto.ecto_overview)', 'index-0', u'NopCell (ecto cell in module ecto.ecto_overview)')]
/home/abdu/ws/src/ecto/doc/kitchen/ecto/overview/cells.rst:181: WARNING: 4 column based index found. It might be a bug of extensions you use: [('single', u'Cell; Printer01 (module ecto.ecto_overview)', 'index-1', u'Cell; Printer01 (module ecto.ecto_overview)'), ('single', u'Printer01 (ecto cell in module ecto.ecto_overview)', 'index-1', u'Printer01 (ecto cell in module ecto.ecto_overview)')]

Exception occurred:
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/ecto/sphinx/programoutput.py", line 165, in __missing__
    raise CalledProcessError
TypeError: __init__() takes at least 3 arguments (1 given)
The full traceback has been saved in /tmp/sphinx-err-D1rsl5.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
ecto/CMakeFiles/ecto-sphinx.dir/build.make:57: recipe for target 'ecto-sphinx' failed
make[3]: *** [ecto-sphinx] Error 2
CMakeFiles/Makefile2:474: recipe for target 'ecto/CMakeFiles/ecto-sphinx.dir/all' failed
make[2]: *** [ecto/CMakeFiles/ecto-sphinx.dir/all] Error 2
CMakeFiles/Makefile2:530: recipe for target 'ecto/CMakeFiles/sphinx-doc.dir/rule' failed
make[1]: *** [ecto/CMakeFiles/sphinx-doc.dir/rule] Error 2
Makefile:316: recipe for target 'sphinx-doc' failed
make: *** [sphinx-doc] Error 2
>
```

### Environment info
- OS: <Linux/ ubuntu 16.04>
- Python version: 2.7
- Sphinx version: Running Sphinx v1.7.5

**Comment by tk0miya** [comment] 2018-07-05 15:03
It seems ecto module raised the error. It's not a part of sphinx-core. Could you ask to the author of the module please?
```
Exception occurred:
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/ecto/sphinx/programoutput.py", line 165, in __missing__
    raise CalledProcessError
TypeError: __init__() takes at least 3 arguments (1 given)
```

Thanks,

**Comment by tk0miya** [comment] 2018-07-16 10:17
I'm closing this because this is not a bug of Sphinx-core.
Thanks,

**Closed as completed by tk0miya** 2018-07-16 10:17 UTC
Labels: type:question
