### ISSUE TITLE
Table object has no attribute stubs

### ISSUE THREAD

**Issue by clayrisser** [sphinx-doc/sphinx#6691] opened 2019-09-08 23:03 UTC
I am getting the following error with this docutils tree.

```
<document source="/home/codejamninja/Projects/sphinx-markdown-parser/examples/javascript/docs/index.md"><table><thead><row><entry>hello</entry></row></thead><tbody><row><entry>world</entry></row></tbody></table></document>
```

```
Exception occurred:
  File "/home/codejamninja/Projects/sphinx-markdown-parser/examples/javascript/env/lib/python3.6/site-packages/docutils/writers/_html_base.py", line 755, in visit_entry
    if node.parent.parent.parent.stubs[node.parent.column]:
AttributeError: 'table' object has no attribute 'stubs'
The full traceback has been saved in /tmp/sphinx-err-qoq1d_sc.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Makefile:69: recipe for target 'html' failed
make[1]: *** [html] Error 2
make[1]: Leaving directory '/home/codejamninja/Projects/sphinx-markdown-parser/examples/javascript'
Makefile:9: recipe for target 'start' failed
make: *** [start] Error 2
```

**Comment by danwos** [comment] 2020-01-03 10:45
Had the same problem and it took me half a day to solve it.

Problem for me was the order of constructing my table.
First I created my nodes, then I have put them together
```
table = nodes.table()
tgroup = nodes.tgroup()
colspec = nodes.colspec()
tbody = nodes.tbody()
row = nodes.row()
entry = nodes.entry()

row += entry
tbody += row
tgroup += colspec
tgroup += tbody
table += tgroup
```

I needed to assign tgroup directly after creation to table (and colspec):
```
table = nodes.table()

tgroup = nodes.tgroup()
table += tgroup   # change

colspec = nodes.colspec()
tgroup +=colspec  # change

tbody = nodes.tbody()
row = nodes.row()
entry = nodes.entry()

row += entry
tbody += row
tgroup += tbody

```

I can't say, why this really solves it.
Must have something to do with the visit_routines for tgroup and colspec, as they set the ``stubs`` attribute, which is needed by ``visit_entry``.
If they get not called first, ``visit_entry`` will fail

**Comment by tk0miya** [comment] 2020-01-03 14:23
I guess you're using 3rd party extension to generate the document tree. Therefore, it's not a bug of Sphinx core. Closing.
If not, please file a new issue with our issue template. We need to know how to reproduce the error.

FYI: Unfortunately, docutils spec does not have correct structure of table model. So we have to read its source code to know it.
https://docutils.sourceforge.io/docs/ref/doctree.html#table

Thanks,

**Closed as completed by tk0miya** 2020-01-03 14:23 UTC
Labels: type:question
