### ISSUE TITLE
make html cause OSError: raw write() returned invalid length

### ISSUE THREAD

**Issue by gbhlwm** [sphinx-doc/sphinx#4270] opened 2017-12-01 03:06 UTC
Subject: <what happen when you do on which document project>

### Problem
-Today, my computer update it's system win10 version,. Then i built html as usual, it returned this error. As before, it was built successfully not reported this error.
-Then,i try to sphinx-quickstart a new document, and make html, it report this error too 

#### Error logs / results
```
# Sphinx version: 1.4.9

# Python version: 3.4.4 (CPython)

# Docutils version: 0.12 release
# Jinja2 version: 2.8

# Last messages:

#   Running Sphinx v1.4.9

#   loading pickled environment...

#   not yet created
#   building [mo]: targets for 0 po files that are out of date
# Loaded extensions:

#   sphinx.ext.mathjax (1.4.9) from c:\python34\lib\site-packages\sphinx\ext\mathjax.py

#   sphinx.ext.doctest (1.4.9) from c:\python34\lib\site-packages\sphinx\ext\doctest.py

#   sphinx.ext.ifconfig (1.4.9) from c:\python34\lib\site-packages\sphinx\ext\ifconfig.py

#   alabaster (0.7.9) from c:\python34\lib\site-packages\alabaster\__init__.py
Traceback 
(most recent call last):
  File "c:\python34\lib\site-packages\sphinx\cmdline.py", 
line 244, in main
    app.build(opts.force_all, filenames)
  
File "c:\python34\lib\site-packages\sphinx\application.py", 
line 297, in build
    self.builder.build_update()
  
File "c:\python34\lib\site-packages\sphinx\builders\__init__.py", 
line 251, in build_update
    'out of date' % len(to_build))
  
File "c:\python34\lib\site-packages\sphinx\builders\__init__.py", 
line 259, in build
    self.info(bold('building [%s]' % self.name) + ': ' + summary)
  
File "c:\python34\lib\site-packages\sphinx\application.py", 
line 370, in info
    self._log(message, self._status, nonl)
  
File "c:\python34\lib\site-packages\sphinx\application.py", 
line 322, in _log
    wfile.write(message)
  
File "c:\python34\lib\site-packages\colorama\ansitowin32.py", 
line 40, in write
    self.__convertor.write(text)
  
File "c:\python34\lib\site-packages\colorama\ansitowin32.py", 
line 141, in write
    self.write_and_convert(text)
  
File "c:\python34\lib\site-packages\colorama\ansitowin32.py", 
line 169, in write_and_convert
   self.write_plain_text(text, cursor, len(text))
  
File "c:\python34\lib\site-packages\colorama\ansitowin32.py", 
line 175, in write_plain_text
    self.wrapped.flush()

OSError: raw write() returned invalid length 98 (should have been between 0 and 49)

```

### Environment info
- OS: Win10
- Python version: 3.4.4
- Sphinx version: 1.4.9

**Comment by LlianeFR** [comment] 2017-12-07 14:52
Hello,
I encountered the same bug in different modules (pip, pytest), it seems to be between python i/o and the console stream (and yes, caused by the latest win10 update), so nothing wrong with sphinx itself

https://github.com/Microsoft/vscode/issues/39149

**Comment by LlianeFR** [comment] 2017-12-11 10:07
This issue has been documented here, you can update to python 3.6 or install and enable the win_unicode_console package to solve it

https://bugs.python.org/issue32245

**Comment by gbhlwm** [comment] 2017-12-11 11:01
@LlianeFR thanks, i have a try now.

**Comment by tk0miya** [comment] 2017-12-21 15:55
It seems the bug is resolved on latest python.
Anyway, this is not a bug of Sphinx. So I close this now.
Thanks,

**Closed as completed by tk0miya** 2017-12-21 15:55 UTC
Labels: help wanted
