### ISSUE TITLE
Cannot import module which is clearly there

### ISSUE THREAD

**Issue by alper** [sphinx-doc/sphinx#8410] opened 2020-11-11 13:09 UTC
I get this error:

`ModuleNotFoundError: No module named 'rest_framework'`

If I fire up Python and I do:

`import rest_framework`

That works.

I don't understand why Sphinx would not be able to find it.

**Comment by cblegare** [comment] 2020-11-12 02:20
The python runtime you "fire up" and the one at use by sphinx might not be the same.  This can be the case if you "fire up" a runtime from a local Virtual Environment while invoking `sphinx-build` from a global site-packages.

The `conf.py` generated by `sphinx-quickstart` provide guidance to configure the Python path in these cases.
Otherwise, without a proper example, reproduction steps with a minimal installation or anything of that kind, it will be hard to troubleshoot from here.

**Comment by alper** [comment] 2020-11-12 12:01
I've searched around for solutions which seem to revolve around `sys.path` munging in `conf.py`. I don't think that's a solution or very sustainable since the dependencies that this is about are usually in a virtualenv with a directory that's hidden and highly mutable.

How would one make sure that the virtualenv python that has all the right dependencies and the python that sphinx use are the same? Why wouldn't they be the same? Can we fix this?

**Comment by cblegare** [comment] 2020-11-12 13:17
The right answer is "it depends", since we don't know how your project is structured, where `rest_framework` can be found, etc.  Could you create a minimal project that replicate this issue in a public github repository?

**Comment by tk0miya** [comment] 2020-12-25 15:55
Now I'm closing this. Please call help in the sphinx-users forum (instead of here) if you're still in trouble.
Thanks,

**Closed as completed by tk0miya** 2020-12-25 15:55 UTC
Labels: type:question

**Comment by alper** [comment] 2020-12-25 16:13
I didn't dive into sphinx, the initial experience was not very good but this:

> The python runtime you "fire up" and the one at use by sphinx might not be the same.

 and

> The conf.py generated by sphinx-quickstart provide guidance to configure the Python path in these cases.

Especially all the tutorials that recommend manual tweaking of `sys.path` (huge anti-pattern there).

Both seem like bugs to me.
