### ISSUE TITLE
Feature request: SVG support in latexpdf builder

### ISSUE THREAD

**Issue by kottkrig** [sphinx-doc/sphinx#2273] opened 2016-01-27 14:41 UTC
## Repro Steps
1. Refence a SVG in source files
2. Run `make latexpdf`

**Expected:** The SVG should be visible in the generated PDF. Preferably in vector form.
**Actual:** `make latex` produces an error `! LaTeX Error: Unknown graphics extension: .svg.` and the svg is not visible in the generated pdf.

**Comment by lehmannro** [comment] 2016-01-27 16:35
Duplicate of #1907 (fix pending in #2166).

Please use [Github search](https://help.github.com/articles/searching-issues/) ([relevant example](https://github.com/sphinx-doc/sphinx/issues?q=svg+latex)) to find related issues.

**Closed as completed by lehmannro** 2016-01-27 16:35 UTC
Labels: closed:duplicate

**Comment by Borda** [comment] 2019-12-10 08:56
@lehmannro it is not duplicity since #2166 was closed without proper solution and this as created even after the previous was closed...

**Comment by tk0miya** [comment] 2019-12-10 13:45
We already have `sphinx.ext.imgconverter` to do that as a proper solution. Could you try this please?
https://www.sphinx-doc.org/en/master/usage/extensions/imgconverter.html

**Comment by Borda** [comment] 2019-12-10 13:53
I have tried, and locally it fails but on a server it runs... https://github.com/sfneal/ImgConverter/issues/3

**Comment by tk0miya** [comment] 2019-12-10 16:37
Okay, I'll track your error. Please file a new issue with your settings. It would be very nice if there are  small reproducible example!
