### ISSUE TITLE
URL-decodable paths don't seem to work

### ISSUE THREAD

**Issue by mgeier** [sphinx-doc/sphinx#3097] opened 2016-10-25 20:14 UTC
This is not something I would do in a "normal" Sphinx project, but it came up while using auto-generated files as input to Sphinx. See https://github.com/spatialaudio/nbsphinx/issues/67.

When using a sequence like `%AB` (where `A` and `B` are any hexadecimal digits) in a source file or directory name, the link to the resulting page in the HTML output will not work.

For example, try using a source file named `%3f.rst`. Sphinx will generate a link to `%3f.html`, which the browser will interpret as URL-encoded string and will try to open a file named `?.html` (which doesn't exist).

In order for this to work, Sphinx would have to URL-encode the link to `%253f.html`. The generated file is correctly named `%3f.html`, it's just the link that's broken.

When using LaTeX output, this is not a problem. However, when using an URL-decodable file name for the `image` directive, it breaks in both HTML and LaTeX mode. Here again, the generated image file name is correct, but the image is not displayed. There may be other directives which don't work with such a file name.

Is this a bug or a feature?

For an image URL it would make sense to expect an URL-encoded string, but what about a local image?
And what about a local source file in a `toctree`?

**Comment by tk0miya** [comment] 2016-10-26 03:52
IMO, this is not an intended behavior. So it's a bug.
But I believe this is not a standard usecase. so I marked this as low priority.

**Closed as completed** 2021-09-25 05:38 UTC
Labels: type:bug, markup
