### ISSUE TITLE
Duplicate method in classes

### ISSUE THREAD

**Issue by TheKernelZ** [sphinx-doc/sphinx#12857] opened 2024-09-03 06:53 UTC
### Describe the bug

When I write docstring to method, there will be duplicated method in the global sidebar.
![image](https://github.com/user-attachments/assets/abd9a9de-bfbf-4cdc-b545-85ad77a128b8)
It only appears when I write docstring to this method, like `last`. When it comes to no docstring, it shows well, like `items`

### How to Reproduce

```make clean```
```make html```

### Environment Information

```text
Sphinx                        7.4.7
sphinx-autodoc-typehints      2.2.3
sphinx-basic-ng               1.0.0b2
sphinx_design                 0.6.0
```

### Sphinx extensions

```python
extensions = [
    "numpydoc",
    "sphinx_design",
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.doctest",
]
```

**Comment by electric-coder** [comment] 2024-09-03 07:48
This isn't a minimal reproducible example because you don't show any `.rst` files or docstrings. It's likely an error in how you structure your docstrings/rst.

**Comment by TheKernelZ** [comment] 2024-09-03 08:07
> This isn't a minimal reproducible example because you don't show any `.rst` files or docstrings. It's likely an error in how you structure your docstrings/rst.


I'm sorry for that. There's my `index.rst`
```
.. _autoapi:


API Reference
=============

.. autosummary::
   :toctree: api
   :recursive:

   boomdata.Feature
   boomdata.RolledFeature
   boomdata.GroupedFeature
   boomdata.ResampledFeature
   boomdata.IO
   boomdata.util
   boomdata.alternative
   boomdata.market
```
In my opinion, there's no difference between `first` and `items` as I've mentioned, except one have docstring.

**Comment by TheKernelZ** [comment] 2024-09-03 08:25
Thanks for your apply!
I find a field named `numpydoc_class_members_toctree`, which solved my problem.

**Comment by electric-coder** [comment] 2024-09-03 13:47
@TheKernelZ if you solved the problem please consider closing the question.

**Closed as completed** 2024-09-03 18:50 UTC
Labels: type:bug, awaiting:response
