### ISSUE TITLE
Autosummary doesn't detect toctree rst files with members named 'data'

### ISSUE THREAD

**Issue by hameerabbasi** [sphinx-doc/sphinx#4379] opened 2018-01-05 11:28 UTC
Subject: Autosummary causes issues with members named 'data'

### Problem
- Autosummary doesn't detect toctree files with members named 'data'

#### Procedure to reproduce the problem
```
rm -rf build/ docs/generated/ && python setup.py build_sphinx
```

#### Error logs / results
```
running build_sphinx
creating /Users/hameerabbasi/PycharmProjects/sphinx_test/build
creating /Users/hameerabbasi/PycharmProjects/sphinx_test/build/sphinx
creating /Users/hameerabbasi/PycharmProjects/sphinx_test/build/sphinx/doctrees
creating /Users/hameerabbasi/PycharmProjects/sphinx_test/build/sphinx/html
Running Sphinx v1.6.5
loading pickled environment... not yet created
[autosummary] generating autosummary for: index.rst
[autosummary] generating autosummary for: /Users/hameerabbasi/PycharmProjects/sphinx_test/docs/generated/sphinx_test.sptest.data.rst, /Users/hameerabbasi/PycharmProjects/sphinx_test/docs/generated/sphinx_test.sptest.test_function.rst
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1 source files that are out of date
updating environment: 2 added, 0 changed, 0 removed
reading sources... [100%] index                                                 
/Users/hameerabbasi/PycharmProjects/sphinx_test/docs/index.rst:7: WARNING: toctree references unknown document 'generated/sphinx_test.sptest.data'
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index                                                  
<autosummary>:: WARNING: toctree contains reference to nonexisting document 'generated/sphinx_test.sptest.data'
<autosummary>:: WARNING: toctree contains reference to nonexisting document 'generated/sphinx_test.sptest.data'
<autosummary>:: WARNING: toctree contains reference to nonexisting document 'generated/sphinx_test.sptest.data'
generating indices... genindex<autosummary>:: WARNING: toctree contains reference to nonexisting document 'generated/sphinx_test.sptest.data'

writing additional pages... search<autosummary>:: WARNING: toctree contains reference to nonexisting document 'generated/sphinx_test.sptest.data'

copying static files... done
[sphinx_test.zip](https://github.com/sphinx-doc/sphinx/files/1606415/sphinx_test.zip)

copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 6 warnings.
```

#### Expected results
It should detect and link the member named `data`. The other member named `test_function` is detected fine.

### Reproducible project / your project
[sphinx_test.zip](https://github.com/sphinx-doc/sphinx/files/1606424/sphinx_test.zip)

### Environment info
- OS: macOS 10.13.2
- Python version: 3.6.4
- Sphinx version: 1.6.5

**Comment by tk0miya** [comment] 2018-09-02 07:56
I found you've given `**data**` to `exclude_patterns`.
```
# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', '**tests**', '**setup**', '**extern**',
                    '**data**']
```

As a result, `generated/sphinx_test.sptest.data.rst` was generated, but ignored sphinx-core. I think this is unintended and unfortunate behavior.

IMO, the `excluce_patterns` is too strong. How about change it?

**Comment by tk0miya** [comment] 2018-09-02 11:29
I just made #5374 to give more appropriate warning message for this.

**Comment by tk0miya** [comment] 2018-09-05 13:57
Now #5374 is merged. I'm closing this now because this is not a bug.
Thanks,

**Closed as completed by tk0miya** 2018-09-05 13:57 UTC
Labels: type:bug, extensions:autosummary
