### ISSUE TITLE
Autosummary does not pass through autodoc-process-docstring as Documentation describes

### ISSUE THREAD

**Issue by tht13** [sphinx-doc/sphinx#2572] opened 2016-05-23 09:22 UTC
The sphinx [documentation](http://www.sphinx-doc.org/en/stable/ext/autosummary.html?highlight=autosummary#directive-autosummary) states that autosummaries should be passed through the [autodoc-process-signature](http://www.sphinx-doc.org/en/stable/ext/autodoc.html#event-autodoc-process-signature) event. However this does not seem to be happening for me. Looking at the code in https://github.com/sphinx-doc/sphinx/blob/master/sphinx/ext/autosummary/__init__.py it seems that the event is not being called, or if it is it then being overwritten by the mangle_signature method.

**Comment by tk0miya** [comment] 2020-04-24 13:16
It seems the autodoc-process-signature event is working fine on Sphinx-3.0.2. So I'm closing this now.
Please feel free to reopen if you still have this problem.
Thanks,

**Comment by tk0miya** [comment] 2020-04-24 13:25
Sorry, now I understand what you're saying with reading #2573.

>it seems that the event is not being called, or if it is it then being overwritten by the mangle_signature method.

It seems the event is actually called. But its result is surely modified by `mangle_signature()` as you mentioned. I think it is expected behavior because the content of autosummary table is too narrow to show them all.

**Closed as completed by tk0miya** 2020-04-24 13:25 UTC
Labels: closed:wontfix, extensions:autosummary
