### ISSUE TITLE
Jinja 2 imports have been deprecated

### ISSUE THREAD

**Issue by jontwo** [sphinx-doc/sphinx#10291] opened 2022-03-24 16:58 UTC
### Describe the bug

There is an `ImportError` when using Sphinx with the latest version of Jinja2.

### How to Reproduce

On any project:
```
$ pip install -U jinja2
$ make html
```

You get the error:
```
  File "/builds/venv/lib/python3.8/site-packages/sphinx/util/rst.py", line 21, in <module>
    from jinja2 import Environment, environmentfilter
ImportError: cannot import name 'environmentfilter' from 'jinja2' (/builds/venv/lib/python3.8/site-packages/jinja2/__init__.py)
```

### Expected behavior

Sphinx builds without error.

### Your project

This will work on any project

### OS

Rocky Linux 8.5

### Python version

3.8.8

### Sphinx version

3.5.4

**Comment by ViktorHaag** [comment] 2022-03-24 19:19
What version of Jinja2 does your upgrade end up installing? I can't replicate this bug here. My system (on a blank docs project started via `sphinx-quickstart`) is:
- macOS 12.3
- Python 3.10.3
- Sphinx 4.4.0
- Jinja2 3.1.0

It's possible that this import issue has already been addressed by a version of Sphinx between your 3.5.4 and 4.4.0?

I can confirm that, via use of iPython, the import error with Jinja2 3.1.0 does appear: 
```
In [2]: from jinja2 import Environment, environmentfilter
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Input In [2], in <cell line: 1>()
----> 1 from jinja2 import Environment, environmentfilter

ImportError: cannot import name 'environmentfilter' from 'jinja2' (/Users/vhaag/.pyenv/versions/3.10.3/lib/python3.10/site-packages/jinja2/__init__.py)
```

**Comment by mdylanbell** [comment] 2022-03-24 19:41
~I'm also experiencing this bug (and it's breaking our builds). In our case, Jinja2 version 3.0.3 is being installed.~

Sorry, I'm wrong. I think that may be from the most recent working container.

**Comment by pllim** [comment] 2022-03-24 19:42
Pinning to `Jinja2<3.1` fixed it for our project. At first I thought 3.0.3 broke it too until I saw something else undoing my pin in the log; you should check again.

**Comment by mdylanbell** [comment] 2022-03-24 19:44
@pllim Yes, I was wrong. I updated my original comment. I was mistakenly looking at our last successful container build.

**Comment by jontwo** [comment] 2022-03-24 20:03
Apologies, I thought I was on the latest Sphinx, as this was a new virtual environment. The bug goes away when I install the latest Sphinx so it must have been fixed somewhere along the way. I tried 4.0.0 and 4.0.1 but they require Jinja2<3.0. With Sphinx 4.0.2 the problem goes away, so this ticket can be closed. Many thanks for your help.

**Comment by Adam--** [comment] 2022-03-24 20:30
@jontwo This threw me for a loop too. I was on 2.4.4.
It looks like the version requirements for Jinja2 were originally >=2.3 and were updated to >=2.3,<3.0 in #9161. That was short lived with support for Jinja2 3.0 being added in #9162. 
To work around this issue until I can use the new version of Sphinx, I just installed an older version of Jinja before installing Sphinx.

**Comment by pllim** [comment] 2022-03-24 21:32
Re: https://github.com/sphinx-doc/sphinx/issues/10291#issuecomment-1078046986 -- Forgot to say our project is pinning to `sphinx<4` for a different issue. Should have clarified. Sorry!

**Comment by choldgraf** [comment] 2022-03-25 20:24
Any chance that the `3.5.x` series could get a patch release that pins the version of Jinja that is used? This could be a simple way for people who are using `3.5.x` to not have to each take a manual step of pinning it themselves.

**Comment by tk0miya** [comment] 2022-03-26 14:52
We only maintain the latest release. So all we can say is please upgrade to your Sphinx to the latest one.
Thanks,

**Closed as completed by tk0miya** 2022-03-26 14:52 UTC
Labels: type:bug

**Comment by aktiver** [comment] 2022-03-26 18:40
You have broken previous releases of Flask, please put Jinja2 3.0.3 back in
