### ISSUE TITLE
sphinxcontrib-htmlhelp 2.0.1: missing git tag

### ISSUE THREAD

**Issue by kloczek** [sphinx-doc/sphinx#11341] opened 2023-04-20 07:49 UTC
### Describe the bug

According to https://pypi.org/project/sphinxcontrib-htmlhelp/ latest version is 2.0.1 and in https://github.com/sphinx-doc/sphinxcontrib-htmlhelp/ is missing `2.0.1` git tag.
Is it possible to add that tag?

### How to Reproduce

N/A

### Environment Information

```text
N/A
```

### Sphinx extensions

```python
N/A
```

### Additional context

N/A

**Comment by AA-Turner** [comment] 2023-04-20 19:37
Duplicate of #11187. Please don't comment on commits or open duplicate issues--it adds extra work.

Thanks,
Adam

**Closed as not planned by AA-Turner** 2023-04-20 19:37 UTC

**Comment by kloczek** [comment] 2023-04-20 21:15
Thank you 👍
