### ISSUE TITLE
Images and figures can't have absolute paths: leading slash is removed at build

### ISSUE THREAD

**Issue by jilljenn** [sphinx-doc/sphinx#7772] opened 2020-06-02 20:14 UTC
**Describe the bug**
Images and figures can't have absolute paths: leading slash is removed at build.

**To Reproduce**
```
.. figure:: /_static/test.png

.. image:: /_static/test.png

$ make html
```

**Expected behavior**
I wanted the links to be `/_static/test.png` but it is `_static/test.png` (without the leading slash).  
It worked before, but on recent versions of Sphinx it does not work anymore.  
Now I have to do `.. image:: //_static/test.png` if I want my absolute path, and I don't think it's normal.

**Environment info**
- OS: Ubuntu 16.04
- Python version: 3.8.2
- Sphinx version: 3.0.4

**Comment by jilljenn** [comment] 2020-07-15 20:25
Any news from this regression?

**Comment by tk0miya** [comment] 2020-07-16 03:59
This is an expected behavior. see our docs:

>When used within Sphinx, the file name given (here gnu.png) must either be relative to the source file, or absolute which means that they are relative to the top source directory. 
>https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#images

The absolute path is considered as a relative path from the source directory.

**Comment by jilljenn** [comment] 2020-07-22 06:32
Sorry @tk0miya, I'm not sure it is. Taking the example from the docs:

    For example, the file sketch/spam.rst could refer to the image images/spam.png as ../images/spam.png or /images/spam.png.

Currently, if `sketch/spam.rst` contains the following absolute path:

    .. image:: /images/spam.png

It will refer to `sketch/images/spam.png`, not `images/spam.png` as expected.

**Comment by tk0miya** [comment] 2020-07-22 19:05
No, it means the image directive in the `srcdir/sketch/spam.rst` can refer the image placed at `srcdir/images/spam.png` via either `/images/spam.png` or `../images/spam.png`. If you'd like to refer an image relative to the directory that the reST file placed, please use a relative path for the argument of the image directive instead of an absolute path.

**Comment by jilljenn** [comment] 2020-08-03 20:20
I am verry sorry to insist but:

> The absolute path is considered as a relative path from the source directory.

Currently it is not.

If `srcdir/sketch/spam.rst` contains the directive `/images/spam.png` it will actually wrongly link to `srcdir/sketch/images/spam.png` instead of `srcdir/images/spam.png`.

**Comment by tk0miya** [comment] 2020-08-05 17:36
I made `srcdir/sketch/spam.rst` with following contents::

```
.. figure:: /_images/spam.png

.. image:: /_images/spam.png
```

And got following HTML output from the file::

```
  <div class="figure align-default">
<img alt="../_images/spam.png" src="../_images/spam.png" />
</div>
<img alt="../_images/spam.png" src="../_images/spam.png" />
```

On my local, it seems working. Could you check it again please?

**Comment by th0ger** [comment] 2020-09-11 14:17
Confirming this bug.
My page is in source/subfolder/page.md (using m2r2).
I can step back to the root via relative paths ../../source/_static/image.md
But /source/_static/image.md doesn't work, as the docs say it would.

**Comment by tk0miya** [comment] 2020-09-11 14:33
That is not related to this issue because this case uses reStructuredText parser, not markdown's. Please report it to m2r2 project if you consider it's a bug.

**Comment by th0ger** [comment] 2020-09-11 16:11
@tk0miya soory for being unclear, this is not m2r2 related. I use the ReST image directive inside the .md, an this directive is passed directly through to ReST/Sphinx.

I have reproduced the issue as follows (minimal, markdown-less):
```bash
sphinx-quickstart # choose seperate source/build dir
cp <myimage> source/_static/image.png
```
Add to `index.rst` the following:
```
.. image:: _static/image.png
.. image:: ./_static/image.png
.. image:: /source/_static/image.png
.. image:: //source/_static/image.png
```

Run `make html`
The first two directive compile sucessfully.
The 3rd directive throws: **image file not readable: source/_static/image.png**
The 4th directive (@jilljenn propsed workaround) also fails.

Full output:
```
(myenv) user@host:~/tmp/sphinx-issue$ make html
Running Sphinx v3.2.1
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1 source files that are out of date
updating environment: 0 added, 1 changed, 0 removed
reading sources... [100%] index
/home/username/tmp/sphinx-issue/source/index.rst:15: WARNING: image file not readable: source/_static/image.png
/home/username/tmp/sphinx-issue/source/index.rst:17: WARNING: image file not readable: /source/_static/image.png
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index
generating indices...  genindexdone
writing additional pages...  searchdone
copying images... [100%] ./_static/image.png
copying static files... ... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 2 warnings.

The HTML pages are in build/html.
```

**Comment by tk0miya** [comment] 2020-09-12 14:33
@th0ger What do you expect? I think the source directory is `/home/username/tmp/sphinx-issue/source` in your case. So `.. image:: /source/_static/image.png` is considered as `/home/username/tmp/sphinx-issue/source/source/_static/image.png` because an absolute path is considered as a relative path from the source directory.

Note: We don't have a rule for the double slashes for now. The current behavior is not undefined.

**Comment by th0ger** [comment] 2020-09-12 16:23
@tk0miya okay, this works:
```
.. image:: /_static/image.png
```
I misunderstood from the documentation how the [source directory](https://www.sphinx-doc.org/en/master/glossary.html#term-source-directory) works. A bit counter-intuitive the the absolue path refers to `../sphinx-issue/source/` and not just `../sphinx-issue/`. But well.

**Comment by tk0miya** [comment] 2020-09-12 16:34
As a default settings of sphinx-quickstart, there is no `source` directory. It generates project files flatly by default. I guess you said yes to "separate source and build directory" question on project initialization.

**Comment by tk0miya** [comment] 2020-09-12 16:36
BTW, are there any more questions or unexpected behaviors? I think there is nothing to discuss more in this issue. Is it okay to close this?

**Comment by skelliam** [comment] 2020-10-20 13:38
@tk0miya Just want to add my comment here, as I struggled with this issue yesterday and found #324 #701 #7000 #170 and even [an extension](https://github.com/vidartf/nbsphinx-link/tree/master/nbsphinx_link) that copies files into the work folder as a workaround for the odd behavior that paths specified as absolute will always be considered as relative, and further they will be considered as relative to the project root.  Several discussions on stackoverflow as well.

What I'm trying to accomplish is to write documentation (non-Python docs) for a piece of hardware.  There are several sections of the documentation that are reused (such as safety info, company contact info, etc).  For those reusable sections, I'm sharing those reusable portions via a git submodule shared in to a folder called /common that exists inside my hardware doc repo.

The problem here is that paths specified in my submodule are all relative to that submodule.  If I build docs from my root repository, the relative paths inside the submodule will *all* fail.

IMO it makes more sense to use an approach like C, where the developer would specify include paths to search for files in the conf.py file.  The C compiler searches the list of include paths and attempts to locate the file you want (whether it is image, figure, include, whatever).  The way that search takes place is following some simple rules as below:

From: https://gcc.gnu.org/onlinedocs/gcc/Directory-Options.html

(this is edited by me for brevity.  For the full text, go to the link above)
```
3.16 Options for Directory Search
These options specify directories to search for header files, for libraries and for parts of the compiler:

-I dir

Add the directory dir to the list of directories to be searched for header files during preprocessing.

You can specify any number or combination of these options on the command line to search for header files in several directories. The lookup order is as follows:

1. For the quote form of the include directive, the directory of the current file is searched first.
2. For the quote form of the include directive, the directories specified by -iquote options are searched in left-to-right order, as they appear on the command line.
3. Directories specified with -I options are scanned in left-to-right order.
```

IMO the direction that #324 was going was the right direction, but it was killed because of the existing behavior.

**Comment by jilljenn** [comment] 2020-11-29 14:17
I don't have much time to investigate yet but please notice that:

- The behavior changed recently. All my images were working before and they do not anymore.
- Currently if I put `../_static/image.png` I have the weird resulting path `source/../_static/image.png` which does not work. The only thing that works is `/../_static/image.png` which seems weird to me.

Does the problem come from the fact that I have `sys.path.insert(0, os.path.abspath('..'))` in my config?

**Comment by AkihaTohno** [comment] 2020-12-04 08:03
Hi,all.
I happened same or nearly case.
I wrote image tag in my rst file, and run make html.
Then, I displayed the html file which sphinx generated.
But sphinx could not generate the path correctly.

Example:
In RST
```
.. image:: /_image/hoge.png
     :alt: hoge
```
In generated HTML
`<img alt="hoge" src="_image/hoge.png" />`

Directory Index
/_image/hoge.png
/documents/example01.rst

How can I fix my RST file?
My environment is here.
OS:Ubuntu 18.04
Sphinx:3.3.1

**Comment by tk0miya** [comment] 2020-12-12 08:43
>The behavior changed recently. All my images were working before and they do not anymore.

AFAIK, this behavior has lasted for a long time and nothing changed. Could you tell me what version was it changed?

>Currently if I put ../_static/image.png I have the weird resulting path source/../_static/image.png which does not work. The only thing that works is /../_static/image.png which seems weird to me.

Sphinx does not support the images outside of the source directory. So there is no good way to specify it well.

**Comment by tk0miya** [comment] 2020-12-12 08:44
@AkihaTohno This is not a forum of Sphinx users. Please post sphinx-users group instead. Thanks,
https://groups.google.com/d/forum/sphinx-users

**Comment by tk0miya** [comment] 2021-05-15 13:37
I'm closing this because discussion is over.
Please feel free to reopen if you'd like to restart the discussion.
Thanks,

**Closed as completed by tk0miya** 2021-05-15 13:37 UTC
Labels: type:question, markup
