### ISSUE TITLE
Please remove "POT-Creation-Date" from pot files.

### ISSUE THREAD

**Issue by methane** [sphinx-doc/sphinx#3443] opened 2017-02-22 08:22 UTC
I use git for manage pot files produced by gettext builder.

Since gettext builder produce 'POT-Creation-Date' header [1], `git diff` shows all pot files are
changed while even when no original text is changed.

To solve this issue, I removed the header by sed [2].  But I think I'm not only one who
using git to manage pot files.
Removing the date header (or adding option to remove it) help people like us.

1: https://github.com/sphinx-doc/sphinx/blob/master/sphinx/builders/gettext.py#L53
2: https://github.com/python-doc-ja/cpython-doc-intl/blob/intl-3.6/Doc/Makefile#L192

**Comment by shimizukawa** [comment] 2017-03-02 07:50
fixed by #3490

**Comment by tk0miya** [comment] 2017-03-11 09:01
Reopened because it seems wrong fix.

**Comment by shibukawa** [comment] 2017-04-20 15:46
I confirmed #3490 fix this issue.

* After #3490, Sphinx doesn't overwrite pot file when only POT-Creation-Date is changed
* Suppressing POT-Creation-Date changes are enough to resolve this issue

So I close this issue. If this fix will cause any trouble, please reopen.

**Closed as completed by shibukawa** 2017-04-20 15:46 UTC
Labels: type:proposal, internals:internationalisation

**Comment by tk0miya** [comment] 2017-04-20 15:47
I've tested #3490 and it works fine.
sorry, I'm closing this again.
