### ISSUE TITLE
master file not found

### ISSUE THREAD

**Issue by geyang** [sphinx-doc/sphinx#6274] opened 2019-04-09 21:46 UTC
**Describe the bug**
If you have a docs folder under a subfolder, sphinx can not find the index.rst

I tried to use absolute path and verified that the abs path is correct. However sphinx is unable to find the index.rst file.

```bash
.
├── Makefile
├── build
│   ├── doctrees
│   └── html
├── make.bat
├── requirements.txt
└── source
    ├── __init__.py
    ├── _static
    ├── _templates
    ├── conf.py
    └── index.rst
```

```python
# conf.py
import os, sys

# --- configure the python environment for autodoc ---
cwd = os.path.dirname(os.path.abspath(__file__))

sys.path.insert(0, os.path.abspath(os.path.join(cwd, '../../')))

# -- Project information -----------------------------------------------------

project = 'ml-logger'
copyright = '2019, Ge Yang'
author = 'Ge Yang'
master_doc = os.path.abspath(os.path.join(cwd, "index"))
print(master_doc)
```

### Error Message

```bash
Sphinx error:
master file /path<blah-blah-blah>/ml_logger/docs/source/index.rst not found
```

**Comment by tk0miya** [comment] 2019-04-11 16:10
`master_doc` is a document name of master document. It is relative path from source directory without file suffix.
In your case, it is simply "index".
https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-master_doc

**Comment by tk0miya** [comment] 2019-05-14 16:45
I'm closing this now because this is not a bug of Sphinx.
Thanks,

**Closed as completed by tk0miya** 2019-05-14 16:45 UTC
Labels: type:question
