### ISSUE TITLE
sphinx 1.6.6 fails test_metadata.py::test_docinfo

### ISSUE THREAD

**Issue by tgurr** [sphinx-doc/sphinx#4408] opened 2018-01-09 18:01 UTC
Subject: sphinx 1.6.6 fails test_metadata.py::test_docinfo

### Problem
- running the tests both Python 2.7 and 3.6 run into a test failure

#### Error logs / results
```
[...]
test_metadata.py::test_docinfo FAILED
[...]
===================================================================== 1 failed, 1103 passed, 4 skipped, 1 warnings in 93.08 seconds ======================================================================

Error:
  * In program cave perform install --hooks --managed-output --output-exclusivity with-others =dev-python/Sphinx-1.6.6:0::python --destination installed --replacing =dev-python/Sphinx-1.6.5:0::installed --x-of-y 1 of 1:
  * When installing 'dev-python/Sphinx-1.6.6:0::python' replacing { 'dev-python/Sphinx-1.6.5:0::installed' }:



            'orphan': u'',
            'nocomments': u'',
        }
>       assert exampledocinfo == expecteddocinfo
E       assert {'address': '...hon.org', ...} == {'address': '1...hon.org', ...}
E         Omitting 13 identical items, use -vv to show
E         Differing items:
E         {'status': 'This is a "work in progress"'} != {'status': 'This is a “work in progress”'}
E         {'copyright': "This document has been placed in the public domain. You\nmay do with it as you wish. You may copy, modif...corporate, collate, fold, staple, or mutilate it, or do\nanything else to it that your or anyone else's heart\ndesires."} != {'copyright': 'This document has been placed in the public domain. You\nmay do with it as you wish. You may copy, modif...corporate, collate, fold, staple, or mutilate it, or do\nanythi...
E         
E         ...Full output truncated (35 lines hidden), use '-vv' to show

test_metadata.py:54: AssertionError
---------------------------------------------------------------------------------------- Captured stdout teardown ----------------------------------------------------------------------------------------
# testroot: root
# builder: pseudoxml
```
### Environment info
- OS: Linux
- Python version: 2.7 and 3.6
- Sphinx version: 1.6.6

I saw there's a lot going on regarding the smartquotes so maybe it's related(?).

**Comment by tk0miya** [comment] 2018-01-14 00:37
Thank you for reporting. This might be related with the order of testing.
I'll investigate it later.

**Comment by tk0miya** [comment] 2018-01-19 05:42
@tgurr I try to fix this by #4456.
Could you check this please?

**Comment by tgurr** [comment] 2018-01-19 12:57
@tk0miya 

Thank you very much, however I'm afraid your fix doesn't seem to do the trick for me. I've applied the patch from your pull request to 1.6.6 and still get:

```
================================================================================================================================== FAILURES ===================================================================================================================================
________________________________________________________________________________________________________________________________ test_docinfo _________________________________________________________________________________________________________________________________

app = <SphinxTestApp buildername='pseudoxml'>, status = <StringIO.StringIO instance at 0x7f8a715a0cb0>, warning = <StringIO.StringIO instance at 0x7f8a715a0050>

    @pytest.mark.sphinx('pseudoxml')
    def test_docinfo(app, status, warning):
        """
        Inspect the 'docinfo' metadata stored in the first node of the document.
        Note this doesn't give us access to data stored in subsequence blocks
        that might be considered document metadata, such as 'abstract' or
        'dedication' blocks, or the 'meta' role. Doing otherwise is probably more
        messing with the internals of sphinx than this rare use case merits.
        """
        # remove doctree cache to rebuild forcely
        (app.doctreedir / 'metadata.doctree').rmtree(ignore_errors=True)
    
        app.builder.build(['metadata'])
        env = app.env
        exampledocinfo = env.metadata['metadata']
        expecteddocinfo = {
            'author': u'David Goodger',
            'authors': [u'Me', u'Myself', u'I'],
            'address': u'123 Example Street\nExample, EX  Canada\nA1B 2C3',
            'field name': u'This is a generic bibliographic field.',
            'field name 2': (u'Generic bibliographic fields may contain multiple '
                             u'body elements.\n\nLike this.'),
            'status': u'This is a “work in progress”',
            'version': u'1',
            'copyright': (u'This document has been placed in the public domain. '
                          u'You\nmay do with it as you wish. You may copy, modify,'
                          u'\nredistribute, reattribute, sell, buy, rent, lease,\n'
                          u'destroy, or improve it, quote it at length, excerpt,\n'
                          u'incorporate, collate, fold, staple, or mutilate it, or '
                          u'do\nanything else to it that your or anyone else’s '
                          u'heart\ndesires.'),
            'contact': u'goodger@python.org',
            'date': u'2006-05-21',
            'organization': u'humankind',
            'revision': u'4564',
            'tocdepth': 1,
            'orphan': u'',
            'nocomments': u'',
        }
>       assert exampledocinfo == expecteddocinfo
E       assert {'address': '...hon.org', ...} == {'address': '1...hon.org', ...}
E         Omitting 13 identical items, use -vv to show
E         Differing items:
E         {'status': 'This is a "work in progress"'} != {'status': 'This is a “work in progress”'}
E         {'copyright': "This document has been placed in the public domain. You\nmay do with it as you wish. You may copy, modif...corporate, collate, fold, staple, or mutilate it, or do\nanything else to it that your or anyone else's heart\ndesires."} != {'copyright': 'This document has been placed in the public domain. You\nmay do with it as you wish. You may copy, modif...corporate, collate, fold, staple, or mutilate it, or do\nanythi...
E         
E         ...Full output truncated (35 lines hidden), use '-vv' to show

test_metadata.py:57: AssertionError
```

**Comment by tk0miya** [comment] 2018-01-20 15:45
Hmm, okay. It seems my patch was wrong.
To investigate in detail, could you let me know the result of `tox -e py36 tests/test_metadata.py` and `tox -e py36 tests/test_metadata.py -- -k test_docinfo` with pure Sphinx-1.6.6?

Note: Please replace `-e py36` option by python you usually use.


If both succeeded, the error is raised only on full test. So it would been caused by order of testcases.
If none, we have to take a look more carefully...

**Comment by tgurr** [comment] 2018-02-12 16:47
Sorry for the lack of response, but currently we don't have tox and it's dependencies packaged on our distribution yet so for now I'm not able to provide the requested information.

**Comment by tk0miya** [comment] 2018-02-12 17:36
How do you run the tests? I'd like to know the result of `tests/test_metadata.py`, so please give any options to your test runner to invoke the specific test case.

**Comment by tk0miya** [comment] 2018-03-14 16:34
ping. any updates?

**Comment by tk0miya** [comment] 2018-04-02 14:12
Note: I will close this if no updates until next release.

**Comment by tk0miya** [comment] 2018-04-21 05:53
In this weekend, we will release 1.7.3 soon. So I will close this at that time if no updates.

**Comment by tk0miya** [comment] 2018-04-22 16:35
I'm closing this now.
Please let me know if you still have this problem on your local.

Thanks,

**Closed as completed by tk0miya** 2018-04-22 16:35 UTC
Labels: type:bug, type:tests
