### ISSUE TITLE
autodoc support packages

### ISSUE THREAD

**Issue by szlinjia** [sphinx-doc/sphinx#3384] opened 2017-02-02 19:38 UTC
Subject: autodoc support packages

### Problem
- I currently working on a project with tons of python files. I used autodoc extension to extract docstring from each file. But I don't want sphinx generate html from rst file for each module. Because this project is being added/removed/modified files everyday by multiple persons.  Maintaining rst file for each module would be painful for the project is changing frequently. Is that a way that I  can only add the package name to some special directive like "automodule: :" so  the autodoc will automatically scan all files under the package and generate html ?
For example, my project structure is like this:

```
package1/                            Top-level package
      __init__.py                    Initialize the package1 
      submodule1/                    Subpackage for submodule1
              __init__.py
              f1.py
              f2py
              ...
      submodule2/                    Subpackage for submodule2
              __init__.py
              f1.py
              f2.py
              ...
```

And I only need to modify the index.rst in this way:
```
.. automodule:: package1
    :members:

```

I had tried to auto doc with a package name. But it looks like sphinx doesn't work for submodule under the package.

###Environment info
- OS:  CentOS release 6.4
- Python version: python2.7
- Sphinx version: v1.5.3+

Any thoughts?

**Comment by tk0miya** [comment] 2017-02-03 04:34
How about `sphinx.ext.autosummary`?
http://www.sphinx-doc.org/en/1.5.1/ext/autosummary.html

**Comment by tk0miya** [comment] 2017-02-11 17:19
Now I close this issue because it's not a bug of Sphinx.
Please feel free to reopen if needed.

**Closed as completed by tk0miya** 2017-02-11 17:19 UTC
Labels: type:question, extensions:autodoc
