### ISSUE TITLE
Sphinx crash copying images

### ISSUE THREAD

**Issue by fluboe** [sphinx-doc/sphinx#3037] opened 2016-10-12 14:49 UTC
```
preparing documents... done
writing output... [100%] wireless-antennae-visual-inspection                   orred
generating indices... genindex
writing additional pages... search
copying images... [  1%] images/BumpStripApply.png
Exception occurred:
  File "C:\Users\fallierd\AppData\Local\Programs\Python\Python35\lib\site-packages\colorama-0.3.7-py3.5.egg\colorama\ansitowin32.py", line 225, in convert_osc
    for match in self.ANSI_OSC_RE.finditer(text):
TypeError: cannot use a string pattern on a bytes-like object
The full traceback has been saved in C:\Users\fallierd\AppData\Local\Temp\sphinx-err-uykmfht7.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at https://github.com/sphinx-doc/sphinx/issues. Thanks!
**Error**: 'sphinx-build -b html -d latest/ug\doctrees -D latex_paper_size=letter sphinx_build_files latest/ug' returned error code 1
```
My build doesn't finish so I can't publish this document.
[sphinx-err-uykmfht7.zip](https://github.com/sphinx-doc/sphinx/files/524842/sphinx-err-uykmfht7.zip)

**Comment by tk0miya** [comment] 2016-10-12 15:51
Thank you for reporting.

This is similar to #3024.

```
# Sphinx version: 1.4.3
# Python version: 3.5.1 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:
#   generating indices...
#   genindex
#   
#   writing additional pages...
#   search
#   
#   copying images... [  0%] images/TemperatureSensorCable1.png
#   copying images... [  0%] ../../../Shared/images/ppe_vest.png
#   copying images... [  1%] ../../DriveShared/images/TurntableOnTable.png
#   copying images... [  1%] images/BumpStripApply.png
# Loaded extensions:
#   sphinx.ext.extlinks (1.4.3) from C:\Users\fallierd\AppData\Local\Programs\Python\Python35\lib\site-packages\sphinx-1.4.3-py3.5.egg\sphinx\ext\extlinks.py
#   sphinx.ext.intersphinx (1.4.3) from C:\Users\fallierd\AppData\Local\Programs\Python\Python35\lib\site-packages\sphinx-1.4.3-py3.5.egg\sphinx\ext\intersphinx.py
#   alabaster (0.7.8) from C:\Users\fallierd\AppData\Local\Programs\Python\Python35\lib\site-packages\alabaster-0.7.8-py3.5.egg\alabaster\__init__.py
#   sphinxcontrib.fulltoc (unknown version) from C:\Users\fallierd\AppData\Local\Programs\Python\Python35\lib\site-packages\sphinxcontrib_fulltoc-1.1-py3.5.egg\sphinxcontrib\fulltoc.py
#   sphinx.ext.todo (1.4.3) from C:\Users\fallierd\AppData\Local\Programs\Python\Python35\lib\site-packages\sphinx-1.4.3-py3.5.egg\sphinx\ext\todo.py
#   ar_sphinx_theme (unknown version) from C:\Users\fallierd\AppData\Local\Programs\Python\Python35\lib\site-packages\ar_sphinx_theme-0.6-py3.5.egg\ar_sphinx_theme\__init__.py
Traceback (most recent call last):
  File "C:\Users\fallierd\AppData\Local\Programs\Python\Python35\lib\site-packages\sphinx-1.4.3-py3.5.egg\sphinx\application.py", line 323, in _log
    wfile.write(message)
  File "C:\Users\fallierd\AppData\Local\Programs\Python\Python35\lib\site-packages\colorama-0.3.7-py3.5.egg\colorama\ansitowin32.py", line 40, in write
    self.__convertor.write(text)
  File "C:\Users\fallierd\AppData\Local\Programs\Python\Python35\lib\site-packages\colorama-0.3.7-py3.5.egg\colorama\ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "C:\Users\fallierd\AppData\Local\Programs\Python\Python35\lib\site-packages\colorama-0.3.7-py3.5.egg\colorama\ansitowin32.py", line 166, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\fallierd\AppData\Local\Programs\Python\Python35\lib\site-packages\colorama-0.3.7-py3.5.egg\colorama\ansitowin32.py", line 174, in write_plain_text
    self.wrapped.write(text[start:end])
  File "C:\Users\fallierd\AppData\Local\Programs\Python\Python35\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u206d' in position 7: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\fallierd\AppData\Local\Programs\Python\Python35\lib\site-packages\sphinx-1.4.3-py3.5.egg\sphinx\cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "C:\Users\fallierd\AppData\Local\Programs\Python\Python35\lib\site-packages\sphinx-1.4.3-py3.5.egg\sphinx\application.py", line 298, in build
    self.builder.build_update()
  File "C:\Users\fallierd\AppData\Local\Programs\Python\Python35\lib\site-packages\sphinx-1.4.3-py3.5.egg\sphinx\builders\__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "C:\Users\fallierd\AppData\Local\Programs\Python\Python35\lib\site-packages\sphinx-1.4.3-py3.5.egg\sphinx\builders\__init__.py", line 325, in build
    self.finish()
  File "C:\Users\fallierd\AppData\Local\Programs\Python\Python35\lib\site-packages\sphinx-1.4.3-py3.5.egg\sphinx\builders\html.py", line 464, in finish
    self.finish_tasks.add_task(self.copy_image_files)
  File "C:\Users\fallierd\AppData\Local\Programs\Python\Python35\lib\site-packages\sphinx-1.4.3-py3.5.egg\sphinx\util\parallel.py", line 40, in add_task
    res = task_func()
  File "C:\Users\fallierd\AppData\Local\Programs\Python\Python35\lib\site-packages\sphinx-1.4.3-py3.5.egg\sphinx\builders\html.py", line 555, in copy_image_files
    brown, len(self.images)):
  File "C:\Users\fallierd\AppData\Local\Programs\Python\Python35\lib\site-packages\sphinx-1.4.3-py3.5.egg\sphinx\application.py", line 455, in status_iterator
    self.info(s, nonl=1)
  File "C:\Users\fallierd\AppData\Local\Programs\Python\Python35\lib\site-packages\sphinx-1.4.3-py3.5.egg\sphinx\application.py", line 371, in info
    self._log(message, self._status, nonl)
  File "C:\Users\fallierd\AppData\Local\Programs\Python\Python35\lib\site-packages\sphinx-1.4.3-py3.5.egg\sphinx\application.py", line 326, in _log
    wfile.write(message.encode(encoding, 'replace'))
  File "C:\Users\fallierd\AppData\Local\Programs\Python\Python35\lib\site-packages\colorama-0.3.7-py3.5.egg\colorama\ansitowin32.py", line 40, in write
    self.__convertor.write(text)
  File "C:\Users\fallierd\AppData\Local\Programs\Python\Python35\lib\site-packages\colorama-0.3.7-py3.5.egg\colorama\ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "C:\Users\fallierd\AppData\Local\Programs\Python\Python35\lib\site-packages\colorama-0.3.7-py3.5.egg\colorama\ansitowin32.py", line 163, in write_and_convert
    text = self.convert_osc(text)
  File "C:\Users\fallierd\AppData\Local\Programs\Python\Python35\lib\site-packages\colorama-0.3.7-py3.5.egg\colorama\ansitowin32.py", line 225, in convert_osc
    for match in self.ANSI_OSC_RE.finditer(text):
TypeError: cannot use a string pattern on a bytes-like object
```

**Comment by shimizukawa** [comment] 2016-12-04 02:22
I guess this problem caused by a Non-ASCII image filename.
It seems that an error occurred because Sphinx could not encode `\u206d` to cp1252 encoding (it might be @fluboe 's console encoding) trying to display "copying images ... <filename>".

@fluboe please check if your image file names contain Unicode character `\u206d`.

**Comment by shimizukawa** [comment] 2016-12-04 02:23
Memo:
```Python
>>> '\u206d'.encode('cp1252')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\taka\Anaconda3\lib\encodings\cp1252.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode character '\u206d' in position 0: character maps to <undefined>
```

**Comment by shimizukawa** [comment] 2016-12-04 04:57
Now I fixed the logging issue at 6ae67f9 (stable branch).

**Comment by tk0miya** [comment] 2018-03-03 17:33
@shimizukawa It seems this was already fixed. Can I close this?

**Comment by shimizukawa** [comment] 2018-03-04 01:55
Thanks for excavating! It seems I forgot to close.

**Closed as completed by shimizukawa** 2018-03-04 01:55 UTC
Labels: type:bug, builder
