### ISSUE TITLE
Parallel workers only for read, not for write

### ISSUE THREAD

**Issue by Chrisbuuren** [sphinx-doc/sphinx#5953] opened 2019-01-14 12:55 UTC
Hello, 

I use the **-j** parameter for building Sphinx-Docs, but and I look over the number of processes spawn. When sphinx-build reads all the docs from sources, it spawns the number of processes I requested, but then, after the read was done and it needs to write the files, only one process is spawned.

**Example Reading the docs from source step:**
`(sphinx) root@cristicatana-VirtualBox:/home/cristicatana/# ps -aux | grep sphinx
cristic+  3974 26.1  0.6 110084 51108 pts/1    S+   14:27   0:03 /home/cristicatana/workspace/sphinx_env/bin/python2 /home/cristicatana/workspace/sphinx_env/bin/sphinx-build -b html -d build/doctrees source build/html -j 4
cristic+  3978 89.4  0.8 134908 69732 pts/1    R+   14:27   0:09 /home/cristicatana/workspace/sphinx_env/bin/python2 /home/cristicatana/workspace/sphinx_env/bin/sphinx-build -b html -d build/doctrees source build/html -j 4
cristic+  3979 91.4  0.8 130904 66624 pts/1    R+   14:27   0:10 /home/cristicatana/workspace/sphinx_env/bin/python2 /home/cristicatana/workspace/sphinx_env/bin/sphinx-build -b html -d build/doctrees source build/html -j 4
cristic+  3980 88.2  0.7 122944 59012 pts/1    R+   14:27   0:09 /home/cristicatana/workspace/sphinx_env/bin/python2 /home/cristicatana/workspace/sphinx_env/bin/sphinx-build -b html -d build/doctrees source build/html -j 4
cristic+  3981 86.8  0.7 124088 60024 pts/1    R+   14:27   0:09 /home/cristicatana/workspace/sphinx_env/bin/python2 /home/cristicatana/workspace/sphinx_env/bin/sphinx-build -b html -d build/doctrees source build/html -j 4
`

**Example Writing the files to build:**
`
(sphinx) root@cristicatana-VirtualBox:/home/cristicatana/# ps -auxf | grep sphinx
cristic+  3974 32.9 10.0 876136 817028 pts/1   R+   14:27   4:06  |   |       \_ /home/cristicatana/workspace/sphinx_env/bin/python2 /home/cristicatana/workspace/sphinx_env/bin/sphinx-build -b html -d build/doctrees source build/html -j 4
cristic+  4114 56.3  0.0      0     0 pts/1    Z+   14:39   0:09  |   |           \_ [sphinx-build] <defunct>
`

PS: Also, when writing the files(to build directory), the amount of used RAM increases very much.
Sphinx Version 1.8.3
OS: Ubuntu 18.04 Bionic
Python 2.7

**Comment by tk0miya** [comment] 2019-01-24 16:23
What extension have you use?  If you're using an extension which disallows parallel-writing, sphinx behaves like you said.

**Comment by Chrisbuuren** [comment] 2019-01-25 09:03
Hello, here are the extensions I use:

extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.ifconfig',
    'sphinx.ext.viewcode',
]

**Comment by tk0miya** [comment] 2019-01-26 03:12
Hmm, bundled extensions are supporting parallel-writing. It's strange. I'll take a look later.
Thank you.

**Comment by tk0miya** [comment] 2019-02-03 09:04
On my local, child processes are appeared on writing phase.
```
39189 ttys000    0:00.01 /Users/tkomiya/.pyenv/versions/3.7.1/bin/python3.7 /Users/tkomiya/.pyenv/versions/3.7.1/bin/flake8 --config=
39199 ttys000    0:04.57 /Users/tkomiya/work/sphinx/.tox/py37/bin/python .tox/py37/bin/sphinx-build -j4 doc/ zzz
39289 ttys000    0:00.58 /Users/tkomiya/work/sphinx/.tox/py37/bin/python .tox/py37/bin/sphinx-build -j4 doc/ zzz
39290 ttys000    0:00.47 /Users/tkomiya/work/sphinx/.tox/py37/bin/python .tox/py37/bin/sphinx-build -j4 doc/ zzz
39291 ttys000    0:00.64 /Users/tkomiya/work/sphinx/.tox/py37/bin/python .tox/py37/bin/sphinx-build -j4 doc/ zzz
```

It seems "waiting for workers" message is shown on writing. 
```
Running Sphinx v1.8.4+/6b3244d67
making output directory...
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 68 source files that are out of date
updating environment: 68 added, 0 changed, 0 removed
reading sources... [100%] web/searchadapters .. websupport
waiting for workers...
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] usage/restructuredtext/basics .. websupport
waiting for workers...
generating indices... genindex py-modindex
highlighting module code... [100%] sphinxcontrib.websupport.storage
writing additional pages... index search opensearch
copying images... [100%] _static/more.png
copying downloadable files... [100%] usage/extensions/example_numpy.py
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded.

The HTML pages are in zzz.
```

Could you check it again please?

Note: Writing HTML is very simple and small process. So child processes are finished instantly. So it is hard to see them by `ps` command.

**Comment by tk0miya** [comment] 2019-02-27 14:24
I'm closing this because not reproducible.
Please feel free to reopen if you're still in trouble.

Thanks,

**Closed as completed by tk0miya** 2019-02-27 14:24 UTC
Labels: type:bug, api:cmdline

**Comment by astrofrog** [comment] 2019-11-11 15:43
@tk0miya - I'm running into the same issue, but before I post more details is there an easy way to see which loaded plugins support/don't support parallel mode?
