### ISSUE TITLE
NotImplementedError: Unknown node: pending_xref still around on Sphinx v1.8.4 (html.py)

### ISSUE THREAD

**Issue by Naereen** [sphinx-doc/sphinx#6166] opened 2019-03-11 14:32 UTC
**Describe the bug**
The `pending_xref` error from #134 is still around, on Sphinx v1.8.4.
(`NotImplementedError: Unknown node: pending_xref`).
I encountered this issue again, with Sphinx v1.8.5, on the documentation [of my SMPyBandits package](https://github.com/SMPyBandits/SMPyBandits/).

**To Reproduce**
```
$ git clone https://github.com/SMPyBandits/SMPyBandits
$ cd some_project
$ pip install -r requirements_full.txt
$ cd docs
$ make html
...
fail with NotImplementedError: Unknown node: pending_xref
```
See the log file attached: [sphinx-err-3eo7ao_8.log](https://github.com/sphinx-doc/sphinx/files/2952408/sphinx-err-3eo7ao_8.log)

**Expected behavior**
This should not happen, and can be fixed very easily by adding the two following (empty) methods to `sphinx/writers/html.py`.
I solved the issue by adding the following (useless) piece of code to `sphinx/writers/html.py` (just before line 903):
```python
    def visit_pending_xref(self, node):
        # type: (nodes.Node) -> None
        pass

    def depart_pending_xref(self, node):
        # type: (nodes.Node) -> None
        pass
```

**Your project**
Link to my sphinx project: [SMPyBandits/SMPyBandits](https://github.com/SMPyBandits/SMPyBandits/).

**Environment info**
- OS: Linux (Ubuntu 18.04)
- Python version: 3.6.7
- Sphinx version: 1.8.4
- Sphinx extensions: sphinx.ext.mathjax (1.8.5), alabaster (0.7.12), sphinx.ext.autodoc (1.8.5), sphinx.ext.viewcode (1.8.5), sphinx.ext.intersphinx (1.8.5), nbsphinx (0.4.2), sphinxcontrib.googleanalytics

Thanks in advance!

**Comment by tk0miya** [comment] 2019-03-17 07:16
I don't think adding `visit_pending_xref` does not resolve your case. It must be a bug of Sphinx-core or extension. We need to investigate who inserts such broken node.

**Comment by tk0miya** [comment] 2019-03-17 08:12
As a trial, I just removed all *.ipynb files. Then the error is resolved. I guess this error would be related with nbsphinx.

**Comment by Naereen** [comment] 2019-03-17 08:42
Okay, it's what I was afraid. I will write an issue ticket for nbsphinx then.

**Comment by tk0miya** [comment] 2019-03-18 16:57
As I commented above, this is not a bug of Sphinx. So I'm closing this now.
If the `pending_xref` nodes are caused by Sphinx core, then please file another issue.
Thanks,

**Closed as completed by tk0miya** 2019-03-18 16:57 UTC
Labels: type:bug

**Comment by Naereen** [comment] 2019-03-18 19:18
Sure; thanks for your quick replies!
