### ISSUE TITLE
Default string literals rendered with too many quotes and backlashes

### ISSUE THREAD

**Issue by laurensvalk** [sphinx-doc/sphinx#10278] opened 2022-03-21 14:37 UTC
### Describe the bug

In overloaded functions, some typed default string literals can be rendered with too many quotes or backlashes:
```
sep: str = "' '", end: str = "'\\n'"
```

### How to Reproduce

This is a minimal repo created for several Sphinx bug reports.

RTD-theme and napoleon are enabled, but it is also reproducable without them.

```
$ git clone https://github.com/pybricks/sphinx-issues-minimal
$ cd sphinx-issues-minimal
# Optional if you don't have Sphinx 4.4 and RTD theme  1.0.0 already:
# poetry install
$ make clean html
$ # Open build/html/bugs.html to see above output
$ # See src/bugs/__init__.py for the offending Python source code
```

### Expected behavior

The expected output for the two arguments would be:
```
sep: str = "", end: str = "\n"
```

### Your project

https://github.com/pybricks/sphinx-issues-minimal

### Screenshots

![image](https://user-images.githubusercontent.com/12326241/159282234-4a405ff5-8767-4a29-915d-f738626894ba.png)

### OS

Ubuntu

### Python version

3.8.3

### Sphinx version

4.4.0

### Sphinx extensions

'sphinx.ext.autodoc', 'sphinx.ext.napoleon', 'sphinx_rtd_theme'

### Additional context

This was originally posted here: https://github.com/pybricks/pybricks-api/issues/81

**Comment by tk0miya** [comment] 2022-03-31 17:31
The root cause of this problem is the same as #10279. This will also be fixed by https://github.com/sphinx-doc/sphinx/pull/10315.

**Closed as completed by tk0miya** 2022-03-31 17:31 UTC
Labels: type:bug, closed:duplicate, extensions:autodoc
