### ISSUE TITLE
Exceptions with types in environment.py

### ISSUE THREAD

**Issue by virtualritz** [sphinx-doc/sphinx#3049] opened 2016-10-13 15:31 UTC
```
writing output... [  3%] constraints/angle
Exception occurred:
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sphinx/environment.py", line 1302, in _toctree_prune
    if maxdepth > 0 and int(depth) > maxdepth:
TypeError: unorderable types: str() > int()
```

```
# Sphinx version: 1.4.8
# Python version: 3.4.5 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:
#   looking for now-outdated files...
#   none found
#   pickling environment...
#   done
#   checking consistency...
#   /Users/moeller/code/solvespace/doc/constraints/specific_constraints.rst:: WARNING: document isn't included in any toctree
#   done
#   preparing documents...
#   done
#   writing output... [  3%] constraints/angle
# Loaded extensions:
#   sphinx.ext.todo (1.4.8) from /opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sphinx/ext/todo.py
#   sphinx.ext.pngmath (1.4.8) from /opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sphinx/ext/pngmath.py
#   alabaster (0.7.9) from /opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/alabaster/__init__.py
#   sphinx.ext.ifconfig (1.4.8) from /opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sphinx/ext/ifconfig.py
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sphinx/cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sphinx/application.py", line 297, in build
    self.builder.build_update()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sphinx/builders/__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sphinx/builders/__init__.py", line 322, in build
    self.write(docnames, list(updated_docnames), method)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sphinx/builders/__init__.py", line 360, in write
    self._write_serial(sorted(docnames), warnings)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sphinx/builders/__init__.py", line 368, in _write_serial
    self.write_doc(docname, doctree)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sphinx/builders/html.py", line 454, in write_doc
    self.handle_page(docname, ctx, event_arg=doctree)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sphinx/builders/html.py", line 815, in handle_page
    output = self.templates.render(templatename, ctx)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sphinx/jinja2glue.py", line 160, in render
    return self.environment.get_template(template).render(context)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sphinx/themes/basic/page.html", line 10, in top-level template code
    {%- extends "layout.html" %}
  File "/Users/moeller/code/solvespace/doc/_themes/read_the_docs/layout.html", line 123, in top-level template code
    {% block menu %}
  File "/Users/moeller/code/solvespace/doc/_themes/read_the_docs/layout.html", line 124, in block "menu"
    {% set toctree = toctree(maxdepth=theme_navigation_depth, collapse=theme_collapse_navigation, includehidden=True) %}
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/jinja2/sandbox.py", line 355, in call
    return __context.call(__obj, *args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sphinx/builders/html.py", line 805, in <lambda>
    ctx['toctree'] = lambda **kw: self._get_local_toctree(pagename, **kw)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sphinx/builders/html.py", line 731, in _get_local_toctree
    docname, self, collapse, **kwds))['fragment']
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sphinx/environment.py", line 1234, in get_toctree_for
    prune=True, **kwds)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sphinx/environment.py", line 1508, in resolve_toctree
    self._toctree_prune(newnode, 1, prune and maxdepth or 0, collapse)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sphinx/environment.py", line 1302, in _toctree_prune
    if maxdepth > 0 and int(depth) > maxdepth:
TypeError: unorderable types: str() > int()

```

**Comment by tk0miya** [comment] 2016-10-14 03:19
Did you use alpha version of sphinx_rtd_theme?
It is a bug of the theme.
https://github.com/snide/sphinx_rtd_theme/issues/323

Please check the version of the theme you used.

**Comment by tk0miya** [comment] 2016-11-02 15:39
Now I close this because this is not a bug of Sphinx.
Thank you for reporting.

**Closed as completed by tk0miya** 2016-11-02 15:39 UTC
Labels: type:question, html theme
