### ISSUE TITLE
autodoc_warningiserror doesn't behave as expected

### ISSUE THREAD

**Issue by emlys** [sphinx-doc/sphinx#8516] opened 2020-12-03 22:30 UTC
**Describe the bug**
Even when `autodoc_warningiserror = True`, no error is actually raised for import warnings. This makes it essentially useless for my use case. I'm seeing two issues causing this behavior:

(1) My project is `a.b`, and my rst file contains `.. automodule:: a.b.c`. If we change the structure and `a.b.c` no longer exists, importing `a.b.c` will fail. But autodoc then retries importing `a.b`, which should always work. This is annoying because I want to know if the documentation is pointing to a module that no longer exists. [Here](https://github.com/sphinx-doc/sphinx/blob/9cf28264917800534e56a92c1fa5c1196c73e73f/sphinx/ext/autodoc/importer.py#L86-L97) is the responsible code.

(2) Even if the top-level import `a` fails, and the error is raised on [line 97](https://github.com/sphinx-doc/sphinx/blob/9cf28264917800534e56a92c1fa5c1196c73e73f/sphinx/ext/autodoc/importer.py#L97), it is later suppressed. The `Documenter.import_error` argument `raiseerror` defaults to `False` in most cases.

Having this option to error on warnings from autodoc only would be great because in my case, autodoc warnings tend to be import errors resulting in entire sections of documentation missing, while other sphinx warnings tend to be minor syntax issues. If this is not the intended functionality of the `autodoc_warningiserror` parameter, its description could be made a lot clearer.

**Expected behavior**
The description of `autodoc_warningiserror` states, _"This value controls the behavior of `sphinx-build -W` during importing modules. If False is given, autodoc forcedly suppresses the error if the imported module emits warnings. By default, True."_. To me this sounds like `autodoc_warningiserror = True` should have the same effect as `sphinx-build -W` on all warnings coming from autodoc. However, with `sphinx-build -W` these warnings do get raised to errors.

**Environment info**
- OS: Mac
- Python version: 3.7.9
- Sphinx version: 3.3.1
- Sphinx extensions:  autodoc, mathjax, napoleon
- Extra tools: None

**Comment by emlys** [comment] 2020-12-03 22:56
A better solution would be to improve sphinx's warning/error filtering options in general. The `suppress_warnings` options are not useful for my situation. It would be nice to be able to filter out specific warnings like 'Unexpected indentation'. This would need to go in `conf.py` to be useful on ReadTheDocs.

**Comment by tk0miya** [comment] 2020-12-14 16:18
`autodoc_warningiserror` was added for the module that emits a warning on importing it (see https://github.com/sphinx-doc/sphinx/issues/3926). In other words, it is only useful on documenting a module calling `logging.warning()` globally. So I think it does not work for your case.

**Comment by tk0miya** [comment] 2020-12-25 16:35
Now I'm closing this because this is not a bug of Sphinx.
Thanks,

**Closed as completed by tk0miya** 2020-12-25 16:35 UTC
Labels: type:question, extensions:autodoc
