### ISSUE TITLE
Linux documentation build memory hog

### ISSUE THREAD

**Issue by marxin** [sphinx-doc/sphinx#11116] opened 2023-01-09 14:13 UTC
### Describe the bug

As mentioned here:
https://lore.kernel.org/all/cb916eae-fdf6-504f-8f38-7928e0fa8344@gmail.com/

the Linux kernel documentation builds https://docs.kernel.org/doc-guide/sphinx.html?highlight=sphinx#sphinx-build gets slower and consumer much more memory.

I bisected that to 080517ce55119a6358337b5f939b3942e4de63b4.
@AA-Turner: Can you please take a look?

### How to Reproduce

Clone Linux repo and apply:
https://lore.kernel.org/all/87wn629ggg.fsf@meer.lwn.net/

`make htmldocs`

### Environment Information

```text
Aforementioned Sphinx version.
```

**Comment by AA-Turner** [comment] 2023-01-09 14:15
@AA-Turner: Can you please take a look?

I'm taking a break due to other work until Easter; apologies for this. I'd advise pinning to an earlier version if a root cause can't be found.

A

**Comment by marxin** [comment] 2023-01-09 14:30
Do you think it would make sense to bisect `docutils` in order to find what caused that?

**Comment by marxin** [comment] 2023-01-10 05:51
So the issue is caused by the following removed hunk:
https://github.com/sphinx-doc/sphinx/blob/4660b62de0e83f42b6e2ede7a1a19e861e4d34e4/sphinx/util/nodes.py#L630-L643

which now relies on `docutils` `copy function which also copies `_document` property:
https://github.com/docutils/docutils/blob/bc9bf5fc2c7f905507a49e8e37c12368c2f4a0cc/docutils/docutils/nodes.py#L1056-L1061

If I add copying of `_document` to the `_new_copy` function, I get the very same memory hog.

**Comment by AA-Turner** [comment] 2023-01-10 16:03
I have released v6.1.3 which should fix this.

A

**Comment by jfbu** [comment] 2023-01-10 21:55
I will close the issue for time being but we can always reopen at later date.

The fix happened at dcb4429abacda015f98875fe9489ced696155bd7 and was merged into 6.1.3.

The original removal of the monkeypatch of DocUtils happened at 080517ce55119a6358337b5f939b3942e4de63b4 from #10470 which was part of the `6.0.0` release.

**Closed as completed by jfbu** 2023-01-10 21:55 UTC
