### ISSUE TITLE
How to exclude robot test case code from getting documented.

### ISSUE THREAD

**Issue by satya-plivo** [sphinx-doc/sphinx#4855] opened 2018-04-16 07:38 UTC
Subject: <what happen when you do on which document project>

### Problem
- I am trying to document a robot file which contains 5 test-cases, each test case have separate documentation. when i try to document that robot test case using "robot-test", my html file includes the test codes as well. So please let me know how to exclude the test case code from documenting
<Detail of problem>
<public link of unexpected result if you have>

#### Expected results
Give me an example rst file for the robot file and also index.rst file to generate documentation which does not include the test case code.
<Describe what to actually do>

### Environment info
- OS: Mac
- Python version: 2.7
- Sphinx version:
- <Extra tools: MacTex>

**Comment by tk0miya** [comment] 2018-06-16 15:43
What is "robot test"? I can't understand your question. Please let me know in detail.
Thanks,

**Comment by tk0miya** [comment] 2018-07-16 10:19
I'm closing this because this is not a bug.
Thanks,

**Closed as completed by tk0miya** 2018-07-16 10:19 UTC
Labels: type:question
