### ISSUE TITLE
AttributeError in autodoc.py during build

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1423] opened 2015-01-03 09:16 UTC
Error:

Exception occurred:
  File "/var/build/user_builds/flowp/envs/latest/lib/python3.3/site-packages/sphinx/ext/autodoc.py", line 1183, in import_object
    obj_from_parent = self.parent.**dict**.get(self.object_name)
AttributeError: 'NoneType' object has no attribute '**dict**'

Exception occurred during build at readthedocs,
details: https://readthedocs.org/builds/flowp/1231844/

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1423
- Originally reported by: Anonymous
- Originally created at: 2014-03-15T14:01:22.790

**Comment by tk0miya** [comment] 2018-02-28 16:37
At present, the errored line is not left. The `import_object()` function is much refactored after reporeted. So we can't reproduce the error now.
So I'm closing this now.
Pelase let me know if you still have this problem.

Thanks,

**Closed as completed by tk0miya** 2018-02-28 16:37 UTC
Labels: type:bug, extensions:autodoc
