### ISSUE TITLE
(Trivial) test_build_html.test_html_warnings (etc.) fails on Windows

### ISSUE THREAD

**Issue by hhsprings** [sphinx-doc/sphinx#3016] opened 2016-10-06 19:40 UTC
`test_build_html.test_html_warnings`, `test_build_latex.test_latex_warnings`, and `test_build_texinfo.test_texinfo_warnings` fails on Windows because `Encoding 'utf-8-sig'` warnings is actually generated like this:

```
WARNING: Encoding 'utf-8-sig' used for reading included file 'c://Users//hhsprings//work//sphinx//tests//build//test-warnings//wrongenc.inc' seems to be wrong, try giving an :encoding: option
```

(`//`, not `/`)

This might be the problem for some kind of IDE which gives you the ability to jump to the location, so I can't say that `I don't think this should be fixed` like as #3015, but I think this is trivial.

**Comment by hhsprings** [comment] 2016-10-07 02:43
In `directives/code.py`:

``` python
        except (IOError, OSError):
            return [document.reporter.warning(
                'Include file %r not found or reading it failed' % filename,
                line=self.lineno)]
        except UnicodeError:
            return [document.reporter.warning(
                'Encoding %r used for reading included file %r seems to '
                'be wrong, try giving an :encoding: option' %
                (encoding, filename))]
```

`repr(filename)` &rarr; `'c:\\Users\\hhsprings\\...`., this would be `'c://Users//hhsprings//...` with `replace(os.sep, '/')`.

**Comment by hhsprings** [comment] 2016-10-07 02:48
Of course, this can be fixed:

``` python
    def read_with_encoding(self, filename, document, codec_info, encoding):
        from os import path
        filename = filename.replace(path.sep, "/")
```

**Comment by hhsprings** [comment] 2016-10-07 03:01
This case is potentially not only in `read_with_encoding`.

``` python
        if objectname is not None:
            from sphinx.pycode import ModuleAnalyzer
            analyzer = ModuleAnalyzer.for_file(filename, '')
            tags = analyzer.find_tags()
            if objectname not in tags:
                return [document.reporter.warning(
                    'Object named %r not found in include file %r' %
                    (objectname, filename), line=self.lineno)]
            else:
```

``` python
            # just ignore non-existing lines
            lines = [lines[i] for i in linelist if i < len(lines)]
            if not lines:
                return [document.reporter.warning(
                    'Line spec %r: no lines pulled from include file %r' %
                    (linespec, filename), line=self.lineno)]
```

**Comment by shimizukawa** [comment] 2016-11-23 14:26
I can't reproduce the error on Windows + Py3.5 with Sphinx-1.4.9 (stable HEAD).
@hhsprings please let me know your versions and a command-line for testing.

**Comment by shimizukawa** [comment] 2016-12-03 06:42
Now I close this issue. Please feel free to resume at any time if you catch a problem.

**Closed as completed by shimizukawa** 2016-12-03 06:42 UTC
