### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by rahulkmr75** [sphinx-doc/sphinx#3745] opened 2017-05-13 07:11 UTC
Subject: while bulding documentation for essentia an error occured

### Problem
```
Exception occurred:
  File "/usr/local/lib/python2.7/dist-packages/sphinxcontrib/doxylink/parsing.py", line 116, in normalise
    argument_string_list.append(''.join((arg.qualifier,' ')))
TypeError: sequence item 0: expected string, ParseResults found
```

#### Procedure to reproduce the problem

```
./waf doc
```

#### Error logs / results

```
Exception occurred:
  File "/usr/local/lib/python2.7/dist-packages/sphinxcontrib/doxylink/parsing.py", line 116, in normalise
    argument_string_list.append(''.join((arg.qualifier,' ')))
TypeError: sequence item 0: expected string, ParseResults found
```

#### Expected results
Build the documentation successfully

### Environment info
- OS:  Ubuntu 16.04
- Python version: 2.7
- Sphinx version: 1.5.5
- <Extra tools e.g.: Browser, tex or something else>

**Comment by tk0miya** [comment] 2017-05-13 07:28
```
File "/usr/local/lib/python2.7/dist-packages/sphinxcontrib/doxylink/parsing.py", line 116, in normalise
```
It seems this is a bug of `sphinxcontrib-doxylink`. Could you report this into their project?

Thanks,

**Comment by SteinHeselmans** [comment] 2017-05-24 07:43
I got a similar error on another project. Just wanted to let you know, somebody has filed ticket https://bitbucket.org/birkenfeld/sphinx-contrib/issues/172/doxylink-typeerror-sequence-item-0

The provided solution/workaround works for me...

**Comment by tk0miya** [comment] 2017-05-24 15:34
Thank you for letting me know :-)

Anyway, this is not a bug of Sphinx. So I close this now.

**Closed as completed by tk0miya** 2017-05-24 15:34 UTC
Labels: type:question
