### ISSUE TITLE
TypeError: Cannot change parameter count from 1 to 3

### ISSUE THREAD

**Issue by alflanagan** [sphinx-doc/sphinx#2539] opened 2016-05-12 19:09 UTC
Attempting to autogenerate docs for a module with type hinting. See output below, and attached error log, conf.py, and index.rst.

May be related to sphinx-doc/sphinx#2519

```
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.4.1
loading pickled environment... not yet created
[autosummary] generating autosummary for: api/utl_files.models.rst, api/utl_files.views.rst, index.rst
Using json JSON module.

Exception occurred:

  File "/usr/local/lib/python3.5/typing.py", line 970, in __getitem__
    (len(self.__parameters__), len(params)))
TypeError: Cannot change parameter count from 1 to 3
The full traceback has been saved in /tmp/sphinx-err-n65omrwn.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [html] Error 1
```

[sphinx-err-6va5a25y.txt](https://github.com/sphinx-doc/sphinx/files/262067/sphinx-err-6va5a25y.txt)
[sphinx_config.zip](https://github.com/sphinx-doc/sphinx/files/262078/sphinx_config.zip)

**Comment by tk0miya** [comment] 2016-06-03 15:08
It seems the attached project could not build because source codes are not included.
So I could not reproduce the bug.

BTW, the error log says the error is raised on importing your source codes.

```
...
  File "/home/aflanagan/python-environments/utl_lookup/lib/python3.5/site-packages/sphinx/ext/autosummary/__init__.py", line 502, in _import_by_name
    __import__(modname)
  File "/home/aflanagan/Devel/utl_lookup/utl_files/code_markup.py", line 42, in <module>
    class UTLWithMarkup():
  File "/home/aflanagan/Devel/utl_lookup/utl_files/code_markup.py", line 57, in UTLWithMarkup
    Mapping[int, str]]:
  File "/usr/local/lib/python3.5/typing.py", line 970, in __getitem__
    (len(self.__parameters__), len(params)))
TypeError: Cannot change parameter count from 1 to 3
```

It might it is related with typing module.
Could you check it please?

**Comment by tk0miya** [comment] 2016-07-04 11:38
Now I close this.
Please reopen if you still have a same problem.

**Closed as completed by tk0miya** 2016-07-04 11:38 UTC
Labels: extensions:autodoc
