### ISSUE TITLE
OSError: cannot write mode RGBA as JPEG

### ISSUE THREAD

**Issue by XikunZhang** [sphinx-doc/sphinx#5080] opened 2018-06-13 05:34 UTC
Subject: "OSError: cannot write mode RGBA as JPEG" when making docs of pytorch using sphinx

### Problem
- "OSError: cannot write mode RGBA as JPEG" when making docs of pytorch using sphinx

#### Procedure to reproduce the problem
```
git clone https://github.com/pytorch/tutorials.git
cd tutorials
pip install -r requirements.txt
make docs
```

#### Error logs / results
```
Exception occurred:
  File "/Users/XikunZhang/Applications/anaconda3/lib/python3.6/site-packages/PIL/JpegImagePlugin.py", line 604, in _save
    raise IOError("cannot write mode %s as JPEG" % im.mode)
OSError: cannot write mode RGBA as JPEG
The full traceback has been saved in /var/folders/y9/vtjggrc97gjd26vn5f20qylc0000gn/T/sphinx-err-vepv_szw.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make[1]: *** [html] Error 1
make: *** [docs] Error 2
```

#### Expected results
Successfully make the docs

### Environment info
- OS: Mac OSX 10.13.5
- Python version: 3.6.3
- Sphinx version: 1.6.3

#### Log file
```
# Sphinx version: 1.6.3
# Python version: 3.6.3 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.9.6
# Last messages:
#   reading sources... [ 75%] beginner/nlp/sequence_models_tutorial
#   
#   reading sources... [ 77%] beginner/nlp/word_embeddings_tutorial
#   
#   reading sources... [ 80%] beginner/pytorch_with_examples
#   
#   reading sources... [ 82%] beginner/transfer_learning_tutorial
#   
#   reading sources... [ 85%] index
#   
# Loaded extensions:
#   alabaster (0.7.10) from /Users/XikunZhang/Applications/anaconda3/lib/python3.6/site-packages/alabaster/__init__.py
#   sphinx.ext.mathjax (1.6.3) from /Users/XikunZhang/Applications/anaconda3/lib/python3.6/site-packages/sphinx/ext/mathjax.py
#   sphinx_gallery.gen_gallery (0.2.0) from /Users/XikunZhang/Applications/anaconda3/lib/python3.6/site-packages/sphinx_gallery/gen_gallery.py
Traceback (most recent call last):
  File "/Users/XikunZhang/Applications/anaconda3/lib/python3.6/site-packages/PIL/JpegImagePlugin.py", line 602, in _save
    rawmode = RAWMODE[im.mode]
KeyError: 'RGBA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/XikunZhang/Applications/anaconda3/lib/python3.6/site-packages/sphinx/cmdline.py", line 306, in main
    app.build(opts.force_all, filenames)
  File "/Users/XikunZhang/Applications/anaconda3/lib/python3.6/site-packages/sphinx/application.py", line 339, in build
    self.builder.build_update()
  File "/Users/XikunZhang/Applications/anaconda3/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 331, in build_update
    'out of date' % len(to_build))
  File "/Users/XikunZhang/Applications/anaconda3/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 344, in build
    updated_docnames = set(self.env.update(self.config, self.srcdir, self.doctreedir))
  File "/Users/XikunZhang/Applications/anaconda3/lib/python3.6/site-packages/sphinx/environment/__init__.py", line 583, in update
    self._read_serial(docnames, self.app)
  File "/Users/XikunZhang/Applications/anaconda3/lib/python3.6/site-packages/sphinx/environment/__init__.py", line 602, in _read_serial
    self.read_doc(docname, app)
  File "/Users/XikunZhang/Applications/anaconda3/lib/python3.6/site-packages/sphinx/environment/__init__.py", line 723, in read_doc
    pub.publish()
  File "/Users/XikunZhang/Applications/anaconda3/lib/python3.6/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/Users/XikunZhang/Applications/anaconda3/lib/python3.6/site-packages/sphinx/io.py", line 74, in read
    self.parse()
  File "/Users/XikunZhang/Applications/anaconda3/lib/python3.6/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/Users/XikunZhang/Applications/anaconda3/lib/python3.6/site-packages/docutils/parsers/rst/__init__.py", line 191, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/Users/XikunZhang/Applications/anaconda3/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File "/Users/XikunZhang/Applications/anaconda3/lib/python3.6/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Users/XikunZhang/Applications/anaconda3/lib/python3.6/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Users/XikunZhang/Applications/anaconda3/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2753, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/Users/XikunZhang/Applications/anaconda3/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/Users/XikunZhang/Applications/anaconda3/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/Users/XikunZhang/Applications/anaconda3/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/Users/XikunZhang/Applications/anaconda3/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/Users/XikunZhang/Applications/anaconda3/lib/python3.6/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Users/XikunZhang/Applications/anaconda3/lib/python3.6/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Users/XikunZhang/Applications/anaconda3/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2753, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/Users/XikunZhang/Applications/anaconda3/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/Users/XikunZhang/Applications/anaconda3/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/Users/XikunZhang/Applications/anaconda3/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/Users/XikunZhang/Applications/anaconda3/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/Users/XikunZhang/Applications/anaconda3/lib/python3.6/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Users/XikunZhang/Applications/anaconda3/lib/python3.6/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Users/XikunZhang/Applications/anaconda3/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2328, in explicit_markup
    self.explicit_list(blank_finish)
  File "/Users/XikunZhang/Applications/anaconda3/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2358, in explicit_list
    match_titles=self.state_machine.match_titles)
  File "/Users/XikunZhang/Applications/anaconda3/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 319, in nested_list_parse
    node=node, match_titles=match_titles)
  File "/Users/XikunZhang/Applications/anaconda3/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/Users/XikunZhang/Applications/anaconda3/lib/python3.6/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Users/XikunZhang/Applications/anaconda3/lib/python3.6/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Users/XikunZhang/Applications/anaconda3/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2631, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/Users/XikunZhang/Applications/anaconda3/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2338, in explicit_construct
    return method(self, expmatch)
  File "/Users/XikunZhang/Applications/anaconda3/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2081, in directive
    directive_class, match, type_name, option_presets)
  File "/Users/XikunZhang/Applications/anaconda3/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2130, in run_directive
    result = directive_instance.run()
  File "/Users/XikunZhang/OneDrive - University of Illinois - Urbana/snap research/pytorch_tutorials_31/custom_directives.py", line 185, in run
    sphinx_gallery.gen_rst.scale_image(figname, thumbnail, 400, 280)
  File "/Users/XikunZhang/Applications/anaconda3/lib/python3.6/site-packages/sphinx_gallery/gen_rst.py", line 395, in scale_image
    thumb.save(out_fname)
  File "/Users/XikunZhang/Applications/anaconda3/lib/python3.6/site-packages/PIL/Image.py", line 1893, in save
    save_handler(self, fp, filename)
  File "/Users/XikunZhang/Applications/anaconda3/lib/python3.6/site-packages/PIL/JpegImagePlugin.py", line 604, in _save
    raise IOError("cannot write mode %s as JPEG" % im.mode)
OSError: cannot write mode RGBA as JPEG
```

**Comment by XikunZhang** [comment] 2018-06-13 06:03
This seems to do with the version of pillow by the way, and not to do with sphinx.

**Comment by tk0miya** [comment] 2018-06-13 14:07
It seems Pillow is called by `sphinx_gallery` extension.
```
  File "/Users/XikunZhang/Applications/anaconda3/lib/python3.6/site-packages/sphinx_gallery/gen_rst.py", line 395, in scale_image
    thumb.save(out_fname)
  File "/Users/XikunZhang/Applications/anaconda3/lib/python3.6/site-packages/PIL/Image.py", line 1893, in save
    save_handler(self, fp, filename)
  File "/Users/XikunZhang/Applications/anaconda3/lib/python3.6/site-packages/PIL/JpegImagePlugin.py", line 604, in _save
    raise IOError("cannot write mode %s as JPEG" % im.mode)
OSError: cannot write mode RGBA as JPEG
```

I feel there are nothing to do from sphinx-core side...

**Comment by tk0miya** [comment] 2018-06-20 16:34
I'm closing this now because this is not a bug of Sphinx.
Thanks,

**Closed as completed by tk0miya** 2018-06-20 16:34 UTC
Labels: type:question
