### ISSUE TITLE
Nature theme CSS needs updating

### ISSUE THREAD

**Issue by navhaxs** [sphinx-doc/sphinx#3418] opened 2017-02-13 05:12 UTC
After upgrading to the latest version of Sphinx, the Nature theme has some CSS issues.

### Problem
- The `Go`` search button is misaligned
- The "parameters" text looks squished (generated from `.. param` syntax)

See screenshot of latest Sphinx 1.5.2 (on left) compared to Sphinx 1.3.1 (on right):
<img width="1391" alt="untitled" src="https://cloud.githubusercontent.com/assets/5162718/22871474/46f89d34-f205-11e6-80fe-8bdb2711ec00.png">

#### Procedure to reproduce the problem
Build any project with the `nature` theme

### Environment info
- Python version: 2.7
- Sphinx version: 1.5.2

### Workaround

Currently I have the following custom CSS styles defined:

```
.search input[type="submit"] {
      margin-left: 20px;
}
th.field-name {
   white-space: nowrap;
}
```

**Comment by shibukawa** [comment] 2017-02-24 11:29
Great report! Your screenshot is very nice to know the detail.

Could you add reST source file too? I will check with other themes too.

Thank you.

**Comment by tk0miya** [comment] 2017-02-25 02:58
I fixed the alignment of search button at 4e8c622.
But I don't fixed the folding of parameter label yet, because I could not reproduce it.

**Comment by navhaxs** [comment] 2017-02-25 21:56
okay, I can reproduce with this sphinx project: https://github.com/navhaxs/sphinx-test

**Comment by tk0miya** [comment] 2017-02-26 04:29
Thanks, but I still could not reproduce. What browser did you use?
I checked it with Chrome, Firefox and Safari.

Note: the folding style (`hyphens`) was added since #3276 . It is intentional. So we need to change carefully.

**Comment by tk0miya** [comment] 2017-02-26 04:31
I partially fixed the alignment of button at 1.5.3.
But the folding problem will be fixed at 1.5.4.

**Comment by navhaxs** [comment] 2017-02-26 06:10
I had resized the browser to a small width during testing (both Chrome and Safari).

Since the hyphens are intentional, then I think this issue can be closed. 👍

**Comment by tk0miya** [comment] 2017-03-01 15:15
Thank you for comment.
In my investigation, it is intentional behavior.
So I determined not to fix it.

Thank you for reporting.

**Closed as completed by tk0miya** 2017-03-01 15:15 UTC
Labels: type:bug, html theme
