### ISSUE TITLE
Build fails during eclim (aur) build: Babel data files not available

### ISSUE THREAD

**Issue by vegarab** [sphinx-doc/sphinx#4481] opened 2018-01-23 10:01 UTC
Subject: Build fails during eclim (aur) buid: Babel data files not available

Not sure if this is where you'd want this issue, as it might be regarding eclim.. however error told me to post here.

### Problem
- RunTime error on build when trying to build [eclim (aur package)](https://aur.archlinux.org/packages/eclim/) towards eclipse-java with jdk8
- The babel data files are not available.

#### Procedure to reproduce the problem
```
packer -S eclim
```

#### Error logs / results
```
==> Entering fakeroot environment...
==> Starting package()...
Buildfile: /tmp/packerbuild-1000/eclim/eclim/src/eclim_2.7.1/build.xml

docs:

gant:
     [echo] ${eclipse}: /usr/lib/eclipse
     [echo] # Skipping org.eclim.wst, missing org.eclipse.wst.web_ui.feature
     [echo] # Skipping org.eclim.sdt, missing org.scala-ide.sdt.feature
     [echo] # Skipping org.eclim.pydev, missing org.python.pydev.feature
     [echo] # Skipping org.eclim.pdt, missing org.eclipse.php
     [echo] # Skipping org.eclim.groovy, missing org.codehaus.groovy.jdt.patch
     [echo] # Skipping org.eclim.dltkruby, missing org.eclipse.dltk.ruby
     [echo] # Skipping org.eclim.dltk, missing org.eclipse.dltk.core
     [echo] # Skipping org.eclim.cdt, missing org.eclipse.cdt
     [echo] # Skipping org.eclim.adt, missing com.android.ide.eclipse.adt.feature
     [echo] Plugins:
     [echo]   org.eclim.jdt
docs:
init:
     [echo] eclim.version: 2.7.1
     [echo] eclim.release: 2.7.1
org.eclim.jdt.classpath:
------ org.eclim.jdt.classpath
------ init
     [exec] Running Sphinx v1.6.6
     [exec] Change of translator for the html builder.
     [exec] loading pickled environment... not yet created
     [exec] building [mo]: targets for 0 po files that are out of date
     [exec] building [html]: targets for 86 source files that are out of date
     [exec] /usr/lib/python2.7/site-packages/sphinx/util/compat.py:40: RemovedInSphinx17Warning: sphinx.util.compat.Directive is deprecated and will be removed in Sphinx 1.7, please use docutils' instead.
     [exec] updating environment: 86 added, 0 changed, 0 removed  RemovedInSphinx17Warning)
     [exec] 
     [exec] reading sources... [  1%] 404
     [exec] WARNING: while setting up extension eclim.sphinx.include: directive 'include' is already registered, it will be overridden
     [exec] reading sources... [  2%] archive/changes
     [exec] reading sources... [  3%] archive/news
     [exec] reading sources... [  4%] changes
     [exec] reading sources... [  5%] cheatsheet
     [exec] reading sources... [  6%] contribute
     [exec] reading sources... [  8%] development/architecture
     [exec] reading sources... [  9%] development/commands
     [exec] reading sources... [ 10%] development/gettingstarted
     [exec] reading sources... [ 11%] development/index
     [exec] reading sources... [ 12%] development/installer
     [exec] reading sources... [ 13%] development/plugins
     [exec] reading sources... [ 15%] eclimd
     [exec] reading sources... [ 16%] faq
     [exec] reading sources... [ 17%] features
     [exec] reading sources... [ 18%] gettinghelp
     [exec] reading sources... [ 19%] gettingstarted
     [exec] reading sources... [ 20%] index
     [exec] reading sources... [ 22%] install
     [exec] reading sources... [ 23%] relatedprojects
     [exec] reading sources... [ 24%] vim/c/complete
     [exec] reading sources... [ 25%] vim/c/index
     [exec] reading sources... [ 26%] vim/c/inspection
     [exec] reading sources... [ 27%] vim/c/project
     [exec] reading sources... [ 29%] vim/c/search
     [exec] reading sources... [ 30%] vim/c/validate
     [exec] reading sources... [ 31%] vim/code_completion
     [exec] reading sources... [ 32%] vim/core/eclim
     [exec] reading sources... [ 33%] vim/core/history
     [exec] reading sources... [ 34%] vim/core/index
     [exec] reading sources... [ 36%] vim/core/locate
     [exec] reading sources... [ 37%] vim/core/project
     [exec] reading sources... [ 38%] vim/core/util
     [exec] reading sources... [ 39%] vim/dltk/buildpath
     [exec] reading sources... [ 40%] vim/groovy/complete
     [exec] reading sources... [ 41%] vim/groovy/index
     [exec] reading sources... [ 43%] vim/groovy/validate
     [exec] reading sources... [ 44%] vim/html/index
     [exec] reading sources... [ 45%] vim/index
     [exec] reading sources... [ 46%] vim/java/android
     [exec] reading sources... [ 47%] vim/java/ant
     [exec] reading sources... [ 48%] vim/java/classpath
     [exec] reading sources... [ 50%] vim/java/complete
     [exec] reading sources... [ 51%] vim/java/debug
     [exec] reading sources... [ 52%] vim/java/format
     [exec] reading sources... [ 53%] vim/java/import
     [exec] reading sources... [ 54%] vim/java/index
     [exec] reading sources... [ 55%] vim/java/inspection
     [exec] reading sources... [ 56%] vim/java/java
     [exec] reading sources... [ 58%] vim/java/javadoc
     [exec] reading sources... [ 59%] vim/java/logging
     [exec] reading sources... [ 60%] vim/java/maven
     [exec] reading sources... [ 61%] vim/java/methods
     [exec] reading sources... [ 62%] vim/java/refactor
     [exec] reading sources... [ 63%] vim/java/search
     [exec] reading sources... [ 65%] vim/java/types
     [exec] reading sources... [ 66%] vim/java/unittests
     [exec] reading sources... [ 67%] vim/java/validate
     [exec] reading sources... [ 68%] vim/java/webxml
     [exec] reading sources... [ 69%] vim/javascript/index
     [exec] reading sources... [ 70%] vim/php/buildpath
     [exec] reading sources... [ 72%] vim/php/complete
     [exec] reading sources... [ 73%] vim/php/index
     [exec] reading sources... [ 74%] vim/php/search
     [exec] reading sources... [ 75%] vim/php/validate
     [exec] reading sources... [ 76%] vim/python/complete
     [exec] reading sources... [ 77%] vim/python/django
     [exec] reading sources... [ 79%] vim/python/index
     [exec] reading sources... [ 80%] vim/python/path
     [exec] reading sources... [ 81%] vim/python/search
     [exec] reading sources... [ 82%] vim/python/validate
     [exec] reading sources... [ 83%] vim/refactoring
     [exec] reading sources... [ 84%] vim/ruby/buildpath
     [exec] reading sources... [ 86%] vim/ruby/complete
     [exec] reading sources... [ 87%] vim/ruby/index
     [exec] reading sources... [ 88%] vim/ruby/search
     [exec] reading sources... [ 89%] vim/ruby/validate
     [exec] reading sources... [ 90%] vim/scala/complete
     [exec] reading sources... [ 91%] vim/scala/import
     [exec] reading sources... [ 93%] vim/scala/index
     [exec] reading sources... [ 94%] vim/scala/search
     [exec] reading sources... [ 95%] vim/scala/validate
     [exec] reading sources... [ 96%] vim/search
     [exec] reading sources... [ 97%] vim/settings
     [exec] reading sources... [ 98%] vim/validation
     [exec] reading sources... [100%] vim/xml/index
     [exec] 
     [exec] looking for now-outdated files... none found
     [exec] pickling environment... done
     [exec] checking consistency... done
     [exec] 
     [exec] Exception occurred:
     [exec]   File "/usr/lib/python2.7/site-packages/babel/core.py", line 27, in _raise_no_data_error
     [exec]     raise RuntimeError('The babel data files are not available. '
     [exec] RuntimeError: The babel data files are not available. This usually happens because you are using a source checkout from Babel and you did not build the data files.  Just make sure to run "python setup.py import_cldr" before installing the library.
     [exec] The full traceback has been saved in /tmp/sphinx-err-VzZona.log, if you want to report the issue to the developers.
     [exec] Please also report this if it was a user error, so that a better error message can be provided next time.
     [exec] A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
     [exec] preparing documents... 

BUILD FAILED
/tmp/packerbuild-1000/eclim/eclim/src/eclim_2.7.1/build.xml:114: The following error occurred while executing this line:
/tmp/packerbuild-1000/eclim/eclim/src/eclim_2.7.1/build.xml:163: : exec returned: 1

Total time: 6 seconds
==> ERROR: A failure occurred in package().
    Aborting...
The build failed.
```

### Environment info
- OS: ArchLinux 4.14.13
- Python version: 2.7

**Comment by tk0miya** [comment] 2018-01-23 11:37
>     [exec] RuntimeError: The babel data files are not available. This usually happens because you are using a source checkout from Babel and you did not build the data files.  Just make sure to run "python setup.py import_cldr" before installing the library.

The error also says this is an issue related with installation.
How did you install babel package?

FYI: babel is one of dependency packages of Sphinx.

**Comment by vegarab** [comment] 2018-01-23 11:41
>  How did you install babel package?

I've tried to install Sphinx and Babel from the Arch central repo with pacman, and with pip2 before attempting to install eclim. I always get the exact same build error.

**Comment by tk0miya** [comment] 2018-01-28 16:03
Hmm... sorry, I'm not good at both babel and Arch Linux. Please ask to the babel project about the message.
Thanks,

**Comment by tk0miya** [comment] 2018-02-20 17:31
I'm closing this now because this is not a bug of Sphinx.
Thanks,

**Closed as completed by tk0miya** 2018-02-20 17:31 UTC
Labels: type:question
