### ISSUE TITLE
Circular dependency causes dependency checking tools to fail

### ISSUE THREAD

**Issue by lseek** [sphinx-doc/sphinx#1845] opened 2015-04-14 05:44 UTC
`sphinx` specifies `sphinx_rtd_theme` as a dependency in `tests-reqs.txt` but `sphinx_rtd_theme` specifies `sphinx>=1.1` as a dependency, thus leading to a circular dependency which causes a dependency checking tool (currently using `pip-compile`) to flag an error.

**Comment by birkenfeld** [comment] 2015-04-14 06:15
Hmm, since these are not "needs to build" dependencies but "needs to run" dependencies, I don't see why the circular dependency is so bad. ("install_requires", despite the slightly misleading name, means "needs to be installed together with this one". The build-time dependency would be "setup_requires".) So please take this up with the `pip-compile` authors.

If that is considered inacceptable, I suggest filing this with sphinx_rtd_theme, since Sphinx _definitely_ doesn't run without it now, while the theme doesn't "run" (or do anything) anyway if Sphinx is not present.

**Comment by jakirkham** [comment] 2015-04-22 16:19
This appears to be suboptimal for building with `conda build`. When trying to build a newer version of `sphinx`, `conda` will try to fill the dependency by installing an older version of `sphinx` to satisfy `sphinx_rtd_theme`. The unfortunate consequence appears to be the final built `sphinx` package cannot be imported. Trying to make `sphinx_rtd_theme` a run requirement and not a build requirement fails as `setuptools` will try to download the missing requirement at build time, which is forbidden in `conda build`.

Could another solution please be considered? Perhaps bundling an acceptable copy of `sphinx_rtd_theme` as an extension (or otherwise) that can be upgraded or similar.

**Comment by birkenfeld** [comment] 2015-04-22 18:30
Well, what do the conda people say about this?

**Comment by jakirkham** [comment] 2015-04-22 20:51
Fair question, asked in this issue ( https://github.com/conda/conda-build/issues/381 ). I tried a different manner of building here ( https://github.com/conda/conda-build/issues/380 ), which has a different result. So, I can't conclusive say what the cause was, but I am a little worried about how these dependencies are setup.

**Comment by jakirkham** [comment] 2015-04-22 20:57
Also, @birkenfeld, I have followed up on your previous point by opening an issue with [`sphinx_rtd_theme`](https://github.com/snide/sphinx_rtd_theme) as seen here ( https://github.com/snide/sphinx_rtd_theme/issues/189 ).

**Comment by birkenfeld** [comment] 2015-04-23 06:21
Thanks!

**Comment by karelin** [comment] 2015-07-02 08:52
Perhaps I'm missing something, but Sphinx requires sphinx_rtd_theme in its setup.py script. It seems not 'testing requirement'. Will it be more wise not to rely on any particular themes that user may not need?

**Comment by jakirkham** [comment] 2016-01-12 00:58
It looks like the `sphinx_rtd_theme` issue was closed out by this PR ( https://github.com/snide/sphinx_rtd_theme/pull/275 ). So, maybe we can close this out now as it is no longer a circular dependency, but just a dependency.

**Comment by tk0miya** [comment] 2016-01-14 12:59
@jakirkham Thank you for letting us know.
Now, I close this issue.

**Closed as completed by tk0miya** 2016-01-14 12:59 UTC
