### ISSUE TITLE
Getting apidoc --imported-members behaviour with autosummary

### ISSUE THREAD

**Issue by hameerabbasi** [sphinx-doc/sphinx#4372] opened 2018-01-03 13:23 UTC
Subject: Getting apidoc `--imported-members` behaviour with autosummary

### Problem
- I'm trying to find out how to get `sphinx-apidoc`'s `--imported-members` functionality with `autosummary_generate = True`. I can't seem to find anything for this in the issue tracker. It also ignores `__all__` in `__init__.py` for the module.

#### Procedure to reproduce the problem
```
rm -rf build/ docs/_build/ docs/generated/ && python setup.py build_sphinx
```

#### Error logs / results
```
running build_sphinx
creating /Users/hameerabbasi/PycharmProjects/sparse/build
creating /Users/hameerabbasi/PycharmProjects/sparse/build/sphinx
creating /Users/hameerabbasi/PycharmProjects/sparse/build/sphinx/doctrees
creating /Users/hameerabbasi/PycharmProjects/sparse/build/sphinx/html
Running Sphinx v1.6.5
loading pickled environment... not yet created
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://docs.scipy.org/doc/numpy/objects.inv...
loading intersphinx inventory from https://docs.scipy.org/doc/scipy/reference/objects.inv...
[autosummary] generating autosummary for: index.rst, modules.rst
[autosummary] generating autosummary for: /Users/hameerabbasi/PycharmProjects/sparse/docs/_autosummary/sparse.rst
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 2 source files that are out of date
updating environment: 3 added, 0 changed, 0 removed
reading sources... [100%] modules                                               
/Users/hameerabbasi/PycharmProjects/sparse/docs/modules.rst:7: WARNING: Error in "autosummary" directive:
unknown option: "imported_members".

.. autosummary::
   :toctree: _autosummary
   :imported_members: True

   sparse
looking for now-outdated files... none found
pickling environment... done
checking consistency... /Users/hameerabbasi/PycharmProjects/sparse/docs/_autosummary/sparse.rst: WARNING: document isn't included in any toctree
done
preparing documents... done
writing output... [100%] modules                                                
generating indices... genindex py-modindex
writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 2 warnings.
```
- <public link of unexpected result if you have>

#### Expected results
There should be a `:imported_members:` option, or maybe it's called something else and I'm not aware of it?

### Reproducible project / your project
- https://github.com/nils-werner/sparse/tree/docs

Add the `:imported_members:` line in `docs/modules.rst`

### Environment info
- OS: macOS 10.13.2
- Python version: 3.6.4
- Sphinx version: 1.6.5

**Comment by tk0miya** [comment] 2018-01-04 13:50
I tested with following Dockerfile, but I can't reproduce the error.
```
FROM tk0miya/sphinx-html

RUN git clone https://github.com/nils-werner/sparse
WORKDIR /docs/sparse

RUN git checkout docs
RUN pip3 install -U -e . matplotlib sphinxcontrib-napoleon sphinx_rtd_theme Sphinx
RUN rm -rf docs/_autosummary && python3 setup.py build_sphinx
```
```
$ docker build .
(snip)
Step 6/6 : RUN rm -rf docs/_autosummary && python3 setup.py build_sphinx
 ---> Running in e7d4462a3e7e
running build_sphinx
creating /docs/sparse/build
creating /docs/sparse/build/sphinx
creating /docs/sparse/build/sphinx/doctrees
creating /docs/sparse/build/sphinx/html
Running Sphinx v1.6.5
loading pickled environment... not yet created
loading intersphinx inventory from https://docs.scipy.org/doc/scipy/reference/objects.inv...
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://docs.scipy.org/doc/numpy/objects.inv...
[autosummary] generating autosummary for: index.rst, modules.rst
[autosummary] generating autosummary for: /docs/sparse/docs/generated/sparse.rst
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 2 source files that are out of date
updating environment: 3 added, 0 changed, 0 removed
reading sources... [ 33%] generated/sparse
reading sources... [ 66%] index
reading sources... [100%] modules

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [ 33%] generated/sparse
writing output... [ 66%] index
writing output... [100%] modules

generating indices... genindex py-modindex
writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded.
 ---> e867844d1660
Removing intermediate container e7d4462a3e7e
Successfully built e867844d1660
```

I feel a bit strange for your error log. Sphinx uses hyphens for `:imported-members:` option, not underscore. I wonder where does the invalid option come from.

**Comment by hameerabbasi** [comment] 2018-01-04 14:07
@tk0miya You have to manually add the `:imported-members:` option in `docs/modules.rst`, it's not actually added. Also, the problem is in `autosummary`, not `autodoc`. There is no `:imported-members:` in `autosummary`.

**Comment by hameerabbasi** [comment] 2018-01-04 14:09
Also, if you inspect the generated docs, they're mostly empty, which is why I need `:imported-members:`... Or that `autosummary` should include something like detecting members from `__all__`

**Comment by MarSoft** [comment] 2018-10-29 15:27
Would be great to have this functionality.

**Comment by tk0miya** [comment] 2019-04-04 14:08
`autosummary_imported_members ` option is added in #6212 . I think it resolves this. So I'm closing this now.
Thank you for reporting.

**Closed as completed by tk0miya** 2019-04-04 14:08 UTC
Labels: extensions:apidoc, extensions:autosummary
