### ISSUE TITLE
Remove chapters for custom howto LaTeX classes

### ISSUE THREAD

**Issue by sephalon** [sphinx-doc/sphinx#6672] opened 2019-08-26 13:37 UTC
**Is your feature request related to a problem? Please describe.**
Since the `article` LaTeX class, which the Sphinx `howto` class is based upon, does not support chapters they are removed according to the following control structure in `sphinx/writers/latex.py`:

        # we assume LaTeX class provides \chapter command except in case
        # of non-Japanese 'howto' case
        self.sectionnames = LATEXSECTIONNAMES[:]
        if self.settings.docclass == 'howto':
            docclass = self.config.latex_docclass.get('howto', 'article')
            if docclass[0] == 'j':  # Japanese class...
                pass
            else:
                self.sectionnames.remove('chapter')
        else:
            docclass = self.config.latex_docclass.get('manual', 'report')
        self.elements['docclass'] = docclass

We use custom LaTeX classes that are based on (i.e. `\LoadClass` them) the default Sphinx `howto` and `manual` classes. However, it is not possible to trigger the removal of chapters with a custom class name. The option `latex_toplevel_sectioning` only works on a global level and does not allow us to mix `howto`/`manual`-style classes in the `latex_documents` list anymore.

**Describe the solution you'd like**
An easy solution would be to replace the line

        if self.settings.docclass == 'howto':

by

        if 'howto' in self.settings.docclass:

enabling the removal of chapters for any class containing the keyword `howto`.

**Describe alternatives you've considered**
Have not come up with any other solution so far.

**Comment by jfbu** [comment] 2019-09-02 12:44
Do I understand correctly that you use something like `'sephalonhowto'` as docclass, and that you have a LaTeX custom class file `sephalonhowto.cls` (added to [`latex_additionalfiles`](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-latex_additional_files)) which will execute `\LoadClass{sphinxhowto}`? (this is not something expected...)

+1 for your proposal, reasonable.

Alternative I see is to have in your project source a custom file `sphinxhowto.cls` which would rather than use `\LoadClass` physically incorporate the original official one. Then you would use `'howto'` as docclass.

**Comment by sephalon** [comment] 2019-09-04 07:46
> Do I understand correctly that you use something like 'sephalonhowto' as docclass, and that you have a LaTeX custom class file sephalonhowto.cls (added to latex_additionalfiles) which will execute \LoadClass{sphinxhowto}? (this is not something expected...)

Yes, correct. As the official classes do some Sphinx-specific stuff, I wanted to preserve this in my own custom classes. Or are there any reasons for not doing this?

> Alternative I see is to have in your project source a custom file sphinxhowto.cls which would rather than use \LoadClass physically incorporate the original official one. Then you would use 'howto' as docclass.

That should work, however then one would have to make sure that the copied parts stay in sync with the official classes after every update.

In any case we should work towards a guide on how to create custom LaTeX classes as right now there is almost no documentation available.

**Comment by jfbu** [comment] 2019-09-04 08:40
> 
> Yes, correct. As the official classes do some Sphinx-specific stuff, I wanted to preserve this in my own custom classes. Or are there any reasons for not doing this?
> 

As [our documentation](https://www.sphinx-doc.org/en/master/usage/configuration.html?highlight=latex_documents#confval-latex_documents)  tersely says

> Other document classes can be given. Independently of the document class, the “sphinx” package is always loaded in order to define Sphinx’s custom LaTeX commands.

which implies that it is not strictly required to load one of the two Sphinx LaTeX class file.

I got myself confused about that in the past and introduced a regression with `\sphinxmaketitle` which is used by our LaTeX template but was defined in our class files not in ``sphinx.sty`` (see #6683 for a fix to be merged soon).

Also, the `\sphinxbackoftitlepage` is provided to add something at back of title page (manual class) but will remain effectless if user chosen docclass is not the `'manual'` one. A user doing  `\LoadClass{sphinxmanual}` as you suggest recovers the functionality.

The officially supported way goes the opposite direction: the two Sphinx classes are conceived as "wrapper classes" of user provided ones. This is customizable via the [``latex_docclass``](https://www.sphinx-doc.org/en/master/usage/configuration.html?#confval-latex_docclass) dictionary which tells which LaTeX classes the ``'howto'`` or ``'manual'`` are supposed to incorporate via ``\LoadClass``. By default they will be the ``article``, respectively ``report`` standard LaTeX classes.

This means that a user chosen LaTeX document class can provide custom configuration but if it tries to define its own ``\sphinxmaketitle`` that gets lost, because the Sphinx own classes define this macro after having done ``\LoadClass`` on your custom class.


> > Alternative I see is to have in your project source a custom file sphinxhowto.cls which would rather than use \LoadClass physically incorporate the original official one. Then you would use 'howto' as docclass.
> 
> That should work, however then one would have to make sure that the copied parts stay in sync with the official classes after every update.
> 


Yes, definitely a drawback.

> In any case we should work towards a guide on how to create custom LaTeX classes as right now there is almost no documentation available.

As you may have guessed, it took me years to start to understand what I have explained above, so I heartfully agree our documentation is a bit terse. And the current situation is not good because it means any new functionality we add to our two Sphinx classes gets lost on people who use neither ``'howto'`` nor  ``'manual'`` but their own, meaning then that ``sphinxhowto.cls/sphinxmanual.cls`` are bypassed completely, bringing complexity to maintenance and documentation.

And the [``latex_docclass``](https://www.sphinx-doc.org/en/master/usage/configuration.html?#confval-latex_docclass) mechanism to use correctly ``sphinxhowto.cls/sphinxmanual.cls`` as wrapper classes of user specified one is probably not so known.

And your issue raises the question of providing some official mechanism to wrap the Sphinx wrappers (of some ``article``, ``book``, ``memoir``... LaTeX class) inside some own encapsulator allowing further customization at the class level. This sounds quite legitimate.

**Comment by jfbu** [comment] 2019-09-04 08:59
As (temporary) workaround for this issue with removing chapters, you can (see bottom of https://www.sphinx-doc.org/en/master/latex.html page) use a custom `latex.tex_t`  template file. You only need to copy the [official one](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/templates/latex/latex.tex_t) and modify https://github.com/sphinx-doc/sphinx/blob/3261b87cf54fbccc9b2a306e032be9941db509cb/sphinx/templates/latex/latex.tex_t#L12 to specify directly your own class (which will do `\LoadClass{sphinxhowto}`).

If you do that simply use ``'howto'`` in ``latex_documents``. Untested but it should work.

**Comment by sephalon** [comment] 2019-09-06 08:23
> As (temporary) workaround for this issue with removing chapters, you can (see bottom of https://www.sphinx-doc.org/en/master/latex.html page) use a custom `latex.tex_t` template file. You only need to copy the [official one](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/templates/latex/latex.tex_t) and modify
> https://github.com/sphinx-doc/sphinx/blob/3261b87cf54fbccc9b2a306e032be9941db509cb/sphinx/templates/latex/latex.tex_t#L12
> to specify directly your own class (which will do `\LoadClass{sphinxhowto}`).
> 
> If you do that simply use `'howto'` in `latex_documents`. Untested but it should work.

Thanks, that was a hint into the right direction. I replaced

https://github.com/sphinx-doc/sphinx/blob/3261b87cf54fbccc9b2a306e032be9941db509cb/sphinx/templates/latex/latex.tex_t#L12

by

    \documentclass[<%= papersize %>,<%= pointsize %><%= classoptions %>]{<%= wrapperclass.replace('sphinx', 'sephalon' %>}

which preserves the chapter pruning for howto classes and the loads the right document class, plus I can mix `howto` and `manual` in `latex_documents`. This workaround solves my problem for now.

**Comment by sephalon** [comment] 2019-09-06 08:28
> The officially supported way goes the opposite direction: the two Sphinx classes are conceived as "wrapper classes" of user provided ones. This is customizable via the [`latex_docclass`](https://www.sphinx-doc.org/en/master/usage/configuration.html?#confval-latex_docclass) dictionary which tells which LaTeX classes the `'howto'` or `'manual'` are supposed to incorporate via `\LoadClass`. By default they will be the `article`, respectively `report` standard LaTeX classes.
> 
> This means that a user chosen LaTeX document class can provide custom configuration but if it tries to define its own `\sphinxmaketitle` that gets lost, because the Sphinx own classes define this macro after having done `\LoadClass` on your custom class.

I think it's a major drawback if one can't override everything in their custom class, especially something as common as `\sphinxmaketitle`.

> As you may have guessed, it took me years to start to understand what I have explained above, so I heartfully agree our documentation is a bit terse. And the current situation is not good because it means any new functionality we add to our two Sphinx classes gets lost on people who use neither `'howto'` nor `'manual'` but their own, meaning then that `sphinxhowto.cls/sphinxmanual.cls` are bypassed completely, bringing complexity to maintenance and documentation.
> 
> And the [`latex_docclass`](https://www.sphinx-doc.org/en/master/usage/configuration.html?#confval-latex_docclass) mechanism to use correctly `sphinxhowto.cls/sphinxmanual.cls` as wrapper classes of user specified one is probably not so known.
> 
> And your issue raises the question of providing some official mechanism to wrap the Sphinx wrappers (of some `article`, `book`, `memoir`... LaTeX class) inside some own encapsulator allowing further customization at the class level. This sounds quite legitimate.

Thanks for all your explanations; I understand that the situation is rather complicate. If I can help with something let me know.

**Comment by jfbu** [comment] 2019-09-06 08:30
Looks brillant. There is non public https://github.com/sphinx-doc/sphinx/blob/00efa53decbdf7a49f0883deb61ea5be9e66fb21/sphinx/writers/latex.py#L650-L656
which should perhaps be exposed so that the `'sphinx'` prefix could become a user specified prefix, in your case `'sephalon'`.

And/or add a user customizable `wrapperclass` latex variable to influence https://github.com/sphinx-doc/sphinx/blob/00efa53decbdf7a49f0883deb61ea5be9e66fb21/sphinx/writers/latex.py#L481-L482

**Comment by jfbu** [comment] 2019-09-06 08:38
> I think it's a major drawback if one can't override everything in their custom class, especially something as common as `\sphinxmaketitle`.

I agree but notice that the class is loaded at the very beginning. Almost all of Sphinx specific LaTeX manoeuvers happen later in the preamble, particularly via loading of `sphinx.sty`. And user has the `'preamble'` key of `latex_elements` to override most everything.

I do agree that the title layout may be argued to belong to the class proper. But imagine you want to render it using some fancy TikZ thing, then the logic means the class itself whould load `tcolorbox/tikz` etc... not that there is anything bad about it, but this raises potential for conflict with `sphinx.sty`. Thus a comprehensive solution to your issue seems to require a more modular approach, currently we have a rather big an monolithic `sphinx.sty` with a few bits and pieces of package loading detached to user customizable `latex_elements` and/or template keys.

Anyway, for time being I think exposing the `'sphinx'` prefix hard-coded in `format_docclass()` to some user customizable string, and adding a bit of documentation understandable by Sphinx users knowing what a LaTeX document class is could resolve to a large extent your issue.

**Comment by tk0miya** [comment] 2020-03-14 08:00
I added an experimental feature: LaTeX theming. It allows you to choose top-level sectioning unit. Please try it.
Thanks,

**Closed as completed by tk0miya** 2020-03-14 08:00 UTC
Labels: type:enhancement, builder:latex
