### ISSUE TITLE
ipython warning

### ISSUE THREAD

**Issue by raybellwaves** [sphinx-doc/sphinx#4394] opened 2018-01-08 03:07 UTC
First time using `sphinx` so apologize for any lack of information.

Subject: typing `ipython` on my console brings up a `sphinx` warning. TL;DR: possibly due to `conda` installation installing version 1.6.3 (I see 1.6.5 is released now).

### Problem
Not a major problem in the slightest. Just trying to understand it a bit better.
Typing `ipython` gives a Warning from `sphinx`. I'm surprised/don't understand that when I type `ipython` it looks in the `sphinx` package. 

#### Procedure to reproduce the problem
```
$ ipython
```

#### Error logs / results
```
$ ipython
/Users/Ray/anaconda/lib/python3.6/site-packages/sphinx/util/compat.py:40: RemovedInSphinx17Warning: sphinx.util.compat.Directive is deprecated and will be removed in Sphinx 1.7, please use docutils' instead.
  RemovedInSphinx17Warning)
Python 3.6.3 | packaged by conda-forge | (default, Nov  4 2017, 10:13:32) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: 
```
- <public link of unexpected result if you have>

#### Expected results
Typing `ipython` would not bring up any Warnings.

### Reproducible project / your project
N/A

### Environment info
- OS: 10.13.2
- Python version: 3.6.3
- Sphinx version: 1.6.3
- IPython version: 6.2.1
- Installation: conda install -c anaconda sphinx

**Comment by tk0miya** [comment] 2018-01-08 03:27
It is a deprecation message for sphinx extensions. I don't know why it is emitted on invoking ipython.
But I guess any sphinx extensions are called and uses deprecated interfaces.

You can investigate what module emits it using `PYTHONWARNINGS` envvar like `PYTHONWARNINGS=error ipython`.
https://docs.python.org/3/using/cmdline.html#envvar-PYTHONWARNINGS

**Comment by jfbu** [comment] 2018-01-08 08:00
can you confirm your version of ipython (well I do see 6.2.1) in your post. The issue you report was fixed [upstream](https://github.com/ipython/ipython/pull/10668) and I can not reproduce your issue in a virtualenv with sphinx==1.6.3 and ipython==6.2.1. Perhaps try to re-install IPython.

**Comment by jfbu** [comment] 2018-01-08 08:17
to be sure, locate and check contents of file

    lib/python3.6/site-packages/IPython/sphinxext/ipython_directive.py

in your Anaconda install. It is buggy if it contains the line

    from sphinx.util.compat import Directive

The upstream fix is in ipython 6.2.1. and was also backported to ipython 6.2.0.

**Comment by tk0miya** [comment] 2018-01-09 16:35
jfbu, thank you for your comment.
It seems this is already resolved on upstream.

Anyway, this is not a bug of Sphinx. So I close this now.
Thanks,

**Closed as completed by tk0miya** 2018-01-09 16:35 UTC
Labels: type:question

**Comment by raybellwaves** [comment] 2018-01-10 13:21
Thanks for your teachings
