### ISSUE TITLE
 add_css = getattr(app, "add_css_file", app.add_stylesheet)                                            

### ISSUE THREAD

**Issue by zhuxining928** [sphinx-doc/sphinx#12004] opened 2024-02-25 07:47 UTC
### Describe the bug

AttributeError: 'Sphinx' object has no attribute 'add_stylesheet'

### How to Reproduce

AttributeError: 'Sphinx' object has no attribute 'add_stylesheet'

### Environment Information

```text
sphinx 7.2.6
```

### Sphinx extensions

```python
no
```

### Additional context

no

**Comment by picnixz** [comment] 2024-02-25 08:28
Please provide a better traceback and a MWE. I suspect the issue is from a custom extension or a theme. 

This function is likely deprecated and the theme you are using is not up-to-date.

**Comment by electric-coder** [comment] 2024-02-25 08:43
@zhuxining928 see the definition of [minimum reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example). You need to give us a minimum example of code that allows to reproduce the same error.

**Comment by picnixz** [comment] 2024-02-25 10:57
Don't use `` add_css = getattr(app, "add_css_file", app.add_stylesheet)``. If you want to support "multiple" versions of Sphinx, you should rather do:

```python

try:
	add_css = app.add_css_file
except AttributeError:
	add_css = app.add_stylesheet
```

With your construction, `app.add_stylesheet` is executed whether `add_css_file` exists or not. I am closing this issue since it does not affect Sphinx core development.

**Closed as not planned by picnixz** 2024-02-25 10:57 UTC
