### ISSUE TITLE
Incorrect Makefile quoting in sphinx-quickstart

### ISSUE THREAD

**Issue by EtchedPixels** [sphinx-doc/sphinx#6272] opened 2019-04-08 20:14 UTC
**Describe the bug**
If you have for example a space or meta characer in the build directory name the resulting Makefile is invalid

**To Reproduce**
Run sphinx quickstart
Give $splat as the directory name
Admire the bogus makefile

**Expected behavior**
Quoted string

**Environment info**
- OS:  Linux (Fedora)
- Python version: 3.6.8

**Comment by tk0miya** [comment] 2019-04-11 16:28
I'm not good at Makefile. So I marked this as "help wanted".

**Comment by jfbu** [comment] 2019-04-14 16:37
With current sphinx-quickstart at master one can not give build directory a name interactively. The build directory will be either ``_build`` or ``build``. One can give sphinx-quickstart the root of project I tried with proper quoting in shell

```
$ sphinx-quickstart \$foo
```

and all seems OK. In fact [our docs](http://www.sphinx-doc.org/en/master/man/sphinx-quickstart.html) does not even indicate possibility to pass such a repertory name. I think documented usage is that ``sphinx-quickstart`` creates the Sphinx project inside current directory. Can you please explain more how you get wrong Makefile?

**Comment by EtchedPixels** [comment] 2019-04-14 18:14
I ran sphinx-quickstart and when it asked for the prefix I said '$' (when I actually found it initially I had 'scratch ' with a space which also broke.

**Comment by jfbu** [comment] 2019-04-14 19:16
@EtchedPixels since recently released 2.0.1 the sphinx-quickstart will not ask user for a prefix. Either there is an argument which is then taken as name of the directory to create, and of course it should be properly shell-quoted, or there is no argument and then the structure is created with root being ``.``. Thus I can not reproduce your problem with Sphinx 2.0.1.

**Comment by EtchedPixels** [comment] 2019-04-14 22:12
I am still on 1.x so that makes sense

**Comment by jfbu** [comment] 2019-04-15 08:45
For 2.0.1, some variables can be set as options on command line but neither the source nor the build directory (which end up in the Makefile) are among them ; and the sole argument is the project root path which clearly should be shell-escaped and/or protected by quotes and anyway it does not end up in Makefile either.

There will be no update to 1.x series, so I think we can close this.

Waiting for @tk0miya go-ahead. Thanks for reporting!

**Closed as completed** 2019-04-15 10:22 UTC
Labels: type:bug, help wanted
