### ISSUE TITLE
Acrobat Reader cannot open generated pdf with too many chapters

### ISSUE THREAD

**Issue by Kamil-D** [sphinx-doc/sphinx#4947] opened 2018-05-09 12:37 UTC
Subject: Acrobat Reader cannot open generated pdf with too many chapters

I encountered a problem with opening pdf generated by Sphinx 'make pdf' command. As it turned out I can open file on the browser or by another pdf reader but the problem is when using Adobe Acrobat Reader. An error on Adobe software is - "There was an error processing a page. There was a problem reading this document (15)".
I made an investigation and I discovered that mentioned error occurs only when document has too many chapters (not regardless of the level of nesting). I thought that the problem is with some marks with whom Adobe can't handle but no.
To sum up - this is probably some kind of Sphinx bug. Have you got any clues how to solve this problem for this moment?

I found quite similar issue on the stackoverflow but the given solution doesn't work in my case (setting uppdf_break_level to 0).
https://stackoverflow.com/questions/25838717/sphinx-pdf-output-is-bad-how-do-i-chase-down-the-cause

Please check attached "Sample Sphinx.zip" file - there are all project files.

#### Procedure to reproduce the problem

Just add a new one chapter on the "one.rst" or "two.rst" file and generate pdf file. Then an error will show up during opening .pdf in Acrobat Reader.

### Environment info
- OS: Windows 7 (64 bit)
- Python version: 2.7.9
- Sphinx version: 1.7.3
- Extra tools: Google Chrome 66.0.3359.139, Adobe Acrobat Reader DC 18.009.20044.55097 (the newest one)

[Sample Sphinx.zip](https://github.com/sphinx-doc/sphinx/files/1987764/Sample.Sphinx.zip)

EDIT: I've forgotten to wrote that I am using rst2pdf tool

**Comment by jfbu** [comment] 2018-05-10 16:40
@tk0miya does this go through latex writer at all? (I see you added latex tag). For info, I have no problem with test project after commenting out loading of `rst2pdf.builder` extension and using `make latexpdf` which uses Sphinx LaTeX writer + pdfLaTeX tool chain to get to final pdf. Tested with Acrobat Reader on Mac OS X.

**Comment by tk0miya** [comment] 2018-05-13 15:11
Ah, sorry. I did not check in detail.

@Kamil-D Have you used rst2pdf to convert docs to PDF? If true, this would be a bug of rst2pdf.

**Comment by tk0miya** [comment] 2018-05-13 15:13
Oh, sorry. I added the label without checking tarball in detail.

@Kamil-D Have you built PDF with rst2pdf? If true, this would be a bug of rst2pdf, not Sphinx.
Thanks,

**Comment by Kamil-D** [comment] 2018-05-14 06:12
@tk0miya Yes. I used rst2pdf to built PDF. If there is any possibility to use some similar tool like rst2pdf?

**Comment by tk0miya** [comment] 2018-05-14 13:46
We officially supports our LaTeX builder only. AFAIK, rinohtype can also build PDF document.

**Comment by tk0miya** [comment] 2018-05-19 05:34
I'm closing this now because this is not a bug of Sphinx.
Thanks,

**Closed as completed by tk0miya** 2018-05-19 05:34 UTC
Labels: type:question
