### ISSUE TITLE
http url not working with html_logo

### ISSUE THREAD

**Issue by PhilipMay** [sphinx-doc/sphinx#9444] opened 2021-07-13 08:48 UTC
### Describe the bug

If I provide `html_logo` in the config and pass an http url then it adds a prefix called `__static/` which breaks the link.

### How to Reproduce

-

### Expected behavior

-

### Your project

-

### Screenshots

-

### OS

linux

### Python version

3.8

### Sphinx version

4.1.0

### Sphinx extensions

-

### Extra tools

-

### Additional context

-

**Comment by astrojuanlu** [comment] 2021-07-13 08:59
Is this a duplicate of #9438?

**Comment by PhilipMay** [comment] 2021-07-13 10:09
> Is this a duplicate of #9438?

From the description point of view: no

From code (fixing) point of view: maybe

**Comment by tk0miya** [comment] 2021-07-13 17:37
Fixed by #9440. I'll ship a bugfix release within a day.

**Closed as completed** 2021-07-13 17:37 UTC
Labels: type:bug, builder:html
