### ISSUE TITLE
Warning "cannot cache unpickable configuration value" when config contains a reference to a function

### ISSUE THREAD

**Issue by theOehrly** [sphinx-doc/sphinx#12300] opened 2024-04-17 11:08 UTC
### Describe the bug

When the configuration contains a reference to a function, the warning "cannot cache unpickable configuration value" is show. If warnings are treated as errors, this of course fails the configuration build.

This problem was introduced in v7.3.0. It seems to only occur on a clean build (at least in the case that I observed). This is still problematic because CI workflows commonly do clean builds and then fail.

For the reason why function references are used in the configuration, I'll refer to #11777 where there is a more detailed explanation of the reasons. 
The steps for reproduction are the same as in that issue, albeit with a different outcome/error.

### How to Reproduce

```
pip install sphinx sphinx-gallery
sphinx-quickstart --sep --project test --author me -l en -r 0.0.1
mkdir examples
echo "" > examples/readme.txt
```

Add the following content to the end of the default ``conf.py`` in the ``source`` directory:

```
extensions = [
    'sphinx_gallery.gen_gallery',
]


def example_func():
    return


sphinx_gallery_conf = {
   'reset_modules': (example_func, ),
}
```

Run ``make html`` and notice "WARNING: cannot cache unpickable configuration value: 'sphinx_gallery_conf'" in the output.
This problem only occurs on a clean build (at least in this case), so it is necessary to run ``make clean`` before reproducing the problem again.

### Environment Information

```text
Platform:              win32; (Windows-10-10.0.19044-SP0)
Python version:        3.12.1 (tags/v3.12.1:2305ca5, Dec  7 2023, 22:03:25) [MSC v.1937 64 bit (AMD64)])
Python implementation: CPython
Sphinx version:        7.3.0
Docutils version:      0.21.1
Jinja2 version:        3.1.3
Pygments version:      2.17.2
```

### Sphinx extensions

```python
extensions = [
    'sphinx_gallery.gen_gallery',
]
```

### Additional context

* Sphinx-Gallery tracking issue: https://github.com/sphinx-gallery/sphinx-gallery/issues/1286

**Comment by chrisjsewell** [comment] 2024-04-17 11:16
Heya, this is not a bug, it is intended: https://github.com/sphinx-doc/sphinx/pull/12203

If you are happy to live with not having caching, then you simply add the config: `suppress_warnings = ["config.cache"]`,

(note also the new config to show warning types: https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-show_warning_types

**Comment by chrisjsewell** [comment] 2024-04-17 11:21
With https://github.com/sphinx-doc/sphinx/commit/959f73fe4b795b069319e62afc24599810526e4b, 
potentially you could omit this warning; for config that only rebuilds `html` AND are un-cacheable because they are `FunctionType`.
But that is quite specific obviously

**Comment by chrisjsewell** [comment] 2024-04-17 11:35
I'd note that one of the reasons I added this is that I literally come across the issue when adding this configuration: https://myst-nb.readthedocs.io/en/latest/authoring/custom-formats.html#custom-formats,
originally this was given as a function, but because of the issue of caching, I changed the behaviour to simply have the config be fully qualified name, then load that within the extension

I feel this may be the better route for extensions to go, rather than relying on Sphinx to have complex cache special cases

**Comment by chrisjsewell** [comment] 2024-04-17 14:19
> So a full rebuild is then only triggered if these values are actually accessed?

Not that is not the case:

for configuration variables that are set with `rebuild='env'` (the default), this is the relevant code: https://github.com/sphinx-doc/sphinx/blob/da4c6a783066f0eb711f109461275415f99e3568/sphinx/environment/__init__.py#L326-L330

So for these configuration variables, if they do not get cached, then they will for sure trigger a "full" rebuild, i.e. re-parsing all documents and re-writing all output files (e.g. HTML files)

As per https://github.com/sphinx-doc/sphinx/pull/12203, I certainly feel it is not a good user-experience, to have these re-builds triggered, without any indication that it is because of un-cacheable variables

for configuration variables, that are set with `rebuild='html'`, then this is where https://github.com/sphinx-doc/sphinx/commit/959f73fe4b795b069319e62afc24599810526e4b comes in: https://github.com/sphinx-doc/sphinx/blob/da4c6a783066f0eb711f109461275415f99e3568/sphinx/builders/html/__init__.py#L141-L143

If this hash is not equal, then it will trigger a "write" re-build, i.e. just re-writing all the HTML files

here, then yes there is now some "handling" of these un-cacheable values

I honestly feel that it is not ideal, that there are these two wildly different mechanisms for cache-busting 🤔

> With my current and still somewhat limited overview, I'd argue that this warning should be improved to better guide the user.

Well, this is why I introduced #12131, and in the future would like to make it the default 😄,
because then you could do like rust, ruff, mypy, etc do and have a specific documentation URL to explain each (core) warning type and how you might fix them:
- https://doc.rust-lang.org/stable/error_codes
- https://docs.astral.sh/ruff/rules/
- https://mypy.readthedocs.io/en/stable/error_code_list.html

**Comment by larsoner** [comment] 2024-04-17 17:08
From the description of #12203 :

> it can be a source of confusion when, on performing a sphinx-build on a cached project, an unchanged configuration variable is always marked as changed (which then triggers a full rebuild).

Agreed about this, it can be confusing! However, in sphinx-gallery we ensure that the `__repr__` of our functions are always stable across invocations of `sphinx-build` (by making them the `__call__` of a class with a stable `__repr__`), so the variable is *never* marked as changed, and everything works okay. On first build it builds the whole site, then subsequent calls are no-ops. At least that was the case on previous versions of sphinx for years, not sure if it's still true or not (I need to check!).

If it doesn't cause a rebuild in practice, maybe one improvement would be to make the message more verbose in saying that this inability to cache properly will cause a rebuild only if the object does not have a stable `__repr__`?

And maybe at the SG end we can figure out how to make the objects pass the `is_serializable` check (see also https://github.com/sphinx-gallery/sphinx-gallery/issues/1286).

**Comment by chrisjsewell** [comment] 2024-04-17 17:17
> we ensure that the `__repr__` of our functions are always stable across invocations of sphinx-build

I'd just re-emphasise: this only works (and has only ever worked) with config variables marked as `rebuild="html"` (well technically also `epub`), not the default `rebuild="env"`

This is the case for sphinx-gallery, but obviously not the case for others: https://github.com/sphinx-gallery/sphinx-gallery/blob/e22fc20463055199dee565db3c21c34c9d195c6e/sphinx_gallery/gen_gallery.py#L1550-L1552

**Comment by AA-Turner** [comment] 2024-04-17 20:41
Closing this now:

1. The warning is new and intended to address a common failure mode of the build cache.
2. The warning can be disabled with ``suppress_warnings = ["config.cache"]``
3. Documentation has been added at [``suppress_warnings``](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-suppress_warnings).
4. Extensions that rely on functions within ``setup.py`` should seek to add an alternate configration mechanism that doesn't rely on using such functions or classes.

A

**Closed as completed by AA-Turner** 2024-04-17 20:41 UTC
Labels: awaiting:response

**Comment by chrisjsewell** [comment] 2024-04-18 12:33
Thanks for mentioning about the caching discrepancy with `html` re-builds though @theOehrly

**Comment by jschueller** [comment] 2024-04-22 18:00
I get the same error, but my sphinx_gallery_conf only contains strings, is that the same error ?
```
extensions.append('sphinx_gallery.gen_gallery')
sphinx_gallery_conf = {
     'examples_dirs': ['examples'], # path to example scripts
     'gallery_dirs': ['auto_examples'], # path to where to save gallery gen. output
     'ignore_pattern': '/(torque_model)|(__init__.py)',
}

sphinx.errors.SphinxWarning: cannot cache unpickable configuration value: 'sphinx_gallery_conf' (because it contains a function, class, or module object)
Warning, treated as error:
cannot cache unpickable configuration value: 'sphinx_gallery_conf' (because it contains a function, class, or module object)
```

**Comment by larsoner** [comment] 2024-04-22 18:03
Pretty sure it's the same error because sphinx-gallery fills in entries in the conf when it loads, and some of those entries are classes

**Comment by jschueller** [comment] 2024-04-22 18:07
oh, we must wait #1289 then, got it
