### ISSUE TITLE
Annoying links to original on scaled images

### ISSUE THREAD

**Issue by txomon** [sphinx-doc/sphinx#4229] opened 2017-11-09 19:33 UTC
Subject: It's annoying to have all rescaled images linked to original one always

### Problem
- If you rescale anything, even an icon, sphinx will generate a link to it

#### Procedure to reproduce the problem
Scale an image.

#### Expected results
Can we just add an option to image to avoid the generation of the link?

### Environment info
- OS: Linux
- Python version: 3.6
- Sphinx version: latest
- html builder

I can make a PR, but just want confirmation that it would be accepted. Although maybe it exists already...

**Comment by tk0miya** [comment] 2017-11-11 08:34
How about `html_scaled_image_link`?

**Comment by txomon** [comment] 2017-11-11 09:20
I do want that pictures that are scaled actually have a link to originals,
that's just fine. But there are small ones like icons etc that just don't
make sense =)

**Comment by tk0miya** [comment] 2017-11-11 12:20
Ah, I understand. sorry, `html_scaled_image_link` is not good.
Indeed, such a hyperlink is not needed. Yes, any contribution is always welcome :-)
I think no option is needed. It's reasonable behavior to me.

**Comment by txomon** [comment] 2017-11-11 15:53
When you mean no option, you mean that no additional attribute for
`..image::` is required? If so, what method for not generating the link do
you propose?

**Comment by tk0miya** [comment] 2017-11-12 10:29
AFAIK the thumbnail images are used only if users uses `:scale:`, `:width:` or `:height:` options for images. So it is possible to know the conversion is needed or not. I think a hyperlink is not needed for not converted images even if these options are specified.

**Comment by txomon** [comment] 2017-11-12 13:38
Yes, my question is, how do we deactivate the hyperlink generation when those images are specified?

```
.. image:: something.jpg
   :scale: 50
   :nolink:
```
my proposal was to add an option, and you seemed to say that no option is needed, so I am asking what solution would you propose.

Sorry if I wasn't clear enough =)

**Comment by tk0miya** [comment] 2017-11-15 15:13
Ah, sorry. I'd misunderstood your request.  Okay, you'd like to disable hyperlinks of specific images, right?
I'd like to hear you why do you want to disable specific ones?

I think we have to be careful to add a new option by Sphinx to keep syntax simple. So I'd like to know the reason.

**Comment by txomon** [comment] 2017-11-15 16:18
> I'd like to hear you why do you want to disable specific ones?

It's part of the problem description when I opened the issue. It doesn't make sense to have a link in an icon.

Another alternative I had thought of was to put some null link or something in the link in the existing `:target:` option, but couldn't figure it out. I am really open to suggestions

**Comment by RGSchuster** [comment] 2017-11-15 18:03
I may be too new to Sphinx, but could you add a feature, say `html_icon_image_link` that, when set to false, disables the `post_process_images` function for images below a certain size?

**Comment by txomon** [comment] 2017-11-15 22:08
In my case it's just for specific images. I wouldn't do it also dependant
on below a certain size, but just disabled by image. The use case is just
for certain images, is not something general. I could have another image
set to 50% scale and be an image I want a link for...

**Comment by tony** [comment] 2018-02-21 18:57
I don't think ``html_scaled_image_link`` is sufficient because I want to preserve the link behavior by default. I want to opt-out of the link for scaled images.

So I like the ``:nolink:`` idea.

**Comment by mgeier** [comment] 2018-11-02 15:48
:+1: for the `:nolink:` option (or something similar)!

I've used the `:width:` and `:height:` option for reST content that is auto-generated by a Sphinx extension, where having a link to the full-sized image doesn't make sense (see https://github.com/spatialaudio/nbsphinx/issues/226 and https://github.com/spatialaudio/nbsphinx/pull/222).

However there may be user-generated reST pages in the same Sphinx project where the link indeed does make sense, so using `html_scaled_image_link = False` isn't really an option.

**Comment by jmckenna** [comment] 2020-05-09 13:23
agreed with @txomon, we really need a `:nolink:` option for Sphinx image directives (I keep hitting this issue).

**Comment by tk0miya** [comment] 2020-05-09 13:45
I added a new style option `:class: no-scaled-link` since Sphinx-2.4 (refs: #7032).
I think this issue was already fixed, right?

**Comment by mgeier** [comment] 2020-05-09 14:51
Thanks @tk0miya!
I've used this in https://github.com/spatialaudio/nbsphinx/pull/461 and it works great!

But are you sure about the version number 2.4?
AFAICT #7032 is available since Sphinx 3.0.0b1. Or am I missing something?
See https://github.com/sphinx-doc/sphinx/pull/7062#discussion_r422504497.

**Comment by jmckenna** [comment] 2020-05-09 15:06
oh true @tk0miya confirmed, works great! (with 3.0.3)  Sorry for my misunderstanding.

**Comment by tk0miya** [comment] 2020-05-09 15:19
oh, sorry. It was released as 3.0. I saw wrongly the milestone of #7032.

**Comment by tk0miya** [comment] 2020-05-09 15:20
Closing. Thank you for discussing!

**Closed as completed by tk0miya** 2020-05-09 15:20 UTC
Labels: builder:html, type:proposal
