### ISSUE TITLE
LaTeX replaces " in output

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#973] opened 2015-01-03 01:56 UTC
When I have the following Sphinx input:

```
If ``type == "action"`` ...
```

The LaTeX output looks like this:

```
If type == äction" ...
```

i.e. "a gets turned into ä.

(Not that I have language = 'de' in my conf.py)

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/973
- Originally reported by: Walter Dörwald
- Originally created at: 2012-07-24T16:42:23.195

**Comment by shimizukawa** [comment] 2015-01-03 01:56
_From Georg Brandl on 2012-08-19 10:21:13+00:00_

Hmm, I can't reproduce that here.  Can you check if \shorthandoff{"} is generated in your .tex file?

**Comment by shimizukawa** [comment] 2015-01-03 01:56
_From Walter Dörwald on 2012-08-19 14:07:24+00:00_

No it isn't. What I get in the TeX file is the following:

{{{
#!tex

If \code{type == "action"} 
}}}

The command "shorthandoff" is nowhere in the file.

**Comment by doerwalter** [comment] 2015-07-17 13:05
Further info on this: The problem still exists with Sphinx 1.3.1. However it only happens on the Mac (with MacTeX 2013). On Linux it works as expected.

**Comment by tk0miya** [comment] 2016-01-13 09:07
I can't reproduce this too.
I tested with Sphinx-1.3.4 and MacTeX 2015.

Could you give me example project?

**Comment by tk0miya** [comment] 2016-02-11 05:16
Now I close this issue.
Please feel free to reopen if you get same error.

Thanks,

**Closed as completed by tk0miya** 2016-02-11 05:16 UTC
Labels: type:bug
