### ISSUE TITLE
Recursion error - should tell what is actually failing

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#991] opened 2015-01-03 02:01 UTC
Hi, I keep getting RecursionErrors on generating my docs:
http://pastebin.com/mGL36ssE

Would it be possible to make it tell me what attribute is actually failing instead of just continuing the loop?

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/991
- Originally reported by: Endre Karlson
- Originally created at: 2012-08-13T14:27:39.940

**Comment by shimizukawa** [comment] 2015-01-03 02:01
_From Endre Karlson on 2012-08-14 21:50:10+00:00_

In my rst files I got:

  1 The :mod:`bookie.populate` Module
  2 =================================
  3
  4 .. automodule:: bookie.populate
  5     :members:
  6     :undoc-members:
  7     :show-inheritance:

**Comment by tk0miya** [comment] 2018-02-24 01:57
I can't reproduce the error. So I'm closing this now.
Please file a new issue if you still have this problem.
Thanks,

**Closed as completed by tk0miya** 2018-02-24 01:57 UTC
Labels: type:bug
