### ISSUE TITLE
Unable to use cross-reference for figure/image :target: directive

### ISSUE THREAD

**Issue by Profoktor** [sphinx-doc/sphinx#11788] opened 2023-12-09 23:03 UTC
### Describe the bug

Use Case: I'd like to use an image or a figure as a tile to redirect to a specific page or section in the documentation (e.g. from the startpage of the documentation)

- Define a reference in another rst-file
- use this reference via the :target: directive, s.th. the image links to the reference

This only works, if I use a "local" reference within the same rst-document
It fails as soon as a global reference shall be linked to

This has been observed before, though I did not find an issue in the tracker here
https://stackoverflow.com/questions/32340062/sphinx-restructuredtext-how-to-link-an-image-to-a-document-page
(the workaround listed there obviously breaks for pdf / confluence builds)

### How to Reproduce

```
.. _start:

.. figure:: figure.png
    :name: myFigure
    :width: 95%
    :figwidth: 32%
    :align: center
    :target: `start`_
 
..Reference in another document:

.. figure:: figure.png
    :name: myFigure
    :width: 95%
    :figwidth: 32%
    :align: center
    :target: `anotherreference`_

# build fails, Unknown target name: "anotherreference".

.. figure:: figure.png
    :name: myFigure
    :width: 95%
    :figwidth: 32%
    :align: center
    :target: :ref:`start`

# builds, but creates relative link to :ref:%60start%60, which does not exist
```

### Environment Information

```text
Tested with 7.2.6
```

**Comment by picnixz** [comment] 2023-12-24 13:43
Your `anotherreference` is never defined so it wouldn't work anyway. Now the issue is known but not fixed: https://github.com/sphinx-doc/sphinx/issues/4351.

So I'll close this one as a duplicate.

**Closed as not planned by picnixz** 2023-12-24 13:43 UTC
