### ISSUE TITLE
Warns every other build: `search index couldn't be loaded, but not all documents will be built: the index will be incomplete.` 

### ISSUE THREAD

**Issue by rpatterson** [sphinx-doc/sphinx#11759] opened 2023-11-15 17:19 UTC
### Describe the bug

Every other time Sphinx builds various formats it issues the warning:

```
search index couldn't be loaded, but not all documents will be built: the index will be incomplete.
```

### How to Reproduce

```
$ touch ./docs/index.rst
$ .tox/build/bin/sphinx-build -b html -W ./docs/ ./build/docs/devhelp/
$ touch ./docs/index.rst
$ .tox/build/bin/sphinx-build -b html -W ./docs/ ./build/docs/devhelp/
```

### Environment Information

```text
Platform:              linux; (Linux-6.5.6-76060506-generic-x86_64-with-glibc2.35)
Python version:        3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0])
Python implementation: CPython
Sphinx version:        7.2.6
Docutils version:      0.20.1
Jinja2 version:        3.1.2
Pygments version:      2.16.1
```

### Sphinx extensions

```python
extensions = []
```

### Additional context

The warning cannot be reproduced when using the `-a` or `-E` CLI options or both.  It also cannot be reproduced without `$ touch ./docs/index.rst`.

**Comment by rpatterson** [comment] 2023-11-18 17:52
I was just able to reproduce this with the `html`, `latex` and `texinfo` builders, so I don't think this issue is specific to any particular builder.

**Comment by picnixz** [comment] 2023-12-24 14:28
Err, I don't know what happened but I cannot reproduce it. 

I don't know what you have in `docs/` but with an empty `docs/conf.py` and an empty `docs/index.rst`, I have no issue.

**Comment by rpatterson** [comment] 2023-12-24 14:50
> I don't know what you have in `docs/` but with an empty `docs/conf.py` and an empty `docs/index.rst`, I have no issue.

I'm pretty sure I went back to a vanilla `./docs/` directory as generated by `$ sphinx-quickstart`  but I wouldn't be surprised if there wasn't some other factor I haven't identified.  I don't have time to get back into this right now, so feel free to close as `can't repro`, and I (or someone else) can re-open if that factor can be isolated in the future.

**Comment by picnixz** [comment] 2023-12-24 15:03
I'll close it as 'cannot reproduce' for now, but feel free to reopen if you can give me a MWE. I tried with the autogenerated content by sphinx-quickstart but nothing failed. Maybe you had some cache issues.

**Closed as not planned by picnixz** 2023-12-24 15:03 UTC
