### ISSUE TITLE
2.0.0b1: Warning builder.script_files is deprecated. Please use app.add_js_file() instead

### ISSUE THREAD

**Issue by terrisgit** [sphinx-doc/sphinx#6088] opened 2019-02-18 20:47 UTC
When building HTML documentation using Python 3.6, I get the warning :

```.venv/lib/python3.7/site-packages/sphinx/builders/html.py:137: RemovedInSphinx30Warning: builder.script_files is deprecated. Please use app.add_js_file() instead.```

Sphinx                        2.0.0b1   
sphinx-rtd-theme              0.4.3     
sphinxcontrib-applehelp       1.0.1     
sphinxcontrib-devhelp         1.0.1     
sphinxcontrib-htmlhelp        1.0.1     
sphinxcontrib-jsmath          1.0.1     
sphinxcontrib-qthelp          1.0.1     
sphinxcontrib-serializinghtml 1.1.1     
sphinxcontrib-websupport      1.1.0

**Comment by tk0miya** [comment] 2019-02-22 01:42
This is not a bug. Since 1.6, appending `script_files` were deprecated. I guess your theme appends 
 a script via `script_files` like following:
```
{% set script_files = script_files + ['/path/to/script.js'] %}
```

There are two ways as an alternative.

1. Insert a `<script>` tag directly in `scripts` block in your theme.
   ```
   {% block scripts %}
      <script type="text/script" src="/path/to/script.js"></script>
   {% endblock %}
   ```

2. Use `app.add_js_file()` API on your `conf.py`.
    ```
    def setup(app):
        app.add_js_file('script.js')
    ```
   Note: script.js should be placed under `html_static_path`.

Both are okay.

**Comment by terrisgit** [comment] 2019-02-22 02:55
This is not in my code. Where would it be coming from? This is a new warning that only appears in 2.0 beta. Is this a problem with the rtd theme? I grepped my source dir and .venv and can’t find any usage of script_files

**Comment by tk0miya** [comment] 2019-02-22 03:56
Are you using sphinx-rtd-theme, right? If so, it should be fixed on the theme. Could you file a issue to thier project?
It seems they have still used deprecated API.
https://github.com/rtfd/sphinx_rtd_theme/blob/ecbc09f22a076b6ca985f6c5cab0967976dad12a/sphinx_rtd_theme/search.html#L12

**Comment by tk0miya** [comment] 2019-02-24 08:23
I just updated the warning message because of not understandable (see #6093).
I'm closing this now.

Thanks,

**Closed as completed by tk0miya** 2019-02-24 08:23 UTC
Labels: type:question

**Comment by Blendify** [comment] 2019-02-25 15:51
Hi I saw this from the mailing list, I opened a PR for our theme and waiting for an approval. See above for a link to the PR.
