### ISSUE TITLE
Support turning on very truncated error messages

### ISSUE THREAD

**Issue by BarrySmith** [sphinx-doc/sphinx#11491] opened 2023-07-18 19:38 UTC
**Is your feature request related to a problem? Please describe.**

Sphinx can produce long error messages that, for most users, serve no useful purpose and must be waded through to get to the real issue. For example for our package it can generate

```
ERROR Uses Input Parameter but has multiple input parameters in SNESVIGetActiveSetIS() src/snes/impls/vi/vi.c
ERROR Uses Input Parameter but has multiple input parameters in SNESVIGetActiveSetIS() src/snes/impls/vi/vi.c
make[2]: *** [makefile:459: allmanpages] Error 1
make[1]: *** [GNUmakefile:17: allmanpages] Error 2
make[1]: Leaving directory '/scratch/svcpetsc/glci-builds/fcN4nxDN/0/petsc/petsc'
Traceback (most recent call last):
  File "/scratch/svcpetsc/glci-builds/fcN4nxDN/0/petsc/petsc/venv-petsc-docs/lib/python3.11/site-packages/sphinx/events.py", line 94, in emit
    results.append(listener.handler(self.app, *args))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/svcpetsc/glci-builds/fcN4nxDN/0/petsc/petsc/doc/conf.py", line 185, in builder_init_handler
    _build_classic_docs(app, 'pre')
  File "/scratch/svcpetsc/glci-builds/fcN4nxDN/0/petsc/petsc/doc/conf.py", line 218, in _build_classic_docs
    build_classic_docs.main(stage,app.outdir)
  File "/scratch/svcpetsc/glci-builds/fcN4nxDN/0/petsc/petsc/doc/build_classic_docs.py", line 67, in main
    subprocess.run(command, cwd=petsc_dir, check=True)
  File "/nfs/gce/projects/petsc/soft/u20.04/spack-2023-04-12/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/python-3.11.2-6p2ktljbg76lvecm6w6gywnfldgtvbrl/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['make', 'allmanpages', 'PETSC_DIR=/scratch/svcpetsc/glci-builds/fcN4nxDN/0/petsc/petsc', 'PETSC_ARCH=arch-classic-docs', 'HTMLMAP=/scratch/svcpetsc/glci-builds/fcN4nxDN/0/petsc/petsc/doc/manualpages/htmlmap', 'LOC=/scratch/svcpetsc/glci-builds/fcN4nxDN/0/petsc/petsc/doc']' returned non-zero exit status 2.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/scratch/svcpetsc/glci-builds/fcN4nxDN/0/petsc/petsc/venv-petsc-docs/lib/python3.11/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/svcpetsc/glci-builds/fcN4nxDN/0/petsc/petsc/venv-petsc-docs/lib/python3.11/site-packages/sphinx/application.py", line 262, in __init__
    self._init_builder()
  File "/scratch/svcpetsc/glci-builds/fcN4nxDN/0/petsc/petsc/venv-petsc-docs/lib/python3.11/site-packages/sphinx/application.py", line 335, in _init_builder
    self.events.emit('builder-inited')
  File "/scratch/svcpetsc/glci-builds/fcN4nxDN/0/petsc/petsc/venv-petsc-docs/lib/python3.11/site-packages/sphinx/events.py", line 105, in emit
    raise ExtensionError(__("Handler %r for event %r threw an exception") %
sphinx.errors.ExtensionError: Handler <function builder_init_handler at 0x7f15038659e0> for event 'builder-inited' threw an exception (exception: Command '['make', 'allmanpages', 'PETSC_DIR=/scratch/svcpetsc/glci-builds/fcN4nxDN/0/petsc/petsc', 'PETSC_ARCH=arch-classic-docs', 'HTMLMAP=/scratch/svcpetsc/glci-builds/fcN4nxDN/0/petsc/petsc/doc/manualpages/htmlmap', 'LOC=/scratch/svcpetsc/glci-builds/fcN4nxDN/0/petsc/petsc/doc']' returned non-zero exit status 2.)
Extension error:
Handler <function builder_init_handler at 0x7f15038659e0> for event 'builder-inited' threw an exception (exception: Command '['make', 'allmanpages', 'PETSC_DIR=/scratch/svcpetsc/glci-builds/fcN4nxDN/0/petsc/petsc', 'PETSC_ARCH=arch-classic-docs', 'HTMLMAP=/scratch/svcpetsc/glci-builds/fcN4nxDN/0/petsc/petsc/doc/manualpages/htmlmap', 'LOC=/scratch/svcpetsc/glci-builds/fcN4nxDN/0/petsc/petsc/doc']' returned non-zero exit status 2.)
```

**Describe the solution you'd like**
An option one can add to conf.py that causes a grace error output from Sphinx without any of the tracebacks

**Comment by AA-Turner** [comment] 2023-07-19 06:25
Dear Barry,

Please would you supply either a reproducible example of the error, or the desired output instead?

Thanks,
Adam

**Comment by picnixz** [comment] 2023-10-04 10:11
Since the OP hasn't replied for a while, I'll close this issue.

Feel free to reopen by giving a minimal reproducible example (without third-party extensions).

**Closed as not planned by picnixz** 2023-10-04 10:11 UTC
