### ISSUE TITLE
Issue with change to special_members

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#927] opened 2015-01-03 01:14 UTC
In the latest revision of Sphinx (6e960412308f), I get the following error when trying to build my docs:

```
  File "/Users/tom/Library/Python/2.7/lib/python/site-packages/Sphinx-1.2pre_6e960412308fdev_20120513-py2.7.egg/sphinx/ext/autodoc.py", line 580, in filter_members
    membername in self.options.special_members:
TypeError: argument of type 'object' is not iterable
```

This seems related to a change since the last stable release.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/927
- Originally reported by: [astrofrog](https://bitbucket.org/astrofrog)
- Originally created at: 2012-05-13T19:48:23.043

**Comment by shimizukawa** [comment] 2015-01-03 01:14
_From Bob Tanner on 2012-05-25 20:33:05+00:00_

Just adding a backtrace with more details.

{{{
autodoc_default_flags = [
    'members', 
    'undoc-members', 
    'private-members', 

# 'special-members',

```
'inherited-members',
'show-inheritance']
```

}}}

Comment out special-members and things work.

**Comment by tk0miya** [comment] 2019-05-30 11:01
I'm closing this because this is not reproducible.
Feel free to reopen if you're still in problem.

Thanks,

**Closed as completed by tk0miya** 2019-05-30 11:01 UTC
Labels: type:bug, closed:wontfix, extensions:autodoc
