### ISSUE TITLE
Bug ? Placement of toctree code which file? HTML files will not interlink. 

### ISSUE THREAD

**Issue by AnthonyTheKoala** [sphinx-doc/sphinx#8325] opened 2020-10-21 10:24 UTC
### Not being able to navigate around compiled html files, toctree issue - which file to put the toctree code

How to get the *.html files linked to each other - yes I know it's a toctree issue, but where to put the toctree information in order to get to navigate the index and run the offline search function please. I don't know if this is a bug. If it is not a bug, the other forum dealing with Sphinx frustrated me in not being able to submit my comprehensive detailed question.

### Steps to replicate the problem
Background information:
I have had no problem in using Sphinx but for this case. It's never been a problem until now.'
I like to have the "read the docs" documentation on my computer without resorting to going online. 
Normally, I download a python package's *.zip file. I copy the 'docs' folder to a folder in the c:\thing folder.

The structure tree of this particular "docs" folder is located in c:\thing
The tree is:
<pre>
C:\THING
|   thing.txt (this tree from command tree /a /f c:\thing)
|   
\---docs
    |   autodoc.py
    |   mkdocs.yml
    |   
    \---templates
        |   contributions.md
        |   doc_index.md
        |   examples.md
        |   getting_started.md
        |   index.md
        |   installation.md
        |   license.md
        |   tutorials.md
        |   
        +---css
        |       extra.css
        |       
        +---img
        |       graph.png
        |       layer_visualization.png
        |       loss_acc.png
        |       
        \---tutorials
                quickstart.md
</pre>

### Steps to replicate the problem:
(1) in the 'docs' subfolder, run sphinx-quickstart:
<pre>
C:\thing\docs>sphinx-quickstart
Welcome to the Sphinx 3.2.1 quickstart utility.

Please enter values for the following settings (just press Enter to
accept a default value, if one is given in brackets).

Selected root path: .

You have two options for placing the build directory for Sphinx output.
Either, you use a directory "_build" within the root path, or you separate
"source" and "build" directories within the root path.
> Separate source and build directories (y/n) [n]: y

The project name will occur in several places in the built documentation.
> Project name: tflearn
> Author name(s): various
> Project release []: 1

If the documents are to be written in a language other than English,
you can select a language here by its language code. Sphinx will then
translate text that it generates into that language.

For a list of supported codes, see
https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-language.
> Project language [en]: en

Creating file C:\thing\docs\source\conf.py.
Creating file C:\thing\docs\source\index.rst.
Creating file C:\thing\docs\Makefile.
Creating file C:\thing\docs\make.bat.

Finished: An initial directory structure has been created.

You should now populate your master file C:\thing\docs\source\index.rst and crea
te other documentation
source files. Use the Makefile to build the docs, like so:
   make builder
where "builder" is one of the supported builders, e.g. html, latex or linkcheck.
</pre>

(2) in the c:\thing\docs folder, modify the make.bat file from
<pre>
set SOURCEDIR=source
set BUILDDIR=build
</pre>
To 
<pre>
set SOURCEDIR=c:\thing\docs\templates set BUILDDIR=c:\thing
set BUILDDIR=c:\thing
</pre>

(3) copy contents of C:\thing\docs\source to C:\thing\docs\templates

(4) Modify the conf.py file in templates folder
project = 'tflearn'
copyright = '2020, various'
author = 'various'
release = '1'
source_suffix = ['.rst', '.md']
source_parsers = {'.md': 'recommonmark.parser.CommonMarkParser',} 
import sphinx_rtd_theme
extensions = ["sphinx_rtd_theme",]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# -- Options for HTML output -------------------------------------------------

html_theme = "sphinx_rtd_theme"
html_static_path = ['_static']
</pre>

(4) in the c:\things\docs  
<pre>
make html
</pre>
Compiles well but 124 warnings including toctree warnings.

Typically the compilation output is:
<pre>
#All the *.md files had the following - here is a sample of warnings
c:\thing\docs\templates\doc_index.md:12: WARNING: Unexpected indentation.
c:\thing\docs\templates\doc_index.md:14: WARNING: Block quote ends without a blank line; unexpected unindent.
c:\thing\docs\templates\getting_started.md:20: WARNING: Inline interpreted textor phrase reference start-string without end-string.

#IMPORTANTLY There is a toctree issue
checking consistency... c:\thing\docs\templates\contributions.md: WARNING: document isn't included in any toctree
c:\thing\docs\templates\doc_index.md: WARNING: document isn't included in any toctree
c:\thing\docs\templates\examples.md: WARNING: document isn't included in any toctree
c:\thing\docs\templates\getting_started.md: WARNING: document isn't included in any toctree
c:\thing\docs\templates\installation.md: WARNING: document isn't included in any toctree
c:\thing\docs\templates\license.md: WARNING: document isn't included in any toctree

#End of compiling
preparing documents... done
writing output... [100%] tutorials/quickstart
generating indices...  genindexdone
writing additional pages...  searchdone
copying static files... ... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 124 warnings.
</pre>

Appearance is nice, BUT cannot navigate to other *.html files

![image](https://user-images.githubusercontent.com/26536316/96704837-410e7280-13e0-11eb-9126-b0c58357c05c.png)

### In sum:
* Cannot navigate to other HTML pages when compiling 
* The searching function of the compiled HTML pages  do not work.
* Although there is a mention of toctree on the Sphinx page, I could not find any info about where to put the toctree code.

So when you put the location of index.html you get a nice picture, BUT navigation and content is non-existent and other *.html files don't seem to be linked.

Other information:
OS: Win 7
Python: v3.8.6 64-bit
Sphinx:: v3.2.1

Please help,
Anthony of Sydney

**Comment by cblegare** [comment] 2020-11-12 03:31
You need to include files in a toctree in `index.rst`.  See https://www.sphinx-doc.org/en/master/usage/quickstart.html for tips.

Also, for using Markdown, you might want to have a look at the [Myst](https://myst-parser.readthedocs.io/en/latest/) parser instead of recommonmark.

**Comment by AnthonyTheKoala** [comment] 2020-11-12 04:41
Dear sir, 
Thank you for your kind response, merci pour votre aimable réponse (en utilisant google translate).
I will be experimenting with the 'quickstart' and the Myst parser.
I will be posting a response.
Merci,
Anthony (Antoine) de Sydney Australie

**Comment by tk0miya** [comment] 2020-12-25 15:54
Now I'm closing this because this is not a bug of Sphinx.
Thanks,

**Closed as completed by tk0miya** 2020-12-25 15:54 UTC
Labels: type:question
