### ISSUE TITLE
Translated strings do not get replaced in files

### ISSUE THREAD

**Issue by Swader** [sphinx-doc/sphinx#1993] opened 2015-08-11 16:31 UTC
[This](http://tldrify.com/ara) is as far as I can get with the internationalization instructions. It seems my mo/po files aren't taken into account during this final build.

In `index.rst` I tried both: `Contents:` and `_('Contents:')`, and they show up as such in the final generated HTML even though their values are set in the po file. I always regenerate the mo files with `sphinx-intl build --locale-dir=source/locale` and always rebuild HTML with `make -e SPHINXOPTS="-D language='hr'" html` after every change, but I can't get the strings to replace the placeholders. 

I have generated all the language files up to that point successfully for the `hr` locale, so that's alright, it's just as if it totally ignores my `mo` files.

What am I doing wrong?

It might be worth noting that the title of the page (the `titlesuffix` part) IS translated (automatically), so it _does_ take the language setting into consideration, it just doesn't use the language files.

**Comment by NoralK** [comment] 2015-08-11 16:48
I do not know if this will help but the graphic shows `-Dlanguage=` and you have `-D language=`.

**Comment by Swader** [comment] 2015-08-11 16:53
No, that has no effect, thanks though.

**Comment by Swader** [comment] 2015-08-11 18:04
Having further experimented, I've noticed that things DO work when using the very default setup - namely, not separating the source and build folders. I wonder if there's a way to get around that.

**Comment by shimizukawa** [comment] 2015-12-21 00:41
I can't reproduce the issue whether source and build directories were separated or not.
My project source is here:
https://dl.dropboxusercontent.com/u/284189/sphinx-issues/issue1993-20151221.tgz

Now I close this ticket. Please feel free to reopen if you still have trouble. And/Or document is hard to understand, please let me know. Thanks.

**Closed as completed by shimizukawa** 2015-12-21 00:41 UTC
Labels: internals:internationalisation
