### ISSUE TITLE
Sphinx doesn't support python 3.10

### ISSUE THREAD

**Issue by Itotutona** [sphinx-doc/sphinx#9562] opened 2021-08-19 01:21 UTC
# Problem
Recently, I updated Python 3.9.6 to Python 3.10 RC. No problems. When I want to compile my Sphinx documentation (make html), I see: 

`$ make build`
sphinx-build -b html -d _build/doctrees   . _build/html
Traceback (most recent call last):
  File "/home/titouan/.local/bin/sphinx-build", line 5, in <module>
    from sphinx.cmd.build import main
  File "/home/titouan/.local/lib/python3.10/site-packages/sphinx/cmd/build.py", line 25, in <module>
    from sphinx.application import Sphinx
  File "/home/titouan/.local/lib/python3.10/site-packages/sphinx/application.py", line 32, in <module>
    from sphinx.config import Config
  File "/home/titouan/.local/lib/python3.10/site-packages/sphinx/config.py", line 21, in <module>
    from sphinx.util import logging
  File "/home/titouan/.local/lib/python3.10/site-packages/sphinx/util/__init__.py", line 41, in <module>
    from sphinx.util.typing import PathMatcher
  File "/home/titouan/.local/lib/python3.10/site-packages/sphinx/util/typing.py", line 37, in <module>
    from types import Union as types_Union
ImportError: cannot import name 'Union' from 'types' (/usr/lib64/python3.10/types.py)
make: *** [Makefile:53 : html] Erreur 1

> Union is no longer in types 

I suggest you update the sphinx code to be usable with oython 3.10 as it will be released very soon 
If you want some help, I can contribute to sphinx.

# Solution

I suggest you update the sphinx code to be usable with python 3.10 as it will be released very soon ( 4 october )
If you want some help, I can contribute to sphinx.

**Additional context**

- [What's new Python 3.10](https://docs.python.org/fr/3.10/whatsnew/3.10.html)
- [Python 3.10 on python.org](https://www.python.org/downloads/release/python-3100b3/)
- [Release notes](https://www.python.org/dev/peps/pep-0619/)

**Comment by astrojuanlu** [comment] 2021-08-19 09:37
Hi @Itotutona , you forgot to say what version of Sphinx are you using. I see that this error should be fixed at least on `master`:

https://github.com/sphinx-doc/sphinx/blob/8fd4373d3aec07b8d9a4fb159b6236f4dc715b21/sphinx/util/typing.py#L36-L39

**Comment by Itotutona** [comment] 2021-08-19 17:56
@astrojuanlu  I use 4.1.2

**Comment by jaraco** [comment] 2021-08-29 14:54
I just attempted to build docs using Sphinx and Python 3.10 and the issue still exists. I can work around it by building docs on Python 3.9. If the issue is fixed on master, maybe consider cutting a release with the fix so that others like me don't have to encounter the issue.

**Comment by psss** [comment] 2021-09-01 14:02
Confirm the problem is still present when testing with the latest Fedora (35 and Rawhide).

**Comment by astrojuanlu** [comment] 2021-09-01 15:29
From my understanding, the problem is present in Sphinx 4.1.2:

https://github.com/sphinx-doc/sphinx/blob/4ba5c21b0182557157710a457bed470d335f7571/sphinx/util/typing.py#L36-L39

but it was fixed on the `master` and `4.1.x` branches:

https://github.com/sphinx-doc/sphinx/blob/a1bb4a81ced6f39504cd409e5d7305d35ed0ddb1/sphinx/util/typing.py#L36-L39

Can folks try to reproduce the problem with the development version?

**Comment by astrojuanlu** [comment] 2021-09-01 15:30
In principle, this issue is a duplicate of #9512, which was fixed in #9513.

**Comment by jaraco** [comment] 2021-09-04 14:40
> I just attempted to build docs using Sphinx and Python 3.10 and the issue still exists. I can work around it by building docs on Python 3.9. If the issue is fixed on master, maybe consider cutting a release with the fix so that others like me don't have to encounter the issue.

This issue cause a failed release of Setuptools requiring a workaround to be committed to the repo and adding debt to remove that workaround later. Please consider cutting a release so that there is a working published version of Sphinx for Python 3.10.

**Comment by tk0miya** [comment] 2021-09-05 09:39
4.2.0 will be released

**Comment by tk0miya** [comment] 2021-09-05 09:40
4.2.0 will be released the next weekend. Please wait a moment more.

**Closed as completed** 2021-09-05 09:39 UTC
Labels: type:enhancement
