### ISSUE TITLE
autodoc_member_order doesn't work when using six 

### ISSUE THREAD

**Issue by dokato** [sphinx-doc/sphinx#2042] opened 2015-09-15 16:27 UTC
Hi, today I was fighting with `autodoc_member_order = 'bysource'` which wasn't working only in one file. After few tries I realized that the problem had started to occur after migration to python3. I used `python-modernize` which changed my abstract class definition to:

```
class MyClass(six.with_metaclass(ABCMeta, object)):
   pass
```

and that line switches off autodoc_member_order, but I don't know why.
I'm using sphinx 1.3, python 2.7.2 and my repo is [here](https://github.com/dokato/connectivipy/).

Is that a bug?

**Comment by roqnosis** [comment] 2016-03-29 18:14
Not a sphinx/autodoc expert, but I spent a few hours today tracking down what I imagine is fundamentally an expression of the same issue.  Or at least the same symptom and a similar cause. 

python 2.7.6 and sphinx 1.3.6

I have a script that is using `from __future__ import print_function`

and later in the file I have a line like `print("foo", file=stderr)`

This causes the python language parser to fail, but it fails pretty late and I could detect no missing data on the page, but it was in alphabetical rather than source order.  The failure is silent unless you run the builder with -vvv and look at the debug information spitting out on your screen.  Then you'll see a parser failure if you're having the same problem as me. 

The sort failure is caused by the `Documenter.generate()` function setting analyzer to None when the parser fails.  The code needs the analyzer to find code order and it is no longer available.  I don't know what the impact of not setting the analyzer to None and in my case I was able to work around by not using `__future__`.  

Hopefully that helps someone who actually knows sphinx architecture.  

I gave up before trying to figure out the python parser, but if you're using python2.7 and your code is in python3, that might be part of the issue.

**Comment by tk0miya** [comment] 2020-04-26 15:19
Sorry for the long silence. Yes, to use "bysource" sort, Sphinx needs to parse the code via ModuleAnalyzer. I guess it was failed for some reason. I don't know why it failed.

Anyway, now python2 becomes EOL in this year. So I'm closing this now. Sorry for not helping you.
Thanks,

**Closed as completed by tk0miya** 2020-04-26 15:19 UTC
Labels: type:bug, closed:wontfix, extensions:autodoc
