### ISSUE TITLE
AttributeError: 'BuildEnvironment' object has no attribute 'note_versionchange'

### ISSUE THREAD

**Issue by AraHaan** [sphinx-doc/sphinx#8353] opened 2020-10-31 23:27 UTC
**Describe the bug**
When trying to build python 3.4.10 docs. This happens ``AttributeError: 'BuildEnvironment' object has no attribute 'note_versionchange'`` with latest stable build of sphinx on system installed python 3.9 on windows 10.

**To Reproduce**
1. Download the sources from the https://github.com/python/cpython under the last tag on the 3.4 branch (3.4.10 but it adds a ``+`` to the end of patchlevel.h on the python sources)
2. Have and install python 3.9 on Windows 10, and also install sphinx.
3. Replace the following in ``Doc\tools\extensions\pyspecific.py`` ``add_description_unit`` -> ``add_object_type``
4. How it will complain about the missing method and it will also complain about some embedded code on the rst files.

**Expected behavior**
For the stuff to build cleanly.

**Your project**
Not my project, it's obtained from the cpython github repository that I linked above.

**Screenshots**
N/A

**Environment info**
- OS: [e.g. Win]
- Python version: 3.9.0
- Sphinx version: the latest stable from pip
- Sphinx extensions:  sphinx-htmlhelp, etc.
- Extra tools: I did not install any other tools other than the ones from ``pip install -U sphinx``.

**Additional context**
Not sure why this stuff just fails to work.

**Comment by tk0miya** [comment] 2020-11-01 13:37
`env.note_versionchanged()` was deprecated since v1.8.0 and removed at v3.0.0. I think you should use old version of Sphinx to build old python-doc.

**Comment by AraHaan** [comment] 2020-11-02 12:33
So what was the replacement for it?

**Comment by tk0miya** [comment] 2020-11-02 13:43
I hope https://www.sphinx-doc.org/en/master/extdev/deprecated.html will help you.

The successor of the API is ChangesDomain.note_changeset(). So you do it with this:
```
changeset = env.get_domain('changeset')
changeset.note_changeset(node)
```

**Comment by tk0miya** [comment] 2020-11-12 18:05
I'm closing this now because this is not a bug.
Thanks,

**Closed as completed by tk0miya** 2020-11-12 18:05 UTC
Labels: type:question, api
