### ISSUE TITLE
Intersphinx undefined label while objects.inv lists it

### ISSUE THREAD

**Issue by ixje** [sphinx-doc/sphinx#6659] opened 2019-08-19 13:42 UTC
**Describe the bug**
Following the 1st example from http://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html the code
```
:ref:`comparison manual <python:comparisons>`
```
creates a valid link. All good so far.

However, when I change the link to 
```
:ref:`comparison manual <python:ipaddress>`
```
I get 
```
WARNING: undefined label: python:ipaddress (if the link has no caption the label must precede a section header)
```

Searching in the `objects.inv` files according to the instructions in the link shows it should be a valid label
```
python -msphinx.ext.intersphinx https://docs.python.org/3/objects.inv | grep ipaddress
        ...
	ipaddress                                library/ipaddress.html#module-ipaddress
	howto/ipaddress                          An introduction to the ipaddress module : howto/ipaddress.html
	library/ipaddress                        ipaddress — IPv4/IPv6 manipulation library: library/ipaddress.html
```

**To Reproduce**
1. Follows the 1st example from http://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html 
2. create the link `:ref:`comparison manual <python:ipaddress>`
3. generate docs e.g. `sphinx-build -b html docs/source/ docs/build/`

alternatively download the sample project attached and run `make html`

**Expected behavior**
I expect a valid link to be created to `https://docs.python.org/3/library/ipaddress.html#module-ipaddress`

**Your project**
[broken-intersphinx.zip](https://github.com/sphinx-doc/sphinx/files/3516156/broken-intersphinx.zip)

**Screenshots**
n/a

**Environment info**
- OS: OSX 10.14.6
- Python version: 3.7.0
- Sphinx version: 2.2.0
- Sphinx extensions:  intersphinx
- Extra tools: n/a

**Additional context**
n/a

**Comment by tk0miya** [comment] 2019-08-20 12:50
The `ipaddress` on python document is not a label. It's a python module. So you should use ```:py:mod:`comparison manual <python:ipaddress>` ``` instead of `:ref:` role.

**Comment by ixje** [comment] 2019-08-20 16:33
Your suggestion works, thank you for that. 

Before I close the issue I hope you can elaborate why `:ref:` is incorrect? 

I found a page related to `:ref:` saying:
> ...is compulsory if the link is to be found in an external RST file

Given that the python3 documentation is external + the intersphinx example uses `:ref:` I assumed I had to use `:ref:`. I also thought that anything in the left column of `python -msphinx.ext.intersphinx objects.inv` output were labels, but apparently they're not?

Thank you in advance.

**Comment by ixje** [comment] 2019-09-10 14:14
@tk0miya 

I'm asking the above because I googled a lot before posting here and there seem to be a fair amount of confusion on how it works (by looking at the stackoverflow questions on the topic). I believe by answering the above we could have a nice comment with an explanation that can be referred to. 

Thanks again.

**Comment by webknjaz** [comment] 2020-09-01 21:45
@ixje it looks like the left column is the role that you can use except when it's `:std:label:`, you should use `:std:ref:`, I guess.

**Comment by tk0miya** [comment] 2020-09-05 07:16
oh sorry. I missed your additional question until now.

In Sphinx, python objects (module, class, function and so on) are not labels. Other objects for C, C++, JS and so are also. And `:ref:` role is used to refer to labels. As @webknjaz said, entries inside `std:label` are only referenceable by `:ref:` role.

**Comment by webknjaz** [comment] 2020-09-05 07:20
@tk0miya and that is confusing. I had to special-case labels in my intersphinx preview generator: https://webknjaz.github.io/intersphinx-untangled/

**Comment by tk0miya** [comment] 2020-09-05 07:32
Oh. I need to mention the left column is not a role for the entries. It's a data type of the entries inside the inventory file.

**Comment by ixje** [comment] 2020-09-05 07:41
> @tk0miya and that is confusing. I had to special-case labels in my intersphinx preview generator: https://webknjaz.github.io/intersphinx-untangled/

@webknjaz great page you got there! definitely bookmarking it

**Comment by webknjaz** [comment] 2020-09-05 10:12
> Oh. I need to mention the left column is not a role for the entries. It's a data type of the entries inside the inventory file.

Yep. I've figured that already. But what's stopping us from having the same name for both role and data type? I mean, all the other entries are linkable using the same name. It's the only special case I've noticed. Wouldn't it be easier not to have special cases?

**Comment by tk0miya** [comment] 2020-09-05 11:09
>But what's stopping us from having the same name for both role and data type?

I don't know. AFAIK, nobody requests that.

Note: TBH, I can't determine if somebody sends a request. Please ask to the original author...

**Comment by ixje** [comment] 2020-09-05 14:26
> Note: TBH, I can't determine if somebody sends a request. Please ask to the original author...

I don't see why my involvement as original author is needed to accept a solution provided by somebody else. I just posted this question because it is/was a very common problem on SO without (apparently) a good solution (as I still ended up here). @webknjaz seems to have a good understanding of the root cause and has a proposed solution for it. fwiw; no special cases sounds good to me.

**Comment by webknjaz** [comment] 2020-09-05 14:34
Agreed. My proposal is to get rid of special cases. Or at least have `ref` alias of `label` for backward compat (I guess that would involve declaring a role called `label` doing exactly the same as `ref`). In fact, that self-updating static website I've mentioned earlier (https://github.com/webknjaz/intersphinx-untangled) was a preparation for a slightly different proposal related to this that I haven't had time to properly file on this tracker yet :)

**Comment by webknjaz** [comment] 2020-09-05 14:41
If somebody were to look into it in order to craft a PR, here's some clues:

- https://github.com/sphinx-doc/sphinx/blob/31f26a0/sphinx/domains/std.py#L560-L561
- https://github.com/sphinx-doc/sphinx/blob/31f26a0/sphinx/domains/std.py#L584
- https://github.com/sphinx-doc/sphinx/blob/31f26a0/sphinx/domains/std.py#L612-L613
- https://github.com/sphinx-doc/sphinx/blob/31f26a0/sphinx/domains/std.py#L790-L791
- https://github.com/sphinx-doc/sphinx/blob/31f26a0/sphinx/domains/std.py#L827-L828
- https://github.com/sphinx-doc/sphinx/blob/31f26a0/sphinx/domains/std.py#L983

**Comment by tk0miya** [comment] 2020-12-25 15:58
Now I'm closing this because this is not a bug of Sphinx.
Thanks,

**Closed as completed by tk0miya** 2020-12-25 15:58 UTC
Labels: type:question
