### ISSUE TITLE
attribute documentation ignored by sphinx.ext.autodoc

### ISSUE THREAD

**Issue by cjw296** [sphinx-doc/sphinx#3157] opened 2016-11-17 08:11 UTC
The following attribute documentation is being ignored:

https://github.com/cjw296/chide/blob/2.0.1/chide/set.py#L29

...as you can see here:

http://chide.readthedocs.io/en/latest/api.html#chide.Set

Here's the directive that builds the page:

https://raw.githubusercontent.com/cjw296/chide/2.0.1/docs/api.rst

I'm assuming this is a bug, but is there any way I can work around it until it's fixed?

**Comment by tk0miya** [comment] 2016-11-17 15:51
In my short investigate:
With `.. automodule:: chide`, autodoc analyzes the file located `chide/__init__.py`.
But `Set.identify` and its comment are defined at `chide/set.py`.
So autodoc could not find the comment.

As a work around, you can do it with following notation:

```
.. automodule:: chide.set
   :members:
```

I don't know this is a bug or not. But I agree that this behavior is hard to understand.

**Comment by cjw296** [comment] 2016-11-18 11:06
So, the problem is that, conceptually, I want `Set` to be imported from chide, not `chide.set`, so I want the docs to reflect that. However, trying your suggested workaround on another project does not improve things:

https://github.com/Simplistix/mush/blob/master/docs/api.txt#L18

...still doesn't result in the attribute documentation being rendered:

http://mush.readthedocs.io/en/latest/api.html#mush.plug.Plug

**Comment by tk0miya** [comment] 2016-11-20 09:38
What variable did you mean?
If you mean `mush.plug.Plug.ignore`, it seems the variable does not have any comment. So it is correct result, I think.

**Comment by cjw296** [comment] 2016-11-20 18:22
Sorry, I was referring to `Plug.explicit`, which has docs here:

https://github.com/Simplistix/mush/blob/master/mush/plug.py#L58

...but even when I move them to L41, those comment lines are ignored.

**Comment by tk0miya** [comment] 2016-11-22 16:52
Really? At this moment, `Plug.explicit` appeared in RTD.

If you commented on L.58, the comment is not used for a description of `Plug.explicit`. Because  `if self.explit:` is not a definition of `Plug.explicit`.

**Comment by cjw296** [comment] 2016-12-12 07:14
So, interestingly, I've inadvertently left this in a perfect state for Sphinx people to see what's going on:

The API docs I *want* are the ones that come from:
https://github.com/Simplistix/mush/blob/master/docs/api.txt#L4
https://github.com/Simplistix/mush/blob/master/mush/__init__.py#L13

However, those render *without* explicit, as can be seen here:
http://mush.readthedocs.io/en/latest/api.html#mush.Plug

Out of desperation, I also included `Plug` from a location that I *don't* want people to be importing it from:
https://github.com/Simplistix/mush/blob/master/docs/api.txt#L18

Annoyingly, that renders correctly:
http://mush.readthedocs.io/en/latest/api.html#mush.plug.Plug

So, how can I get the former documentation to render correctly so I no longer need to include the latter from an incorrect location?

**Comment by HyukjinKwon** [comment] 2017-11-12 06:32
Hi all, does anyone know if maybe this is resolved by https://github.com/sphinx-doc/sphinx/pull/2299?

**Comment by cjw296** [comment] 2017-11-13 08:36
@HyukjinKwon - unsure, but if you fancy experimenting on Mush, if there's any changes needed, feel free to put in a PR!

**Comment by tk0miya** [comment] 2018-08-26 15:37
I confirmed this issue is already fixed. The `Set.identify` is documented with latest Sphinx.
```
FROM tk0miya/sphinx-html

RUN git clone https://github.com/cjw296/chide
WORKDIR /docs/chide
RUN pip3 install -r requirements.txt sqlalchemy
RUN sphinx-build -b html -d _build/doctrees docs/ _build/html
RUN grep -C5 'You may also want to subclass' _build/html/api.html
```
```
Step 5/6 : RUN sphinx-build -b html -d _build/doctrees docs/ _build/html
 ---> Running in e28e0e4db058
Running Sphinx v1.7.6
(snip)
Step 6/6 : RUN grep -C5 'You may also want to subclass' _build/html/api.html
 ---> Running in 461aa6934361
</dd></dl>

<dl class="attribute">
<dt id="chide.Set.identify">
<code class="descname">identify</code><em class="property"> = None</em><a class="headerlink" href="#chide.Set.identify" title="Permalink to this definition">¶</a></dt>
<dd><p>You may also want to subclass <a class="reference internal" href="#chide.Set" title="chide.Set"><code class="xref py py-class docutils literal notranslate"><span class="pre">Set</span></code></a> and implement
an <a class="reference internal" href="#chide.Set.identify" title="chide.Set.identify"><code class="xref py py-meth docutils literal notranslate"><span class="pre">identify()</span></code></a> method, see <a class="reference internal" href="#chide.sqlalchemy.Set" title="chide.sqlalchemy.Set"><code class="xref py py-class docutils literal notranslate"><span class="pre">chide.sqlalchemy.Set</span></code></a>
for an example.</p>
</dd></dl>

</dd></dl>
 ---> d9865d3c0856
```

So I'm closing this now. Please feel free to reopen if you are still in trouble.
Thanks,

**Closed as completed by tk0miya** 2018-08-26 15:37 UTC
Labels: extensions:autodoc
