### ISSUE TITLE
IndexError: pop from empty list when switching to pydata-sphinx-theme from sphinx_rtd_theme

### ISSUE THREAD

**Issue by ghost** [sphinx-doc/sphinx#11227] opened 2023-03-08 15:41 UTC
### Describe the bug

I have a doc site running fine with sphinx_rtd_theme. I am trying to test out pydata-sphinx-theme but getting following error.

 Platform:         win32; (Windows-10-10.0.19044-SP0)
 Sphinx version:   6.1.3
 Python version:   3.9.9 (CPython)
 Docutils version: 0.19
 Jinja2 version:   3.1.2
 Pygments version: 2.14.0

# Last messages:
   
  looking for now-outdated files...
  none found
  pickling environment...
  done
  checking consistency...
  done
  preparing documents...
  done
  writing output... [  4%] about

# Loaded extensions:
  sphinx.ext.mathjax (6.1.3)
  sphinxcontrib.applehelp (1.0.4)
  sphinxcontrib.devhelp (1.0.2)
  sphinxcontrib.htmlhelp (2.0.1)
  sphinxcontrib.serializinghtml (1.1.5)
  sphinxcontrib.qthelp (1.0.3)
  alabaster (0.7.13)
  nbsphinx (0.8.12)
  sphinx.ext.autodoc.preserve_defaults (6.1.3)
  sphinx.ext.autodoc.type_comment (6.1.3)
  sphinx.ext.autodoc.typehints (6.1.3)
  sphinx.ext.autodoc (6.1.3)
  sphinx.ext.napoleon (6.1.3)
  sphinx.ext.viewcode (6.1.3)
  rst2pdf.pdfbuilder (0.99)
  sphinx_last_updated_by_git (0.3.4)
  myst_parser (1.0.0)
  pydata_sphinx_theme (unknown version)

# Traceback:
Traceback (most recent call last):
  File "C:\Users\AP\source\repos\DAEDoc\venv\lib\site-packages\sphinx\cmd\build.py", line 284, in build_main
    app.build(args.force_all, args.filenames)
  File "C:\Users\AP\source\repos\DAEDoc\venv\lib\site-packages\sphinx\application.py", line 347, in build
    self.builder.build_update()
  File "C:\Users\AP\source\repos\DAEDoc\venv\lib\site-packages\sphinx\builders\__init__.py", line 311, in build_update
    self.build(to_build,
  File "C:\Users\AP\source\repos\DAEDoc\venv\lib\site-packages\sphinx\builders\__init__.py", line 377, in build
    self.write(docnames, list(updated_docnames), method)
  File "C:\Users\AP\source\repos\DAEDoc\venv\lib\site-packages\sphinx\builders\__init__.py", line 579, in write
    self._write_serial(sorted(docnames))
  File "C:\Users\AP\source\repos\DAEDoc\venv\lib\site-packages\sphinx\builders\__init__.py", line 589, in _write_serial
    self.write_doc(docname, doctree)
  File "C:\Users\AP\source\repos\DAEDoc\venv\lib\site-packages\sphinx\builders\html\__init__.py", line 671, in write_doc
    self.docwriter.write(doctree, destination)
  File "C:\Users\AP\source\repos\DAEDoc\venv\lib\site-packages\docutils\writers\__init__.py", line 77, in write
    self.translate()
  File "C:\Users\AP\source\repos\DAEDoc\venv\lib\site-packages\sphinx\writers\html.py", line 37, in translate
    self.document.walkabout(visitor)
  File "C:\Users\AP\source\repos\DAEDoc\venv\lib\site-packages\docutils\nodes.py", line 186, in walkabout
    if child.walkabout(visitor):
  File "C:\Users\AP\source\repos\DAEDoc\venv\lib\site-packages\docutils\nodes.py", line 186, in walkabout
    if child.walkabout(visitor):
  File "C:\Users\AP\source\repos\DAEDoc\venv\lib\site-packages\docutils\nodes.py", line 186, in walkabout
    if child.walkabout(visitor):
  File "C:\Users\AP\source\repos\DAEDoc\venv\lib\site-packages\docutils\nodes.py", line 199, in walkabout
    visitor.dispatch_departure(self)
  File "C:\Users\AP\source\repos\DAEDoc\venv\lib\site-packages\sphinx\util\docutils.py", line 585, in dispatch_departure
    method(node)
  File "C:\Users\AP\source\repos\DAEDoc\venv\lib\site-packages\sphinx\writers\_html4.py", line 800, in depart_table
    super().depart_table(node)
  File "C:\Users\AP\source\repos\DAEDoc\venv\lib\site-packages\docutils\writers\html4css1\__init__.py", line 862, in depart_table
    self.compact_p = self.context.pop()
IndexError: pop from empty list

### How to Reproduce

Just running make html gives this error

**Comment by paradox-lab** [comment] 2023-10-14 02:08
Can you provide a minimal code repository link for reproducible problems?

**Comment by picnixz** [comment] 2023-10-14 08:07
I will close this issue since this is not related to sphinx core development. Some advices:

1. Please upgrade to the latest Sphinx version.
2. If it still doesn't work, please open an issue on pydata-sphinx-theme directly.

**Closed as not planned** 2023-10-14 08:07 UTC
