### ISSUE TITLE
`sphinx.util.cfamily.DefinitionError`: Error in template parameter list

### ISSUE THREAD

**Issue by aprotyas** [sphinx-doc/sphinx#9460] opened 2021-07-16 19:38 UTC
### Describe the bug

Sphinx is having some trouble parsing a template parameter list, which I can confirm is valid C++11 syntax (builds with `g++ -std=c++11`). For reference, I first manually run `doxygen` on the project, and then have the `breath` and `exhale` extensions to `sphinx` extract the Doxygen tags and generate appropriate documentation. More about this later.

The signature in question:
```cpp
template<
  class InsertIterator,
  typename std::enable_if<
    std::is_same<
      InsertIterator &,
      decltype(std::declval<InsertIterator>().operator=(std::declval<std::string>()))>::value
  >::type * = nullptr>
void
split(const std::string & input, char delim, InsertIterator & it, bool skip_empty = false);
```

Here's the full traceback:

<details>
  <summary>Full Traceback</summary>

```  
# Sphinx version: 4.0.2
# Python version: 3.8.10 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 2.10.1
# Last messages:
#   updating environment:
#   [new config]
#   15 added, 0 changed, 0 removed
#   reading sources... [  6%] api/class_view_hierarchy
#   reading sources... [ 13%] api/dir_include
#   reading sources... [ 20%] api/dir_include_rcpputils
#   reading sources... [ 26%] api/file_README.md
#   reading sources... [ 33%] api/file_include_rcpputils_split.hpp
#   reading sources... [ 40%] api/file_view_hierarchy
#   reading sources... [ 46%] api/function_namespacercpputils_1a345c5a517eb613e45f68668b50824a45
# Loaded extensions:
#   sphinx.ext.mathjax (4.0.2) from /home/abrar/.local/lib/python3.8/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /home/abrar/.local/lib/python3.8/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /home/abrar/.local/lib/python3.8/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (2.0.0) from /home/abrar/.local/lib/python3.8/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.5) from /home/abrar/.local/lib/python3.8/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /home/abrar/.local/lib/python3.8/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.8) from /usr/lib/python3/dist-packages/alabaster/__init__.py
#   sphinx_rtd_theme (unknown version) from /home/abrar/.local/lib/python3.8/site-packages/sphinx_rtd_theme/__init__.py
#   breathe (4.30.0) from /home/abrar/.local/lib/python3.8/site-packages/breathe/__init__.py
#   exhale (0.2.3) from /home/abrar/Documents/open_robotics/code/exhale/src/exhale/exhale/__init__.py
#   sphinx.ext.intersphinx (4.0.2) from /home/abrar/.local/lib/python3.8/site-packages/sphinx/ext/intersphinx.py
#   sphinx.ext.viewcode (4.0.2) from /home/abrar/.local/lib/python3.8/site-packages/sphinx/ext/viewcode.py
#   sphinx.ext.autodoc.preserve_defaults (1.0) from /home/abrar/.local/lib/python3.8/site-packages/sphinx/ext/autodoc/preserve_defaults.py
#   sphinx.ext.autodoc.type_comment (4.0.2) from /home/abrar/.local/lib/python3.8/site-packages/sphinx/ext/autodoc/type_comment.py
#   sphinx.ext.autodoc (4.0.2) from /home/abrar/.local/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py
Traceback (most recent call last):
  File "/home/abrar/.local/lib/python3.8/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/home/abrar/.local/lib/python3.8/site-packages/sphinx/application.py", line 350, in build
    self.builder.build_update()
  File "/home/abrar/.local/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 292, in build_update
    self.build(to_build,
  File "/home/abrar/.local/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 306, in build
    updated_docnames = set(self.read())
  File "/home/abrar/.local/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 413, in read
    self._read_serial(docnames)
  File "/home/abrar/.local/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 434, in _read_serial
    self.read_doc(docname)
  File "/home/abrar/.local/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 474, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/home/abrar/.local/lib/python3.8/site-packages/sphinx/io.py", line 188, in read_doc
    pub.publish()
  File "/usr/lib/python3/dist-packages/docutils/core.py", line 217, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "/home/abrar/.local/lib/python3.8/site-packages/sphinx/io.py", line 108, in read
    self.parse()
  File "/usr/lib/python3/dist-packages/docutils/readers/__init__.py", line 77, in parse
    self.parser.parse(self.input, document)
  File "/home/abrar/.local/lib/python3.8/site-packages/sphinx/parsers.py", line 100, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 171, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
  File "/usr/lib/python3/dist-packages/docutils/statemachine.py", line 241, in run
    context, next_state, result = self.check_line(
  File "/usr/lib/python3/dist-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 2770, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 328, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 394, in new_subsection
    newabsoffset = self.nested_parse(
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 197, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python3/dist-packages/docutils/statemachine.py", line 241, in run
    context, next_state, result = self.check_line(
  File "/usr/lib/python3/dist-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 2770, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 328, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 394, in new_subsection
    newabsoffset = self.nested_parse(
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 197, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python3/dist-packages/docutils/statemachine.py", line 241, in run
    context, next_state, result = self.check_line(
  File "/usr/lib/python3/dist-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 2343, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 2355, in explicit_construct
    return method(self, expmatch)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 2097, in directive
    return self.run_directive(
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 2147, in run_directive
    result = directive_instance.run()
  File "/home/abrar/.local/lib/python3.8/site-packages/breathe/directives.py", line 110, in run
    node_stack = self._resolve_function(matches, args, project_info)
  File "/home/abrar/.local/lib/python3.8/site-packages/breathe/directives.py", line 218, in _resolve_function
    signature = self._create_function_signature(entry, project_info, filter_,
  File "/home/abrar/.local/lib/python3.8/site-packages/breathe/directives.py", line 196, in _create_function_signature
    ast = parser.parse_declaration('function', 'function')
  File "/home/abrar/.local/lib/python3.8/site-packages/sphinx/domains/cpp.py", line 6687, in parse_declaration
    templatePrefix = self._parse_template_declaration_prefix(objectType)
  File "/home/abrar/.local/lib/python3.8/site-packages/sphinx/domains/cpp.py", line 6613, in _parse_template_declaration_prefix
    raise e
  File "/home/abrar/.local/lib/python3.8/site-packages/sphinx/domains/cpp.py", line 6608, in _parse_template_declaration_prefix
    params = self._parse_template_parameter_list()
  File "/home/abrar/.local/lib/python3.8/site-packages/sphinx/domains/cpp.py", line 6505, in _parse_template_parameter_list
    raise self._make_multi_error(errs, header)
sphinx.util.cfamily.DefinitionError: Error in template parameter list.

Main error:
  Invalid C++ declaration: Expected "," or ">". [error at 54]
    template<class InsertIterator, typename std::enable_if< std::is_same< InsertIterator &, decltype(std::declval< InsertIterator >().operator=(std::declval< std::string >()))>::value, ::type * = nullptr> void split (const std::string &input, char delim, InsertIterator &it, bool skip_empty=false)
    ------------------------------------------------------^
Potential other error:
  Main error:
    Invalid C++ declaration: Expected identifier in nested name. [error at 54]
      template<class InsertIterator, typename std::enable_if< std::is_same< InsertIterator &, decltype(std::declval< InsertIterator >().operator=(std::declval< std::string >()))>::value, ::type * = nullptr> void split (const std::string &input, char delim, InsertIterator &it, bool skip_empty=false)
      ------------------------------------------------------^
  Potential other error:
    Error in parsing template argument list.
    If type argument:
      Invalid C++ declaration: Expected "...>", ">" or "," in template argument list. [error at 190]
        template<class InsertIterator, typename std::enable_if< std::is_same< InsertIterator &, decltype(std::declval< InsertIterator >().operator=(std::declval< std::string >()))>::value, ::type * = nullptr> void split (const std::string &input, char delim, InsertIterator &it, bool skip_empty=false)
        ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------^
    If non-type argument:
      Invalid C++ declaration: Expected "...>", ">" or "," in template argument list. [error at 188]
        template<class InsertIterator, typename std::enable_if< std::is_same< InsertIterator &, decltype(std::declval< InsertIterator >().operator=(std::declval< std::string >()))>::value, ::type * = nullptr> void split (const std::string &input, char delim, InsertIterator &it, bool skip_empty=false)
        --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------^

```
</details>

### How to Reproduce

```
$ git clone https://github.com/aprotyas/rcpputils.git -b aprotyas/sphinx_template_issue template_issue
$ cd template_issue
$ pip install -r requirements.txt
$ doxygen Doxyfile
$ sphinx-build -b build docs output
```

If `doxygen` is not readily available to the maintainers, I can upload a zip file with the generated Doxygen tags.

### Expected behavior

`sphinx-build` should succeed.

### Your project

https://github.com/aprotyas/rcpputils/tree/aprotyas/sphinx_template_issue

### OS

Ubuntu 20.04

### Python version

3.8.10

### Sphinx version

4.0.2

### Sphinx extensions

sphinx_rtd_theme, breathe, exhale

### Additional context

More versioning information:

```
breathe: 4.30.0
exhale: 0.2.3
```

**Comment by jakobandersen** [comment] 2021-07-17 10:28
Thanks for reporting. I'm quite sure this is a duplicate of #9449 and #9433 though, but otherwise please reopen or post a new issue.
The problem is in Breathe and I think it should be fixed by https://github.com/michaeljones/breathe/pull/711.

**Closed as completed by jakobandersen** 2021-07-17 10:28 UTC
Labels: closed:duplicate, domains:cpp

**Comment by aprotyas** [comment] 2021-07-29 06:06
I can confirm that your patch fixes this issue. Thanks a lot :-)

**Comment by aprotyas** [comment] 2021-08-05 15:56
@jakobandersen I'll discuss here instead of opening a new issue since this might be related. I'm getting similar errors again, but for a different signature and with different `sphinx`/`breathe`/`exhale` version combinations.

```
sphinx: 4.1.2
breathe: 4.3.0
exhale: 0.2.3
```

The error:
```
sphinx.util.cfamily.DefinitionError: Invalid C++ declaration: Expected identifier in nested name, got keyword: template [error at 8]
  template< typename T, class A > class                                                             
  --------^  
```

<details><summary>Full traceback</summary>
<p>

```
# Sphinx version: 4.1.2
# Python version: 3.8.10 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 3.0.1
# Last messages:
#   reading sources... [ 55%] api/function_namespacercpputils_1_1fs_1a92b275ab987cc10f793f5cd03e76380d
#   reading sources... [ 56%] api/function_namespacercpputils_1_1fs_1a9c35781f3734e62e88e49902f53a6dd4
#   reading sources... [ 57%] api/function_namespacercpputils_1_1fs_1abd843c981e15af009557d6016fa2c482
#   reading sources... [ 57%] api/function_namespacercpputils_1_1fs_1acec26e9f29d267a466462cbac1f84337
#   reading sources... [ 58%] api/function_namespacercpputils_1_1fs_1ae192bc4007e41ee74c59f6e540a608e4
#   reading sources... [ 59%] api/function_namespacercpputils_1_1fs_1ae4d0583d5f5da1f09e261a57e688a472
#   reading sources... [ 60%] api/function_namespacercpputils_1_1fs_1af0f06f24ecaf53be0f33e155d5e661b9
#   reading sources... [ 61%] api/function_namespacercpputils_1_1fs_1af4c78edeb35f86d943ca7b5118ac9fbb
#   reading sources... [ 61%] api/function_namespacercpputils_1_1fs_1afa772a97a7982df046f6122a5d34bbab
#   reading sources... [ 62%] api/function_namespacercpputils_1a00ce90ea881ec2c2a5ac74de08c2378c
# Loaded extensions:
#   sphinx.ext.mathjax (4.1.2) from /home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (2.0.0) from /home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.5) from /home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/alabaster/__init__.py
#   sphinx_rtd_theme (unknown version) from /home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/sphinx_rtd_theme/__init__.py
#   sphinx.ext.autodoc.preserve_defaults (1.0) from /home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/sphinx/ext/autodoc/preserve_defaults.py
#   sphinx.ext.autodoc.type_comment (4.1.2) from /home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/sphinx/ext/autodoc/type_comment.py
#   sphinx.ext.autodoc (4.1.2) from /home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.intersphinx (4.1.2) from /home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/sphinx/ext/intersphinx.py
#   breathe (4.30.0) from /home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/breathe/__init__.py
#   exhale (0.2.3) from /home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/exhale/__init__.py
#   myst_parser (0.15.1) from /home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/myst_parser/__init__.py
Traceback (most recent call last):
  File "/home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/sphinx/application.py", line 343, in build
    self.builder.build_update()
  File "/home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 293, in build_update
    self.build(to_build,
  File "/home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 307, in build
    updated_docnames = set(self.read())
  File "/home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 414, in read
    self._read_serial(docnames)
  File "/home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 435, in _read_serial
    self.read_doc(docname)
  File "/home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 475, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/sphinx/io.py", line 188, in read_doc
    pub.publish()
  File "/home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/docutils/core.py", line 217, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "/home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/sphinx/io.py", line 108, in read
    self.parse()
  File "/home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/docutils/readers/__init__.py", line 77, in parse
    self.parser.parse(self.input, document)
  File "/home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/sphinx/parsers.py", line 100, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 170, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
  File "/home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/docutils/statemachine.py", line 241, in run
    context, next_state, result = self.check_line(
  File "/home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2769, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 393, in new_subsection
    newabsoffset = self.nested_parse(
  File "/home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/docutils/statemachine.py", line 241, in run
    context, next_state, result = self.check_line(
  File "/home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2769, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 393, in new_subsection
    newabsoffset = self.nested_parse(
  File "/home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/docutils/statemachine.py", line 241, in run
    context, next_state, result = self.check_line(
  File "/home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2342, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2354, in explicit_construct
    return method(self, expmatch)
  File "/home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2096, in directive
    return self.run_directive(
  File "/home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2146, in run_directive
    result = directive_instance.run()
  File "/home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/breathe/directives.py", line 110, in run
    node_stack = self._resolve_function(matches, args, project_info)
  File "/home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/breathe/directives.py", line 218, in _resolve_function
    signature = self._create_function_signature(entry, project_info, filter_,
  File "/home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/breathe/directives.py", line 188, in _create_function_signature
    object_renderer.create_template_prefix(node),
  File "/home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/breathe/renderer/sphinxrenderer.py", line 780, in create_template_prefix
    nodes = self.render(decl.templateparamlist)
  File "/home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/breathe/renderer/sphinxrenderer.py", line 2279, in render
    result = method(self, node)  # type: ignore
  File "/home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/breathe/renderer/sphinxrenderer.py", line 2089, in visit_templateparamlist
    nodelist.extend(self.visit_param(item, insertDeclNameByParsing=True))
  File "/home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/breathe/renderer/sphinxrenderer.py", line 2051, in visit_param
    ast = parser._parse_type(named='single', outer='templateParam')
  File "/home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/sphinx/domains/cpp.py", line 6415, in _parse_type
    declSpecs = self._parse_decl_specs(outer=outer)
  File "/home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/sphinx/domains/cpp.py", line 6109, in _parse_decl_specs
    trailing = self._parse_trailing_type_spec()
  File "/home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/sphinx/domains/cpp.py", line 5874, in _parse_trailing_type_spec
    nestedName = self._parse_nested_name()
  File "/home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/sphinx/domains/cpp.py", line 5800, in _parse_nested_name
    self.fail("Expected identifier in nested name, "
  File "/home/abrar/Documents/open_robotics/code/ros2_humble/env/lib/python3.8/site-packages/sphinx/util/cfamily.py", line 275, in fail
    raise self._make_multi_error(errors, '')
sphinx.util.cfamily.DefinitionError: Invalid C++ declaration: Expected identifier in nested name, got keyword: template [error at 8]
  template< typename T, class A > class
  --------^
```

</p>
</details>

The signature in question:
```cpp
template<
  typename CharT, typename ValueT, typename AllocatorT,
  template<typename T, class A> class ContainerT>
std::basic_string<CharT>
join(const ContainerT<ValueT, AllocatorT> & container, const CharT * delim);
```

Having said all this, main question: do you think this error is targeted by the fix you've drafted in michaeljones/breathe#711?

**Comment by jakobandersen** [comment] 2021-08-05 17:17
Good example, it indeed triggers the parsing error, but it should work with the proposed PR (it does in my local test).

**Comment by aprotyas** [comment] 2021-08-05 17:24
Thanks for letting me know. Hope that PR gets merged in soon.
