### ISSUE TITLE
Invalid C++ declaration: typename

### ISSUE THREAD

**Issue by IceflowRE** [sphinx-doc/sphinx#9449] opened 2021-07-14 21:22 UTC
### Describe the bug

```
sphinx.util.cfamily.DefinitionError: Invalid C++ declaration: Expected identifier in nested name. [error at 8]
    typename...
    --------^
```

Iam actually not that deep into Sphinx and we use breathe and exhale to produce the documentation. So i just want to report it here, that it worked with 4.0.3 and stopped working with 4.1.0 (4.1.1 also).

### How to Reproduce

https://github.com/inexorgame/vulkan-renderer/runs/3070534572

You can see a log there.

### Your project

https://github.com/inexorgame/vulkan-renderer/tree/master/documentation/source

### OS

Windows/Linux

### Python version

3.9.6

### Sphinx version

4.1.1

### Sphinx extensions

breathe, exhale, recommonmark, sphinxcontrib.mermaid

### Additional context

log
```
# Sphinx version: 4.1.1
# Python version: 3.9.6 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 2.11.3
# Last messages:
#   reading sources... [ 15%] exhale-generated/classinexor_1_1vulkan__renderer_1_1_graphics_stage
#   reading sources... [ 15%] exhale-generated/classinexor_1_1vulkan__renderer_1_1_im_g_u_i_overlay
#   reading sources... [ 16%] exhale-generated/classinexor_1_1vulkan__renderer_1_1_inexor_exception
#   reading sources... [ 16%] exhale-generated/classinexor_1_1vulkan__renderer_1_1_physical_back_buffer
#   reading sources... [ 16%] exhale-generated/classinexor_1_1vulkan__renderer_1_1_physical_buffer
#   reading sources... [ 17%] exhale-generated/classinexor_1_1vulkan__renderer_1_1_physical_graphics_stage
#   reading sources... [ 17%] exhale-generated/classinexor_1_1vulkan__renderer_1_1_physical_image
#   reading sources... [ 17%] exhale-generated/classinexor_1_1vulkan__renderer_1_1_physical_resource
#   reading sources... [ 18%] exhale-generated/classinexor_1_1vulkan__renderer_1_1_physical_stage
#   reading sources... [ 18%] exhale-generated/classinexor_1_1vulkan__renderer_1_1_render_graph
# Loaded extensions:
#   sphinx.ext.mathjax (4.1.1) from c:\python39\lib\site-packages\sphinx\ext\mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from c:\python39\lib\site-packages\sphinxcontrib\applehelp\__init__.py
#   sphinxcontrib.devhelp (1.0.2) from c:\python39\lib\site-packages\sphinxcontrib\devhelp\__init__.py
#   sphinxcontrib.htmlhelp (2.0.0) from c:\python39\lib\site-packages\sphinxcontrib\htmlhelp\__init__.py
#   sphinxcontrib.serializinghtml (1.1.5) from c:\python39\lib\site-packages\sphinxcontrib\serializinghtml\__init__.py
#   sphinxcontrib.qthelp (1.0.3) from c:\python39\lib\site-packages\sphinxcontrib\qthelp\__init__.py
#   alabaster (0.7.12) from c:\python39\lib\site-packages\alabaster\__init__.py
#   breathe (4.30.0) from c:\python39\lib\site-packages\breathe\__init__.py
#   exhale (0.2.3) from c:\python39\lib\site-packages\exhale\__init__.py
#   recommonmark (0.7.1) from c:\python39\lib\site-packages\recommonmark\__init__.py
#   sphinxcontrib.mermaid (4.1.1) from c:\python39\lib\site-packages\sphinxcontrib\mermaid.py
Traceback (most recent call last):
  File "c:\python39\lib\site-packages\sphinx\cmd\build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "c:\python39\lib\site-packages\sphinx\application.py", line 337, in build
    self.builder.build_all()
  File "c:\python39\lib\site-packages\sphinx\builders\__init__.py", line 257, in build_all
    self.build(None, summary=__('all source files'), method='all')
  File "c:\python39\lib\site-packages\sphinx\builders\__init__.py", line 307, in build
    updated_docnames = set(self.read())
  File "c:\python39\lib\site-packages\sphinx\builders\__init__.py", line 414, in read
    self._read_serial(docnames)
  File "c:\python39\lib\site-packages\sphinx\builders\__init__.py", line 435, in _read_serial
    self.read_doc(docname)
  File "c:\python39\lib\site-packages\sphinx\builders\__init__.py", line 475, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "c:\python39\lib\site-packages\sphinx\io.py", line 188, in read_doc
    pub.publish()
  File "c:\python39\lib\site-packages\docutils\core.py", line 217, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "c:\python39\lib\site-packages\sphinx\io.py", line 108, in read
    self.parse()
  File "c:\python39\lib\site-packages\docutils\readers\__init__.py", line 77, in parse
    self.parser.parse(self.input, document)
  File "c:\python39\lib\site-packages\sphinx\parsers.py", line 100, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "c:\python39\lib\site-packages\docutils\parsers\rst\states.py", line 170, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
  File "c:\python39\lib\site-packages\docutils\statemachine.py", line 241, in run
    context, next_state, result = self.check_line(
  File "c:\python39\lib\site-packages\docutils\statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "c:\python39\lib\site-packages\docutils\parsers\rst\states.py", line 2769, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "c:\python39\lib\site-packages\docutils\parsers\rst\states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "c:\python39\lib\site-packages\docutils\parsers\rst\states.py", line 393, in new_subsection
    newabsoffset = self.nested_parse(
  File "c:\python39\lib\site-packages\docutils\parsers\rst\states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "c:\python39\lib\site-packages\docutils\parsers\rst\states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "c:\python39\lib\site-packages\docutils\statemachine.py", line 241, in run
    context, next_state, result = self.check_line(
  File "c:\python39\lib\site-packages\docutils\statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "c:\python39\lib\site-packages\docutils\parsers\rst\states.py", line 2769, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "c:\python39\lib\site-packages\docutils\parsers\rst\states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "c:\python39\lib\site-packages\docutils\parsers\rst\states.py", line 393, in new_subsection
    newabsoffset = self.nested_parse(
  File "c:\python39\lib\site-packages\docutils\parsers\rst\states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "c:\python39\lib\site-packages\docutils\parsers\rst\states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "c:\python39\lib\site-packages\docutils\statemachine.py", line 241, in run
    context, next_state, result = self.check_line(
  File "c:\python39\lib\site-packages\docutils\statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "c:\python39\lib\site-packages\docutils\parsers\rst\states.py", line 2342, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "c:\python39\lib\site-packages\docutils\parsers\rst\states.py", line 2354, in explicit_construct
    return method(self, expmatch)
  File "c:\python39\lib\site-packages\docutils\parsers\rst\states.py", line 2096, in directive
    return self.run_directive(
  File "c:\python39\lib\site-packages\docutils\parsers\rst\states.py", line 2146, in run_directive
    result = directive_instance.run()
  File "c:\python39\lib\site-packages\breathe\directives.py", line 292, in run
    return self.render(matches[0], project_info, filter_, target_handler, mask_factory,
  File "c:\python39\lib\site-packages\breathe\directive\base.py", line 96, in render
    return object_renderer.render(node_stack[0], context)
  File "c:\python39\lib\site-packages\breathe\renderer\sphinxrenderer.py", line 2279, in render
    result = method(self, node)  # type: ignore
  File "c:\python39\lib\site-packages\breathe\renderer\sphinxrenderer.py", line 2166, in dispatch_compound
    return self.visit_compound(node)
  File "c:\python39\lib\site-packages\breathe\renderer\sphinxrenderer.py", line 1063, in visit_compound
    return self.visit_class(node)
  File "c:\python39\lib\site-packages\breathe\renderer\sphinxrenderer.py", line 1006, in visit_class
    nodes = self.handle_declaration(nodeDef, declaration, content_callback=content,
  File "c:\python39\lib\site-packages\breathe\renderer\sphinxrenderer.py", line 637, in handle_declaration
    nodes_ = self.run_directive(obj_type, declaration, content_callback, options)
  File "c:\python39\lib\site-packages\breathe\renderer\sphinxrenderer.py", line 596, in run_directive
    nodes = directive.run()
  File "c:\python39\lib\site-packages\sphinx\domains\cpp.py", line 7100, in run
    return super().run()
  File "c:\python39\lib\site-packages\sphinx\directives\__init__.py", line 209, in run
    self.transform_content(contentnode)
  File "c:\python39\lib\site-packages\breathe\renderer\sphinxrenderer.py", line 67, in transform_content
    callback(contentnode)
  File "c:\python39\lib\site-packages\breathe\renderer\sphinxrenderer.py", line 1001, in content
    rendered_data = self.render(file_data, parent_context)
  File "c:\python39\lib\site-packages\breathe\renderer\sphinxrenderer.py", line 2279, in render
    result = method(self, node)  # type: ignore
  File "c:\python39\lib\site-packages\breathe\renderer\sphinxrenderer.py", line 924, in visit_doxygendef
    return self.render(node.compounddef)
  File "c:\python39\lib\site-packages\breathe\renderer\sphinxrenderer.py", line 2279, in render
    result = method(self, node)  # type: ignore
  File "c:\python39\lib\site-packages\breathe\renderer\sphinxrenderer.py", line 1257, in visit_compounddef
    child_nodes = self.render(sectiondef)
  File "c:\python39\lib\site-packages\breathe\renderer\sphinxrenderer.py", line 2279, in render
    result = method(self, node)  # type: ignore
  File "c:\python39\lib\site-packages\breathe\renderer\sphinxrenderer.py", line 1299, in visit_sectiondef
    node_list.extend(self.render_iterable(node.memberdef))
  File "c:\python39\lib\site-packages\breathe\renderer\sphinxrenderer.py", line 2289, in render_iterable
    output.extend(self.render(entry))
  File "c:\python39\lib\site-packages\breathe\renderer\sphinxrenderer.py", line 2279, in render
    result = method(self, node)  # type: ignore
  File "c:\python39\lib\site-packages\breathe\renderer\sphinxrenderer.py", line 2172, in dispatch_memberdef
    return self.visit_function(node)
  File "c:\python39\lib\site-packages\breathe\renderer\sphinxrenderer.py", line 1805, in visit_function
    elements = [self.create_template_prefix(node)]
  File "c:\python39\lib\site-packages\breathe\renderer\sphinxrenderer.py", line 780, in create_template_prefix
    nodes = self.render(decl.templateparamlist)
  File "c:\python39\lib\site-packages\breathe\renderer\sphinxrenderer.py", line 2279, in render
    result = method(self, node)  # type: ignore
  File "c:\python39\lib\site-packages\breathe\renderer\sphinxrenderer.py", line 2089, in visit_templateparamlist
    nodelist.extend(self.visit_param(item, insertDeclNameByParsing=True))
  File "c:\python39\lib\site-packages\breathe\renderer\sphinxrenderer.py", line 2051, in visit_param
    ast = parser._parse_type(named='single', outer='templateParam')
  File "c:\python39\lib\site-packages\sphinx\domains\cpp.py", line 6415, in _parse_type
    declSpecs = self._parse_decl_specs(outer=outer)
  File "c:\python39\lib\site-packages\sphinx\domains\cpp.py", line 6109, in _parse_decl_specs
    trailing = self._parse_trailing_type_spec()
  File "c:\python39\lib\site-packages\sphinx\domains\cpp.py", line 5874, in _parse_trailing_type_spec
    nestedName = self._parse_nested_name()
  File "c:\python39\lib\site-packages\sphinx\domains\cpp.py", line 5796, in _parse_nested_name
    self.fail("Expected identifier in nested name.")
  File "c:\python39\lib\site-packages\sphinx\util\cfamily.py", line 275, in fail
    raise self._make_multi_error(errors, '')
sphinx.util.cfamily.DefinitionError: Invalid C++ declaration: Expected identifier in nested name. [error at 8]
  typename...
  --------^
```

**Comment by jakobandersen** [comment] 2021-07-15 08:24
Thanks for reporting, though I think this is duplicate of #9433. Otherwise please reopen.
Despite how the error looks I'm quite sure this is a problem in Breathe, that will get fixed with https://github.com/michaeljones/breathe/pull/711.

**Closed as completed by jakobandersen** 2021-07-15 08:24 UTC
Labels: closed:duplicate, domains:cpp
