### ISSUE TITLE
make clean does not remove stubs

### ISSUE THREAD

**Issue by rvernica** [sphinx-doc/sphinx#10458] opened 2022-05-16 23:52 UTC
**Is your feature request related to a problem? Please describe.**

`stubs` directory is generated by `make html` but `make clean` does not clean it.

**Comment by AA-Turner** [comment] 2022-05-17 00:40
Please provide a reproducing example. Does this happen on every project?

A

**Comment by rvernica** [comment] 2022-05-17 00:52
I would think it happens on every project. `make clean` just removed the `_build` directory as it states when it runs. The `stubs` directory is a sibling of the `_build` directory.

**Comment by AA-Turner** [comment] 2022-05-17 00:55
I'm on mobile at present, but I don't particularly remember a `stubs` directory being generated, which makes me think this is due to an extension, hence the request for a reproducing example. 

What happens when you start a new project with `Sphinx-QuickStart`? Does the stubs directory still get generated?

A

**Comment by rvernica** [comment] 2022-05-17 01:11
No worries, right, we are using `sphinx.ext.autodoc` and `sphinx.ext.autosummary`. One of them is generating the `stubs` directory. Is this not the right place to report issues with these extensions?

**Comment by AA-Turner** [comment] 2022-05-17 01:39
That's helpful, thank you. This is the right place, but there's somewhat of a conceptual difference between Sphinx as the core application and the built-in extensions to Sphinx.

A

**Comment by tk0miya** [comment] 2022-05-22 16:52
Thank you for reporting. But it was already reported as #1999. Closing.

**Closed as completed by tk0miya** 2022-05-22 16:52 UTC
Labels: closed:duplicate, type:enhancement, extensions:autosummary
