### ISSUE TITLE
C++20 requires clause not supported

### ISSUE THREAD

**Issue by mpusz** [sphinx-doc/sphinx#7295] opened 2020-03-11 09:55 UTC
Could you please add the support for C++ [requires clauses](https://en.cppreference.com/w/cpp/language/constraints)?

I am the author of [mp-units](https://github.com/mpusz/units) which is a Physical Units Library targeting C++23 and implemented in C++20. You can find the initial version of docs here: <https://mpusz.github.io/units/index.html>. That documentation is meant to help with getting user's feedback before C++ standardization so it would be great if you could help here.

**Comment by jakobandersen** [comment] 2020-05-15 18:38
Instead of reinventing the wheel regarding name mangling I try to to follow (in spirit) the Itanium ABI, but it looks like the standard is not yet clear on some details (itanium-cxx-abi/cxx-abi#24).
@mpusz, do you happen to have seen mangled names with constraints? I can't get GCC to produce any so far.

**Comment by jakobandersen** [comment] 2020-05-16 08:08
I believe PR #7670 implements the most of the feature, including ID generation. @mpusz, can you check with your project if it fixes the cases one might expect?

What is missing, and will be deferred to later is the indentation of the lines with requires clauses (see also for a similar issue #1514).

**Comment by mpusz** [comment] 2020-05-17 14:50
I checked the latest version and it still does not work but the generated errors are different. For example for the following code: https://github.com/mpusz/units/blob/master/src/include/units/quantity_cast.h#L327-L329 Sphinx 3.0.3 generated the following error:

```
/home/conan/.conan/data/mp-units/0.6.0/mpusz/testing/build/84fafb7fe407ee8fe81202463e0abcc961cfd947/docs/reference/functions.rst:7: WARNING: Invalid C++ declaration: Expected end of definition. [error at 129]
  template<Quantity To, typename D, typename U, typename Rep> constexpr auto units::quantity_cast (const quantity< D, U, Rep > &q) requires QuantityOf< To
  ---------------------------------------------------------------------------------------------------------------------------------^
```

while the PR #7670 prints:

```
[build] /home/mpusz/repos/units/docs/reference/functions.rst:7: WARNING: 
[build] Main error:
[build]   Invalid C++ declaration: Expected end of definition. [error at 148]
[build]     template<Quantity To, typename D, typename U, typename Rep> constexpr auto units::quantity_cast (const quantity< D, U, Rep > &q) requires QuantityOf< To
[build]     ----------------------------------------------------------------------------------------------------------------------------------------------------^
[build] Potential other error:
[build]   Error in parsing template argument list.
[build]   If type argument:
[build]     Invalid C++ declaration: Expected "...>", ">" or "," in template argument list. [error at 152]
[build]       template<Quantity To, typename D, typename U, typename Rep> constexpr auto units::quantity_cast (const quantity< D, U, Rep > &q) requires QuantityOf< To
[build]       --------------------------------------------------------------------------------------------------------------------------------------------------------^
[build]   If non-type argument:
[build]     Invalid C++ declaration: Expected "...>", ">" or "," in template argument list. [error at 152]
[build]       template<Quantity To, typename D, typename U, typename Rep> constexpr auto units::quantity_cast (const quantity< D, U, Rep > &q) requires QuantityOf< To
[build]       --------------------------------------------------------------------------------------------------------------------------------------------------------^
[build] 
```

**Comment by jakobandersen** [comment] 2020-05-17 17:03
In the code the declaration ends with ``requires QuantityOf<To, D>`` but in the shown error output the declaration looks like ``requires QuantityOf< To``. Is this a copy-paste error, or was the output really like this? If so, it may be that Doxygen/Breathe doesn't give the right thing to Sphinx.

**Comment by mpusz** [comment] 2020-05-24 20:56
I am sorry, I missed your answer :-(

I confirm it is not a copy-paste error but a full line of the trace I get.

**Comment by jakobandersen** [comment] 2020-05-25 17:03
In that case I guess Breathe or Doxygen may have a problem. I didn't find an easy, quick way to build your docs, so I can't check.
Let's move the discussion over to the Breathe issue. I'll close this for now, as the Sphinx part seems to work as intended.

**Closed as completed by jakobandersen** 2020-05-25 17:03 UTC
Labels: type:enhancement, domains:cpp

**Comment by mpusz** [comment] 2020-05-26 13:14
In case you are interested, you can find info on how to build docs here: https://mpusz.github.io/units/usage.html#full-mp-units-build-unit-testing-and-documentation-generation and the following remotes have to be added to Conan:
https://mpusz.github.io/units/usage.html#non-standard-conan-remotes.
