### ISSUE TITLE
`sphinx-doc.org` (without `www.`) does not support HTTPS

### ISSUE THREAD

**Issue by ghost** [sphinx-doc/sphinx#9660] opened 2021-09-21 08:20 UTC
### Describe the bug

``sphinx-doc.org`` (without ``www.``) does not support HTTPS.
This prevents the redirect `sphinx-doc.org` --> `www.sphinx-doc.org` from happening with HTTPS.

Remark: Whether this is a bug or a feature request might depend on one's viewpoint.  Mine is that nowadays not supporting HTTPS is a bug.

### How to Reproduce

Use Firefox in HTTPS-only mode (or any other browser with that capability) and visit ``https://sphinx-doc.org``.  Alternatively you can use ``curl https://sphinx-doc.org`` or ``wget https://sphinx-doc.org``.

### Expected behavior

A HTTPS redirect to https://www.sphinx-doc.org.

### Your project

N/A

### OS

N/A

### Python version

N/A

### Sphinx version

N/A

**Comment by tk0miya** [comment] 2021-09-23 03:58
sphinx-doc.org is not a proper URL for Sphinx website. Please use www.sphinx-doc.org instead.

**Comment by jmckenna** [comment] 2021-09-23 19:10
@tk0miya I think supporting without 'www' is now common and I recommend that this is supported, as the reporter noted.

**Comment by wolph** [comment] 2022-04-28 20:07
https://sphinx-doc.org/ without the www used to be a valid and working url. I'm sure it worked before since referenced it in my book about 6 years ago.

Even if it's not recommend by you anymore, please fix this for the sake of not breaking existing urls on the internet :)

It looks like the current domain is set-up through Cloudflare so it should be trivial to enable this. I have this working for all of my domains without any issues.
Here's a tutorial on redirecting if you prefer that: https://community.cloudflare.com/t/redirect-example-com-to-www-example-com/78348

**Comment by tk0miya** [comment] 2022-04-30 15:53
I don't have control for the domain settings. So I assigned this issue to @birkenfeld.

**Comment by birkenfeld** [comment] 2022-05-04 04:42
RTD states (https://docs.readthedocs.io/en/stable/custom_domains.html) that the root domain needs to be forwarded with an ANAME or ALIAS entry. The previous way with fixed IPs is no longer supported.

Unfortunately I can't add such an entry in my domain provider's interface.

I'm however prepared to transfer the domain if someone on the team is willing to take it over.

**Comment by jayaddison** [comment] 2024-03-04 22:36
Duplicate of #7779.

**Closed as not planned by jayaddison** 2024-03-04 22:36 UTC
Labels: type:bug, type:docs
