### ISSUE TITLE
[docs] They don't mention `float` package needed for figure_align='H' latex option

### ISSUE THREAD

**Issue by ghost** [sphinx-doc/sphinx#2679] opened 2016-06-15 13:36 UTC
Came across a problem with some, not all, latex builds failing with:
`! LaTeX Error: Unknown float option H'`

I'd set `figure_align='H'` in conf.py but assumed it hadn't worked. It's just that some TeX Live versions ignore it, some don't. Solution is to add `\usepackage{float}` to the preamble. This should be checked and added to the docs beside the text for figure_align when the 'H' setting is mentioned.

**Comment by jfbu** [comment] 2016-06-15 17:59
Memo: suppression of `float` happened at a1240d2 (1.3.4. fix #2147). But indeed `newfloat` does not provide `H`. (PR #2660 proposes removal of `newfloat` which is to define new float environments, not to enhance existing ones). Either re-use `float`, or it is also possible to let Sphinx intercept `H` specifier. In that case we don't need a floating environment. We can use `capt-of` package, already loaded by `sphinx.sty` and its macro `\captionof`.

**Comment by jfbu** [comment] 2016-06-15 18:39
side note: the name `figure_align` is a bit misleading; although it is a sort or "vertical" alignment, in LaTeX people speak of `float placement specifier`. This is different from horizontal `alignment` of the image which could be left, right, center.

**Comment by jfbu** [comment] 2016-06-19 18:29
@tk0miya I have investigated a bit the issue.

#. first I wanted to see if we can use again package `float`, as it was removed on the occasion of  PR #2153, perhaps there was incompatibility with `newfloat`? I have not found obvious incompatibility and anyway, `newfloat` package will not be used in future from PR #2660.

#. it is important to load `float.sty` before `hyperref.sty`.

#. there is incompatibility if user does something like `\floatstyle{plaintop}\restylefloat{figure}`, so that `figure` is given a style handled by `float` package. The problem is that our `sphinxfigure-in-table` environment does not work anymore. I have not tried to hard see how to make it work, because that looks quite complicated and there is also `hyperref` in the loop. What I discovered however is that with `\restylefloat*{figure}` which says to `float` not to modify `\caption` for `figure` the it works, but then interest of `\floatstyle` seems weak.

#. I looked if you can define `literalblock` using `float`, as an alternative to the code from PR #2660 which itself replaces the one with `newfloat`; yes this is possible but it is crucial to use `\restylefloat*`, else `\caption` handling in literal-block will  crash (same problem as for figure in table). And we have to keep the custom definition of `\theliteralblock` (to avoid chapter 0 numbering). And a few other things. Hence it would not really simplify code from PR #2660, and I think we can spare using `float.sty` for literal blocks. After all they are _not_ floats, and the only reason to pretend they are is because of `\caption` use in custom `Verbatim`. And if we use `float` package we must tell it explicitely with `\restylefloat*` starred macro to **not** modify `\caption` for literal blocks...

#. as user will not really be authorized customize `figure` environment from using package `float` due to problem above of `figure-in-table`, the only interest of `float` is then for `H` specifier. This `H` is handled via global `'figure_align'` option which is specific to latex target. Brief investigation shows that our existing `sphinxfigure-in-table` essentially already does the job, replace `\begin{figure}[H]` by `\par\noindent\begin{sphinxfigure-in-table}` etc.. in latex file and it works. But the difference would presumably be in vertical spaces, I have not checked. I hope that the float package `\begin{figure}[H]` does the right thing and has exactly same spaces as `\begin{figure}[htbp]` when there is room for `h` to work.

I did brief testing both on stable and master and PR #2660 with adding `\RequirePackage{float}` (before hyperref) and see no problem. As I said above the important point is that user should be warned that it can not restyle float environment `figure` using package `float`, because this breaks the special code of Sphinx to allow figures inside tables.

**Comment by tk0miya** [comment] 2016-06-20 01:56
I overlooked the package was used. So the removal was my mistake.
+1 for adding `\RequirePackage{float}`.

**Comment by jfbu** [comment] 2016-06-20 07:30
fixed via PR #2697. `float` package will be used again by Sphinx 1.4.5. Thank you for reporting !

**Closed as completed by jfbu** 2016-06-20 07:30 UTC
Labels: builder:latex
