### ISSUE TITLE
Highlighting skipped for C#

### ISSUE THREAD

**Issue by NikitaEgorov** [sphinx-doc/sphinx#3484] opened 2017-03-01 12:33 UTC
Subject: Add c# ``code-block``

### Problem
WARNING: Could not lex literal_block as "C#". Highlighting skipped.

#### Procedure to reproduce the problem
```
.. code-block:: C#
    :linenos:   
    
    var i = 1;
    var str = $"test{i}";
```

#### Error logs / results
WARNING: Could not lex literal_block as "C#". Highlighting skipped.

### Environment info
- Python version: 2.7
- Sphinx version: 1.5.2

**Comment by tk0miya** [comment] 2017-03-01 15:09
I don't know the syntax of C#, but pygments causes parsing error for your example:
```
$ cat test.cs
var i = 1;
var str = $"test{i}";
```
```
$ cat test.cs | .tox/py27/bin/pygmentize -l 'C#' -F raiseonerror
var i = 1;

*** Error while highlighting:
ErrorToken: $
   (file "/Users/tkomiya/work/sphinx/.tox/py27/lib/python2.7/site-packages/pygments/filters/__init__.py", line 196, in filter)
*** If this is a bug you want to report, please rerun with -v.
var str = %
```

If it's valid, it might be a bug of pygments.
Thanks,

**Comment by NikitaEgorov** [comment] 2017-03-01 17:57
@tk0miya 

It'is valid syntax of c# 
https://msdn.microsoft.com/library/dn961160.aspx

**Comment by NikitaEgorov** [comment] 2017-03-01 22:59
Create issue for pygments

https://bitbucket.org/birkenfeld/pygments-main/issues/1334/highlighting-error-for-c

**Comment by tk0miya** [comment] 2017-03-03 15:11
Thanks,
It seems this is not a bug of Sphinx.
So I close this now.

Thank you for reporting.

**Closed as completed by tk0miya** 2017-03-03 15:11 UTC
Labels: type:question, markup
