### ISSUE TITLE
Nested ordered list

### ISSUE THREAD

**Issue by YiHoze** [sphinx-doc/sphinx#3823] opened 2017-05-29 06:05 UTC
Subject: Nested ordered list

### Problem
- In nested ordered lists, unlike nested unordered lists, child lists  are wrapped by `<blockquote>`  in html, and not nested properly in latex. 

#### Procedure to reproduce the problem
```
#. Blah
#. Blah

  #. Blah
  #. Blah

#. Blah
#. Blah
```

### Environment info
- OS: <Windows 10>
- Python version: 3.5.2
- Sphinx version: 1.5.5

**Comment by jfbu** [comment] 2017-05-29 06:30
Hi, please try with one more space character for indentation:

```
#. Blah
#. Blah

   #. Blah
   #. Blah

#. Blah
#. Blah
```

See http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#enumerated-lists

Closing as this is not a bug of Sphinx, thanks for report.

**Closed as completed by jfbu** 2017-05-29 06:30 UTC
Labels: type:question, markup

**Comment by YiHoze** [comment] 2017-05-30 01:15
Thanks for your reply, but you don't seem to understand my question.
Please see this image, which I made only with default settings.

![blockquote_child_ordered_list](https://cloud.githubusercontent.com/assets/13652634/26564796/7a30c01e-4520-11e7-8010-5ed66ef4493b.png)

The child list is in a <blockquote> block.
I also did a test with bullet list. In the result, the child list is wrapped by <p></p>
I think <blockquote> blocks in nested ordered lists should be replaced with <p>blocks likewise.

Hoze

**Comment by YiHoze** [comment] 2017-05-30 05:16
I've not fully understood how many spaces child items should be indented.
Thanks.
