### ISSUE TITLE
Sphinx does not import module path defined via pathlib (PosixPath)

### ISSUE THREAD

**Issue by sivakhno** [sphinx-doc/sphinx#8525] opened 2020-12-10 10:25 UTC
**Describe the bug**
Sphinx build (apidoc) does not import / recognise python modules from **path** defined via pathlib

**To Reproduce**
```
-- in conf.py
_path = Path(os.path.dirname(os.path.abspath(__file__))).parent.parent
sys.path.insert(0, _path.joinpath('plugins'))
print('PYTHONPATH', sys.path)

-- run sphinx-apidoc
-- run sphinx-build 

-- sphinx-build command output
PYTHONPATH PosixPath('...')
WARNING: autodoc: failed to import module 'Y' from module 'X'; the following exception was raised:
No module named 'X'

-- all is fine if I use os.path
sys.path.insert(0, os.path.join(_path, 'plugins'))
'''

**Expected behavior**
python packages should be imported given pathlib path 

**Environment info**
- OS: MacOS
- Python version: 3.7
- Sphinx version: 3.3.1
- Sphinx extensions:  ['m2r2', 'sphinx.ext.napoleon', 'sphinx.ext.autodoc', 'sphinxcontrib.confluencebuilder']

**Comment by tk0miya** [comment] 2020-12-12 03:46
Is it available for sys-path entry? Python-document says strings and bytes are only allowed. Sphinx uses `importlib` to import python objects on generating documents. So the all sys-path entries should obey the convention of python.

>A program is free to modify this list for its own purposes. Only strings and bytes should be added to sys.path; all other data types are ignored during import.
>https://docs.python.org/3/library/sys.html#sys.path

**Comment by tk0miya** [comment] 2020-12-25 16:34
Now I'm closing this because I think this is not a bug of Sphinx.
Thanks,

**Closed as completed by tk0miya** 2020-12-25 16:34 UTC
Labels: type:question
