### ISSUE TITLE
2.1.0 regression [autodoc]: Unknown target name: "type"

### ISSUE THREAD

**Issue by pitrou** [sphinx-doc/sphinx#6436] opened 2019-06-03 07:59 UTC
Our CI jobs started failing with Sphinx 2.1.0.
Example here:
https://travis-ci.org/apache/arrow/jobs/540490192#L5631

The error is:
```
Warning, treated as error:
docstring of pyarrow.SerializationContext.register_type:0:Unknown target name: "type".
```

Here is said docstring:
```python
        """EXPERIMENTAL: Add type to the list of types we can serialize.

        Parameters
        ----------
        type_ : TypeType
            The type that we can serialize.
        type_id : string
            A string used to identify the type.
        pickle : bool
            True if the serialization should be done with pickle.
            False if it should be done efficiently with Arrow.
        custom_serializer : callable
            This argument is optional, but can be provided to
            serialize objects of the class in a particular way.
        custom_deserializer : callable
            This argument is optional, but can be provided to
            deserialize objects of the class in a particular way.
        """
```

You can find out `conf.py` here:
https://github.com/apache/arrow/blob/master/docs/source/conf.py

**Comment by tk0miya** [comment] 2019-06-03 16:48
Sorry for inconvenience. Will take a look tomorrow.

**Comment by tk0miya** [comment] 2019-06-04 15:26
Hmm, pyarrow's document is too complex... Now I'm trying to reproduce the error on local. Can you reproduce it? If possible, I'd like to know the output of sphinx-build command with `-vvv` option.

**Comment by pitrou** [comment] 2019-06-05 18:42
Ok, I ran:
```
LANG=C sphinx-build -vvv -b html -d _build/doctrees -W source _build/html
```
Here is the (long) output:
https://gist.githubusercontent.com/pitrou/4156eb2d4fbd11488eabac0c6d8d2944/raw/65cdef49e7d0229731c1ddc4119dd4e92a1c244b/gistfile1.txt

And here's the error at the end:
```
Traceback (most recent call last):
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/site-packages/sphinx/cmd/build.py", line 284, in build_main
    app.build(args.force_all, filenames)
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/site-packages/sphinx/application.py", line 345, in build
    self.builder.build_update()
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 319, in build_update
    len(to_build))
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 332, in build
    updated_docnames = set(self.read())
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/site-packages/sphinx/util/logging.py", line 230, in pending_warnings
    memhandler.flushTo(logger)
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/site-packages/sphinx/util/logging.py", line 193, in flushTo
    logger.handle(record)
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/logging/__init__.py", line 901, in handle
    rv = self.filter(record)
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/logging/__init__.py", line 762, in filter
    result = f.filter(record)
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/site-packages/sphinx/util/logging.py", line 426, in filter
    raise SphinxWarning(location + ":" + message)
sphinx.errors.SphinxWarning: docstring of pyarrow.SerializationContext.register_type:0:Unknown target name: "type".

Warning, treated as error:
docstring of pyarrow.SerializationContext.register_type:0:Unknown target name: "type".
```

**Comment by pitrou** [comment] 2019-06-05 18:43
(note: unfortunately, I didn't manage to write a standalone reproducer)

**Comment by tk0miya** [comment] 2019-06-06 16:32
Thank you for information. I still can't reproduce the error. But I'll try again tomorrow.

**Comment by tk0miya** [comment] 2019-06-08 14:13
I still can't reproduce the error, but https://github.com/apache/arrow/commit/f8874e081552d9ff237a90e7f18cf589732ae171 lets us know that sphinx considers `type_` as a reference notation.
I think napoleon should escape it on conversion docstrings into reST.

**Comment by pitrou** [comment] 2019-06-08 14:48
@tk0miya Yes, this seems to be the reason. It's easy to work around, but the error message made it a bit difficult to understand what was happening at first.

**Comment by tk0miya** [comment] 2019-06-08 15:27
I posted #6460 to escape the variable on conversion. With the change, the workaround https://github.com/apache/arrow/commit/f8874e081552d9ff237a90e7f18cf589732ae171 will be not needed.

**Comment by pitrou** [comment] 2019-06-08 20:25
Will #6460 break the workaround?

**Comment by tk0miya** [comment] 2019-06-09 16:01
Unfortunately, yes. backslash will be shown after upgrade.

**Comment by tk0miya** [comment] 2019-06-09 16:10
Now I'm merging #6460 into 2.1.1 branch. It will be released within a day (maybe).
Thank you for reporting.

**Closed as completed by tk0miya** 2019-06-09 16:10 UTC
Labels: type:bug, extensions:napoleon
