### ISSUE TITLE
3.1.2: test suite is failing

### ISSUE THREAD

**Issue by kloczek** [sphinx-doc/sphinx#8003] opened 2020-07-24 14:44 UTC
```
+ cd Sphinx-3.1.2
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-sphinx-3.1.2-2.fc33.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/python3 -m pytest -k 'not linkcheck and not latex_remote_images and not test_latex_images and not test_gettext_definition_terms and not test_text_definition_terms'
========================================================================================= test session starts ==========================================================================================
platform linux -- Python 3.8.3, pytest-4.6.9, py-1.8.0, pluggy-0.13.1
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/home/tkloczko/rpmbuild/BUILD/Sphinx-3.1.2/.hypothesis/examples')
libraries: Sphinx-3.1.2, docutils-0.16
base tempdir: /tmp/pytest-of-tkloczko/pytest-1
rootdir: /home/tkloczko/rpmbuild/BUILD/Sphinx-3.1.2, inifile: setup.cfg, testpaths: tests
plugins: forked-1.1.1, mock-1.10.4, expect-1.1.0, hypothesis-4.23.8, xdist-1.31.0, httpbin-0.3.0, cov-2.8.1, timeout-1.3.4, rerunfailures-8.0, flaky-3.6.1
collected 1525 items / 9 deselected / 1516 selected

tests/test_api_translator.py ...........                                                                                                                                                         [  0%]
tests/test_application.py .......                                                                                                                                                                [  1%]
tests/test_build.py .........                                                                                                                                                                    [  1%]
tests/test_build_changes.py ..                                                                                                                                                                   [  1%]
tests/test_build_dirhtml.py .                                                                                                                                                                    [  1%]
tests/test_build_epub.py ..........s                                                                                                                                                             [  2%]
tests/test_build_gettext.py ......                                                                                                                                                               [  3%]
tests/test_build_html.py ....................................................................................................................................................................... [ 14%]
................................................................................................................................................................................................ [ 26%]
...........................................................................................................................................................                                      [ 37%]
tests/test_build_latex.py ...............................................................................                                                                                        [ 42%]
tests/test_build_manpage.py ....                                                                                                                                                                 [ 42%]
tests/test_build_texinfo.py ......                                                                                                                                                               [ 42%]
tests/test_build_text.py ...............                                                                                                                                                         [ 43%]
tests/test_builder.py ..                                                                                                                                                                         [ 43%]
tests/test_catalogs.py ...                                                                                                                                                                       [ 44%]
tests/test_config.py ............................                                                                                                                                                [ 46%]
tests/test_correct_year.py ...                                                                                                                                                                   [ 46%]
tests/test_directive_code.py .......................................                                                                                                                             [ 48%]
tests/test_directive_only.py .                                                                                                                                                                   [ 48%]
tests/test_directive_other.py .......                                                                                                                                                            [ 49%]
tests/test_directive_patch.py ..                                                                                                                                                                 [ 49%]
tests/test_docutilsconf.py ..                                                                                                                                                                    [ 49%]
tests/test_domain_c.py ..................                                                                                                                                                        [ 50%]
tests/test_domain_cpp.py ...........................                                                                                                                                             [ 52%]
tests/test_domain_js.py ........                                                                                                                                                                 [ 53%]
tests/test_domain_py.py .............................                                                                                                                                            [ 55%]
tests/test_domain_rst.py ........                                                                                                                                                                [ 55%]
tests/test_domain_std.py ..............                                                                                                                                                          [ 56%]
tests/test_environment.py ....                                                                                                                                                                   [ 56%]
tests/test_environment_indexentries.py ........                                                                                                                                                  [ 57%]
tests/test_environment_toctree.py .........                                                                                                                                                      [ 57%]
tests/test_errors.py ..                                                                                                                                                                          [ 57%]
tests/test_events.py ..                                                                                                                                                                          [ 58%]
tests/test_ext_apidoc.py ........................                                                                                                                                                [ 59%]
tests/test_ext_autodoc.py ...............................................s............                                                                                                           [ 63%]
tests/test_ext_autodoc_autofunction.py ..........                                                                                                                                                [ 64%]
tests/test_ext_autodoc_configs.py ...............                                                                                                                                                [ 65%]
tests/test_ext_autodoc_events.py ....                                                                                                                                                            [ 65%]
tests/test_ext_autodoc_mock.py ......                                                                                                                                                            [ 65%]
tests/test_ext_autodoc_private_members.py ..                                                                                                                                                     [ 66%]
tests/test_ext_autosectionlabel.py ...                                                                                                                                                           [ 66%]
tests/test_ext_autosummary.py .....................                                                                                                                                              [ 67%]
tests/test_ext_coverage.py ....                                                                                                                                                                  [ 67%]
tests/test_ext_doctest.py ......                                                                                                                                                                 [ 68%]
tests/test_ext_duration.py .                                                                                                                                                                     [ 68%]
tests/test_ext_githubpages.py ...                                                                                                                                                                [ 68%]
tests/test_ext_graphviz.py .....                                                                                                                                                                 [ 68%]
tests/test_ext_ifconfig.py .                                                                                                                                                                     [ 68%]
tests/test_ext_imgconverter.py .                                                                                                                                                                 [ 69%]
tests/test_ext_inheritance_diagram.py ......                                                                                                                                                     [ 69%]
tests/test_ext_intersphinx.py ..................                                                                                                                                                 [ 70%]
tests/test_ext_math.py .F...........                                                                                                                                                             [ 71%]
tests/test_ext_napoleon.py ................                                                                                                                                                      [ 72%]
tests/test_ext_napoleon_docstring.py ...............................                                                                                                                             [ 74%]
tests/test_ext_napoleon_iterators.py ................                                                                                                                                            [ 75%]
tests/test_ext_todo.py ...                                                                                                                                                                       [ 75%]
tests/test_ext_viewcode.py ...                                                                                                                                                                   [ 76%]
tests/test_highlighting.py .....                                                                                                                                                                 [ 76%]
tests/test_intl.py ..............................................                                                                                                                                [ 79%]
tests/test_locale.py ...                                                                                                                                                                         [ 79%]
tests/test_markup.py .................................                                                                                                                                           [ 81%]
tests/test_metadata.py .                                                                                                                                                                         [ 81%]
tests/test_parser.py .                                                                                                                                                                           [ 81%]
tests/test_project.py ...                                                                                                                                                                        [ 82%]
tests/test_pycode.py ........                                                                                                                                                                    [ 82%]
tests/test_pycode_ast.py .......................................                                                                                                                                 [ 85%]
tests/test_pycode_parser.py .............................                                                                                                                                        [ 87%]
tests/test_quickstart.py .........                                                                                                                                                               [ 87%]
tests/test_roles.py .                                                                                                                                                                            [ 87%]
tests/test_search.py ...........                                                                                                                                                                 [ 88%]
tests/test_setup_command.py .......                                                                                                                                                              [ 88%]
tests/test_smartquotes.py .........                                                                                                                                                              [ 89%]
tests/test_templating.py ...                                                                                                                                                                     [ 89%]
tests/test_theming.py .......                                                                                                                                                                    [ 90%]
tests/test_toctree.py ...                                                                                                                                                                        [ 90%]
tests/test_transforms_post_transforms_code.py ..                                                                                                                                                 [ 90%]
tests/test_util.py ........                                                                                                                                                                      [ 91%]
tests/test_util_docstrings.py ...                                                                                                                                                                [ 91%]
tests/test_util_docutils.py ...                                                                                                                                                                  [ 91%]
tests/test_util_fileutil.py ..                                                                                                                                                                   [ 91%]
tests/test_util_i18n.py .......                                                                                                                                                                  [ 92%]
tests/test_util_images.py ....                                                                                                                                                                   [ 92%]
tests/test_util_inspect.py ....................................                                                                                                                                  [ 94%]
tests/test_util_inventory.py ...                                                                                                                                                                 [ 94%]
tests/test_util_jsdump.py .                                                                                                                                                                      [ 94%]
tests/test_util_logging.py .................                                                                                                                                                     [ 96%]
tests/test_util_matching.py ..                                                                                                                                                                   [ 96%]
tests/test_util_nodes.py ..........................                                                                                                                                              [ 97%]
tests/test_util_pycompat.py ..                                                                                                                                                                   [ 98%]
tests/test_util_rst.py .......                                                                                                                                                                   [ 98%]
tests/test_util_template.py ..                                                                                                                                                                   [ 98%]
tests/test_util_typing.py ..s......                                                                                                                                                              [ 99%]
tests/test_versioning.py ..........                                                                                                                                                              [ 99%]
tests/test_writer_latex.py .                                                                                                                                                                     [100%]

=============================================================================================== FAILURES ===============================================================================================
___________________________________________________________________________________________ test_imgmath_svg ___________________________________________________________________________________________

src = '/tmp/tmpq1no423o/math.svg', dst = '/tmp/pytest-of-tkloczko/pytest-1/ext-math-simple/_build/html/_images/math/629f623183b046595b4a2c96990664cf3fbe89ee.svg'
copy_function = <function copy2 at 0x7f5a17f31e50>

    def move(src, dst, copy_function=copy2):
        """Recursively move a file or directory to another location. This is
        similar to the Unix "mv" command. Return the file or directory's
        destination.

        If the destination is a directory or a symlink to a directory, the source
        is moved inside the directory. The destination path must not already
        exist.

        If the destination already exists but is not a directory, it may be
        overwritten depending on os.rename() semantics.

        If the destination is on our current filesystem, then rename() is used.
        Otherwise, src is copied to the destination and then removed. Symlinks are
        recreated under the new name if os.rename() fails because of cross
        filesystem renames.

        The optional `copy_function` argument is a callable that will be used
        to copy the source or it will be delegated to `copytree`.
        By default, copy2() is used, but any function that supports the same
        signature (like copy()) can be used.

        A lot more could be done here...  A look at a mv.c shows a lot of
        the issues this implementation glosses over.

        """
        sys.audit("shutil.move", src, dst)
        real_dst = dst
        if os.path.isdir(dst):
            if _samefile(src, dst):
                # We might be on a case insensitive filesystem,
                # perform the rename anyway.
                os.rename(src, dst)
                return

            real_dst = os.path.join(dst, _basename(src))
            if os.path.exists(real_dst):
                raise Error("Destination path '%s' already exists" % real_dst)
        try:
>           os.rename(src, real_dst)
E           FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpq1no423o/math.svg' -> '/tmp/pytest-of-tkloczko/pytest-1/ext-math-simple/_build/html/_images/math/629f623183b046595b4a2c96990664cf3fbe89ee.svg'

/usr/lib64/python3.8/shutil.py:788: FileNotFoundError

During handling of the above exception, another exception occurred:

app = <SphinxTestApp buildername='html'>, status = <_io.StringIO object at 0x7f5a0912d280>, warning = <_io.StringIO object at 0x7f5a0912d5e0>

    @pytest.mark.skipif(not has_binary('dvisvgm'),
                        reason='Requires dvisvgm" binary')
    @pytest.mark.sphinx('html', testroot='ext-math-simple',
                        confoverrides={'extensions': ['sphinx.ext.imgmath'],
                                       'imgmath_image_format': 'svg'})
    def test_imgmath_svg(app, status, warning):
>       app.builder.build_all()

tests/test_ext_math.py:54:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
sphinx/builders/__init__.py:260: in build_all
    self.build(None, summary=__('all source files'), method='all')
sphinx/builders/__init__.py:361: in build
    self.write(docnames, list(updated_docnames), method)
sphinx/builders/__init__.py:535: in write
    self._write_serial(sorted(docnames))
sphinx/builders/__init__.py:545: in _write_serial
    self.write_doc(docname, doctree)
sphinx/builders/html/__init__.py:596: in write_doc
    self.docwriter.write(doctree, destination)
/usr/lib/python3.8/site-packages/docutils/writers/__init__.py:78: in write
    self.translate()
sphinx/writers/html.py:71: in translate
    self.document.walkabout(visitor)
/usr/lib/python3.8/site-packages/docutils/nodes.py:214: in walkabout
    if child.walkabout(visitor):
/usr/lib/python3.8/site-packages/docutils/nodes.py:214: in walkabout
    if child.walkabout(visitor):
/usr/lib/python3.8/site-packages/docutils/nodes.py:206: in walkabout
    visitor.dispatch_visit(self)
sphinx/util/docutils.py:468: in dispatch_visit
    method(node)
sphinx/writers/html5.py:781: in visit_math_block
    visit(self, node)
sphinx/ext/imgmath.py:348: in html_visit_displaymath
    fname, depth = render_math(self, latex)
sphinx/ext/imgmath.py:298: in render_math
    shutil.move(imgpath, outfn)
/usr/lib64/python3.8/shutil.py:802: in move
    copy_function(src, real_dst)
/usr/lib64/python3.8/shutil.py:432: in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

src = '/tmp/tmpq1no423o/math.svg', dst = '/tmp/pytest-of-tkloczko/pytest-1/ext-math-simple/_build/html/_images/math/629f623183b046595b4a2c96990664cf3fbe89ee.svg'

    def copyfile(src, dst, *, follow_symlinks=True):
        """Copy data from src to dst in the most efficient way possible.

        If follow_symlinks is not set and src is a symbolic link, a new
        symlink will be created instead of copying the file it points to.

        """
        sys.audit("shutil.copyfile", src, dst)

        if _samefile(src, dst):
            raise SameFileError("{!r} and {!r} are the same file".format(src, dst))

        file_size = 0
        for i, fn in enumerate([src, dst]):
            try:
                st = _stat(fn)
            except OSError:
                # File most likely does not exist
                pass
            else:
                # XXX What about other special files? (sockets, devices...)
                if stat.S_ISFIFO(st.st_mode):
                    fn = fn.path if isinstance(fn, os.DirEntry) else fn
                    raise SpecialFileError("`%s` is a named pipe" % fn)
                if _WINDOWS and i == 0:
                    file_size = st.st_size

        if not follow_symlinks and _islink(src):
            os.symlink(os.readlink(src), dst)
        else:
>           with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
E           FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpq1no423o/math.svg'

/usr/lib64/python3.8/shutil.py:261: FileNotFoundError
--------------------------------------------------------------------------------------- Captured stdout teardown ---------------------------------------------------------------------------------------
# testroot: root
# builder: html
# srcdir: /tmp/pytest-of-tkloczko/pytest-1/ext-math-simple
# outdir: /tmp/pytest-of-tkloczko/pytest-1/ext-math-simple/_build/html
# status:
Running Sphinx v3.1.2
loading pickled environment... done
building [html]: all source files
updating environment: 0 added, 0 changed, 0 removed
looking for now-outdated files... none found
preparing documents... done
writing output... [100%] index
# warning:

=================================================================== 1 failed, 1512 passed, 3 skipped, 9 deselected in 127.78 seconds ===================================================================
```

**Comment by kloczek** [comment] 2020-07-24 15:07
Usig tox it fails as well
[sphinx-test_suite_using_tox.txt](https://github.com/sphinx-doc/sphinx/files/4972724/sphinx-test_suite_using_tox.txt)

**Comment by tk0miya** [comment] 2020-07-25 03:44
It seems something dvisvgm was crashed for some reason and did not generate an SVG file. Could you try the following command and check the output?
```
sphinx-build -b html -Dextensions=sphinx.ext.imgmath -Dimgmath_image_format=SVG tests/roots/test-ext-math-simple _build/html
```

**Comment by tk0miya** [comment] 2020-10-03 07:10
I'm closing this now because we can't reproduce the error. Please feel free to reopen if you are still in trouble. We need additional information to reproduce it.

**Closed as completed by tk0miya** 2020-10-03 07:10 UTC
Labels: type:bug, type:tests

**Comment by kloczek** [comment] 2020-10-03 08:52
Could you please drop the hash of the commit with fix for that issue?
I would be glad to test that fix before actual release :)

Or just please ping me day or two before release to test what will be on the master :)

**Comment by tk0miya** [comment] 2020-10-03 12:48
As I commented above, I can't reproduce the error. So I can't determine what a commit causes your error. I guess it is related to your environment (might be related to dvisvgm).

>Or just please ping me day or two before release to test what will be on the master :)

We'll release a new package after a week.
