### ISSUE TITLE
<what happen when you do on which document project>

### ISSUE THREAD

**Issue by LuciusMos** [sphinx-doc/sphinx#8401] opened 2020-11-10 13:08 UTC
**Describe the bug**
I decorate a method in a class with a self-written decorator. Then in the doc will not show this method.
If I remove the decorator, the mothod can show properly.

**To Reproduce**
```
$ make html
$ # open _build/html/index and see the class's method
```

**Expected behavior**
The doc will show this method with decorator.

**Your project**
No need.

**Screenshots**
No need.

**Environment info**
- OS: Win10
- Python version: 3.6.5
- Sphinx version: 3.1.2
- Sphinx extensions:  sphinx-rtd-theme==0.4.3, sphinxcontrib-applehelp==1.0.2, sphinxcontrib-devhelp==1.0.1, sphinxcontrib-htmlhelp==1.0.2, sphinxcontrib-jsmath==1.0.1, sphinxcontrib-qthelp==1.0.2. sphinxcontrib-serializinghtml==1.1.3, sphinxcontrib-websupport==1.2.0

**Additional context**
No

**Comment by cblegare** [comment] 2020-11-12 02:31
It would be helpful to have a sample project, if not your project to help.

You might be overwriting your function's docstring with the decorator.  See https://docs.python.org/3/library/functools.html#functools.wraps for a possible solution

**Comment by tk0miya** [comment] 2020-11-12 17:03
Agreed. I think you need to use `functools.wraps` for your decorator to create a document a "decorated" function.

@cblegare Thank you for your support.

**Comment by tk0miya** [comment] 2020-12-25 15:56
Now I'm closing this because this is not a bug of Sphinx.
Thanks,

**Closed as completed by tk0miya** 2020-12-25 15:56 UTC
Labels: type:question, extensions:autodoc
