### ISSUE TITLE
weird alignment

### ISSUE THREAD

**Issue by andreacassioli** [sphinx-doc/sphinx#2535] opened 2016-05-10 09:22 UTC
I have a code like this:

```
.. rubric:: See also

:ref:`iparam.bi_ignore_max_iter`, :ref:`iparam.bi_ignore_num_error`, :ref:`iparam.bi_max_iterations`, :ref:`iparam.bi_clean_optimizer`
```

All ref point to sections, whose titles are uppercase names (fairly long indeed).

I generate tex for it, which is

```
\paragraph{See also}

{\hyperref[iparam_bi_ignore_max_iter:iparam\string-bi\string-ignore\string-max\string-iter]{\crossref{MSK\_IPAR\_BI\_IGNORE\_MAX\_ITER}}}, {\hyperref[iparam_bi_ignore_num_error:iparam\string-bi\string-ignore\string-num\\
string-error]{\crossref{MSK\_IPAR\_BI\_IGNORE\_NUM\_ERROR}}}, {\hyperref[iparam_bi_max_iterations:iparam\string-bi\string-max\string-iterations]{\crossref{MSK\_IPAR\_BI\_MAX\_ITERATIONS}}}, {\hyperref[iparam_bi_clean_op\
timizer:iparam\string-bi\string-clean\string-optimizer]{\crossref{MSK\_IPAR\_BI\_CLEAN\_OPTIMIZER}}}
```

Strangely the final output shows me padded test as shown below

![screenshot from 2016-05-10 11 22 08](https://cloud.githubusercontent.com/assets/6704112/15141677/8079566a-16a1-11e6-879f-6dd1757da3d7.png)

Is it intended? That looks ugly!

**Comment by tk0miya** [comment] 2016-05-28 08:23
Here is an example to reproduce the problem.

```
.. _label:

LONG_LONG_LONG_LONG_SECTION_NAME
================================

:ref:`label` :ref:`label` :ref:`label` :ref:`label` :ref:`label` :ref:`label`
```

Result:
![2016-05-28 15 34 13](https://cloud.githubusercontent.com/assets/748828/15625643/acf56f34-24e9-11e6-808e-84ef56d3c781.png)

**Comment by tk0miya** [comment] 2016-05-29 03:40
Note: This is not only for hyperlinks, but normal text is aligned like above.
So it seems this is a default behavior of TeX layouting.

```
Welcome to test's documentation!
================================

Contents:

LONG_LONG_LONG_LONG_SECTION_NAME
LONG_LONG_LONG_LONG_SECTION_NAME
LONG_LONG_LONG_LONG_SECTION_NAME
LONG_LONG_LONG_LONG_SECTION_NAME
LONG_LONG_LONG_LONG_SECTION_NAME
LONG_LONG_LONG_LONG_SECTION_NAME
```

Result:
![2016-05-29 12 39 32](https://cloud.githubusercontent.com/assets/748828/15631259/7203aaa6-259a-11e6-8b3f-f8297b8696c2.png)

**Comment by andreacassioli** [comment] 2016-05-30 07:02
@tk0miya 

Well, there is something fishy anyway: I have tried the following 

```
\documentclass[a4paper]{book}

\begin{document}

0123456789qwertyuiopasdfghjkl, 0123456789qwertyuiopasdfghjkl, 0123456789qwertyuiopasdfghjkl, 0123456789qwertyuiopasdfghjkl, 0123456789qwertyuiopasdfghjkl, 0123456789qwertyuiopasdfghjkl, 0123456789qwertyuiopasdfghjkl, 0123456789qwertyuiopasdfghjkl, 0123456789qwertyuiopasdfghjkl, 0123456789qwertyuiopasdfghjkl, 0123456789qwertyuiopasdfghjkl, 0123456789qwertyuiopasdfghjkl, 0123456789qwertyuiopasdfghjkl, 0123456789qwertyuiopasdfghjkl, 0123456789qwertyuiopasdfghjkl, 0123456789qwertyuiopasdfghjkl, 0123456789qwertyuiopasdfghjkl, 0123456789qwertyuiopasdfghjkl, 0123456789qwertyuiopasdfghjkl, 


aaaaa\_bbbbbbbbb\_ccccccccc\_ddddddddddddd\_eeeeeeeeeeee\_fffffff\_gggggg, aaaaa\_bbbbbbbbb\_ccccccccc\_ddddddddddddd\_eeeeeeeeeeee\_fffffff\_gggggg, aaaaa\_bbbbbbbbb\_ccccccccc\_ddddddddddddd\_eeeeeeeeeeee\_fffffff\_gggggg, aaaaa\_bbbbbbbbb\_ccccccccc\_ddddddddddddd\_eeeeeeeeeeee\_fffffff\_gggggg, aaaaa\_bbbbbbbbb\_ccccccccc\_ddddddddddddd\_eeeeeeeeeeee\_fffffff\_gggggg, aaaaa\_bbbbbbbbb\_ccccccccc\_ddddddddddddd\_eeeeeeeeeeee\_fffffff\_gggggg, aaaaa\_bbbbbbbbb\_ccccccccc\_ddddddddddddd\_eeeeeeeeeeee\_fffffff\_gggggg, aaaaa\_bbbbbbbbb\_ccccccccc\_ddddddddddddd\_eeeeeeeeeeee\_fffffff\_gggggg, aaaaa\_bbbbbbbbb\_ccccccccc\_ddddddddddddd\_eeeeeeeeeeee\_fffffff\_gggggg, aaaaa\_bbbbbbbbb\_ccccccccc\_ddddddddddddd\_eeeeeeeeeeee\_fffffff\_gggggg, aaaaa\_bbbbbbbbb\_ccccccccc\_ddddddddddddd\_eeeeeeeeeeee\_fffffff\_gggggg, aaaaa\_bbbbbbbbb\_ccccccccc\_ddddddddddddd\_eeeeeeeeeeee\_fffffff\_gggggg, aaaaa\_bbbbbbbbb\_ccccccccc\_ddddddddddddd\_eeeeeeeeeeee\_fffffff\_gggggg, aaaaa\_bbbbbbbbb\_ccccccccc\_ddddddddddddd\_eeeeeeeeeeee\_fffffff\_gggggg, aaaaa\_bbbbbbbbb\_ccccccccc\_ddddddddddddd\_eeeeeeeeeeee\_fffffff\_gggggg, aaaaa\_bbbbbbbbb\_ccccccccc\_ddddddddddddd\_eeeeeeeeeeee\_fffffff\_gggggggg, 

\end{document}
```

If you run on `pdflatex` You will see the first block is correctly aligned, whereas the second is not. This is due to margin overflow and fact that tex does not know how to hypenize the long words (they are clearly not English...).

But in our case it sounds like some words are kind of right aligned, or better the line is set to spread all the line.

**Comment by tk0miya** [comment] 2016-05-31 01:35
Sphinx tries to control margins using following settings (defined at sphinx.sty):

```
\oddsidemargin 0pt
\evensidemargin 0pt
\textwidth \paperwidth
\advance\textwidth by -2in
\sloppy
```

I added this setings into your example, then it aligns like sphinx does.
I don't know what this does.

**Comment by tk0miya** [comment] 2016-05-31 01:37
Note: the settings are appeared since the beginning of  the latex writer: https://github.com/sphinx-doc/sphinx/commit/3d74adea2595f35994093091410bc8607bd49f74#diff-1d5cb1825858bd97a9964854a60eb331R130

**Comment by andreacassioli** [comment] 2016-05-31 07:07
As far as I know those settings are used to define front/rear pages so that the left and right margins changes accordingly. This is the case with book class, because you want to consider the binding.

https://en.wikibooks.org/wiki/LaTeX/Page_Layout

Setting to zero might have been a way to use book to generate pdf with equal margins even with the book class.

**Comment by jfbu** [comment] 2016-05-31 08:34
Regarding initial TeX layout problem, yes I confirm this is TeX behaviour: when it does not know where to hyphenate, it will stretch available white spaces. But typically it does not move things too long to next line, if there is not enough stretching possible, the too long thing overflows into right margin.
If we add

```
\DeclareRobustCommand{\_}{%
\ifmmode\nfss@text{\textunderscore}\else\textunderscore\allowbreak\fi}
```

inside preamble (the only difference from latex default is added `\allowbreak`), then @tk0miya example produces

![capture d ecran 2016-05-31 a 10 22 52](https://cloud.githubusercontent.com/assets/2589111/15668095/d3847b0e-2719-11e6-98ad-55ba1f2ed745.png)

There is still some stretching of white space, but the underscore are well aligned with right end of text lines.

On final line the white space is set at natural (short) width, as last lines of paragraphs always end with infinitely stretchable glue in TeX to make them flush left.

**Comment by jfbu** [comment] 2016-05-31 09:02
@tk0miya regarding

``` latex
\oddsidemargin 0pt
\evensidemargin 0pt
\textwidth \paperwidth
\advance\textwidth by -2in
```

you can see its effect by adding `\usepackage{layout}` to latex preamble and `\layout` command after `\begin{document}`, and commenting out these lines in `sphinx.sty`.

The produced pdf will then graphically document the various page layout parameters. The `\paperwidth` is set by LaTeX depending on option passed to document class: `a4paper`, `letterpaper`, ... (default `letterpaper`). Nowadays, use of package `geometry` is recommended (people using Koma-script classes will use package `typearea` I think) to set page layout parameters.

The `\sloppy` essentially adds `3em` of total extra stretch to white spaces between words, per line, allowing TeX to stretch beyond what it does usually.

**Comment by jfbu** [comment] 2016-11-18 23:02
Thus, this has more to do with TeX layout that is has to do with Sphinx. Have you tried above advice, to use `'preamble'` key like this:

``` python
latex_elements = {
    'preamble' :
"""\\makeatletter
\\protected\\def\\_{\\ifmmode\\nfss@text{\\textunderscore}\\else
                    \\textunderscore\\allowbreak\\fi}
\\makeatother""",
}
```

I replaced  `\DeclareRobustCommand` as in https://github.com/sphinx-doc/sphinx/issues/2535#issuecomment-222625445 by `\protected\def` which is more modern syntax. The definition itself differs from the standard LaTeX one for `\_` only by addition of an `\allowbreak`. With:

``` rst
Welcome to a's documentation!
=============================

LONG_LONG_LONG_LONG_SECTION_NAME
LONG_LONG_LONG_LONG_SECTION_NAME
LONG_LONG_LONG_LONG_SECTION_NAME
LONG_LONG_LONG_LONG_SECTION_NAME
LONG_LONG_LONG_LONG_SECTION_NAME
LONG_LONG_LONG_LONG_SECTION_NAME

.. _label:

LONG_LONG_LONG_LONG_SECTION_NAME
--------------------------------

:ref:`label` :ref:`label` :ref:`label` :ref:`label` :ref:`label` :ref:`label`

```

this gives in particular

![capture d ecran 2016-11-19 a 00 00 26](https://cloud.githubusercontent.com/assets/2589111/20449710/562cedf4-adeb-11e6-93fd-589fbc3468a9.png)

Can we close the issue ?

**Comment by jfbu** [comment] 2016-12-14 17:20
@andreacassioli I hope https://github.com/sphinx-doc/sphinx/issues/2535#issuecomment-261664881 helps you.

I am not sure about whether `\crossref`, which now at 1.5 is `\sphinxcrossref` should try to improve TeX behaviour: sure it can do it for ``\_`` but then why not for other characters ? Typical typographical approach would be to typeset your long references as items in a list rather than all aligned in single line. Hacky TeX solution would do the redefinition of ``\_`` as in https://github.com/sphinx-doc/sphinx/issues/2535#issuecomment-261664881.

Sometimes, breaking is not wished for. Hence if implemented by Sphinx also option to customize it is needed. This looks like much effort for something which can be handled directly by TeX savvy users or worked around by using lists e.g. as alternative.

**Comment by jfbu** [comment] 2017-05-09 20:55
I am closing this. Feel free to re-open if your issue is not solved.

**Closed as completed by jfbu** 2017-05-09 20:55 UTC
Labels: builder:latex
