### ISSUE TITLE
Meta Directive & Open Graph

### ISSUE THREAD

**Issue by MichaelMarcialis** [sphinx-doc/sphinx#2645] opened 2016-06-08 13:59 UTC
I'm currently using the `meta` directive to generate appropriate meta descriptions on my Sphinx pages.

```
.. meta::
   :description: This is a meta description.
```

I'd also like to create Open Graph descriptions for each page, using the same description value in the `meta` directive.

```
<meta name="og:description" content="This is a meta description." />
```

Unfortunately, I'm a bit new to Sphinx and I don't know how to obtain this value from the RST source and inject it into my template. Does anyone know of a way to pull this off?

**Comment by shibukawa** [comment] 2016-07-19 20:32
It is a docutils' issue:

https://sourceforge.net/p/docutils/bugs/281/

**Comment by tk0miya** [comment] 2018-02-03 06:19
It looks like the issue is fixed. But it is not released yet.
Let's take a look again after the release.

**Comment by tk0miya** [comment] 2020-02-09 01:31
docutils-0.16 was released in this January. So it's time to support!

In addition, @shimizukawa made a good extension to build OGP info from content.
https://sphinx-users.jp/cookbook/ogp/index.html

I thought:

* Allow to configure global (default) OGP info via conf.py
* Allow to override OGP info via docinfo of each document
* Collect OGP info dynamically from its content (if needed)

**Comment by shimizukawa** [comment] 2020-02-09 02:26
Sounds good!

The OGP extension repository is here: https://github.com/sphinx-contrib/ogp

**Comment by Daltz333** [comment] 2020-06-13 21:53
Any update on this @tk0miya ? I've made an issue on the OGP extension repo but no response yet.

**Comment by Daltz333** [comment] 2020-07-01 02:27
I have published https://pypi.org/project/sphinxext-opengraph/ on PyPI in the meantime.

**Comment by tk0miya** [comment] 2020-07-18 05:02
I did it in #7974!

**Comment by tk0miya** [comment] 2020-12-20 09:46
Now OGP feature has been provided by https://pypi.org/project/sphinxext-opengraph/. So it is no longer needed to implement it on Sphinx core side. I'm closing this now.

**Closed as completed by tk0miya** 2020-12-20 09:46 UTC
Labels: builder:html, type:proposal
