### ISSUE TITLE
**kwargs in docstrings leads to 

### ISSUE THREAD

**Issue by waprin** [sphinx-doc/sphinx#2869] opened 2016-08-18 18:49 UTC
Putting **kwargs in :param docstring leads to:

WARNING: Inline literal start-string without end-string.

http://stackoverflow.com/questions/30454549/a-literal-in-restructuredtext

Couldn't' find this when searching for it sorry if I missed it. Any existing discussion on best practices to avoid this or suggestions on how to fix it?

**Comment by tk0miya** [comment] 2018-02-03 01:01
I think reST spec might help you. 
http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#escaping-mechanism

Personally, I don't use `*` and `**` for param notations.

**Comment by tk0miya** [comment] 2018-05-19 05:32
I'm closing this now because this is not a bug.
Thanks,

**Closed as completed by tk0miya** 2018-05-19 05:32 UTC
Labels: type:question, markup
