### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'Pygments>=2.0' distribution was not found and is required by Sphinx

### ISSUE THREAD

**Issue by PandaWuu** [sphinx-doc/sphinx#7987] opened 2020-07-20 02:40 UTC
**Describe the bug**
pkg_resources.DistributionNotFound: The 'Pygments>=2.0' distribution was not found and is required by Sphinx

**To Reproduce**
sphinx-build --version
Traceback (most recent call last):
pkg_resources.DistributionNotFound: The 'Pygments>=2.0' distribution was not found and is required by Sphinx

Actually, i have installed a 2.0.2 python-Pygments：
**yum list python-Pygments**
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
Installed Packages
**python-Pygments.noarch   2.0.2-1.1** 

So i installed pygments is mismatched package?

**Expected behavior**
sphinx-build --version run success

**Comment by PandaWuu** [comment] 2020-07-20 02:48
sphinx version 1.3.6

yum list python-sphinx
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
Installed Packages
python-Sphinx.noarch                                                                                  1.3.6-31.2

**Comment by PandaWuu** [comment] 2020-07-20 02:59
when i installed a 2.1 python-Pygments, command run success

**Comment by tk0miya** [comment] 2020-07-20 14:50
Good to know. I guess your problem was installation trouble, not a bug of Sphinx. So I might not answer to you because I'm not good at RedHat families. closing now.

**Closed as completed by tk0miya** 2020-07-20 14:50 UTC
Labels: type:question
