### ISSUE TITLE
Seem to be having issues using `edit_on_github`

### ISSUE THREAD

**Issue by cnobile2012** [sphinx-doc/sphinx#2506] opened 2016-04-30 05:15 UTC
I get a traceback when I try to create the html. This has happened on two different project the other one was with Python 2.7.

```
# Sphinx version: 1.4.1
# Python version: 3.4.3 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:
#   writing output... [ 70%] index
#   writing output... [ 80%] installation
#   writing output... [ 90%] modules
#   writing output... [100%] overview
#   
#   generating indices...
#   genindex
#   py-modindex
#   
#   highlighting module code... [ 11%] django_pam.accounts.forms
# Loaded extensions:
#   sphinx.ext.todo (1.4.1) from /home/cnobile/.virtualenvs/pam3/lib/python3.4/site-packages/sphinx/ext/todo.py
#   sphinx.ext.autodoc (1.4.1) from /home/cnobile/.virtualenvs/pam3/lib/python3.4/site-packages/sphinx/ext/autodoc.py
#   edit_on_github (unknown version) from /home/cnobile/src/django/django_pam/docs/source/_ext/edit_on_github.py
#   alabaster (0.7.7) from /home/cnobile/.virtualenvs/pam3/lib/python3.4/site-packages/alabaster/__init__.py
#   sphinx.ext.viewcode (1.4.1) from /home/cnobile/.virtualenvs/pam3/lib/python3.4/site-packages/sphinx/ext/viewcode.py
#   sphinx.ext.githubpages (1.4.1) from /home/cnobile/.virtualenvs/pam3/lib/python3.4/site-packages/sphinx/ext/githubpages.py
#   sphinx.ext.coverage (1.4.1) from /home/cnobile/.virtualenvs/pam3/lib/python3.4/site-packages/sphinx/ext/coverage.py
Traceback (most recent call last):
  File "/home/cnobile/.virtualenvs/pam3/lib/python3.4/site-packages/sphinx/cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "/home/cnobile/.virtualenvs/pam3/lib/python3.4/site-packages/sphinx/application.py", line 287, in build
    self.builder.build_update()
  File "/home/cnobile/.virtualenvs/pam3/lib/python3.4/site-packages/sphinx/builders/__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "/home/cnobile/.virtualenvs/pam3/lib/python3.4/site-packages/sphinx/builders/__init__.py", line 325, in build
    self.finish()
  File "/home/cnobile/.virtualenvs/pam3/lib/python3.4/site-packages/sphinx/builders/html.py", line 463, in finish
    self.finish_tasks.add_task(self.gen_additional_pages)
  File "/home/cnobile/.virtualenvs/pam3/lib/python3.4/site-packages/sphinx/util/parallel.py", line 40, in add_task
    res = task_func()
  File "/home/cnobile/.virtualenvs/pam3/lib/python3.4/site-packages/sphinx/builders/html.py", line 489, in gen_additional_pages
    self.handle_page(pagename, context, template)
  File "/home/cnobile/.virtualenvs/pam3/lib/python3.4/site-packages/sphinx/builders/html.py", line 798, in handle_page
    templatename, ctx, event_arg)
  File "/home/cnobile/.virtualenvs/pam3/lib/python3.4/site-packages/sphinx/application.py", line 540, in emit_firstresult
    for result in self.emit(event, *args):
  File "/home/cnobile/.virtualenvs/pam3/lib/python3.4/site-packages/sphinx/application.py", line 536, in emit
    results.append(callback(self, *args))
  File "/home/cnobile/src/django/django_pam/docs/source/_ext/edit_on_github.py", line 31, in html_page_context
    path = os.path.relpath(doctree.get('source'), app.builder.srcdir)
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by tk0miya** [comment] 2016-05-28 08:23
Is `edit_on_github` you said downloaded from https://gist.github.com/mgedmin/6052926 ?

It seems the module has conflicted with `sphinx.ext.viewcode`.
`_module/index.html` is generated as a index of modules if you use `sphinx.ext.viewcode`. But it causes the error in `edit_on_github` because the page does not have doctree.

**Comment by cnobile2012** [comment] 2016-05-28 13:27
Yes that's the link to the code I used. However, as it turns out
readthedocs.io automatically adds an "Edit on GitHub" link, so I'm just
using what they give me now--it's much easier.

On Sat, May 28, 2016 at 4:23 AM, Takeshi KOMIYA notifications@github.com
wrote:

> Reopened #2506 https://github.com/sphinx-doc/sphinx/issues/2506.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/sphinx-doc/sphinx/issues/2506#event-675151461, or mute
> the thread
> https://github.com/notifications/unsubscribe/AB4UTZvU_7xDvTHCX5zIwoZu4AwURsKNks5qF_uegaJpZM4ITVS-
> .

## 

---

Carl J. Nobile (Software Engineer)

## carl.nobile@gmail.com

**Comment by tk0miya** [comment] 2016-05-28 15:18
This is not a bug of Sphinx, so I close this now.
Thanks,

**Closed as completed by tk0miya** 2016-05-28 15:18 UTC
Labels: extensions
