### ISSUE TITLE
Using multiple return values in Google-style docstrings

### ISSUE THREAD

**Issue by fzalkow** [sphinx-doc/sphinx#9119] opened 2021-04-20 09:29 UTC
When using NumPy-style docstrings, I can document multiple return values. Let us consider the following function as an example (**version 1**):

```Python
def foo(a, b):
    """Function

    Parameters
    ----------
    a : float
        First number

    b : float
        Second number

    Returns
    -------
    result_sum : float
        Sum of numbers

    result_prod : float
        Product of numbers
    """
    result_sum = a + b
    result_prod = a * b
    return result_sum, result_prod
```

When using autodoc, napoleon, and the rtd theme, the API documentation is rendered as follows:

![Screenshot from 2021-04-20 10-54-09](https://user-images.githubusercontent.com/5499717/115368986-ec4d8800-a1c7-11eb-979a-c81ea83688fa.png)

I would like to obtain the same result using Google-style docstrings. The Google-style version of the docstring looks as follows (**version 2**):

```Python
def foo(a, b):
    """Function

    Args:
        a (float): First number
        b (float): Second number

    Returns:
        result_sum (float): Sum of numbers
        result_prod (float): Product of numbers
    """
    result_sum = a + b
    result_prod = a * b
    return result_sum, result_prod
```

However, the rendering of this docstring is messed up. It does not seem to be recognized that there are two return values instead of a single one. 

![Screenshot from 2021-04-20 10-46-34](https://user-images.githubusercontent.com/5499717/115369367-50704c00-a1c8-11eb-9181-e477c386b732.png)

There are two related StackOverflow questions ([[1]](https://stackoverflow.com/questions/31413955/sphinx-napoleon-extension-document-multiple-return-arguments-with-google-style), [[2]](https://stackoverflow.com/questions/29221551/can-sphinx-napoleon-document-function-returning-multiple-arguments)), where some users recommend using a docstring in the following style (**version 3**):

```Python
def foo(a, b):
    """Function

    Args:
        a (float): First number
        b (float): Second number

    Returns:
        tuple containing

        - result_sum (float): Sum of numbers
        - result_prod (float): Product of numbers
    """
    result_sum = a + b
    result_prod = a * b
    return result_sum, result_prod
```

This docstring is rendered as follows:

![Screenshot from 2021-04-20 10-51-25](https://user-images.githubusercontent.com/5499717/115370124-0cca1200-a1c9-11eb-883d-3d5782feeaff.png)

However, I feel that there is a semantic difference between version 1 and version 3. Version 1 documents that there are two return values. Version 3 documents that there is a single return value (a tuple). Although both perspectives are the same from a technical point of view, the versions have different flavors. Furthermore, the formatting is missing in version 3 (bold return value name, italic return value type).

I would like to obtain the same output as in version 1, using clean Google-style docstrings (without messing around too much with the docstring, e.g., `**bold**` formatting in the docstring). I am not sure if the output of version 2 is a bug or if it is intended to be like this.

I use sphinx 4.0.0b1.dev20210414 and sphinx-rtd-theme 0.5.2. Note that the problem also exists when using in-package themes, such as classic or alabasta. (I.e., it is not related to sphinx-rtd-theme).

Many thanks for any help on this issue.

**Comment by fzalkow** [comment] 2021-04-20 11:12
I just found a solution to the problem – I can configure the `Returns` section to behave like the `Args` section with the following option:

```Python
napoleon_custom_sections = [('Returns', 'params_style')]
```

Question to the experts: Do I still adhere to the Google-style docstring convention when using this option?

**Comment by tk0miya** [comment] 2021-04-21 13:28
It seems google style does not define the structure of the "Returns" section. I think it considers the section as a mere text (simple mark-ups).
https://google.github.io/styleguide/pyguide.html#383-functions-and-methods

So I don't know this is really a bug of napoleon because it's not the proper syntax of Google-style.

**Comment by berkdemir** [comment] 2022-01-28 08:05
> Question to the experts: Do I still adhere to the Google-style docstring convention when using this option?

from https://google.github.io/styleguide/pyguide.html

> Do not imitate ‘NumPy style’ (example), which frequently documents a tuple return value as if it were multiple return values with individual names (never mentioning the tuple). Instead, describe such a return value as: “Returns a tuple (mat_a, mat_b), where mat_a is …, and …”.

**Comment by tk0miya** [comment] 2022-01-30 15:05
@berkdemir Thank you for your wisdom! As you mentioned, Google-style does not support the multiple return values explicitly.

So this is not a bug and no reason to support it. Closing.

**Closed as completed by tk0miya** 2022-01-30 15:05 UTC
Labels: closed:wontfix, type:proposal, extensions:napoleon
