### ISSUE TITLE
Exception thrown with some YAML

### ISSUE THREAD

**Issue by treydock** [sphinx-doc/sphinx#8492] opened 2020-11-25 20:08 UTC
**Describe the bug**

```
Exception occurred:
  File "/usr/lib/python3.6/site-packages/jinja2/parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: unexpected '.'
The full traceback has been saved in /tmp/sphinx-err-6qvfz3e9.log, if you want to report the issue to the developers.
```

**To Reproduce**

```
$ git clone https://github.com/OSC/ood-documentation
$ cd ood-documentation
$ docker run --rm -i -t -v "${PWD}:/doc" -v "/tmp:/tmp" -u "$(id -u):$(id -g)" ohiosupercomputer/docker-sphinx sphinx-build --version
sphinx-build 1.8.0
$ docker run --rm -i -t -v "${PWD}:/doc" -v "/tmp:/tmp" -u "$(id -u):$(id -g)" ohiosupercomputer/docker-sphinx make html
```

Add this to a file:

```
.. code-block:: yaml

   process_names:
   - name: ood-pun
     comm:
     - nginx
     - Passenger
     - Passenger NodeA
     - PassengerAgent
     - ruby
    - name: "{{.Comm}}:{{.Username}}"
      cmdline:
      - ".+"
```

**Expected behavior**
I would expect the HTML to be generated.  If I delete this part of above there are no errors:

```
    - name: "{{.Comm}}:{{.Username}}"
      cmdline:
      - ".+"
```

**Your project**
https://osc.github.io/ood-documentation/latest/index.html

Docker build environment: https://github.com/OSC/docker-sphinx

**Environment info**
- OS: [e.g. Unix/Linux/Mac/Win/other with version]
- Python version: [e.g. 3.7.1] 3.6
- Sphinx version: [e.g. 1.8.2] 1.8.0
- Sphinx extensions:  [e.g. sphinx.ext.autodoc, recommonmark]
- Extra tools: [e.g. Browser, tex or something else]

**Additional context**

- [e.g. URL or Ticket]

**Comment by treydock** [comment] 2020-11-25 20:09
Full trace:

```
$ cat /tmp/sphinx-err-_zkvwiwy.log 
# Sphinx version: 1.8.0
# Python version: 3.6.8 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10.1
# Last messages:
#   reading sources... [ 77%] installation/resource-manager/torque
#   
#   reading sources... [ 78%] installation/start-apache
#   
#   reading sources... [ 79%] issues/overview
#   
#   reading sources... [ 80%] monitoring
#   
#   reading sources... [ 80%] monitoring/prometheus
#   
# Loaded extensions:
#   sphinx.ext.mathjax (1.8.0) from /usr/lib/python3.6/site-packages/sphinx/ext/mathjax.py
#   alabaster (0.7.12) from /usr/lib/python3.6/site-packages/alabaster/__init__.py
#   sphinx.ext.githubpages (1.8.0) from /usr/lib/python3.6/site-packages/sphinx/ext/githubpages.py
#   sphinxcontrib.httpdomain (unknown version) from /usr/lib/python3.6/site-packages/sphinxcontrib/httpdomain.py
#   sphinxcontrib.plantuml (unknown version) from /usr/lib/python3.6/site-packages/sphinxcontrib/plantuml.py
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/sphinx/cmd/build.py", line 304, in build_main
    app.build(args.force_all, filenames)
  File "/usr/lib/python3.6/site-packages/sphinx/application.py", line 341, in build
    self.builder.build_update()
  File "/usr/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 347, in build_update
    len(to_build))
  File "/usr/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 360, in build
    updated_docnames = set(self.read())
  File "/usr/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 468, in read
    self._read_serial(docnames)
  File "/usr/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 490, in _read_serial
    self.read_doc(docname)
  File "/usr/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 534, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/usr/lib/python3.6/site-packages/sphinx/io.py", line 318, in read_doc
    pub.publish()
  File "/usr/lib/python3.6/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/usr/lib/python3.6/site-packages/docutils/readers/__init__.py", line 71, in read
    self.input = self.source.read()
  File "/usr/lib/python3.6/site-packages/sphinx/io.py", line 255, in read
    inputstring = SphinxBaseFileInput.read(self)
  File "/usr/lib/python3.6/site-packages/sphinx/io.py", line 192, in read
    self.app.emit('source-read', self.env.docname, arg)
  File "/usr/lib/python3.6/site-packages/sphinx/application.py", line 510, in emit
    return self.events.emit(event, self, *args)
  File "/usr/lib/python3.6/site-packages/sphinx/events.py", line 80, in emit
    results.append(callback(*args))
  File "/doc/source/conf.py", line 399, in rstjinja
    rendered = jinja_env.from_string(src).render(doc_context)
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 880, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<unknown>", line 153, in template
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/usr/lib/python3.6/site-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/usr/lib/python3.6/site-packages/jinja2/parser.py", line 875, in subparse
    add_data(self.parse_tuple(with_condexpr=True))
  File "/usr/lib/python3.6/site-packages/jinja2/parser.py", line 620, in parse_tuple
    args.append(parse())
  File "/usr/lib/python3.6/site-packages/jinja2/parser.py", line 432, in parse_expression
    return self.parse_condexpr()
  File "/usr/lib/python3.6/site-packages/jinja2/parser.py", line 437, in parse_condexpr
    expr1 = self.parse_or()
  File "/usr/lib/python3.6/site-packages/jinja2/parser.py", line 450, in parse_or
    left = self.parse_and()
  File "/usr/lib/python3.6/site-packages/jinja2/parser.py", line 459, in parse_and
    left = self.parse_not()
  File "/usr/lib/python3.6/site-packages/jinja2/parser.py", line 470, in parse_not
    return self.parse_compare()
  File "/usr/lib/python3.6/site-packages/jinja2/parser.py", line 474, in parse_compare
    expr = self.parse_math1()
  File "/usr/lib/python3.6/site-packages/jinja2/parser.py", line 496, in parse_math1
    left = self.parse_concat()
  File "/usr/lib/python3.6/site-packages/jinja2/parser.py", line 507, in parse_concat
    args = [self.parse_math2()]
  File "/usr/lib/python3.6/site-packages/jinja2/parser.py", line 517, in parse_math2
    left = self.parse_pow()
  File "/usr/lib/python3.6/site-packages/jinja2/parser.py", line 528, in parse_pow
    left = self.parse_unary()
  File "/usr/lib/python3.6/site-packages/jinja2/parser.py", line 546, in parse_unary
    node = self.parse_primary()
  File "/usr/lib/python3.6/site-packages/jinja2/parser.py", line 583, in parse_primary
    self.fail("unexpected '%s'" % describe_token(token), token.lineno)
  File "/usr/lib/python3.6/site-packages/jinja2/parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: unexpected '.'
```

**Comment by tk0miya** [comment] 2020-11-28 02:17
On my local, the error is not reproduced. I used the latest Sphinx for the test. I guess this is already resolved. Could you check the error still happens in the latest Sphinx?

**Comment by treydock** [comment] 2020-11-30 15:03
I tried v3.3.1 and get a different error:

```
sphinx-build -b html -d build/doctrees  -W source build/html
Running Sphinx v3.3.1
/doc/source/conf.py:404: RemovedInSphinx40Warning: The app.add_stylesheet() is deprecated. Please use app.add_css_file() instead.
  app.add_stylesheet('css/custom.css')
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 130 source files that are out of date
updating environment: [new config] 130 added, 0 changed, 0 removed
reading sources... [ 80%] monitoring/prometheus                                                                   
Extension error:
Handler <function rstjinja at 0x7f69245e1dc0> for event 'source-read' threw an exception (exception: unexpected '.')
make: *** [Makefile:53: html] Error 2
```

This is the snipped causing the failure:

```
.. code-block:: yaml

   process_names:
   - name: ood-pun
     comm:
     - nginx
     - Passenger
     - Passenger NodeA
     - PassengerAgent
     - ruby
   - name: "{{.Comm}}:{{.Username}}"
     cmdline:
     - ".+"
```

If I remove part and just have the following there is no error:

```
.. code-block:: yaml

   process_names:
   - name: ood-pun
     comm:
     - nginx
     - Passenger
     - Passenger NodeA
     - PassengerAgent
     - ruby
```

**Comment by tk0miya** [comment] 2020-12-12 10:04
```
Handler <function rstjinja at 0x7f69245e1dc0> for event 'source-read' threw an exception (exception: unexpected '.')
```

It seems the error was raised inside an event handler named `rstjinja`. And it is not a part of Sphinx-core. Do you know where it came from? I guess it is a part of 3rd party extension.

**Comment by tk0miya** [comment] 2021-01-23 08:53
It seems this is not a bug of Sphinx. Closing.

**Closed as completed by tk0miya** 2021-01-23 08:53 UTC
Labels: type:bug, builder:html
