### ISSUE TITLE
A file named home.rst in a numbered toctree does not get a number in HTML 

### ISSUE THREAD

**Issue by Znni** [sphinx-doc/sphinx#3142] opened 2016-11-10 13:03 UTC
I have an index.rst with a toctree:

.. toctree::
   :glob:
   :numbered:
   :maxdepth: 2
   
   some/thing
   something/else
   userguide/userguide

Then in my userguide/userguide.rst I have another toctree:

.. toctree::
   :glob:
   :numbered:
   
   home/home
   other/things

I build the project with sphinx and the resulting toctree in HTML contains something like this:

...
5. Fifth header

- Home category
- 5.1. Subheader 1
- 5.2. Subheader 2

...

"Home category" should have number 5.1, but it is completely without a number.

Changing the filename from home.rst to something else, e.g. foobar.rst and changing the reference in userguide/userguide.rst to home/foobar.rst fixes the problem and "home category" is correctly numbered as 5.1.

Is "home" a reserved keyword in some system or what causes this problem?

**Comment by tk0miya** [comment] 2016-11-12 02:02
No, "home" is not a reserved and special keyword.
Could you show me small and reproducible example?

**Comment by tk0miya** [comment] 2016-11-24 11:45
Now I close this.
Please reopen if you still have a problem.

**Comment by Znni** [comment] 2016-12-07 07:15
Sorry for the delay. Here is a reproducible example: [SphinxHome.zip](https://github.com/sphinx-doc/sphinx/files/635885/SphinxHome.zip)

I used Sphinx 1.4.8. to generate the html version.

In index.html, toctree item "Home things" (referencing home.rst) should have a a number, but it does not have one. Changing the name from home.rst to something else fixes the problem and a number is given to "Home things" (remember to change the reference to the new name of home.rst in userguide.rst, too).

Please reopen the case, I cannot do that myself.

**Comment by tk0miya** [comment] 2016-12-07 08:17
Reopened to investigate.
I'll take a look later. (maybe in this weekend)

**Comment by tk0miya** [comment] 2016-12-17 08:30
I got it. You'd used numbered toctree with nested.
It causes this problem.
Could you remove `:numbered:` option from child toctree directive?

**Comment by Znni** [comment] 2016-12-21 08:06
Yes, removing `:numbered:` from home.rst fixes the problem. Should I not use several numbered toctrees in a nested manner? Anyway, I don't understand why renaming home.rst to e.g. homeindex.rst fixes the problem, too.

**Comment by tk0miya** [comment] 2017-01-02 16:16
>Should I not use several numbered toctrees in a nested manner? 

Sphinx assigns section numbers to each "numbered" toctree::
```
.. toctree::
   :numbered:

   part1/section1  # => 1.1
   part1/section2  # => 1.2

.. toctree::
   :numbered:

   part2/section1  # => 1.1
   part2/section2  # => 1.2
```
So toctrees are expected as not nested.

>Anyway, I don't understand why renaming home.rst to e.g. homeindex.rst fixes the problem, too.

It was caused by order by numbering process. And its order is not controlled by Sphinx.
The renaming might change the order in your case.

Anyway, I just added warning on nested numbered toctree detected.

**Comment by tk0miya** [comment] 2017-01-08 04:38
I close this now because this is not a bug.
Thank you for reporting.

**Closed as completed by tk0miya** 2017-01-08 04:38 UTC
Labels: type:question, internals:toctree
