### ISSUE TITLE
no library called "cairo-2" was found  on MacOS-12.0.1

### ISSUE THREAD

**Issue by jijingg** [sphinx-doc/sphinx#10072] opened 2022-01-09 05:06 UTC
### Describe the bug

```
# Sphinx version: 4.1.2
# Python version: 3.9.9 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 3.0.3
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/Users/xxx/nutstore/gitlab/docs/SpinalDoc-RTD/.venv/lib/python3.9/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/Users/xxx/nutstore/gitlab/docs/SpinalDoc-RTD/.venv/lib/python3.9/site-packages/sphinx/application.py", line 237, in __init__
    self.setup_extension(extension)
  File "/Users/xxx/nutstore/gitlab/docs/SpinalDoc-RTD/.venv/lib/python3.9/site-packages/sphinx/application.py", line 393, in setup_extension
    self.registry.load_extension(self, extname)
  File "/Users/xxx/nutstore/gitlab/docs/SpinalDoc-RTD/.venv/lib/python3.9/site-packages/sphinx/registry.py", line 429, in load_extension
    mod = import_module(extname)
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/xxx/nutstore/gitlab/docs/SpinalDoc-RTD/.venv/lib/python3.9/site-packages/sphinxcontrib/wavedrom.py", line 15, in <module>
    from .wavedrom_render_image import render_wavedrom_image
  File "/Users/xxx/nutstore/gitlab/docs/SpinalDoc-RTD/.venv/lib/python3.9/site-packages/sphinxcontrib/wavedrom_render_image.py", line 6, in <module>
    import cairosvg
  File "/Users/xxx/nutstore/gitlab/docs/SpinalDoc-RTD/.venv/lib/python3.9/site-packages/cairosvg/__init__.py", line 26, in <module>
    from . import surface  # noqa isort:skip
  File "/Users/xxx/nutstore/gitlab/docs/SpinalDoc-RTD/.venv/lib/python3.9/site-packages/cairosvg/surface.py", line 9, in <module>
    import cairocffi as cairo
  File "/Users/xxx/nutstore/gitlab/docs/SpinalDoc-RTD/.venv/lib/python3.9/site-packages/cairocffi/__init__.py", line 48, in <module>
    cairo = dlopen(
  File "/Users/xxx/nutstore/gitlab/docs/SpinalDoc-RTD/.venv/lib/python3.9/site-packages/cairocffi/__init__.py", line 45, in dlopen
    raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': dlopen(libcairo.so.2, 0x0002): tried: '/opt/homebrew/lib/libcairo.so.2' (no such file), 'libcairo.so.2' (no such file), '/usr/local/lib/libcairo.so.2' (no such file), '/usr/lib/libcairo.so.2' (no such file), '/Users/xxx/nutstore/gitlab/docs/SpinalDoc-RTD/libcairo.so.2' (no such file), '/usr/local/lib/libcairo.so.2' (no such file), '/usr/lib/libcairo.so.2' (no such file)
cannot load library 'libcairo.2.dylib': dlopen(libcairo.2.dylib, 0x0002): tried: '/opt/homebrew/lib/libcairo.2.dylib' (no such file), 'libcairo.2.dylib' (no such file), '/usr/local/lib/libcairo.2.dylib' (no such file), '/usr/lib/libcairo.2.dylib' (no such file), '/Users/xxx/nutstore/gitlab/docs/SpinalDoc-RTD/libcairo.2.dylib' (no such file), '/usr/local/lib/libcairo.2.dylib' (no such file), '/usr/lib/libcairo.2.dylib' (no such file)
cannot load library 'libcairo-2.dll': dlopen(libcairo-2.dll, 0x0002): tried: '/opt/homebrew/lib/libcairo-2.dll' (no such file), 'libcairo-2.dll' (no such file), '/usr/local/lib/libcairo-2.dll' (no such file), '/usr/lib/libcairo-2.dll' (no such file), '/Users/xxx/nutstore/gitlab/docs/SpinalDoc-RTD/libcairo-2.dll' (no such file), '/usr/local/lib/libcairo-2.dll' (no such file), '/usr/lib/libcairo-2.dll' (no such file)   
```

### How to Reproduce

```
$ git clone git@github.com:SpinalHDL/SpinalDoc-RTD.git
$ cd SpinalDoc-RTD
$ python3 -m venv .venv
$ source .venv/bin/activate
$ pip install -r requiremets.txt
$ make html      
```

### Your project

https://github.com/SpinalHDL/SpinalDoc-RTD

### OS

macOS 12.0.1 (21A559)  Darwin 21.1.0

### Python version

3.9.9

### Sphinx version

 4.1.2

### Additional context
```
(.venv) ➜  SpinalDoc-RTD git:(master) pip list
Package                       Version
----------------------------- -----------
alabaster                     0.7.12
attrdict                      2.0.1
Babel                         2.9.1
cairocffi                     1.3.0
CairoSVG                      2.5.2
certifi                       2021.10.8
cffi                          1.15.0
charset-normalizer            2.0.10
cssselect2                    0.4.1
defusedxml                    0.7.1
docutils                      0.16
idna                          3.3
imagesize                     1.3.0
Jinja2                        3.0.3
MarkupSafe                    2.0.1
packaging                     21.3
Pillow                        9.0.0
pip                           21.3.1
pycparser                     2.21
Pygments                      2.11.2
pyparsing                     3.0.6
pytz                          2021.3
requests                      2.27.1
setuptools                    59.0.1
six                           1.16.0
snowballstemmer               2.2.0
Sphinx                        4.1.2
sphinx-multiversion           0.2.4
sphinx-rtd-theme              0.5.2
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
sphinxcontrib-wavedrom        3.0.1
svgwrite                      1.4.1
tinycss2                      1.1.1
urllib3                       1.26.8
wavedrom                      2.0.3.post2
webencodings                  0.5.1
xcffib                        0.11.1
```

**Comment by tk0miya** [comment] 2022-01-09 14:53
It seems sphinxcontrib-wavedrom requires to install Cairo library. Did you try it?
```
  File "/Users/xxx/nutstore/gitlab/docs/SpinalDoc-RTD/.venv/lib/python3.9/site-packages/sphinxcontrib/wavedrom.py", line 15, in <module>
    from .wavedrom_render_image import render_wavedrom_image
  File "/Users/xxx/nutstore/gitlab/docs/SpinalDoc-RTD/.venv/lib/python3.9/site-packages/sphinxcontrib/wavedrom_render_image.py", line 6, in <module>
    import cairosvg
```

Anyway, this is not a bug of Sphinx itself. So I'm closing this.

**Closed as completed by tk0miya** 2022-01-09 14:53 UTC
Labels: type:question

**Comment by jijingg** [comment] 2022-01-10 17:48
thanks, solved ,  mark for others 
On Mac OS X using homebrew
```
brew install cairo
```
ref: https://stackoverflow.com/questions/28211418/python-oserror-cannot-load-library-libcairo-so-2/35880155#35880155
