### ISSUE TITLE
autosummary complains when identifiers ends with _

### ISSUE THREAD

**Issue by xcriptus** [sphinx-doc/sphinx#2387] opened 2016-03-19 20:32 UTC
Hi
It seems that there is a bug in the autosummary extension: when a parameter ends with an underscore (e.g. `_a`), then autosummary raises the following error:

```
<autosummary>:1: ERROR: Unknown target name: "a".
```

Fortunately, sphinx continues, so this is not a major problem. I've looked in already reported bug but have not found it, so ... (the closest one might be #1462(?)).

BTW thanks for this wonderful documentation generator !!!

**Comment by tk0miya** [comment] 2020-04-24 13:46
Sorry for the very late response. Unfortunately, I can't reproduce the error. So I'm closing this now. Please feel free to reopen if you still have this problem.
Thanks,

**Closed as completed by tk0miya** 2020-04-24 13:46 UTC
Labels: extensions:autosummary
