### ISSUE TITLE
On my machine ":ref:" does not consider "include" (any way to just compile files included in the toc tree?)

### ISSUE THREAD

**Issue by tonyriverms** [sphinx-doc/sphinx#5046] opened 2018-06-05 17:27 UTC
Subject: two files

file1.rst

```
discussion

.. include:: file2.rst

discussion

```

file2.rst
```
.. _some_anchor:

blabla...

blabla...

using :ref:`Title <some_anchor>` for the discussion, ...

continue the discussion

```

in the index.rst, I have

```
.. toctree::
   :maxdepth: 2
   :caption: Contents:
   :numbered:

   file1.rst
```

After build, if I click on the link in **file1.html**, it actually jumps to **file2.html** where the anchor is defined, but **it is expected to jump to the anchor in file1.html**.

### Environment info
- OS: Win
- Python version: 3.6
- Sphinx version: 1.7.5

**Comment by tonyriverms** [comment] 2018-06-05 23:07
See here. It looks sphinx-build go through all files that cause duplication. https://stackoverflow.com/questions/39738852/duplicate-index-warning-on-sphinx-build-how-do-i-include-a-file-without-indexin

**Possible solution**:  any way to just compile files included in the toc tree?

**Comment by tk0miya** [comment] 2018-06-06 13:22
Sphinx processes all of `.rst` files. So please rename included files to `.txt` or other extension. Or please use `excluded_files` configuration to skip the processing.

**Comment by tk0miya** [comment] 2018-06-20 16:38
I'm closing this now because this is not a bug of Sphinx.
Thanks,

**Closed as completed by tk0miya** 2018-06-20 16:38 UTC
Labels: type:question
