### ISSUE TITLE
make docs compilation failed

### ISSUE THREAD

**Issue by mrigendrachaubey** [sphinx-doc/sphinx#6269] opened 2019-04-08 07:24 UTC
**Bug**

make docs command fails with below repository,

Get the source code, which is a fork of linux lab repository,

git clone https://github.com/mrigendrachaubey/linux.git

**To Reproduce**

cd linux/tools/labs

make docs

**Expected behavior**

Docs should build without errors and output in Documentation/output

**Environment info**

- OS: ubuntu 16.04 LTS
- Python version: Python 2.7.12
- Sphinx version: Sphinx (sphinx-build) 1.6.7

**Failure log**

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
/home/mrigendra.chaubey/github/linux_lab/linux/Documentation/teaching/labs/deferred_work.rst:775: WARNING: undefined label: ioctl (if the link has no caption the label must precede a section header)
/home/mrigendra.chaubey/github/linux_lab/linux/Documentation/teaching/labs/deferred_work.rst:888: WARNING: undefined label: waiting-queues (if the link has no caption the label must precede a section header)
/home/mrigendra.chaubey/github/linux_lab/linux/Documentation/teaching/labs/interrupts.rst:729: WARNING: Could not lex literal_block as "shell". Highlighting skipped.
/home/mrigendra.chaubey/github/linux_lab/linux/Documentation/teaching/labs/introduction.rst:367: WARNING: Could not lex literal_block as "bash". Highlighting skipped.
/home/mrigendra.chaubey/github/linux_lab/linux/Documentation/teaching/labs/vm.rst:73: WARNING: Could not lex literal_block as "shell". Highlighting skipped.

Exception occurred:
  File "/home/mrigendra.chaubey/.local/lib/python2.7/site-packages/sphinx/writers/html.py", line 597, in visit_image
    if uri.lower().endswith(('svg', 'svgz')):
AttributeError: 'NoneType' object has no attribute 'lower'
The full traceback has been saved in /tmp/sphinx-err-PtNaFF.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Documentation/Makefile:68: recipe for target 'htmldocs' failed
make[2]: *** [htmldocs] Error 1
Makefile:1479: recipe for target 'htmldocs' failed
make[1]: *** [htmldocs] Error 2
make[1]: Leaving directory '/home/mrigendra.chaubey/github/linux_lab/linux'
Makefile:35: recipe for target 'docs' failed
make: *** [docs] Error 2

**Comment by mrigendrachaubey** [comment] 2019-04-08 10:00
Full Log

 Sphinx version: 1.6.7
# Python version: 2.7.12 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10.1
# Last messages:
#   writing output... [ 22%] labs/device_drivers
#   writing output... [ 27%] labs/device_model
#   writing output... [ 33%] labs/exercises
#   writing output... [ 38%] labs/interrupts
#   writing output... [ 44%] labs/introduction
#   writing output... [ 50%] labs/kernel_api
#   writing output... [ 55%] labs/kernel_modules
#   writing output... [ 61%] labs/memory_mapping
#   writing output... [ 66%] labs/vm
#   writing output... [ 72%] lectures/debugging
# Loaded extensions:
#   kfigure (1.0.0) from /home/mrigendra.chaubey/github/linux_lab/linux/Documentation/sphinx/kfigure.py
#   cdomain (1.0) from /home/mrigendra.chaubey/github/linux_lab/linux/Documentation/sphinx/cdomain.py
#   ditaa (unknown version) from /home/mrigendra.chaubey/github/linux_lab/linux/Documentation/sphinx/ditaa.py
#   kernel_include (1.0) from /home/mrigendra.chaubey/github/linux_lab/linux/Documentation/sphinx/kernel_include.py
#   rstFlatTable (1.0) from /home/mrigendra.chaubey/github/linux_lab/linux/Documentation/sphinx/rstFlatTable.py
#   asciicast (unknown version) from /home/mrigendra.chaubey/github/linux_lab/linux/Documentation/sphinx/asciicast.py
#   alabaster (0.7.12) from /home/mrigendra.chaubey/.local/lib/python2.7/site-packages/alabaster/__init__.pyc
#   sphinx.ext.ifconfig (1.6.7) from /home/mrigendra.chaubey/.local/lib/python2.7/site-packages/sphinx/ext/ifconfig.pyc
#   kerneldoc (1.0) from /home/mrigendra.chaubey/github/linux_lab/linux/Documentation/sphinx/kerneldoc.py
#   sphinx.ext.imgmath (1.6.7) from /home/mrigendra.chaubey/.local/lib/python2.7/site-packages/sphinx/ext/imgmath.pyc
#   hieroglyph (unknown version) from /home/mrigendra.chaubey/.local/lib/python2.7/site-packages/hieroglyph/__init__.pyc
Traceback (most recent call last):
  File "/home/mrigendra.chaubey/.local/lib/python2.7/site-packages/sphinx/cmdline.py", line 306, in main
    app.build(opts.force_all, filenames)
  File "/home/mrigendra.chaubey/.local/lib/python2.7/site-packages/sphinx/application.py", line 339, in build
    self.builder.build_update()
  File "/home/mrigendra.chaubey/.local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 329, in build_update
    'out of date' % len(to_build))
  File "/home/mrigendra.chaubey/.local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 395, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/mrigendra.chaubey/.local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 432, in write
    self._write_serial(sorted(docnames))
  File "/home/mrigendra.chaubey/.local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 441, in _write_serial
    self.write_doc(docname, doctree)
  File "/home/mrigendra.chaubey/.local/lib/python2.7/site-packages/sphinx/builders/html.py", line 596, in write_doc
    self.docwriter.write(doctree, destination)
  File "/home/mrigendra.chaubey/.local/lib/python2.7/site-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/home/mrigendra.chaubey/.local/lib/python2.7/site-packages/sphinx/writers/html.py", line 56, in translate
    self.document.walkabout(visitor)
  File "/home/mrigendra.chaubey/.local/lib/python2.7/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/home/mrigendra.chaubey/.local/lib/python2.7/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/home/mrigendra.chaubey/.local/lib/python2.7/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/home/mrigendra.chaubey/.local/lib/python2.7/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/home/mrigendra.chaubey/.local/lib/python2.7/site-packages/docutils/nodes.py", line 166, in walkabout
    visitor.dispatch_visit(self)
  File "/home/mrigendra.chaubey/.local/lib/python2.7/site-packages/docutils/nodes.py", line 1882, in dispatch_visit
    return method(node)
  File "/home/mrigendra.chaubey/.local/lib/python2.7/site-packages/sphinx/writers/html.py", line 597, in visit_image
    if uri.lower().endswith(('svg', 'svgz')):
AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by tk0miya** [comment] 2019-04-13 02:17
The kernel document is too large. It's tough work to find a cause of crash... Could you make a minimal reproducible example?

**Comment by tk0miya** [comment] 2019-04-13 02:19
>Sphinx version: Sphinx (sphinx-build) 1.6.7

Is this error also happened with 2.0.0? 1.6.7 is a bit old.

**Comment by tk0miya** [comment] 2019-05-28 14:14
I'm closing this now because hard to reproduce.
Feel free to reopen if you can make minimal example.
Thanks,

**Closed as completed by tk0miya** 2019-05-28 14:14 UTC
Labels: type:bug
