### ISSUE TITLE
Python2.6.9 and autodoc cause error on abstractproperty

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1589] opened 2015-01-03 11:35 UTC
## Short version

/path/to/repo/docs/test.py:docstring of repo.test.Foo.bar:14: ERROR: Unexpected indentation.

I have tried python2.6 and python2.7, with this error occurring only on the former. abc.abstractproperty's docstring has not changed between the versions, and it appears to be the cause.  This indicates a version specific parsing error in sphinx.
## Long Version

Consider a simple module we are calling autodoc on:

```
#!python

"""Toy example for bug report."""

from abc import ABCMeta, abstractproperty


class Foo(object):

    """Handles foo things."""

    __metaclass__ = ABCMeta

    @abstractproperty
    def bar(self):
        """Bar must be implemented by Foo subclasses."""
        raise NotImplementedError

```

If you try to build this (on python2.6; On python2.7 it succeeds), you get back an error like:

/path/to/repo/docs/test.py:docstring of repo.test.Foo.bar:14: ERROR: Unexpected indentation.

Removing the `@abstractproperty` makes the issue vanish.  Therefore replacing it with the following should show us what is wrong with abstractproperty:

```
#!python

"""Toy example for bug report."""

from abc import ABCMeta

# Implement abc.abstractproperty manually for docs
class abstractproperty(property):
    """A decorator indicating abstract properties.

    Requires that the metaclass is ABCMeta or derived from it.  A
    class that has a metaclass derived from ABCMeta cannot be
    instantiated unless all of its abstract properties are overridden.
    The abstract properties can be called using any of the normal
    'super' call mechanisms.

    Usage:

        class C:
            __metaclass__ = ABCMeta
            @abstractproperty
            def my_abstract_property(self):
                ...

    This defines a read-only property; you can also define a read-write
    abstract property using the 'long' form of property declaration:

        class C:
            __metaclass__ = ABCMeta
            def getx(self): ...
            def setx(self, value): ...
            x = abstractproperty(getx, setx)
    """
    __isabstractmethod__ = True


class Foo(object):

    """Handles foo things."""

    __metaclass__ = ABCMeta

    @abstractproperty
    def bar(self):
        """Bar must be implemented by Foo subclasses."""
        raise NotImplementedError

```

The same error occurs when the above is built, but on line 15 of abstractproperty's docs.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1589
- Originally reported by: Glen Nelson
- Originally created at: 2014-10-08T19:20:42.876

**Comment by shimizukawa** [comment] 2015-01-03 11:35
_From Takayuki Shimizukawa on 2014-10-09 05:55:24+00:00_

Thanks for a reporting!

Your 'self implemented abstractproperty' sample will reproduces the issue on both of Python-2.6 and 2.7. However I can't reproduce the issue with using `abc.abstractproperty`. I'm using Sphinx-1.2.3 & docutils-0.12 & python-2.6.8 / 2.7.5.

Please let me know which set of versions are you using. If you have a chance, please attach small sample to reproduce the issue. Thanks.

**Comment by shimizukawa** [comment] 2015-01-03 11:35
_From Glen Nelson on 2014-10-09 19:17:44+00:00_

Hi,

I was using:

Sphinx-1.2.3

docutils-0.12

python-2.6.9

python-2.7.5

Included an example, type 'make docs' to create the docs.

On python-2.7.5:

```
#!console

build succeeded.

Build finished. The HTML pages are in _build/html.
```

On python-2.6.9:

```
#!console

Warning, treated as error:
/local/home/nelsog4/git/doc_example/doc_example/__init__.py:docstring of doc_example.Foo.bar:14: ERROR: Unexpected indentation.

make[1]: *** [html] Error 1


```

**Comment by shimizukawa** [comment] 2015-01-03 11:35
_From Glen Nelson on 2014-10-09 19:19:11+00:00_

Update the title to be more correct.

**Comment by tk0miya** [comment] 2016-06-25 09:41
In my short investigation:

I couldn't reproduce the issue using first example too.
And succeeded to reproduce using second one.

I got following error message:

```
/Users/tkomiya/work/tmp/doc/example.py:docstring of example.abstractproperty:15: ERROR: Unexpected indentation.
```

The 15th line of `example.abstractproperty` is here:

```
    Usage:

        class C:
            __metaclass__ = ABCMeta
            @abstractproperty
            def my_abstract_property(self):
                ...    # HERE
```

I don't know this line has unexpected indentation. But, certainly the docstring is not valid reStructured Text. The this usage block is not a code-block like following:

```
                <paragraph>
                    Usage:
                <block_quote>
                    <definition_list>
                        <definition_list_item>
                            <term>
                                class C:
                            <definition>
                                <paragraph>
                                    __metaclass__ = ABCMeta
                                    @abstractproperty
                                    def my_abstract_property(self):
                                <block_quote>
                                    <paragraph>
                                        ...
```

I rewrote the docstring to `Usage::` (uses double colons). Then, the error is cleared.

So I think this is not a bug of sphinx.

**Comment by d6tdev** [comment] 2019-01-12 00:58
For those who are getting to this because readthedocs shows the synatax error, see https://github.com/rtfd/readthedocs.org/issues/1855

**Comment by tk0miya** [comment] 2019-01-12 04:07
As following comment said, it is purely syntax error.
>Looks like you're running your py3 code in a py2 virtualenv. Try setting the correct version in the project admin.

**Comment by tk0miya** [comment] 2019-01-12 04:08
Anyway, there are no updates for this issue. And my conclusion is "this is not a bug of sphinx". So I'm closing this now.
Please let me know if you still get this error.
Thanks,

**Closed as completed by tk0miya** 2019-01-12 04:08 UTC
Labels: type:bug, extensions:autodoc
