### ISSUE TITLE
Different template for the index page

### ISSUE THREAD

**Issue by walikha** [sphinx-doc/sphinx#4619] opened 2018-02-14 15:51 UTC
I am creating documentation site using Sphinx. I would like to create a home/index page that has a completely different style and structure than the actual pages in the site. By default, all Sphinx pages build using the same configured template which has the same style and structure. How can I achieve this?

**Comment by tk0miya** [comment] 2018-02-14 16:37
This is a list of issues for Sphinx, not a forum.
Please move to sphinx-users group
https://groups.google.com/forum/#!forum/sphinx-users

Thanks,

**Comment by tk0miya** [comment] 2018-03-06 15:42
I'm closing this now because this is not a bug of Sphinx.
Thanks,

**Closed as completed by tk0miya** 2018-03-06 15:42 UTC
Labels: type:question
