### ISSUE TITLE
I ran make html on sphinx and appears the error  File "c:\python37\lib\site-packages\astroid\builder.py", line 174, in _data_build     ) from exc astroid.exceptions.AstroidSyntaxError: Parsing Python code failed: invalid syntax (<unknown>, line 21)

### ISSUE THREAD

**Issue by hgasca** [sphinx-doc/sphinx#6039] opened 2019-02-08 15:53 UTC
**Describe the bug**

**To Reproduce**
```
<Paste your command-line here which cause the problem>

$ git clone htps://github.com/.../some_project
$ cd some_project
$ pip install -r requirements.txt
$ cd docs
$ make html SPHINXOPTS="-D language=de"
$ # open _build/html/index and see bla bla
```

**Expected behavior**

**Your project**
Link to your sphinx project, or attach zipped small project sample.

**Screenshots**

**Environment info**
- OS: [e.g. Unix/Linux/Mac/Win/other with version]
- Python version: [e.g. 3.7.1]
- Sphinx version: [e.g. 1.8.2]
- Sphinx extensions:  [e.g. sphinx.ext.autodoc, recommonmark]
- Extra tools: [e.g. Browser, tex or something else]

**Additional context**

- [e.g. URL or Ticket]

**Comment by tk0miya** [comment] 2019-02-08 17:29
Sorry, I can't reproduce your error. Please fill our issue template.
Thanks,

**Comment by tk0miya** [comment] 2019-02-10 17:25
Closing now.
Please post another issue if you're still in problem.

Note: it seems the error is related with astroid extension. So I suppose it would be better to report it to their project.

**Closed as completed** 2019-02-10 17:25 UTC
Labels: type:bug
