### ISSUE TITLE
AttributeError: 'Module_six_moves_urllib_parse' object has no attribute 'urlsplit'

### ISSUE THREAD

**Issue by jputrino** [sphinx-doc/sphinx#2500] opened 2016-04-27 15:53 UTC
Same as #2443, which is closed. Previous reporter said that upgrading six solved his problem, but that doesn't solve it for me (I'm already using six 1.10.0). 

```
# Sphinx version: 1.4
# Python version: 2.7.10 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/sphinx/cmdline.py", line 243, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/Library/Python/2.7/site-packages/sphinx/application.py", line 197, in __init__
    self._init_builder(self.buildername)
  File "/Library/Python/2.7/site-packages/sphinx/application.py", line 269, in _init_builder
    self.emit('builder-inited')
  File "/Library/Python/2.7/site-packages/sphinx/application.py", line 536, in emit
    results.append(callback(self, *args))
  File "/Library/Python/2.7/site-packages/sphinx/ext/intersphinx.py", line 291, in load_mappings
    safe_inv_url = _get_safe_url(inv)
  File "/Library/Python/2.7/site-packages/sphinx/ext/intersphinx.py", line 205, in _get_safe_url
    url, username, _ = _strip_basic_auth(url)
  File "/Library/Python/2.7/site-packages/sphinx/ext/intersphinx.py", line 148, in _strip_basic_auth
    url_parts = parse.urlsplit(url)
AttributeError: 'Module_six_moves_urllib_parse' object has no attribute 'urlsplit'
/var/folders/06/0gyp09193p5632bd177_g2pr0r1ztr/T/sphinx-err-jOQNEb.log (END)
```

Thanks!

**Comment by tk0miya** [comment] 2016-04-27 16:19
To investigate what version you are using, please append following lines into your `conf.py` and run `make html`

```
import six
print "six version:", six.__version__
```

And then, you'll see the version like this:

```
$ make html
../bin/sphinx-build -b html -d _build/doctrees  -T . _build/html
Running Sphinx v1.4.1+
six version: 1.10.0
loading pickled environment... done
...
```

**Comment by jputrino** [comment] 2016-04-27 16:34
(edited)

According to pip, I'm using six 1.10.0:

```
$ pip show six
---
Metadata-Version: 2.0
Name: six
Version: 1.10.0
Summary: Python 2 and 3 compatibility utilities
Home-page: http://pypi.python.org/pypi/six/
Author: Benjamin Peterson
Author-email: benjamin@python.org
Installer: pip
License: MIT
Location: /Library/Python/2.7/site-packages
Requires:
Classifiers:
  Programming Language :: Python :: 2
  Programming Language :: Python :: 3
  Intended Audience :: Developers
  License :: OSI Approved :: MIT License
  Topic :: Software Development :: Libraries
  Topic :: Utilities
```

According to sphinx, it's using six 1.4.1:

```
$ sphinx-build docs/ docs/_build/
Running Sphinx v1.4
six version: 1.4.1
loading pickled environment... done
```

Any ideas why this would be the case?

**Comment by birkenfeld** [comment] 2016-04-27 16:41
Please do as @tk0miya suggested and print the version from within conf.py.

**Comment by jputrino** [comment] 2016-04-27 16:52
I added six>=1.8.0 to my requirements.docs.txt file, then installed the requirements in a venv; that seems to have fixed the problem. I'm still curious about why sphinx was using a different version than that installed, though.

Thanks!

**Comment by tk0miya** [comment] 2016-05-01 05:24
I'm interested in that too. 
The error means that six-1.3.0 or older version was installed into the environment. Because `six.moves.urllib_parse` module is introduced since six-1.4.0.

But it is strange. Now Sphinx-1.4 depends on six-1.4.0 and newer.

Anyway, I close this issue because this is not a bug of sphinx.
But please reopen if you find any infromation to reprocude the issue.

Thank you for reporting.

**Closed as completed by tk0miya** 2016-05-01 05:24 UTC
Labels: type:bug, type:question
