### ISSUE TITLE
Sort IntEnum members by integer value instead of name?

### ISSUE THREAD

**Issue by Huite** [sphinx-doc/sphinx#11782] opened 2023-12-01 12:58 UTC
I was surprised to see how my IntEnums are presented in the API docs generated by sphinx.

This:

```python
class GeneralVerbosity(IntEnum):
    """Level of information printed."""

    SILENT = 0
    ERRORS = 1
    WARNINGS = 2
    DIRECT = 3
    INFORMATION = 4
    STATUS = 5
    DEBUG = 99

```

becomes:

![image](https://github.com/sphinx-doc/sphinx/assets/13662783/d5e22fd4-06cb-455f-8b27-61606e20cf1d)

They are sorted alphabetically by name, but I think I would expect the members to be sorted by the integer value in this case. Especially in this case, where the integer values represent something of the severity, it would be nice to have them ordered from less to more severe (or vice versa).

**Comment by electric-coder** [comment] 2023-12-02 01:15
> They are sorted alphabetically by name

This is the expected default behavior of sorting by variable name, it's equivalent to [`'member-order': 'alphabetical'`](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_member_order) see also [`autodoc_default_options`](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_default_options).

> ##### [`autodoc_member_order`](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_member_order)
>
> The default is alphabetical.

**Comment by electric-coder** [comment] 2023-12-02 01:16
@AA-Turner can be closed as non-issue.

**Comment by electric-coder** [comment] 2023-12-04 09:58
@Huite it could make some sense to special case the `IntEnum` but the problem is it would introduce an inconsistency and exception between `IntEnum` and how all the other datatypes are handled. Thus by special casing any gains would be outweighed by violating the principle of least surprise.

**Comment by picnixz** [comment] 2023-12-24 14:59
Ideally, we should have custom formatters but currently, it's a HUGE function formatting whatever we pass to it. 

For your specific use-case, you can use `autodoc_member_order = 'bysource'` but it would affect everything else. Alternatively, you need to write manually:

```rst
.. autoclass:: YourEnum
   :members: 
   :member-order: bysource
```

**Closed as not planned by picnixz** 2023-12-24 14:59 UTC
