### ISSUE TITLE
:numref: does not resolve to a number when using Sphinx 3.5.4. Similar issue in 5.3.0 We found out that it works in 3.2.1

### ISSUE THREAD

**Issue by kvanapal** [sphinx-doc/sphinx#11475] opened 2023-06-29 00:40 UTC
### Describe the bug

Sphinx 3.5.4 does not resolve :numref: to a number. The same thing builds in 3.2.1
Is there any fix to this problem other than changing the version number?

Below is the error we get in Sphinx==3.5.4. We also get a similar error in Sphinx==5.3.0 but we are still using 3.5.4

![image](https://github.com/sphinx-doc/sphinx/assets/17282016/aefe6146-6e7f-45f9-87ee-b558a5b49f60)

![image](https://github.com/sphinx-doc/sphinx/assets/17282016/6bf0efb1-cfa8-4cc6-9698-d9ff2a3cc5d0)

### How to Reproduce

[numref_works_with_321_not_with_354.zip](https://github.com/sphinx-doc/sphinx/files/11900890/numref_works_with_321_not_with_354.zip)

Download the above zip file.
Unzip and run make html

If you have Sphinx 3.2.1 it works
If you have Sphinx 3.5.4, it throws warnings
We also tried 5.3.0 and, it throws similar warnings as well

### Environment Information

```text
sphinx-build --bug-report is not supported in Sphinx==3.5.4 so below I have pasted pip list

Package                       Version
----------------------------- --------
alabaster                     0.7.13
Babel                         2.11.0
certifi                       2023.5.7
charset-normalizer            2.0.12
colorama                      0.4.5
docutils                      0.16
idna                          3.4
imagesize                     1.4.1
Jinja2                        3.0.3
MarkupSafe                    2.0.1
packaging                     21.3
pip                           21.3.1
Pygments                      2.14.0
pyparsing                     3.0.7
pytz                          2023.3
requests                      2.27.1
setuptools                    39.0.1
snowballstemmer               2.2.0
Sphinx                        3.5.4
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
urllib3                       1.26.16


When we tried with Sphinx==5.3.0 this is what we got


Platform:              win32; (Windows-10-10.0.19041-SP0)
Python version:        3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)])
Python implementation: CPython
Sphinx version:        5.3.0
Docutils version:      0.18.1
Jinja2 version:        3.0.3
```

**Comment by picnixz** [comment] 2023-07-11 08:47
I confirmed that it works properly if you add a caption to your figure (which you should always do technically). The reason why this behaviour changed is because of https://github.com/sphinx-doc/sphinx/issues/6914. It actually makes sense that a figure without a caption (therefore, without a text like "Fig. XXX") does not have a number. Therefore, this is an expected behaviour (see https://github.com/sphinx-doc/sphinx/issues/6914#issuecomment-670921264).

**Comment by picnixz** [comment] 2023-08-15 11:44
Closing the issue since it is now an expected behaviour.

**Closed as not planned by picnixz** 2023-08-15 11:44 UTC
