### ISSUE TITLE
Broken meta property tag in HTML output with numbered toctree in Sphinx 2.3.1

### ISSUE THREAD

**Issue by adswa** [sphinx-doc/sphinx#7104] opened 2020-02-07 13:45 UTC
First: Thanks a lot for Sphinx, it is a wonderful tool!

**Describe the bug**
After upgrading from Sphinx 2.1.2 to Sphinx 2.3.1, I found that the meta property ``og:title`` tag is broken in the generated html tags if the toc tree is numbered.
 Here is how the tag in question looks for one example page with Sphinx 2.1.2:
```html
  <meta property="og:title" content="1. Create a dataset &#8212; The DataLad Handbook">
```
Here is how it looks with Sphinx 2.3.1:
```html
  <meta property="og:title" content="<span class="section-number">1. </span>Create a dataset &#8212; The DataLad Handbook">
```

which leads to this:

![image](https://user-images.githubusercontent.com/29738718/74033227-fbc32580-49b5-11ea-851e-fe51d92b1aad.png)

**To Reproduce**
(I assume the problem is not specific to my individual project, but here is how to build my docs)
```

$ git clone git@github.com:datalad-handbook/book.git
$ cd book
$ pip install -r requirements.txt
$ pip install -e .
$ sudo apt-get install librsvg2-bin
$ cd docs
$ make html
$ # open _build/html/basics/101-101-create.html, top of the page
```

**Your project**
https://github.com/datalad-handbook/book

**Environment info**
- OS: Debian 10 (Buster)
- Python version: 3.7.3
- Sphinx version: 2.3.1]
- Sphinx extensions:  'sphinx.ext.ifconfig',  'sphinx.ext.todo',  'sphinx.ext.intersphinx',
  'sphinx.ext.doctest', ['sphinxcontrib.autorunrecord'](https://github.com/mih/autorunrecord/), 'sphinxcontrib.rsvgconverter',  'sphinxcontrib.plantuml',   ['dataladhandbook_support'](https://github.com/datalad-handbook/book/tree/master/dataladhandbook_support)
- Extra tools: not that I'm aware 

**Additional context**

- Here's the website where the problem shows up at the moment: http://handbook.datalad.org/en/latest/basics/101-101-create.html

Thanks!

**Comment by tk0miya** [comment] 2020-02-07 14:52
How do you mark up the og tag? Is this problem related with some extension? Could you make a minimal example please?

**Comment by adswa** [comment] 2020-02-07 15:39
Hi @tk0miya, I noticed only through your question that this tag exists only because of a custom layout in our project (in [``docs/_templates/layout.html``](https://github.com/datalad-handbook/book/blob/master/docs/_templates/layout.html)):

```html
  <meta property="og:title" content="{{ title }}{{ titlesuffix }}">
```

<details><summary> See the full context of this line </summary>

```html
{%- block extrahead %}
  {# No super() because we want to avoid loading an empty custom.css file #}

  {# <meta name="viewport" content="width=device-width, initial-scale=0.75, maximum-scale=0.75" /> #}

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    div.body {
      min-width: initial;
      max-width: initial;
    }
  </style>

  {% if pagename == 'index' %}
  <link rel="canonical" href="https://handbook.datalad.org/"/>
  <meta property="og:url" content="https://handbook.datalad.org/">
  {% elif pagename == '404' %}
  {# No canonical on our 404 template. #}
  {% else %}
  <link rel="canonical" href="https://handbook.datalad.org/{{ pagename }}/"/>
  <meta property="og:url" content="https://handbook.datalad.org/{{ pagename }}">
  {% endif %}

  <link rel="icon" type="image/png" href="https://media.readthedocs.org/images/favicon.png">

  <meta name="twitter:card" content="summary">
  <meta property="twitter:image" content="https://handbook.datalad.org/_static/social-card.jpg">
  <meta property="og:image" content="https://handbook.datalad.org/_static/social-card.jpg">
  <meta property="og:title" content="{{ title }}{{ titlesuffix }}">
  <meta property="og:type" content="article">
  {%- if metatags is defined %}
  {# FIXME: For some reason the `meta` dict is always empty. Extract the desc from the `metatags` text.  #}
  <meta property="og:description" content="{{ metatags[15:-24] }}">
  {%- endif %}

{% endblock %}

```
</details>

For some reason I thought this tag  would be created by default, but if its our template only that suffers (from, as it seems, the section number being enclosed in ``<span class="section-number">1. </span>`` in Sphinx 2.3.1), please feel free to close this issue :)

**Comment by tk0miya** [comment] 2020-02-08 15:55
Yes, this is side effect of #6613 . But, before the change, HTML tags are shown in `title` variable when header contains inline mark up. IMO, this is not a bug. So I'm closing this.
Thanks,

**Closed as completed by tk0miya** 2020-02-08 15:55 UTC
Labels: type:question, html theme
