### ISSUE TITLE
autoclass always shows all inherited members

### ISSUE THREAD

**Issue by mathiasertl** [sphinx-doc/sphinx#4895] opened 2018-04-23 20:38 UTC
Subject: The autoclass directive always shows all inherited members.

*NOTE:* I know how many people are using this and it's odd that I'm the first (?) to report this. Maybe I'm holding it wrong somehow and just can't find it. I've tried my best to debug the code and I'm fairly sure that this is at least some valid edge case where this is a real bug.

### Problem
- When I document a class with autoclass and pass the `members` option, inherited methods are also included, e.g.

```
class foo(object):
    def x():
        """docs for x"""
        pass

class bar(foo):
    def y():
        """docs for y"""
        pass

# in the .rst file:
.. autoclass:: bar
   :members:
```

will show documentation for ``x``. 

I have traced this to [sphinx.ext.autodoc.Documenter.get_object_members](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/ext/autodoc/__init__.py#L545) which in turn calls `sphinx.ext.autodoc.importer.get_object_members`, which uses `__dict__` as a reference for if a method is inherited or not (in line [204](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/ext/autodoc/importer.py#L204) and [216](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/ext/autodoc/importer.py#L216)). As far as I can tell, `__dict__` also contains inherited members and thus `name in obj_dict` in line 216 is always `True`.

This behavior also occurs when I define the `no-inherited-members` option.

#### Procedure to reproduce the problem

Just generate the documentation from my sphinx project (link see below).

#### Expected results
Only show inherited members when the appropriate options are defined.

It seems like [this ticket](https://stackoverflow.com/a/25959545/5894927) also has some solution. But it looks super-complex for a simple question "did this class or one of its parents define this class?".

### Reproducible project / your project
- github: https://github.com/mathiasertl/xmpp-backends
- sphinx file: https://github.com/mathiasertl/xmpp-backends/blob/master/docs/django.rst
- sphinx generated docs: http://xmpp-backends.readthedocs.io/en/latest/django.html#database-backend

### Environment info
- OS: Linux
- Python version: 3.4 or 3.5
- Sphinx version: 1.7.3

**Comment by mondeja** [comment] 2018-05-01 18:32
You still having this issue? I can't reproduce it.

#### Tested in:
-  [x] Python3.5.5rc1 - Sphinx 1.7.3
-  [x] Python3.5.5rc1 - Sphinx 1.7.4
-  [x] Python3.5.0 - Sphinx 1.7.3
-  [x] Python3.5.0 - Sphinx 1.7.4

**Comment by tk0miya** [comment] 2018-05-02 15:26
I also can't reproduce the error from example foo & bar classes.

>Just generate the documentation from my sphinx project (link see below).

Could you tell me in detail. What inherited member is shown? I've never read your code. So I can't understand what is your problem yet.

**Comment by tk0miya** [comment] 2018-05-20 12:15
I'm closing this because I can't reproduce the error.
Feel free to reopen if you still have this problem.

Thanks,

**Closed as completed by tk0miya** 2018-05-20 12:15 UTC
Labels: type:bug, extensions:autodoc
