### ISSUE TITLE
Problem with installation of gearman

### ISSUE THREAD

**Issue by bartek1234321** [sphinx-doc/sphinx#4276] opened 2017-12-04 20:48 UTC
### Problem
Sphinx version: 
- during installation of gearman below described error occures:

Exception occurred:
  File "/usr/lib/python2.7/dist-packages/sphinx/environment.py", line 1206, in get_doctree
    f = open(doctree_filename, 'rb')
IOError: [Errno 2] No such file or directory: u'/vagrant/gearmand/docs/build/doctrees/libgearman/gearman_return_t.doctree'
The full traceback has been saved in /tmp/sphinx-err-938mlk.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!

#### Procedure to reproduce the problem
```
cd /vagrant/gearman; make or sudo make
```

#### Error logs / results
```
# Sphinx version: 1.3.6
# Python version: 2.7.12 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:
#   }
#   gearman_result_store_integer.3 {
#   }
#   gearman_result_store_string.3 {
#   }
#   gearman_result_store_value.3 {
#   }
#   gearman_result_string.3 {
#   }
#   gearman_continue.3 {
# Loaded extensions:
#   alabaster (0.7.7) from /usr/lib/python2.7/dist-packages/alabaster/__init__.pyc
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "/usr/lib/python2.7/dist-packages/sphinx/application.py", line 267, in build
    self.builder.build_update()
  File "/usr/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 246, in build_update
    self.build(['__all__'], to_build)
  File "/usr/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 322, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/lib/python2.7/dist-packages/sphinx/builders/manpage.py", line 70, in write
    tree = self.env.get_doctree(docname)
  File "/usr/lib/python2.7/dist-packages/sphinx/environment.py", line 1206, in get_doctree
    f = open(doctree_filename, 'rb')
IOError: [Errno 2] No such file or directory: u'/vagrant/gearmand/docs/build/doctrees/libgearman/gearman_return_t.doctree'
```

#### Expected results
install gearman :) 

### Environment info
- OS: Mac + VB + Vagrant (Ubuntu 16.04)
- Python version: 2.7.12
- Sphinx version: 1.3.6 or v1.6.5
- Gearman - tag 1.1.15/16/17

**Comment by tk0miya** [comment] 2017-12-15 16:44
Hi,

I'd like to check this bug, but I can't reproduce it.

>Procedure to reproduce the problem
>
>cd /vagrant/gearman; make or sudo make

Could you tell me the procedure in detail?

**Comment by tk0miya** [comment] 2018-02-12 13:02
ping.
I will close this after a while if no comment more.

**Closed as completed** 2018-02-20 17:35 UTC
Labels: type:question
