### ISSUE TITLE
qemu docs fails with version 3.0.1

### ISSUE THREAD

**Issue by kekePower** [sphinx-doc/sphinx#7457] opened 2020-04-10 19:29 UTC
**Describe the bug**
qemu docs fails to build with version 3.0.1.

```
CONFDIR="/etc/qemu" /usr/bin/sphinx-build-3 -W -b html -D version=4.2.92 -D release="4.2.92 (qemu-5.0.0-0.rc2.0.1.mga8)" -d .doctrees/devel-html /home/iurt/rpmbuild/BUILD/qemu-5.0.0-rc2/docs/devel docs/devel
Running Sphinx v3.0.1
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 14 source files that are out of date
updating environment: [new config] 14 added, 0 changed, 0 removed
reading sources... [ 7%] bitops
reading sources... [ 14%] decodetree
reading sources... [ 21%] index
reading sources... [ 28%] kconfig
reading sources... [ 35%] loads-stores
reading sources... [ 42%] memory
reading sources... [ 50%] migration
reading sources... [ 57%] reset
reading sources... [ 64%] s390-dasd-ipl
reading sources... [ 71%] secure-coding-practices
reading sources... [ 78%] stable-process
reading sources... [ 85%] tcg
reading sources... [ 92%] tcg-plugins
reading sources... [100%] testing

Warning, treated as error:
/home/iurt/rpmbuild/BUILD/qemu-5.0.0-rc2/docs/../include/exec/memory.h:3:Type must be either just a name or a typedef-like declaration.
If just a name:
  Error in declarator or parameters
  Invalid C declaration: Expected identifier in nested name, got keyword: struct [error at 6]
    struct MemoryListener
    ------^
If typedef-like declaration:
  Error in declarator or parameters
  Invalid C declaration: Expected identifier in nested name. [error at 21]
    struct MemoryListener
    ---------------------^

make: *** [Makefile:1095: docs/devel/index.html] Error 2
make: *** Waiting for unfinished jobs....
```

**To Reproduce**
```
CONFDIR="/etc/qemu" /usr/bin/sphinx-build-3 -W -b html -D version=4.2.92 -D release="4.2.92 (qemu-5.0.0-0.rc2.0.1.mga8)" -d .doctrees/devel-html /home/iurt/rpmbuild/BUILD/qemu-5.0.0-rc2/docs/devel docs/devel
```

**Expected behavior**
As far as I know, this worked fine with version 2.4.4.

**Your project**
https://github.com/qemu/qemu/

**Screenshots**
N/A

**Environment info**
- OS: Mageia Cauldron
- Python version: 3.8.1
- Sphinx version: 3.0.1
- Sphinx extensions:  N/A
- Extra tools: N/A

**Additional context**
I found this commit for memory.h that includes the section that faults.
https://github.com/qemu/qemu/commit/5d248213180749e674fbccbacc6ee9c38499abb3#diff-d892cbf314945b44699534cc1de4ebbd

You can see the whole build log here.
https://pkgsubmit.mageia.org/uploads/failure/cauldron/core/release/20200410161120.tv.duvel.699/log/qemu-5.0.0-0.rc2.0.1.mga8/build.0.20200410161338.log

Also reported to qemu.
https://bugs.launchpad.net/qemu/+bug/1872113

**Comment by jakobandersen** [comment] 2020-04-11 12:45
This is an intentional breaking change. The ``c:type`` directive is now only accepting either typedefs or a simple name (to signify a typedef for an unspecified type). There are multiple new directives and roles, including a  ``c:struct`` directive which seems like the most relevant here.

**Comment by pm215** [comment] 2020-04-11 14:51
That's a bit awkward -- non-compatible changes are really painful to deal with as a user, because we need to allow our documentation to be built with a pretty wide range of Sphinx versions (depending on what different distros shipped in different distro releases).

Will the c:struct directive work with older versions of Sphinx ?

**Comment by jakobandersen** [comment] 2020-04-11 15:46
@pm215, indeed it can be very painful, and for Sphinx the breaking changes are only occurring for major versions, such as 3.0. Unfortunately the struct directive is not present in older versions, as the C domain was somewhat basic. Note that technically only the newest version of Sphinx is supported, so I guess few distros are shipping supported versions.

I briefly looked at how qemu generates documentation, and if I understand correctly the issue is in how kernel-doc translates in-source comments. Assuming kernel-doc would be updated, it should be possible to invoke different versions of it based on the Sphinx version.

**Comment by pm215** [comment] 2020-04-11 16:05
For instance the current python3-sphinx in Ubuntu Bionic (current long-term-stable release) is 1.6.7; we definitely need to support at least that far back, maybe a little further. It looks like you produce major versions on a faster cycle than they will percolate through distributions, so it's going to be pretty common that users are still using versions that from upstream's point of view are one or two 'major versions' back.

You're right that the fix here is going to be to make the kernel-doc script handle both the old and new Sphinx syntax and have the Sphinx plugin that invokes it tell it which flavour of the syntax it needs to emit based on which Sphinx version is running. (I've also discovered a bug in the kernel-doc script which is definitely an error on our side where it's emitting invalid syntax for a c:function directive: older Sphinxes didn't complain about it but 3.0 does.)

**Comment by jakobandersen** [comment] 2020-04-11 16:15
That's a quite old version. The positive part is that the new version should fix some long-standing bugs, and much more easily allow for future (non-breaking) improvements.

**Comment by pm215** [comment] 2020-04-18 10:22
We've now put the workaround for this breakage into QEMU's documentation/configure machinery/etc, so we can build with Sphinx 3.0. The Linux kernel docs look like they're going to need further work; the kernel doc maintainer's comment (https://www.spinics.net/lists/linux-doc/msg77996.html) was "I really wish they wouldn't break things like that...".

So I guess you can close this bug report, but please: strong strong request that you don't make breaking changes to markup syntax, even across major Sphinx versions. They're just really painful to deal with for people trying to use the tool. TBH it's one of the things that makes me half-regret that we switched over from texinfo to Sphinx -- texinfo has its flaws but we didn't ever have "oops new version doesn't work" problems with it or have to make sure we did CI testing on multiple different versions of the docs tooling in case something snuck in that didn't work with an older version or broke on a newer version.

**Comment by jakobandersen** [comment] 2020-04-18 10:53
It is indeed quite some breakages, but I really see this as a one-time instance to modernize the C domain.
It may be possible to put in an option to accept some of the pre-v3 style declarations and internally convert them, to easy the transition. If relevant, please open an issue with examples.

**Closed as completed by jakobandersen** 2020-04-18 10:53 UTC
Labels: domains:c
