### ISSUE TITLE
building ceph's document produce name 'unicode' is not defined

### ISSUE THREAD

**Issue by tleydxdy** [sphinx-doc/sphinx#5117] opened 2018-06-22 09:17 UTC
Subject: building ceph's document produce name 'unicode' is not defined

### Problem
- seem like the script can't deal with python 3?

#### Procedure to reproduce the problem
```
cd ~/ceph
admin/build-doc
```

#### Error logs / results
```
Exception occurred:
  File "***/ceph/build-doc/virtualenv/src/sphinx-ditaa/sphinxcontrib/ditaa.py", line 118, in render_ditaa
    if isinstance(code, unicode):
NameError: name 'unicode' is not defined
```

### Reproducible project / your project
- https://github.com/ceph/ceph

### Environment info
- OS: openSUSE
- Python version: 
- Sphinx version:
- <Extra tools e.g.: Browser, tex or something else>

**Comment by tk0miya** [comment] 2018-06-23 04:15
It seems the error was raised by `sphinxcontrib-ditaa`. Could you report it to their project?
I guess it does not support python3.

**Comment by tk0miya** [comment] 2018-07-16 10:18
I'm closing this because this is not a bug of Sphinx-core.
Thanks,

**Closed as completed by tk0miya** 2018-07-16 10:18 UTC
Labels: type:question
