### ISSUE TITLE
build fail for git-lfs: host key verification failed

### ISSUE THREAD

**Issue by CodingCattwo** [sphinx-doc/sphinx#7321] opened 2020-03-16 07:35 UTC
I didn't change the configuration file([conf.py](https://github.com/CodingCattwo/WeBASE-Doc/blob/bugfix-dev/conf.py) in my doc project)
But after I added some pics through git-lfs, it came into an error as below:

`subprocess.CalledProcessError: Command '['ssh', 'git@github.com', 'git-lfs-authenticate', '/CodingCattwo/WeBASE-Doc.git', 'download']' returned non-zero exit status 255.
`
 
more info as below: [build details](https://readthedocs.org/projects/webase-doc-cattwo/builds/10620111/)

```
Running Sphinx v1.7.9
Host key verification failed.

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/webase-doc-cattwo/envs/bugfix-dev/lib/python3.7/site-packages/sphinx/config.py", line 161, in __init__
    execfile_(filename, config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/webase-doc-cattwo/envs/bugfix-dev/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "conf.py", line 59, in <module>
    git_lfs.fetch(DOC_SOURCES_DIR)
  File "/home/docs/checkouts/readthedocs.org/user_builds/webase-doc-cattwo/envs/bugfix-dev/lib/python3.7/site-packages/git_lfs/__init__.py", line 207, in fetch
    lfs_url, lfs_auth_info = get_lfs_endpoint_url(git_repo, checkout_dir)
  File "/home/docs/checkouts/readthedocs.org/user_builds/webase-doc-cattwo/envs/bugfix-dev/lib/python3.7/site-packages/git_lfs/__init__.py", line 60, in get_lfs_endpoint_url
    auth_header = get_lfs_api_token(host, path)
  File "/home/docs/checkouts/readthedocs.org/user_builds/webase-doc-cattwo/envs/bugfix-dev/lib/python3.7/site-packages/git_lfs/__init__.py", line 72, in get_lfs_api_token
    output = check_output(query_cmd.split()).strip().decode('utf8')
  File "/home/docs/.pyenv/versions/3.7.3/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/home/docs/.pyenv/versions/3.7.3/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ssh', 'git@github.com', 'git-lfs-authenticate', '/CodingCattwo/WeBASE-Doc.git', 'download']' returned non-zero exit status 255.
```

How can I fix this, I cannot find any git auth options configurations in the configuration file

**Comment by tk0miya** [comment] 2020-03-16 13:50
It seems ssh command fails on key verification. Please check your settings of ssh.

>Host key verification failed.

Anyway, this is not a bug of Sphinx core. So I'm closing this now.
Thanks,

**Closed as completed by tk0miya** 2020-03-16 13:50 UTC
Labels: type:question
