### ISSUE TITLE
sphinx-versioning crashes with SphinxError during sphinx-build

### ISSUE THREAD

**Issue by michalspondr** [sphinx-doc/sphinx#6037] opened 2019-02-08 12:02 UTC
**Bug description**
I am trying to use sphinx-versioning package to have versioned documentation. I generate RST files via sphinx-apidoc, sphinx-build itself works correctly. However I have to use venv, so my build command looks like this:
`PYTHONPATH=src SPHINXBUILD="venv/bin/python3 -m sphinx" venv/bin/sphinx-build docs/ docs/build`
Anyway this works and the documentation is generated in docs/build.

If I try this using same RST files it fails:
 `PYTHONPATH=src SPHINXBUILD="venv/bin/python3 -m sphinx" venv/bin/sphinx-versioning build docs/ docs/build`
this returns the same error btw:
`sphinx-versioning build docs/ docs/build/`

**Error message**
```
$ sphinx-versioning build docs/ docs/build/
=> Reading config from docs/conf.py...
/home/michal/git/pnp-monitoring/venv/lib64/python3.7/site-packages/sphinxcontrib/versioning/sphinx_.py:202: RemovedInSphinx20Warning: `sphinx.build_main()` has moved to `sphinx.cmd.build.build_main()`.
  result = build_main(argv)
Running Sphinx v1.8.3

Exception occurred:
  File "/home/michal/git/pnp-monitoring/venv/lib64/python3.7/site-packages/sphinx/config.py", line 204, in read
    return cls(namespace, overrides or {})
TypeError: __init__() missing 2 required positional arguments: 'overrides' and 'tags'
The full traceback has been saved in /tmp/sphinx-err-0xhjs283.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib64/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/michal/git/pnp-monitoring/venv/lib64/python3.7/site-packages/sphinxcontrib/versioning/sphinx_.py", line 219, in _read_config
    _build(argv, config, Versions(list()), current_name, False)
  File "/home/michal/git/pnp-monitoring/venv/lib64/python3.7/site-packages/sphinxcontrib/versioning/sphinx_.py", line 204, in _build
    raise SphinxError
sphinx.errors.SphinxError
=> sphinx-build failed for branch/tag while reading config: <local>
=> Unable to read file, continuing with only CLI args.
=> Gathering info about the remote git repository...
=> Getting list of all remote branches/tags...
=> Found: master
=> With docs: master
=> Root ref is: master
=> Pre-running Sphinx to collect versions' master_doc and other info.
/home/michal/git/pnp-monitoring/venv/lib64/python3.7/site-packages/sphinxcontrib/versioning/sphinx_.py:202: RemovedInSphinx20Warning: `sphinx.build_main()` has moved to `sphinx.cmd.build.build_main()`.
  result = build_main(argv)
Running Sphinx v1.8.3

Exception occurred:
  File "/home/michal/git/pnp-monitoring/venv/lib64/python3.7/site-packages/sphinx/config.py", line 204, in read
    return cls(namespace, overrides or {})
TypeError: __init__() missing 2 required positional arguments: 'overrides' and 'tags'
The full traceback has been saved in /tmp/sphinx-err-eafinh_e.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib64/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib64/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/michal/git/pnp-monitoring/venv/lib64/python3.7/site-packages/sphinxcontrib/versioning/sphinx_.py", line 204, in _build
    raise SphinxError
sphinx.errors.SphinxError
=> sphinx-build failed for branch/tag: master
Failure.
```
 **Environment info**
Sphinx version: 1.8.3
Python version: 3.7.2 (CPython)
Docutils version: 0.14 
Jinja2 version: 2.10

**Comment by tk0miya** [comment] 2019-02-08 17:27
It seems the error was raised by sphinxcontrib-versioning extension.
And it would be same as https://github.com/Robpol86/sphinxcontrib-versioning/issues/57.

Anyway, this is not a bug of Sphinx. So closing now.

**Closed as completed by tk0miya** 2019-02-08 17:27 UTC
Labels: type:question
