### ISSUE TITLE
Cannot include dynamic list of files

### ISSUE THREAD

**Issue by ephracis** [sphinx-doc/sphinx#4535] opened 2018-02-02 11:54 UTC
Subject: Error when using include inside jinja template

### Problem
Using `.. include::` inside a `.. jinja::` block results in error.

#### Procedure to reproduce the problem
```
.. jinja:: test

   {% for file in include_files %}
   .. include:: {{ file }}
      :code: yaml
   {% endfor %}
```

#### Error logs / results

```
Exception occurred:
  File "/usr/lib/python2.7/posixpath.py", line 54, in isabs
    return s.startswith('/')
AttributeError: 'NoneType' object has no attribute 'startswith'
```

#### Expected results
The build should complete without errors and the build should include all files in the list.

### Environment info
- OS: Linux and Mac
- Python version: 2.7
- Sphinx version: 1.4.6

**Comment by tk0miya** [comment] 2018-02-02 15:33
`jinja` directive is not sphinx's. Could you report this to the extension's project?

**Comment by tk0miya** [comment] 2018-02-20 17:31
I'm closing this now because this is not a bug of Sphinx.
Thanks,

**Closed as completed by tk0miya** 2018-02-20 17:31 UTC
Labels: type:question
