### ISSUE TITLE
Possible for ".. uml::" to support embedding external files?

### ISSUE THREAD

**Issue by Balooga** [sphinx-doc/sphinx#2421] opened 2016-04-04 20:01 UTC
Would it be possible for `.. uml::` to support embedding external files, such is as currently possible with `.. graphviz:: external.dot` ?

For example;

`.. uml:: external.puml`

**Comment by lehmannro** [comment] 2016-04-04 20:27
If this is for [sphinxcontrib.plantuml](https://pypi.python.org/pypi/sphinxcontrib-plantuml), could you file a bug at the [sphinx-contrib](https://bitbucket.org/birkenfeld/sphinx-contrib) repository?

**Comment by tk0miya** [comment] 2016-04-16 07:12
This is not a bug of Sphinx. I close this now.

**Closed as completed by tk0miya** 2016-04-16 07:12 UTC

**Comment by Balooga** [comment] 2016-04-26 23:09
@lehmannro 

Just did.  Thanks for the pointer.

https://bitbucket.org/birkenfeld/sphinx-contrib/issues/148/support-for-uml-to-embedd-external-files
