### ISSUE TITLE
builders.xml requirement since Sphinx 1.5.0

### ISSUE THREAD

**Issue by dwaynebailey** [sphinx-doc/sphinx#3201] opened 2016-12-06 14:25 UTC
Our builds have started to get this Extension error after upgrading Sphinx to 1.5.0

`Could not import extension sphinx.builders.xml (exception: No module named sax.saxutils)`

Our extensions are as follows:
```py
extensions = [
    'translate_docs',
    'sphinx.ext.autodoc',
    'sphinx.ext.coverage',
    'sphinx.ext.extlinks',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
]
```

**Comment by shimizukawa** [comment] 2016-12-06 15:01
Sorry for your inconvenient. Please let us know your full console message, also full traceback log.

**Comment by dwaynebailey** [comment] 2016-12-06 15:04
```pytb
(toolkit)~/dev/toolkit/docs (master)$ sphinx-build -T -b html -d _build/doctrees   . _build/html
Running Sphinx v1.5

Traceback (most recent call last):
  File "/Users/dwayne/dev/envs/toolkit/lib/python2.7/site-packages/sphinx/cmdline.py", line 295, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/Users/dwayne/dev/envs/toolkit/lib/python2.7/site-packages/sphinx/application.py", line 189, in __init__
    self.setup_extension(extension)
  File "/Users/dwayne/dev/envs/toolkit/lib/python2.7/site-packages/sphinx/application.py", line 516, in setup_extension
    err)
ExtensionError: Could not import extension sphinx.builders.xml (exception: No module named sax.saxutils)

Extension error:
Could not import extension sphinx.builders.xml (exception: No module named sax.saxutils)
```

**Comment by shimizukawa** [comment] 2016-12-06 15:29
Thanks.
Once, please run sphinx-build with `-vvv` option and let us know the log.

For now I guess that it is related to relative import (`docutils.writers.docutils_xml` is using `xml.sax.saxutils`).
If you can, please do:
```
$ python
>>> import xml
>>> xml.__file__
>>> import xml.sax.saxutils
>>> xml.sax.saxutils.__file__
```
and let us know the result.
Thanks.

**Comment by dwaynebailey** [comment] 2016-12-06 15:39
[-vvv log](http://dpaste.com/0QKWXSS)

```py
(toolkit)~/dev/toolkit/docs (master)$ python
Python 2.7.10 (default, Jul 30 2016, 18:31:42) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import xml
>>> xml.__file__
'/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/__init__.pyc'
>>> import xml.sax.saxutils
>>> xml.sax.saxutils.__file__
'/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/sax/saxutils.pyc'
>>> 
```

**Comment by shimizukawa** [comment] 2016-12-06 16:17
Strange.. `-vvv log` says 
```
  File "/Users/dwayne/dev/envs/toolkit/lib/python2.7/site-packages/docutils/writers/docutils_xml.py", line 27, in <module>
    import xml.sax.saxutils
ImportError: No module named sax.saxutils
```
However python console can import `xml` and `xml.sax.saxutils`.

I guess that if you run `make xml` (sphinx-build - b xml) with the previous sphinx version you get the same error. If it is true, during sphinx execution, xml module which is not xml of Python standard library is loaded. I think that is the cause of this problem.
Do you have any idea about this?

**Comment by birkenfeld** [comment] 2016-12-06 16:20
Maybe a leftover xml.py or xml.pyc in `/Users/dwayne/dev/envs/toolkit/lib/python2.7/site-packages/docutils/writers`?

**Comment by dwaynebailey** [comment] 2016-12-06 16:32
@shimizukawa confirmed with 1.4.9 using xml builder, see below.  @birkenfeld afraid not stale, I made a new virtualenv to test and ensure it's clean, same error.

The package we build requires `lxml`, that's very likely then to be the on interfering?

Using `sphinx-build -T -b xml -d _build/doctrees   . _build/html` I get:

```pytb
# Sphinx version: 1.4.9
# Python version: 2.7.10 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/Users/dwayne/dev/envs/toolkit2/lib/python2.7/site-packages/sphinx/cmdline.py", line 243, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/Users/dwayne/dev/envs/toolkit2/lib/python2.7/site-packages/sphinx/application.py", line 204, in __init__
    self._init_builder(self.buildername)
  File "/Users/dwayne/dev/envs/toolkit2/lib/python2.7/site-packages/sphinx/application.py", line 277, in _init_builder
    __import__('sphinx.builders.' + mod, None, None, [cls]), cls)
  File "/Users/dwayne/dev/envs/toolkit2/lib/python2.7/site-packages/sphinx/builders/xml.py", line 20, in <module>
    from sphinx.writers.xml import XMLWriter, PseudoXMLWriter
  File "/Users/dwayne/dev/envs/toolkit2/lib/python2.7/site-packages/sphinx/writers/xml.py", line 13, in <module>
    from docutils.writers.docutils_xml import Writer as BaseXMLWriter
  File "/Users/dwayne/dev/envs/toolkit2/lib/python2.7/site-packages/docutils/writers/docutils_xml.py", line 27, in <module>
    import xml.sax.saxutils
ImportError: No module named sax.saxutils
```

**Comment by dwaynebailey** [comment] 2016-12-06 16:33
It could be this also though.  I've used Mock in places to help with autodocs.  The ones at the end potentially being issues.

```py
MOCK_MODULES = [
    'aeidon',
    'aeidon.encodings',
    'aeidon.util',
    'aeidon.files',
    'BeautifulSoup',
    'glib',
    'gobject',
    'gtk',
    'iniparse',
    'lucene',
    'PyLucene',
    'vobject',
    'xapian',
    'xml',
    'xml.dom',
    'xml.etree',
    'xml.parsers',
]
```

**Comment by dwaynebailey** [comment] 2016-12-06 17:03
@shimizukawa taking `xml` out of my MOCK_MODULES causes the build to function properly.

I guess I've never cared to build xml and its only exposed with 1.5.0.

So sounds like a bug in my config rather than Sphinx.  Thanks for the help and patience tracking this down.  I'll leave it to you to decide if this is something that should be fixed/mitigated in Sphinx.

**Comment by shimizukawa** [comment] 2016-12-06 21:59
I'm very happy to hear that it solved!
In the previous version Sphinx did not load built-in builders which was not used.  We will consider reverting to the previous behavior, but I think I will close this ticket. Thank you very much for your investigation.

**Closed as completed by shimizukawa** 2016-12-06 21:59 UTC
Labels: type:bug

**Comment by shimizukawa** [comment] 2016-12-07 14:37
FYI. I guess you are mocking the `xml` module against the whole system, but we recommend `autodoc_mock_imports` as a better way.
http://www.sphinx-doc.org/en/1.5/ext/autodoc.html#confval-autodoc_mock_imports
`autodoc_mock_imports` does not mock the modules which is used by Sphinx, it mocks only when reading the target module of autodoc.
