### ISSUE TITLE
Footnote link not superscripted

### ISSUE THREAD

**Issue by kaipoeritz** [sphinx-doc/sphinx#5153] opened 2018-07-09 10:31 UTC
When using 'make html' to create HTML output, the footnotes in the main text are not superscripted.
I expect the footnote in the text to be superscripted as shown here: http://docutils.sourceforge.net/docs/user/rst/quickref.html#footnotes

The HTML is supposed to be a nested `<a>` in side a `<sup>` . e.g. `<sup><a href="#5">5</a></sup>` .

But all I get is a single `<a>` without the surrounding `<sup>` element `<a class="footnote-reference brackets" href="#id2" id="id1">5</a>`.

### Problem
- <footnotes in HTML are missing the surrounding `<sup>` element>

#### Procedure to reproduce the problem
```
<make html>
```

#### Error logs / results
```
<none>
```
#### Expected results
<surround the footnote with `<sup>` element so it is actually superscripted>

### Reproducible project / your project
- [footnote-superscript-bug.zip](https://github.com/sphinx-doc/sphinx/files/2175715/footnote-superscript-bug.zip)

### Environment info
- OS: <Linux >
- Python version: Python 2.7.14
- Sphinx version: sphinx-build 1.7.4

**Comment by tk0miya** [comment] 2018-07-09 14:41
It seems current docutils (core reST parser) does not make footnotes superscripted.
```
$ echo 'blah blah [1]_\n\n.. [1] footnote blah blah' | rst2html.py | grep blah
<p>blah blah <a class="footnote-reference" href="#id2" id="id1">[1]</a></p>
<tr><td class="label"><a class="fn-backref" href="#id1">[1]</a></td><td>footnote blah blah</td></tr>
```

How about add stylesheet to your project? Following CSS works fine to me.
```
a.footnote-reference {
    vertical-align: super;
    font-size: 80%;
}
```

**Comment by jfbu** [comment] 2018-07-16 13:44
Automatic superscripting of footnotes is theme dependent: it is applied with ``alabaster`` and ``sphinx_rtd_theme`` (Read-the-docs) themes but not with ``classic`` or ``agogo`` themes for example. As pointed out by @tk0miya  you can add your custom CSS styling.

**Comment by tk0miya** [comment] 2018-07-29 14:20
I'm closing this now because this is not a bug of Sphinx.
And I don't think this fix is needed.
Thanks,

**Closed as completed by tk0miya** 2018-07-29 14:20 UTC
Labels: type:question, closed:wontfix, markup, builder:html, html theme
