### ISSUE TITLE
epub 3 validation error regarding to entity reference (this issue is also of html5 builder)

### ISSUE THREAD

**Issue by hhsprings** [sphinx-doc/sphinx#2985] opened 2016-09-30 04:23 UTC
For now, [EpubCheck 4.0.1](https://github.com/IDPF/epubcheck/releases/tag/v4.0.1) complains sphinx epub(3) builder's output is invalid for entity references (even if [PR#2805](https://github.com/sphinx-doc/sphinx/pull/2805) was applied):

> FATAL(RSC-016): Fatal Error while parsing file 'The entity "copy" was referenced, but not declared.'

Currently, in the sphinx code tree, there are many embeded entity references (in locales and themes), so, we can take two approaches:
1.  change all embeded entity reference to numeric reference (or literal)
2.  replace those in writer or builder

Latter approach can be reached using `htmlentityrefs` of standard python library, for example, like this:

``` python
import re
from htmlentitydefs import name2codepoint  # python 2.7
_name2codepoint4html5rgx = re.compile(r"&({});".format("|".join(
    (n for n in name2codepoint if n not in ("amp", "lt", "gt", "quot", "apos")))))

def _unescape_for_html5(s):
    def _sub(m):
        n = m.group(1)
        #return chr(name2codepoint[n])
        return "&#{};".format(name2codepoint[n])
    return _name2codepoint4html5rgx.sub(_sub, s)
```

**Comment by hhsprings** [comment] 2016-09-30 05:29
update:

``` python
import re
from six.moves import html_entities
_name2codepoint4html5rgx = re.compile(r"&({});".format("|".join(
    (n for n in html_entities.name2codepoint if n not in ("amp", "lt", "gt", "quot", "apos")))))

def _unescape_for_html5(s):
    def _sub(m):
        n = m.group(1)
        #return chr(name2codepoint[n])
        return "&#{};".format(html_entities.name2codepoint[n])
    return _name2codepoint4html5rgx.sub(_sub, s)
```

**Comment by tk0miya** [comment] 2016-11-20 05:46
Sorry, I can't reproduce the problem.
Could you show me any reproducible example?

**Comment by tk0miya** [comment] 2017-01-07 17:02
@hhsprings ping

**Comment by tk0miya** [comment] 2017-02-15 12:17
@hhsprings ping

**Comment by tk0miya** [comment] 2017-03-18 11:58
Unfortunately, I can't reproduce this yet. So I close this now.
Please let me know if you still get same error.

Thanks,

**Closed as completed by tk0miya** 2017-03-18 11:58 UTC
Labels: type:bug, builder:html
