### ISSUE TITLE
UnboundLocalError: local variable 'classes' referenced before assignment for SubTitle call in nodes

### ISSUE THREAD

**Issue by lookilooki** [sphinx-doc/sphinx#6275] opened 2019-04-10 12:11 UTC
**Describe the bug**
I created an own extension, according to the ToDo example.
(https://www.sphinx-doc.org/en/master/development/tutorials/todo.html) 

I like to add subtitle into the node:
```
        test_sum_node = test_sum('\n'.join(self.content))
        test_sum_node += nodes.title(_(target_func), _(target_func))
        test_sum_node += nodes.subtitle(_('Test_Detailed'), _('Test_Detailed'))
```
and just call sphinx-build

**Expected behavior**
just build the project and have a subtitle

**Environment info**
- OS: Windows 10
- Python version: 3.7.0
- Sphinx version:  2.0.1

Exception occurred:
  File "docutils\writers\_html_base.py", line 1407, in visit_subtitle
    self.body.append(self.starttag(node, 'p', '', CLASS=classes))
UnboundLocalError: local variable 'classes' referenced before assignment

**Additional context**

[sphinx-err-qvd0cafp.log](https://github.com/sphinx-doc/sphinx/files/3063673/sphinx-err-qvd0cafp.log)

**Comment by tk0miya** [comment] 2019-04-11 16:54
The document tree model expects a parent of subtitle node is only document or sidebar nodes.
http://docutils.sourceforge.net/docs/ref/doctree.html#subtitle

Your code does not follow the rule. Please don't use subtitle node for this purpose.

Thanks,

**Comment by tk0miya** [comment] 2019-05-14 16:44
I'm closing this now because this is not a bug of Sphinx.
Thanks,

**Closed as completed by tk0miya** 2019-05-14 16:44 UTC
Labels: type:question
