### ISSUE TITLE
Footnote in table causes error in LaTeX

### ISSUE THREAD

**Issue by Jellby** [sphinx-doc/sphinx#3915] opened 2017-07-06 13:59 UTC
### Problem
Including a footnote inside a table's content gives an error when building `latexpdf`

#### Procedure to reproduce the problem

Sample document:
```
First section

.. table:: Table caption\ [#a]_

   ========== =====
   Foo        Bar
   ========== =====
   CAS\ [#b]_ 1.497
   ========== =====

.. [#a] Footnote in caption
.. [#b] Footnote in body
```

#### Error logs / results

`make html` works fine and gives a nice result, `make latexpdf` results in:

```
! Extra }, or forgotten \endgroup.
\endfootnote ...H@postfntext \FNH@endnote \egroup 
                                                  \begingroup \let \@makefnt...
l.103 \end{tabulary}
```

#### Expected results
No crash, and pdf output with nice table with footnotes.

#### Fix
The generated `.tex` file says:

```
\sphinxcaption{Table caption\sphinxfootnotemark[1]}\label{\detokenize{one:id3}}
\sphinxaftercaption
\begin{tabulary}{\linewidth}[t]{|T|T|}
\hline
\sphinxstylethead{\sphinxstyletheadfamily
Foo
\unskip}\relax &\sphinxstylethead{\sphinxstyletheadfamily
Bar
\unskip}\relax \\
\hline%
\begin{footnotetext}[1]\sphinxAtStartFootnote
Footnote in caption
%
\end{footnotetext}\ignorespaces
CAS%
\begin{footnote}[2]\sphinxAtStartFootnote
Footnote in body
%
\end{footnote}
```

so the first footnote (in the caption) was replaced with `\sphinxfootnotemark[1]` and `\begin{footnotetext}[1]`, while the second one was replaced with `\begin{footnote}[2]`. If I manually replace the second footnote with:

```
\sphinxfootnotemark[2]%
\begin{footnotetext}[2]\sphinxAtStartFootnote
Footnote in body
%
\end{footnotetext}
```

the document compiles sucessfully (although it would be nicer if the footnotes could be placed inside the table, rather than in the page footer.

### Environment info
- OS: Kubuntu 14.04
- Python version: 2.7
- Sphinx version: 1.6.3
- TeXLive installed with the ubuntu packages

**Comment by jfbu** [comment] 2017-07-23 20:24
Le 6 juil. 2017 à 15:59, Jellby <notifications@github.com> a écrit :

> Problem
> 
> Including a footnote inside a table's content gives an error when building latexpdf
> 
> Procedure to reproduce the problem
> 
> Sample document:
> 
> First section
> 
> .. table:: Table caption\ [#a]_
> 
>    ========== =====
>    Foo        Bar
>    ========== =====
>    CAS\ [#b]_ 1.497
>    ========== =====
> 
> .. [#a] Footnote in caption
> .. [#b] Footnote in body
> Error logs / results
> 
> make html works fine and gives a nice result, make latexpdf results in:
> 
> ! Extra }, or forgotten \endgroup.
> \endfootnote ...H@postfntext \FNH@endnote \egroup 
>                                                   \begingroup \let \@makefnt...
> l.103 \end{tabulary}
> Expected results
> 
> No crash, and pdf output with nice table with footnotes.
> 
> Fix
> 
> The generated .tex file says:
> 
> \sphinxcaption{Table caption\sphinxfootnotemark[1]}\label{\detokenize{one:id3}}
> \sphinxaftercaption
> \begin{tabulary}{\linewidth}[t]{|T|T|}
> \hline
> \sphinxstylethead{\sphinxstyletheadfamily
> Foo
> \unskip}\relax &\sphinxstylethead{\sphinxstyletheadfamily
> Bar
> \unskip}\relax \\
> \hline%
> \begin{footnotetext}[1]\sphinxAtStartFootnote
> Footnote in caption
> %
> \end{footnotetext}\ignorespaces
> CAS%
> \begin{footnote}[2]\sphinxAtStartFootnote
> Footnote in body
> %
> \end{footnote}
> so the first footnote (in the caption) was replaced with \sphinxfootnotemark[1] and \begin{footnotetext}[1], while the second one was replaced with \begin{footnote}[2]. If I manually replace the second footnote with:
> 
> \sphinxfootnotemark[2]%
> \begin{footnotetext}[2]\sphinxAtStartFootnote
> Footnote in body
> %
> \end{footnotetext}
> the document compiles sucessfully (although it would be nicer if the footnotes could be placed inside the table, rather than in the page footer.
> 
> Environment info
> 
> OS: Kubuntu 14.04
> Python version: 2.7
> Sphinx version: 1.6.3
> TeXLive installed with the ubuntu packages

Hi, my quick test with make latexpdf can not reproduce the error with the provided sample document. The produced pdf is like html, except the footnote 1 inside the caption is not hyperlinked, which is known fact due to LaTeXnical issues.

I tried with TeXLive 2014 and with TeXLive 2017 (not up-to-date for the later)

I guess you tried make clean latexpdf to be sure some old tabulary.sty from old version of Sphinx is not there in latex build repertory ?



the generated latex code is like yours (apart from some end of line spaces)

I am stymied ;-)

**Comment by Jellby** [comment] 2017-07-24 10:05
I just created a new empty directory, ran `sphinx-quickstart` with default answers. Modified `index.rst` to include the "sample document" above (just inline, not as a separate file), ran `make latexpdf` and got the error. So the build directory should be clean.

But indeed, there was a `tabulary.sty` file in the build directory, while I see none in the current `texinputs` directory... I guess installing the latest sphinx with `pip install --user --upgrade sphinx` didn't remove old files from previous installations. I uninstalled sphinx (`pip uninstall sphinx`), deleted the whole `~/.local/lib/python2.7/site-packages/sphinx` directory (could it be a leftover from installation from source?), reinstalled sphinx, and now there is no `tabulary.sty` in the build directory, the compilation completes successfully and the pdf looks OK.

**Comment by jfbu** [comment] 2017-07-24 12:34
thanks for feedback: not being familiar with the inner workings of ``pip`` I don't know the exact mechanism why ``texinputs`` was not reset during upgrade; perhaps bad interaction as your report suggests between installation from source (also via ``pip install``?) and subsequent ``pip install`` from internet ?

but yes, Sphinx copies over blindly contents of ``texinputs`` to latex build repertory, so the old custom ``tabulary.sty`` if still resident there got copied over and caused the crash. Since 1.5 however Sphinx uses the ``tabulary.sty`` as present in the TeX installation, not a custom patched copy.

now closing, thanks for reporting.

**Closed as completed by jfbu** 2017-07-24 12:34 UTC
Labels: type:question, builder:latex
