### ISSUE TITLE
ePub3 builder: same headlines in *.md creates "duplicate id" error in epub validation 

### ISSUE THREAD

**Issue by dakoller** [sphinx-doc/sphinx#5507] opened 2018-10-03 04:46 UTC
Subject: <what happen when you do on which document project>

### Problem
- When multiple documents contain the same header (e.g. "### Options" in my case in *.md files), the epub3 builder builds the epub.
- ( as a sidenote: In local ubuntu coolreader shows a completely unreadable epbu file then, but not sure whether this is related)
- anyway epub3 validation at http://validator.idpf.org// complains that the same "id" (like "Options") is used multiple times.
- this poses a problem, when the epub file is to be handed over to someone else for further processing.

#### Procedure to reproduce the problem
```
<Paste your command-line here which cause the problem>
```

#### Error logs / results
```
<Paste your error log here>
```
- <public link of unexpected result if you have>

#### Expected results
Event if the same "duplicated" headline shows up e.g. in in the document or the TOC, one idea copuld be that the id-generation e.g. includes the usually unique document/filename or event the document path.
I'd be happy to support with a pull request, but I'd need a pointer as to where the id-generation happens.

### Reproducible project / your project
- ```### Synopsis

Print the client and server version information for the current context

```
kubectl version [flags]
```

### Examples

```
  # Print the client and server versions for the current context
  kubectl version
```

### Options

```
      --client          Client version only (no server required).
  -h, --help            help for version
  -o, --output string   One of 'yaml' or 'json'.
      --short           Print just the version number.
```
--> these headers show up in multiple different documents.

### Environment info
- OS: Ubuntu
- Python version: 2.x
- Sphinx version: 1.8.1
- <Extra tools e.g.: Browser, tex or something else>

**Comment by tk0miya** [comment] 2018-10-06 15:29
What parser are you using? recommonmark? Sphinx does not support markdown by default. So I guess it might be a bug of the extension.

**Comment by tk0miya** [comment] 2018-11-01 16:05
I'm closing this now because this is not a bug of Sphinx.
Thanks,

**Closed as completed by tk0miya** 2018-11-01 16:05 UTC
Labels: type:question
