### ISSUE TITLE
LaTeX: build failure if language is Japanese when using LuaLaTex (not pLaTeX)

### ISSUE THREAD

**Issue by atsuoishimoto** [sphinx-doc/sphinx#11179] opened 2023-02-07 11:20 UTC
### Describe the bug

# Reproduce lualatex Arithmetic overflow

Building this document causes Arithmetic overflow error with lualatex:

```sh
$ cat source/index.rst
1111111111111
#############

2222222222222
*************

3333333333333
=============

4444444444444
-------------

:class:`555555555555555`
^^^^^^^^^^^^^^^^^^^^^^^^

+-------------+------+
| 0000000     | AAAA |
|             +------+
|             | BBBB |
+-------------+------+

$ cat source/conf.py
project = 'test1'
copyright = '2023, a'
author = 'a'

extensions = []

templates_path = ['_templates']
exclude_patterns = []

language = 'ja'

html_theme = 'alabaster'
html_static_path = ['_static']

latex_engine="lualatex"

latex_docclass = {
'manual': 'ltjsbook',
'howto': 'ltjsarticle'
}


$ make latexpdf
...
...
...
! Arithmetic overflow.
\sphinx@@multirow ... \divide \count@ \count \tw@
                                                  \advance \dimen@ -\count@ ...

l.64 \end{tabulary}
```

### How to Reproduce

1. Clone git repository for test:

```sh
git clone git@github.com:atsuoishimoto/lualatex-arithmetic-overflow.git
cd lualatex-arithmetic-overflow
```

2. Install [Sphinx](https://www.sphinx-doc.org/en/master/) and build.

```sh
pip3 install sphinx
cd sphinx-error/
make latexpdf
```

Alternatively, I created a minimum TeX file to reproduce the error. To build PDF manually:

```sh
cd latex
make library.pdf
```

### Environment Information

I reproduced the error on Ubuntu and macOS.

```text

Ubuntu:


$ sphinx-build --version
sphinx-build 6.1.3

$ lualatex --version
This is LuaHBTeX, Version 1.14.0 (TeX Live 2022/dev/Debian)

$ uname -a
Linux u2204 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux


macOS:
```sh
$ sphinx-build --version
sphinx-build 6.1.3

$ lualatex --version
This is LuaHBTeX, Version 1.15.0 (TeX Live 2022)

$ uname -a
Darwin mbp16.local 21.4.0 Darwin Kernel Version 21.4.0: Mon Feb 21 20:34:37 PST 2022; root:xnu-8020.101.4~2/RELEASE_X86_64 x86_64
```

### Additional context

I encountered this issue while fixing following PDF build issue at docs.python.org.

https://github.com/python/python-docs-ja/issues/35

This issue was first reported at sphinx-users list(https://groups.google.com/g/sphinx-users/c/9sKyElODU5I)

**Comment by atsuoishimoto** [comment] 2023-02-07 12:49
@jfbu filed an issue to luatex-ja 

https://osdn.net/projects/luatex-ja/ticket/47321

**Comment by jfbu** [comment] 2023-02-07 17:37
@atsuoishimoto Thanks for your neat sample project which helped to study this. As is explained in the sphinx-users [thread](https://groups.google.com/g/sphinx-users/c/9sKyElODU5I), the issue ultimately is caused by some upstream LuaLaTeX-ja ["mind-boggling" LaTeX subtlety](https://osdn.net/projects/luatex-ja/ticket/47321).  It will get resolved upstream at some point as fixes are available already.

Thanks for confirming the suggested work-around at Sphinx level does work.

The LuaLaTeX-ja problem has the potential to pop up again in unexpected places though, and I have not yet thought  seirously about whether some of the Sphinx LaTeX style files may create conditions to recreate it in future.  

(and there is no such problem with the default Japanese rendering which goes via uplatex not lualatex and lualatex-ja classes)

I tend to think not much risk because although one of the trigger (`\leavevmode`) will be ubiquitous, the other one, a `\strut` in `\everypar`, which here originated in a hidden way from `titlesec` rendering of sectioning titles, less so.  Sphinx LaTeX does orginate some `\strut` 's which will transit via `\everypar` in the context of Object parameter descriptions via `\item` mark-up in file sphinxlatexobjects.sty.  But this will be wrapped in some "label box" so, a priori, should not trigger the LuaLaTeX-ja problem.  I am only mentioning this here in the case problem does pop up in future and at least we have here some background data.

Maybe the work-around can be merged in our Sphinx latex files as it does not seem to change anything.  Will consider it.

**Closed as completed** 2023-02-11 20:43 UTC
Labels: builder:latex
