### ISSUE TITLE
PDF Generation does not work with multiple TOCs

### ISSUE THREAD

**Issue by Daltz333** [sphinx-doc/sphinx#6483] opened 2019-06-14 18:17 UTC
**Describe the bug**
My repository has an index file with three different TOCs. However, all the TOCs listed below the first TOC are listed as if they were under the first one. This **happens** in PDF generation, EPUB and HTML work as expected. 

**To Reproduce**
1. Have one index file with three TOCs.
2. Generate a PDF with latexpdf

Offending website https://frc-docs.readthedocs.io/en/develop/

**Comment by tk0miya** [comment] 2019-06-15 09:47
Do you meaning PDF does not contain captions of toctrees? If so, they are not used for PDF output because they are not a part of ToC, only decorations.

**Comment by ScriptAutomate** [comment] 2020-05-19 21:21
This might be a duplicate of #4977

**Comment by tk0miya** [comment] 2020-05-20 15:42
Indeed. And it seems not updated so long. So I'm closing this now.

**Closed as completed by tk0miya** 2020-05-20 15:42 UTC
Labels: type:question, builder:latex

**Comment by Daltz333** [comment] 2020-05-20 17:41
It was a duplicate yes.
