### ISSUE TITLE
Is there a way to place 2 figures side by side with captions?

### ISSUE THREAD

**Issue by eflanigan00** [sphinx-doc/sphinx#4003] opened 2017-08-13 16:24 UTC
I'm looking for this type of behavior:
https://tex.stackexchange.com/questions/157453/cant-place-figures-side-by-side

       A                B
     CaptionA       CaptionB 
        Figure 2: My figure

1. Works with two images but isn't a figure

       .. image:: A.png
          :width: 49%
       .. image:: B.png
          :width: 49%

2. Is a little better but I see a line at the bottom of the "table"

       .. |logo1| image:: A.png
           :scale: 60%

       .. |logo2| image:: B.png
           :scale: 60%

       .. table:: My table
          :align: center

          +---------+---------+
          | |logo1| | |logo2| |
          +---------+---------+

**Comment by tk0miya** [comment] 2017-08-19 13:55
Unfortunately, sphinx does not support it.
But sphinxtr might help you:
http://jterrace.github.io/sphinxtr/html/ch-figs/index.html#subfigures

Note:

>Works with two images but isn't a figure

The substitution only supports directives which generates inline node.
But figure directive always returns block nodes. So it cannot work.
http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#substitution-definitions

**Comment by tk0miya** [comment] 2017-09-05 16:23
I'm closing this because this is not a bug of Sphinx.
Thanks,

**Closed as completed by tk0miya** 2017-09-05 16:23 UTC
Labels: type:question

**Comment by eflanigan00** [comment] 2018-02-04 00:43
@tk0miya can we reopen this as a feature request? This is a feature I would use a lot. Even if it isn't implemented right away I think it should be a long term goal to support this.

**Comment by tk0miya** [comment] 2018-02-04 16:43
IMO, best layouting is not a goal of reST and Sphinx. I think this is one of them. So -1 for adding this to Sphinx.
But Sphinx and reST provides many extension points for developers. So my opinion don't prevent you to develop an extension to do that.

**Comment by eflanigan00** [comment] 2018-02-04 16:57
@tk0miya I have never developed an extension for sphinx. Can you explain the best way to approach that?

**Comment by jessetan** [comment] 2018-02-09 10:42
There is a [tutorial for writing an extension for Sphinx](http://www.sphinx-doc.org/en/stable/extdev/tutorial.html), but you can also copy things from one of the [Sphinx extensions on GitHub](https://github.com/topics/sphinx-extension) and expand from there.
The code that handles the subfig commands in sphinxtr is here: https://github.com/jterrace/sphinxtr/blob/master/extensions/subfig.py

I've given it a quick glance and it looks like you have to:
- copy/write the subfig code, fixing any possible issues
- modify the (num)ref code with your extension so that references to subfigures work
- add some CSS styling to place the images properly in HTML
- include the `subcaption` package for LaTeX

**Comment by jhermann** [comment] 2018-03-27 16:24
Another way (HTML only) would be to assign custom CSS classes (or IDs) and make those block elements floating, or change their display style to `inline-block` (not tested).

**Comment by autodataming** [comment] 2019-06-14 08:44
.. list-table:: 

    * - .. figure:: ../_static/1repren.png

           Fig 1. Representations

      - .. figure:: ../_static/5transparency.png

           Fig 2. Transparency
    * - .. figure:: ../_static/9ele.png

           Fig 3. Electrostatics

      - .. figure:: ../_static/11R3D.PNG.png

           Fig 4. R3D

**Comment by autodataming** [comment] 2019-06-14 08:44
`
.. list-table:: 

    * - .. figure:: ../_static/1repren.png

           Fig 1. Representations

      - .. figure:: ../_static/5transparency.png

           Fig 2. Transparency
    * - .. figure:: ../_static/9ele.png

           Fig 3. Electrostatics

      - .. figure:: ../_static/11R3D.PNG.png

           Fig 4. R3D
`
