### ISSUE TITLE
C++ domain -- referencing a method template via :cpp:func:`....`

### ISSUE THREAD

**Issue by wjakob** [sphinx-doc/sphinx#2082] opened 2015-10-12 20:00 UTC
Hi,

I am using the new function template support in a documentation project, which is working well so far. However, I'm having a hard time referencing template functions from within the documentation. See the following minimal example:

```
.. cpp:class:: handle

    Documentation text for class ``handle``

.. cpp:function:: template <typename T> T handle::cast()

    Documentation text for method ``handle::cast()``

And now let's reference :cpp:func:`handle::cast`.
```

The reference at the bottom renders ok, but it does not link to any function. To get the link to work, I have to rewrite this as `:cpp:func:`template <typename T> handle::cast``, which is kind of ugly and seems counter to the usual Sphinx policy of having short links without arguments and return values, which go to the first overload.

Thoughts?

Thanks!
Wenzel

**Comment by Rapptz** [comment] 2015-10-12 21:06
Duplicate of #2057

**Comment by jakobandersen** [comment] 2015-10-12 23:47
I completely agree that the currently working solution is too verbose. I'm working on a short-hand (see #2057 for status).

**Closed as completed by jakobandersen** 2015-10-12 23:47 UTC
Labels: closed:duplicate, type:enhancement, domains:cpp
