### ISSUE TITLE
Using the `only` directive to prepend or append the readme based upon the builder in use

### ISSUE THREAD

**Issue by Carelvd** [sphinx-doc/sphinx#3330] opened 2017-01-12 13:13 UTC
Subject: Using the `only` directive to prepend or append a readme based upon the builder in use

### Problem

I want to control where the `readme.rst` is inserted into my documentation based upon the document I am building. For `singlehtml` and `LaTeX` targets I wanted it to appear before the Table of contents and for `html` I wanted to insert it after the table of contents

#### Procedure to reproduce the problem

I produced an example project using the `sphinx-quickstart` command. 
"""
sphinx-quickstart -p Example -a Author -v 0.0 -r alpha -l=en --sep --dot= --master=index --suffix=.rst --batchfile --makefile --epub --ext-autodoc --ext-doctest --ext-intersphinx --ext-todo --ext-coverage --ext-mathjax --ext-imgmath --ext-ifconfig --ext-viewcode --ext-githubpages .
"""

This produces a typical sphinx project folder with separate source and build directories to which one adds a `readme.rst` file and modifies the `source/index.rst` to reflect the following :

    .. Example documentation master file, created by
       sphinx-quickstart on Thu Jan 12 12:58:12 2017.
       You can adapt this file completely to your liking, but it should at least
       contain the root `toctree` directive.
    
    .. only :: singlehtml or latex
    
       .. include :: ../readme.html
    
    Welcome to Example's documentation!
    ===================================
    
    .. toctree::
       :maxdepth: 2
       :caption: Contents:
    
    .. only :: html
    
       .. include :: ../readme.html
    
    Indices and tables
    ==================
    
    * :ref:`genindex`
    * :ref:`modindex`
    * :ref:`search`

I compile the documentation using the `make.bat` file (I'm on a windows box) in the following ways to produce a single HTML document 

```
make clean & set SPHINXOPTS=-t singlehtml & make singlehtml
```

and a multipage HTML document 

```
make clean & set SPHINXOPTS=-t html & make singlehtml
```

#### Error logs / results
The error I'm encountering is that the content in the `readme.rst` keeps appearing at the end of the HTML file and I have no control over this. 

#### Expected results
I expect the included document to appear where I have it in my document structure, instead it consistently appears at the bottom or not at all. I have tried different recipes for getting this to work from importing two different files with appropriate structures to alternate structures where the `toc` and `include` directives appear under the same `only` directives.

### Reproducible project / your project

My Gitlab server is currently down so I can not provide this at the moment

### Environment info

- OS: Windows 10
- Python version: 3.4
- Sphinx version: 1.5.1

**Comment by tk0miya** [comment] 2017-01-12 15:45
I can't reproduce your problem, but it seems not working.
As documented, the "format" and "name of the current of builder" are always set as a tag.
http://www.sphinx-doc.org/en/1.5.1/markup/misc.html#directive-only

From the behavior, the `html` tag is enabled under both html and singlehtml builder.
Because the format of singlehtml builder is html.
So you'll see README twice in singlehtml.

**Comment by Carelvd** [comment] 2017-01-15 16:27
Hmm... I'm using the autogenerated `make.bat` file to build my documentation. Before posting I looked at how this invoked `Sphinx-Build`. It only sets the `-b BUILDER` flag but it does not set any `-t BUILDER` flag. 

I also looked at the tags that were set within the `conf.py` file (I just printed them to the command line) and this showed an empty set. There does not appear to be any mechanism by which the builder set by `-b BUILDER` is copied into the set of tags. Perhaps this happens after the `conf.py` is read ?

Either way I started explicitly setting the `-t BUILDER` flag as described above (I also tried setting the flags within my `conf.py` by parsing the command line arguments and explicitly setting the builder within the tags) and the `readme.rst` would still pop up arbitrarily, which lead me to believe the Only directive does not behave as documented and is the reason I posted the Issue. 

Perhaps I'm getting these weird outputs as the first `only` directive appears before the first heading ?

**Comment by tk0miya** [comment] 2017-01-15 17:24
>Perhaps this happens after the conf.py is read ?

Yes, it is initialized after that.
https://github.com/sphinx-doc/sphinx/blob/master/sphinx/builders/__init__.py#L78

>Perhaps I'm getting these weird outputs as the first only directive appears before the first heading ?

I can't answer because I can't reproduce your problem yet.
Could you show me your project or minimal reproducible one?

**Comment by tk0miya** [comment] 2017-02-20 04:58
Now I'm closing this issue.
Please reopen if you still have the problem.

Thanks,

**Closed as completed by tk0miya** 2017-02-20 04:58 UTC
Labels: type:question, markup
