### ISSUE TITLE
AttributeError: module 'sphinx.domains.cpp' has no attribute 'CPPUnionObject'

### ISSUE THREAD

**Issue by benfulton** [sphinx-doc/sphinx#6285] opened 2019-04-12 20:24 UTC
**Describe the bug**
Trying to use Breathe to import some Doxygen files

**To Reproduce**
```
$ make html
Running Sphinx v1.6.7

Exception occurred:
  File "/breathe-4.12.0/breathe/renderer/sphinxrenderer.py", line 80, in DomainDirectiveFactory
    'union': (cpp.CPPUnionObject, 'union'),
AttributeError: module 'sphinx.domains.cpp' has no attribute 'CPPUnionObject'
The full traceback has been saved in /tmp/sphinx-err-zro83vpq.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Makefile:20: recipe for target 'html' failed
make: *** [html] Error 1
```

**Environment info**
- OS: Ubuntu 18 through Windows Subsystem for Linux
- Python version: 3.6.7
- Sphinx version: 1.6.7
- Sphinx extensions:  Breathe

**Additional context**
I tried various options to get Sphinx and Breathe to install, including apt-get, pip, pip3, and Git. It's very likely I ended up with some odd incompatibility.

from conf.py:

```
sys.path.append('/breathe-4.12.0')
extensions = ['breathe']
breathe_projects = {
    "docs":"../../src_docs/xml",
    }
breathe_default_project = "docs"
```

**Comment by tk0miya** [comment] 2019-04-13 03:47
The `CPPUnionObject` class was added since 1.8. I guess the version of breathe and Sphinx are mismatched. Please upgrade your Sphinx.
Thanks,

**Comment by tk0miya** [comment] 2019-05-14 16:44
I'm closing this because this is not a bug of Sphinx.
Thanks,

**Closed as completed by tk0miya** 2019-05-14 16:44 UTC
Labels: type:question, domains:cpp
