### ISSUE TITLE
sphinx autosummary: "failed to import Child.model" (inherited instance attribute)

### ISSUE THREAD

**Issue by AntonioCarta** [sphinx-doc/sphinx#9884] opened 2021-11-22 13:16 UTC
### Describe the bug

I'm having trouble with sphinx and autosummary. Apparently, sphinx is unable to document inherited instance attributes. For some reason, the resulting error is an import error.

python code:
```
class Base:
    """Base class."""

    def __init__(self, **kwargs):
        """Init."""
        self.model = None
        """An attribute."""


class Child(Base):
    """Child class."""

    def __init__(self, **kwargs):
        """Init."""
        super().__init__()
        pass
```

rst documentation file:
```
.. autosummary::
    :toctree: generated

    mylib.Base
    mylib.Child
```
when I run sphinx-build with `make html` I get the following error:
```
.../new_docs/generated/mylib.Child.rst:24: WARNING: autosummary: failed to import Child.model
```

Notice that everything else is imported correctly, so this is not a path issue.
Is this a bug? According to #3257 it should be supported. I'm using sphinx-build 4.3.0.

### How to Reproduce

MWE to reproduce the error: [sphinx-demo.zip](https://github.com/sphinx-doc/sphinx/files/7581235/sphinx-demo.zip)
unzip the archive
```
$ cd docs
$ make html
```

### Expected behavior

inherited instance attributes are documented correctly and without warnings.

### Your project

[sphinx-demo.zip](https://github.com/sphinx-doc/sphinx/files/7581235/sphinx-demo.zip)

### OS

WSL 2 (Ubuntu)

### Python version

3.9.7

### Sphinx version

4.3.0

### Sphinx extensions

sphinx.ext.autosummary

**Comment by smarie** [comment] 2022-04-09 12:19
Same problem here. Is this a regression ?

**Comment by melissawm** [comment] 2022-04-18 18:42
It looks like this was supposed to be fixed by #9146, but I'm also seeing this problem. In my case, I was able to fix this using a jinja filter to simply remove the instance attributes from the docs, but it looks like a very clunky solution - and ideally those instance attributes should be documented.

**Comment by AntonioCarta** [comment] 2022-05-11 08:42
@melissawm could you share your jinja filter? It would help as a temporary fix until this is fixed.

**Comment by jenshnielsen** [comment] 2022-07-16 11:55
I had a look at this trying to figure out what goes wrong. As far as I can see the issue is that [import_ivar_by_name](https://github.com/sphinx-doc/sphinx/blob/5.x/sphinx/ext/autosummary/__init__.py#L718) only returns a result if qualname (aka. the name of the Class we are trying to document) is in the name found by ModuleAnalyzer. However for an inherited attribute the name found will be the name of the super class so nothing useful is returned an an ImportError is raised

**Comment by melissawm** [comment] 2022-07-18 16:23
Sure @AntonioCarta [here you go](https://github.com/napari/napari/blob/e490e5535438ab338a23b17905a1952f15a6d27a/docs/conf.py#L180)!

**Comment by jenshnielsen** [comment] 2022-08-12 15:04
@AntonioCarta @janlugt @melissawm Any change that any of you could test my suggested fix in #10691 I have been using it for a while and it seems to resolve my issue

**Comment by mbraakhekke** [comment] 2022-08-13 12:33
I have the same problem and can confirm that #10691 fixes it for me. Thanks! Hope this gets merged soon!

**Comment by taylorm0192** [comment] 2022-08-14 05:53
@jenshnielsen Very keen to have this cut into a new version asap as well, so thank you first for making the PR and second pushing to get it tested/released!  This bug spams our doc builds with all of these silly import errors because of our heavy use of derivative dataclasses.

**Comment by leotrs** [comment] 2022-12-19 20:14
One more for "I have this problem and #10691 " is the fix. Thanks @jenshnielsen

**Comment by oselcuk-iqm** [comment] 2023-01-23 11:59
We also have this problem and #10691 fixes it

**Comment by 12rambau** [comment] 2023-03-07 12:33
One more for "I have this problem and https://github.com/sphinx-doc/sphinx/pull/10691 is the fix". Thanks @jenshnielsen

**Closed as completed** 2023-04-06 22:33 UTC
Labels: type:bug
