### ISSUE TITLE
Wrong indexing of nested attributes

### ISSUE THREAD

**Issue by Bibo-Joshi** [sphinx-doc/sphinx#8657] opened 2021-01-05 17:21 UTC
# Describe the bug
When documenting an attribute of a class attribute, the nested attribute is wrongly indexed as attribute of the class instead of the attribute. However, it's correctly indented in the rendered version.

# To Reproduce
I built an MWE for this, both in an autodoc-variant and with manual documentation
```
$ git clone https://github.com/Bibo-Joshi/sphinx-mwe
$ cd some_project
$ pip install -r requirements.txt
$ make html
$ # open build/html/mwe.html
```
## TL;DR:

```
.. py:class:: Parent

    .. py:attribute:: attr

        .. py:attribute:: hidden_attribute
```
`hidden_attribute` will be indexed as `Parent.hidden_attribute` instead of `Parent.attr.hidden_attribute`

# Expected behavior
Indexing respects indention.

# Your project
We use something like this at https://python-telegram-bot.readthedocs.io/en/stable/telegram.ext.filters.html

# Screenshots
![image](https://user-images.githubusercontent.com/22366557/103676624-97bc2f00-4f81-11eb-9450-2f7cc527c344.png)

# Environment info
- OS: Win
- Python version: 3.8
- Sphinx version: 3.4.2
- Sphinx extensions:  sphinx.ext.autodoc, sphinx.ext.napoleon
- Extra tools: Browser

# Additional context
- Maybe related to #7551 ?
- I know that it's a rather specific/unconventional use case … Still I was surprised that this doesn't work

**Comment by tk0miya** [comment] 2021-01-07 17:12
At present, `py:attribute` directive represents an attribute of a class, not for an object. Surely, it can be nested. But it does not mean supporting a "nested" attribute.

**Comment by Bibo-Joshi** [comment] 2021-01-07 19:47
Okay, thanks for the response :)
May I understand you adding the `enhancement` label as invitation to PR? If so, would you mind pointing me in the right direction? (I'm completely new to the internals of Sphinx …)
If not: There probably isn't an easy workaround expect writing a custom extension? Also in this case, maybe the documentation (currently "Describes an object data attribute.") could be updated (object -> class)

**Comment by jakobandersen** [comment] 2021-01-08 13:53
I suggest you invent a fake class or perhaps a prototype class which you can set as the type of the outer attribute. The inner attribute can then be moved to that class. In this way it mimics what the code is really doing.

**Comment by tk0miya** [comment] 2021-01-08 15:08
I consider this is a feature request, not a bug report. That's only reason why I changed the label of this issue. It does not mean I adopted this idea. Nothing determined yet. Personally, I vote -0 for this because I don't know how important to describe the attribute of attribute. Addition to this, it's complicated to implement it. I feel too expensive to support it.

**Comment by Bibo-Joshi** [comment] 2021-01-08 17:33
@tk0miya All right, thanks for the clarification. I guess I won't start to try if you already guess that it will be complicated.

@jakobandersen I'm not sure if I get you. You'd move the documentation of the inner attribute to the documentation of the class, the outer attribute is an istance of? That's what I'd like to circumvent …

**Comment by tk0miya** [comment] 2021-01-16 13:59
Thank you for proposal. But I marked this as "wontfix" as I commented above.

**Closed as completed by tk0miya** 2021-01-16 13:59 UTC
Labels: type:enhancement, closed:wontfix, domains:py
