### ISSUE TITLE
Latex: terms are not separated by a newline

### ISSUE THREAD

**Issue by marxin** [sphinx-doc/sphinx#9985] opened 2021-12-17 11:54 UTC
### Describe the bug

I use simple indentations for terms and their explanation:

Example:
```rst
Listing:

:samp:`{file}.cc` :samp:`{file}.cp` :samp:`{file}.cxx` :samp:`{file}.cpp` :samp:`{file}.CPP` :samp:`{file}.c++` :samp:`{file}.C`
  C++ source code that must be preprocessed.  Note that in :samp:`.cxx`,
  the last two letters must both be literally :samp:`x`.  Likewise,
  :samp:`.C` refers to a literal capital C.

:samp:`{file}.mm` :samp:`{file}.M`
  Objective-C++ source code that must be preprocessed.

:samp:`{file}.mii`
  Objective-C++ source code that should not be preprocessed.

:samp:`{file}.hh` :samp:`{file}.H` :samp:`{file}.hp` :samp:`{file}.hxx` :samp:`{file}.hpp` :samp:`{file}.HPP` :samp:`{file}.h++` :samp:`{file}.tcc`
  C++ header file to be turned into a precompiled header or Ada spec
```

Which results in the following HTML output:

Alabaster:

![Screenshot from 2021-12-17 12-49-36](https://user-images.githubusercontent.com/2658545/146541051-3d7144ca-e155-41a9-a6f3-3b7ee48efb8e.png)

RTD theme:

![Screenshot from 2021-12-17 12-49-50](https://user-images.githubusercontent.com/2658545/146541053-a8164c2b-5ed7-48b2-b5bb-2ec304eefea4.png)

While xelatex output does not contain a new line:

![Screenshot from 2021-12-17 12-50-53](https://user-images.githubusercontent.com/2658545/146541114-0d1ebd78-1ae3-4fed-b06d-7ed45fe1db33.png)

@jfbu

### How to Reproduce

Build the snippet.

### Your project

Build the snippet

### OS

Linux

### Python version

3.8

### Sphinx version

4.3.0

**Comment by tk0miya** [comment] 2021-12-18 09:54
I don't think this is not a bug. It's not promised a term and description of the definition list are displayed as line-folded.

But I agree it's better to fold them as HTML does.

**Comment by marxin** [comment] 2021-12-18 16:09
Great, thanks for the suggested pull request!

**Comment by jfbu** [comment] 2021-12-18 16:50
@marxin It may take some time before a solution is found because the natural #9988 approach breaks some numpy's LaTeX hack. As a work-around you may try to add to your project their hack
```
latex_elements = {
    'preamble': r'''
% In the parameters section, place a newline after the Parameters
% header
\usepackage{expdlist}
\let\latexdescription=\description
\def\description{\latexdescription{}{} \breaklabel}
% but expdlist old LaTeX package requires fixes:
% 1) remove extra space
\usepackage{etoolbox}
\makeatletter
\patchcmd\@item{{\@breaklabel} }{{\@breaklabel}}{}{}
\makeatother
% 2) fix bug in expdlist's way of breaking the line after long item label
\makeatletter
\def\breaklabel{%
    \def\@breaklabel{%
        \leavevmode\par
        % now a hack because Sphinx inserts \leavevmode after term node
        \def\leavevmode{\def\leavevmode{\unhbox\voidb@x}}%
    }%
}
\makeatother
''',
}
```
I am not completely happy with the resulting looks (see https://github.com/sphinx-doc/sphinx/pull/9988#issuecomment-997227939) but it may serve temporarily.

**Comment by jfbu** [comment] 2021-12-23 18:08
Closed via https://github.com/sphinx-doc/sphinx/commit/9e8e3f9a6efa3f30ecd873a21eca0bfb721588bf (#9999)

**Closed as completed by jfbu** 2021-12-23 18:08 UTC
Labels: builder:latex, type:proposal
