### ISSUE TITLE
Sphinx not respecting __signature__

### ISSUE THREAD

**Issue by asmeurer** [sphinx-doc/sphinx#7613] opened 2020-05-04 21:56 UTC
I am having an issue with Sphinx 3.0.3 where classes that define `__signature__` are being shown with `*args` (the naive signature from `__init__`). This is the project https://github.com/Quansight/ndindex/tree/master/docs.

See for example https://quansight.github.io/ndindex/api.html#slice. The signature on the class in the docs says "Slice(*args)". But if you call inspect.signature, you get

```py
>>> from ndindex import Slice
>>> import inspect
>>> inspect.signature(Slice)
<Signature (start, stop=<class 'ndindex.slice.default'>, step=None)>
```

You can see `__signature__` defined on the superclass [here](https://github.com/Quansight/ndindex/blob/6367b37d4d89094038568e43788208caa1f6de38/ndindex/ndindex.py#L99). 

This was supposedly fixed in #2828, so either there was a regression, or else somehow the code doesn't handle what I am doing properly

**Comment by tk0miya** [comment] 2020-05-10 12:43
Note: ndindex provides `Slice.__signature__` via classproperty. But autodoc refers `Slice.__init__.__signature__` instead. This will not be fixed even if #7384 merged.

https://github.com/Quansight/ndindex/blob/6367b37d4d89094038568e43788208caa1f6de38/ndindex/ndindex.py#L98-L107

**Comment by asmeurer** [comment] 2020-05-10 22:32
I use a class property so that help() shows the signature on the class, not just on instances. Looking at the `__signature__` of the init method itself doesn't seem helpful. Is that even something that can be overridden?

**Comment by eric-wieser** [comment] 2020-05-26 14:22
This ought to be fairly straightforward to add another special-case for.

The problem is that Sphinx cannot use `inspect.signature` directly, as doing so would skip its hooks that allow it to parse `# type:` comments. So Sphinx tries to implement its own version of `inspect.signature` that lines up with the regular implementation in the cases that were worth thinking about.

In this case, that implementation is missing the code path for a `__signature__` attribute.

**Closed as completed** 2020-11-04 16:51 UTC
Labels: type:bug, extensions:autodoc
