### ISSUE TITLE
AttributeError: Values instance has no attribute 'link_base'

### ISSUE THREAD

**Issue by aztrock** [sphinx-doc/sphinx#5285] opened 2018-08-10 21:49 UTC
Subject: <what happen when you do on which document project>

### Problem
Two automodules in same file

#### Procedure to reproduce the problem
```
make html
```

#### Error logs / results
```
# Sphinx version: 1.7.6
# Python version: 2.7.3 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:
#   Running Sphinx v1.7.6
#   loading translations [es]...
#   done
#   loading pickled environment...
#   done
#   building [mo]: targets for 0 po files that are out of date
#   building [html]: targets for 1 source files that are out of date
#   updating environment:
#   0 added, 1 changed, 0 removed
#   reading sources... [100%] citoplus/models
# Loaded extensions:
#   sphinx.ext.coverage (1.7.6) from /opt/citoplus/local/lib/python2.7/site-packages/sphinx/ext/coverage.pyc
#   sphinx.ext.napoleon (1.7.6) from /opt/citoplus/local/lib/python2.7/site-packages/sphinx/ext/napoleon/__init__.pyc
#   sphinx.ext.todo (1.7.6) from /opt/citoplus/local/lib/python2.7/site-packages/sphinx/ext/todo.pyc
#   sphinx.ext.autodoc (1.7.6) from /opt/citoplus/local/lib/python2.7/site-packages/sphinx/ext/autodoc/__init__.pyc
#   sphinxcontrib_django (unknown version) from /opt/citoplus/local/lib/python2.7/site-packages/sphinxcontrib_django/__init__.pyc
#   alabaster (0.7.11) from /opt/citoplus/local/lib/python2.7/site-packages/alabaster/__init__.pyc
#   celery.contrib.sphinx (unknown version) from /opt/citoplus/local/lib/python2.7/site-packages/celery/contrib/sphinx.pyc
Traceback (most recent call last):
  File "/opt/citoplus/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 304, in main
    app.build(args.force_all, filenames)
  File "/opt/citoplus/local/lib/python2.7/site-packages/sphinx/application.py", line 331, in build
    self.builder.build_update()
  File "/opt/citoplus/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 342, in build_update
    'out of date' % len(to_build))
  File "/opt/citoplus/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 355, in build
    updated_docnames = set(self.env.update(self.config, self.srcdir, self.doctreedir))
  File "/opt/citoplus/local/lib/python2.7/site-packages/sphinx/environment/__init__.py", line 565, in update
    self._read_serial(docnames, self.app)
  File "/opt/citoplus/local/lib/python2.7/site-packages/sphinx/environment/__init__.py", line 584, in _read_serial
    self.read_doc(docname, app)
  File "/opt/citoplus/local/lib/python2.7/site-packages/sphinx/environment/__init__.py", line 659, in read_doc
    doctree = read_doc(self.app, self, self.doc2path(docname))
  File "/opt/citoplus/local/lib/python2.7/site-packages/sphinx/io.py", line 302, in read_doc
    pub.publish()
  File "/opt/citoplus/local/lib/python2.7/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/opt/citoplus/local/lib/python2.7/site-packages/docutils/readers/__init__.py", line 72, in read
    self.parse()
  File "/opt/citoplus/local/lib/python2.7/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/opt/citoplus/local/lib/python2.7/site-packages/sphinx/parsers.py", line 85, in parse
    self.statemachine.run(inputstring, document, inliner=self.inliner)
  File "/opt/citoplus/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File "/opt/citoplus/local/lib/python2.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/opt/citoplus/local/lib/python2.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/opt/citoplus/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2753, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/opt/citoplus/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/opt/citoplus/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/opt/citoplus/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/opt/citoplus/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/opt/citoplus/local/lib/python2.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/opt/citoplus/local/lib/python2.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/opt/citoplus/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2753, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/opt/citoplus/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/opt/citoplus/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/opt/citoplus/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/opt/citoplus/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/opt/citoplus/local/lib/python2.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/opt/citoplus/local/lib/python2.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/opt/citoplus/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2326, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/opt/citoplus/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2338, in explicit_construct
    return method(self, expmatch)
  File "/opt/citoplus/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2081, in directive
    directive_class, match, type_name, option_presets)
  File "/opt/citoplus/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2130, in run_directive
    result = directive_instance.run()
  File "/opt/citoplus/local/lib/python2.7/site-packages/sphinx/ext/autodoc/directive.py", line 144, in run
    result = parse_generated_content(self.state, params.result, documenter)
  File "/opt/citoplus/local/lib/python2.7/site-packages/sphinx/ext/autodoc/directive.py", line 85, in parse_generated_content
    nested_parse_with_titles(state, content, node)
  File "/opt/citoplus/local/lib/python2.7/site-packages/sphinx/util/nodes.py", line 219, in nested_parse_with_titles
    return state.nested_parse(content, 0, node, match_titles=1)
  File "/opt/citoplus/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/opt/citoplus/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/opt/citoplus/local/lib/python2.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/opt/citoplus/local/lib/python2.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/opt/citoplus/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2328, in explicit_markup
    self.explicit_list(blank_finish)
  File "/opt/citoplus/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2358, in explicit_list
    match_titles=self.state_machine.match_titles)
  File "/opt/citoplus/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 319, in nested_list_parse
    node=node, match_titles=match_titles)
  File "/opt/citoplus/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/opt/citoplus/local/lib/python2.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/opt/citoplus/local/lib/python2.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/opt/citoplus/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2631, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/opt/citoplus/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2338, in explicit_construct
    return method(self, expmatch)
  File "/opt/citoplus/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2081, in directive
    directive_class, match, type_name, option_presets)
  File "/opt/citoplus/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2130, in run_directive
    result = directive_instance.run()
  File "/opt/citoplus/local/lib/python2.7/site-packages/sphinx/domains/__init__.py", line 237, in run
    return BaseDirective.run(self)
  File "/opt/citoplus/local/lib/python2.7/site-packages/sphinx/directives/__init__.py", line 179, in run
    self.state.nested_parse(self.content, self.content_offset, contentnode)
  File "/opt/citoplus/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/opt/citoplus/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/opt/citoplus/local/lib/python2.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/opt/citoplus/local/lib/python2.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/opt/citoplus/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2767, in text
    paragraph, literalnext = self.paragraph(lines, startline)
  File "/opt/citoplus/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 418, in paragraph
    textnodes, messages = self.inline_text(text, lineno)
  File "/opt/citoplus/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 427, in inline_text
    return self.inliner.parse(text, lineno, self.memo, self.parent)
  File "/opt/citoplus/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 645, in parse
    lineno)
  File "/opt/citoplus/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 787, in interpreted_or_phrase_ref
    lineno)
  File "/opt/citoplus/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 871, in interpreted
    nodes, messages2 = role_fn(role, rawsource, text, lineno, self)
  File "/opt/citoplus/local/lib/python2.7/site-packages/django/contrib/admindocs/utils.py", line 126, in _role
    inliner.document.settings.link_base,
AttributeError: Values instance has no attribute 'link_base'

```

#### Expected results
two automodule. same file

```
Models                                                                          
======                                                                          
                                                                                 
Home                                                                            
____                                                                            
.. automodule:: app.home.models                                                                                                                            
    :members:                                                                   
                                                                                
Usuarios                                                                        
________                                                                        
.. automodule:: app.usuarios.models                                             
    :members:   
```

### Environment info
- OS: Linux debian 7
- Python version: 2.7
- Sphinx version: 1.7.6

**Comment by tk0miya** [comment] 2018-08-13 16:29
It seems `link_base` attribute is not a standard attribute of docutils. It is not also used in Sphinx. I guess it is an original attribute of django's extension.
So I think this is not a bug of Sphinx.

**Comment by tk0miya** [comment] 2018-08-22 14:28
I'm closing this because this is not a bug of Sphinx.
Thanks,

**Closed as completed by tk0miya** 2018-08-22 14:28 UTC
Labels: type:question
