### ISSUE TITLE
bulleted lists defined with dash (-) produce badly formatted output

### ISSUE THREAD

**Issue by Phillip-M-Feldman** [sphinx-doc/sphinx#6027] opened 2019-02-06 06:42 UTC
The attached source code defines some bulleted lists using hyphens (-).  Sphinx appears to understand this markup--it does produce a bulleted list in the generated html--but the formatting is fouled up.  In particular, there is extra space between the first line of a paragraph and the second, which is confusing to the reader.

[Sphinx issues.zip](https://github.com/sphinx-doc/sphinx/files/2835120/Sphinx.issues.zip)

**Comment by tk0miya** [comment] 2019-02-06 13:45
It seems your document is not correct reStructured Text format.

>A text block which begins with a "*", "+", "-", "•", "‣", or "⁃", followed by whitespace, is a bullet list item (a.k.a. "unordered" list item). List item bodies must be left-aligned and indented relative to the bullet; the text immediately after the bullet determines the indentation.
http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#bullet-lists

Please make following lines indented.

**Comment by tk0miya** [comment] 2019-05-14 16:46
I'm closing this now because this is not a bug of Sphinx.
Thanks,

**Closed as completed by tk0miya** 2019-05-14 16:46 UTC
Labels: type:question
