### ISSUE TITLE
Import errro RemovedInSphinx40Warning

### ISSUE THREAD

**Issue by cvanelteren** [sphinx-doc/sphinx#9441] opened 2021-07-13 07:06 UTC
### Describe the bug

When buildings docs I am getting

```
Could not import extension sphinx.builders.epub3 (exception: cannot import name 'RemovedInSphinx40Warning' from 'sphinx.deprecation' (/home/casper/miniconda3/lib/python3.9/site-packages/sphinx/deprecation.py))
```

### How to Reproduce

```
git clone https://github.com/sphinx-doc/sphinx
cd $sphinx && python setup.py install
git clone https://github.com/cvanelteren/Plexsim
cd Plexsim && make html
```

### Expected behavior

Build the docs without error.

Tested on 4.1.0 and latest 4.2.0 dev

### Your project

https://github.com/cvanelteren/Plexsim

### Screenshots

Running Sphinx v4.1.0

Extension error:
Could not import extension sphinx.builders.epub3 (exception: cannot import name 'RemovedInSphinx40Warning' from 'sphinx.deprecation' (/home/casper/miniconda3/lib/python3.9/site-packages/sphinx/deprecation.py))
make: *** [Makefile:19: html] Error 2

### OS

Linux arch 5.12.14

### Python version

3.9.6

### Sphinx version

4.1.0 / 4.2.0

### Sphinx extensions

sphinx.ext.autodoc, sphinx.ext.napoleon, sphinxemoji.sphinxemoji, sphinx.ext.autosummary

**Comment by cvanelteren** [comment] 2021-07-13 07:07
As a workaround 4.0 works fine for me!

**Comment by jakobandersen** [comment] 2021-07-13 07:50
Duplicate of #9434?

**Comment by cvanelteren** [comment] 2021-07-13 10:53
Ah yes. Didn't see it my bad!

**Closed as completed** 2021-07-13 10:53 UTC
Labels: type:bug
