### ISSUE TITLE
Invalid XHTML generated

### ISSUE THREAD

**Issue by Jellby** [sphinx-doc/sphinx#1733] opened 2015-02-20 15:16 UTC
The generated XHTML does not validate at http://validator.w3.org/ because the "role" and "aria-label" attributes are not recognized (and, as far as I know, XHTML is not like CSS, where you can use any kind of custom property).

In addition, a table with labels, such as this:

```
.. _my_label:

.. _test_table:

.. table:: Table caption

   === === ===
   1   2   3
   4   5   6
   === === ===
```

generates invalid code:

```
<table border="1" class="docutils" id="id1">
<span id="test-table"></span><span id="my-label"></span><caption>...</caption>
<colgroup>
```

The `<span>` elements are not allowed as a table child. They should be inside the `<caption>` element or outside the table in a wrapper `<div>` or something.

**Comment by shimizukawa** [comment] 2015-02-20 22:20
hum.. strange..  I couldn't reproduce the html structure.
Which sphinx and docutils versions are you use? (I guess you're using Sphinx-1.3b2)
And if you are using some extensions, please let me know too. Thanks.

**Comment by shimizukawa** [comment] 2015-02-21 05:36
I got. I had looked html element tree by using browser's debugger that correct element order silently...
As you mentioned, HTML source indicate `<span>` tag place after `<table>` tag, it's wrong.

  HTML 4.01 also invalid `<span>` in a `<table>`
  http://www.w3.org/TR/html401/struct/tables.html#h-11.2.1

I'll fix it.

**Comment by shimizukawa** [comment] 2015-02-21 06:15
Hum.. in my short inspection, it's bit complex to fix it.. I'll fix it after 1.3 release.

**Comment by Jellby** [comment] 2015-02-21 07:48
What about "role" and "aria-label"? Those are HTML5 attributes, if I'm not mistaken, but by default the html is declared as XHTML.

**Comment by mgifford** [comment] 2016-05-16 09:33
Did this get fixed in the last release @shimizukawa

**Comment by shimizukawa** [comment] 2016-05-16 09:39
Not yet. It is caused by docutils implementation. For now we have no idea to tweak it from sphinx code.

**Comment by mgifford** [comment] 2016-05-16 09:41
I don't know this project well enough. I'm a PHP guy when it boils down to it. Where is the docutils code managed? Where is the community behind it?

**Comment by shimizukawa** [comment] 2016-05-16 09:44
Here: http://docutils.sourceforge.net/

**Comment by mgifford** [comment] 2016-05-16 10:25
Oh dear.. It's on SF.net & last release was on 2014-07-06. Not a good sign.

**Comment by tk0miya** [comment] 2017-03-02 17:01
An experimental HTML5 writer is now introduced at #3464.
Thanks,

**Comment by tk0miya** [comment] 2017-03-02 17:12
Unfortunately, new HTML5 writer also has same issue (refs: #1562)

**Comment by shibukawa** [comment] 2017-03-02 18:12
I reported to docutils. https://sourceforge.net/p/docutils/bugs/312/

**Comment by shibukawa** [comment] 2017-03-02 23:50
There is working around for adding reference-name to tables.

Adding id by using name parameter keep away from invalid HTML now.

```
... table:: Caption Text
    :name: ref
```

**Closed as completed** 2017-03-03 04:40 UTC
Labels: builder:html
