### ISSUE TITLE
Broken support of rst2pdf

### ISSUE THREAD

**Issue by enchantner** [sphinx-doc/sphinx#1844] opened 2015-04-13 14:19 UTC
After updating on Sphinx 1.3 a huge traceback now appears in logs of 'make pdf'. Build is labeled as succeed, though, but looks like there is some bug.

```
[ERROR] pdfbuilder.py:130 list index out of range
Traceback (most recent call last):
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/rst2pdf/pdfbuilder.py", line 127, in write
    docwriter.write(doctree, destination)
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/rst2pdf/pdfbuilder.py", line 621, in translate
    compressed=self.compressed)
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/rst2pdf/createpdf.py", line 561, in createPdf
    elements = self.gen_elements(self.doctree)
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 250, in elemdispatch
    elements = self.getelements(client, node, style)
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 225, in getelements
    elements = self.gather_elements(client, node, style)
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 205, in gather_elements
    return client.gather_elements(node, style=style)
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/rst2pdf/createpdf.py", line 390, in gather_elements
    r.extend(self.gen_elements(n, style=style))
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 250, in elemdispatch
    elements = self.getelements(client, node, style)
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 225, in getelements
    elements = self.gather_elements(client, node, style)
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/rst2pdf/genelements.py", line 442, in gather_elements
    elements = client.gather_elements(node)
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/rst2pdf/createpdf.py", line 390, in gather_elements
    r.extend(self.gen_elements(n, style=style))
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 250, in elemdispatch
    elements = self.getelements(client, node, style)
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 225, in getelements
    elements = self.gather_elements(client, node, style)
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 205, in gather_elements
    return client.gather_elements(node, style=style)
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/rst2pdf/createpdf.py", line 390, in gather_elements
    r.extend(self.gen_elements(n, style=style))
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 250, in elemdispatch
    elements = self.getelements(client, node, style)
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 225, in getelements
    elements = self.gather_elements(client, node, style)
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 205, in gather_elements
    return client.gather_elements(node, style=style)
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/rst2pdf/createpdf.py", line 390, in gather_elements
    r.extend(self.gen_elements(n, style=style))
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 250, in elemdispatch
    elements = self.getelements(client, node, style)
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 225, in getelements
    elements = self.gather_elements(client, node, style)
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/rst2pdf/genelements.py", line 442, in gather_elements
    elements = client.gather_elements(node)
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/rst2pdf/createpdf.py", line 390, in gather_elements
    r.extend(self.gen_elements(n, style=style))
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 250, in elemdispatch
    elements = self.getelements(client, node, style)
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 225, in getelements
    elements = self.gather_elements(client, node, style)
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 205, in gather_elements
    return client.gather_elements(node, style=style)
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/rst2pdf/createpdf.py", line 390, in gather_elements
    r.extend(self.gen_elements(n, style=style))
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 250, in elemdispatch
    elements = self.getelements(client, node, style)
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 225, in getelements
    elements = self.gather_elements(client, node, style)
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 205, in gather_elements
    return client.gather_elements(node, style=style)
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/rst2pdf/createpdf.py", line 390, in gather_elements
    r.extend(self.gen_elements(n, style=style))
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 250, in elemdispatch
    elements = self.getelements(client, node, style)
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 225, in getelements
    elements = self.gather_elements(client, node, style)
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/rst2pdf/genelements.py", line 442, in gather_elements
    elements = client.gather_elements(node)
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/rst2pdf/createpdf.py", line 390, in gather_elements
    r.extend(self.gen_elements(n, style=style))
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 250, in elemdispatch
    elements = self.getelements(client, node, style)
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 225, in getelements
    elements = self.gather_elements(client, node, style)
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/rst2pdf/genelements.py", line 484, in gather_elements
    style = style)
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/rst2pdf/createpdf.py", line 390, in gather_elements
    r.extend(self.gen_elements(n, style=style))
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 250, in elemdispatch
    elements = self.getelements(client, node, style)
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 225, in getelements
    elements = self.gather_elements(client, node, style)
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/rst2pdf/genelements.py", line 576, in gather_elements
    el = client.gather_elements(node, item_st)
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/rst2pdf/createpdf.py", line 390, in gather_elements
    r.extend(self.gen_elements(n, style=style))
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 250, in elemdispatch
    elements = self.getelements(client, node, style)
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 225, in getelements
    elements = self.gather_elements(client, node, style)
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/rst2pdf/genelements.py", line 188, in gather_elements
    return [Paragraph(client.gen_pdftext(node), style)]
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 280, in textdispatch
    text = self.get_text(client, node, replaceEnt)
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 266, in get_text
    return client.gather_pdftext(node)
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/rst2pdf/createpdf.py", line 380, in gather_pdftext
    for n in node.children])
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 280, in textdispatch
    text = self.get_text(client, node, replaceEnt)
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 266, in get_text
    return client.gather_pdftext(node)
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/rst2pdf/createpdf.py", line 380, in gather_pdftext
    for n in node.children])
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 279, in textdispatch
    pre, post = self.get_pre_post(client, node, replaceEnt)
  File "/home/meow-nofer/.virtualenvs/fuel/local/lib/python2.7/site-packages/rst2pdf/genpdftext.py", line 232, in get_pre_post
    r = client.styleToTags(node['classes'][0])
IndexError: list index out of range
FAILED
build succeeded.
```

**Comment by pditommaso** [comment] 2015-07-31 19:52
Same here. Actually version `Sphinx (sphinx-build) 1.3.1`

**Comment by emmanuelmathot** [comment] 2015-10-06 07:51
Same issue. It works with sphinx 1.2.3.
Any plan to correct this regression?

**Comment by emmanuelmathot** [comment] 2015-10-06 08:08
it is solved with current master version v1.4a0+. Why not reporting it here?

**Comment by joest67** [comment] 2015-12-14 16:30
Same issue, and it works with sphinx < 1.3.

**Comment by tk0miya** [comment] 2016-01-14 12:51
MEMO: It seems this is same error as https://github.com/rst2pdf/rst2pdf/issues/556

**Comment by tk0miya** [comment] 2016-01-16 14:38
In my short investigation:
Before Sphinx-1.3,  the internal references is represented by `nodes.emphasis`. They are not having any classes. However, rst2pdf do not mind that.

Since Sphinx-1.3 (at 8a273d139b74124b11c4b1ba81db3cc0866d9102), Sphinx uses `nodes.inline` instead of `nodes.emphasis` to represent the internal references. They are also having no classes.
But, for all of `nodes.inline` nodes, rst2pdf expects them to have any classes. It causes this IndexError.

BTW, in master branch, we can convert PDF successfully with rst2pdf.
It comes from 6efafcdca49667e37be7323592faadae3ec7972b.
It changes the behavior of the internal references. After this commit, they are represent by `nodes.inline` having `std` and `std-ref` classes.
This change satisfies the expectation of rst2pdf. So Sphinx-1.4a0+ can do without errors.

So this error is come from 8a273d139b74124b11c4b1ba81db3cc0866d9102.
but it says this is a incompatible change:

> - Roles `ref`, `term` and `menusel` now don't generate :durole:`emphasis`
>   nodes anymore.  If you want to keep italic style, adapt your stylesheet.

So I can not determine this is a bug or not.

**Comment by shimizukawa** [comment] 2016-01-16 15:18
It looks there is nothing to do from Sphinx side. The problem should be resolved by the rst2pdf builder by adapting to node structure after Sphinx-1.3. Now I close this ticket.

**Closed as completed by shimizukawa** 2016-01-16 15:18 UTC
