### ISSUE TITLE
5.1.0 Extension error (sphinx.ext.napoleon): (exception: pop from an empty deque)

### ISSUE THREAD

**Issue by Zlopez** [sphinx-doc/sphinx#10705] opened 2022-07-25 12:13 UTC
### Describe the bug

When updating sphinx from 5.0.2 to 5.1.0 following error started happening in sphinx build of [Anitya](https://github.com/fedora-infra/anitya) project:
```
Extension error (sphinx.ext.napoleon):
Handler <function _process_docstring at 0x7fb4a98f60e0> for event 'autodoc-process-docstring' threw an exception (exception: pop from an empty deque)
```

### How to Reproduce

```
$ git clone https://github.com/fedora-infra/anitya
$ git checkout dependabot/pip/sphinx-5.1.0
$ pip install -r requirements.txt -r test_requirements.txt
$ pip install .
$ cd docs
$ sphinx-build -W -b html  .  _build/html
```

### Expected behavior

Documentation is build

### Your project

https://github.com/fedora-infra/anitya

### OS

Linux

### Python version

3.10.5

### Sphinx version

5.1.0

### Sphinx extensions

sphinx.ext.napoleon

**Comment by vfazio** [comment] 2022-07-25 13:44
Same, our project is now running into this.

**Comment by vfazio** [comment] 2022-07-25 14:10
probably dupe of #10701 caused by #9856

**Comment by AA-Turner** [comment] 2022-07-25 21:57
Duplicates #10701

**Closed as not planned by AA-Turner** 2022-07-25 21:57 UTC
Labels: type:bug, extensions:napoleon

**Comment by AA-Turner** [comment] 2022-07-25 22:10
I plan to release 5.1.1 **tomorrow**, details in #10710. Please test the `5.1.x` branch as soon as possible, as set out in #10710.

A

**Comment by anoopks12** [comment] 2022-07-27 11:13
Working fine in Sphinx 5.1.1
