### ISSUE TITLE
Intersphinx show mapping (run as __main__) requires config file

### ISSUE THREAD

**Issue by erichiller** [sphinx-doc/sphinx#5987] opened 2019-01-26 18:34 UTC
**Describe the bug**

**To Reproduce**
Following the Procedure outlined in [Showing all links of an Intersphinx mapping file](http://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html#showing-all-links-of-an-intersphinx-mapping-file) run:

```
python -msphinx.ext.intersphinx https://docs.python.org/3/objects.inv
```

**Expected behavior**
I would expect to see a dump of available references from python.org

instead I receive:

```
python -msphinx.ext.intersphinx https://docs.python.org/3/objects.inv

Application error:
config directory doesn't contain a conf.py file (.ext.intersphinx)
```

**Environment info**
- OS: Windows 10 1809
- Python version: 3.7.2
- Sphinx version: 1.8.3
- Sphinx extensions: sphinx.ext.intersphinx

**Comment by tk0miya** [comment] 2019-01-27 02:37
It's strange. The error message is `sphinx-build`'s, not intersphinx debug command.
I guess your command line contains a space after `-m sphinx` (ex. `-m sphinx .ext.intersphinx`).

Could you check it again please?

**Comment by erichiller** [comment] 2019-01-27 19:02
Yes, that was all it was. Glad it was so easy.
`python -m sphinx.ext.intersphinx https://docs.python.org/3/objects.inv` works.

I suppose if you could just update the [documentation](http://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html#showing-all-links-of-an-intersphinx-mapping-file) to add the space.

**Comment by tk0miya** [comment] 2019-01-28 16:40
No, our document is correct. I guess you inserted a space just after `sphinx`, not after `-m`.
Sphinx can take both `-msphinx.ext.intersphinx` and `-m sphinx.ext.intersphinx`.

Anyway, this is not a bug. So I'm closing this now.
Thanks,

**Closed as completed by tk0miya** 2019-01-28 16:40 UTC
Labels: type:question, extensions
