### ISSUE TITLE
Sphinx domain objects generating wrong html structure in some cases

### ISSUE THREAD

**Issue by dojutsu-user** [sphinx-doc/sphinx#6617] opened 2019-07-30 14:56 UTC
Consider the following sphinx domain in requests docs: https://2.python-requests.org/en/master/api/#requests.cookies.RequestsCookieJar.popitem

Here is the source of it: https://github.com/python/cpython/blob/3.7/Lib/_collections_abc.py#L804-L807

The output generated by sphinx is something like this:
```
<index entries="['single',\ 'popitem()\ (requests.cookies.RequestsCookieJar\ method)',\ 'requests.cookies.RequestsCookieJar.popitem',\ '',\ None]">
<desc desctype="method" domain="py" noindex="False" objtype="method">
<desc_signature class="RequestsCookieJar" first="False" fullname="RequestsCookieJar.popitem" ids="requests.cookies.RequestsCookieJar.popitem" module="requests.cookies" names="requests.cookies.RequestsCookieJar.popitem">
<desc_name xml:space="preserve">
popitem
<desc_parameterlist xml:space="preserve">
<desc_returns xml:space="preserve">
(k, v), remove and return some (key, value) pair
<desc_content>
<paragraph>
as a 2-tuple; but raise KeyError if D is empty.
<index entries="['single',\ 'set()\ (requests.cookies.RequestsCookieJar\ method)',\ 'requests.cookies.RequestsCookieJar.set',\ '',\ None]">
```

And the generated html is:
```html
<dl class="method">
    <dt id="requests.cookies.RequestsCookieJar.popitem">
        <code class="descname">popitem</code>
        <span class="sig-paren">(</span>
        <span class="sig-paren">)</span> → (k, v), remove and return some (key, value) pair <a class="headerlink" href="#requests.cookies.RequestsCookieJar.popitem" title="Permalink to this definition">¶</a>
    </dt>
    <dd>
        <p>as a 2-tuple; but raise KeyError if D is empty.</p>
    </dd>
</dl>
```

What I believe is wrong in the generated output is that half of the docstrings are treated as sphinx domain's signature and other half of the docstrings are treated normally.

The docs are built on Read the Docs -- https://readthedocs.org/projects/requests/

**Comment by tk0miya** [comment] 2019-08-01 15:39
As an effect of `autodoc_docstring_signature` option, the first line of docstring is converted to signature if it looks like a signature.
https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_docstring_signature

If you'd not like to convert it automatically, please disable the option.

Otherwise, it might also helpful for you to disable `autodoc_inherit_docstrings`. It stops to extract docstrings from parent class.
https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_inherit_docstrings

**Comment by dojutsu-user** [comment] 2019-08-02 07:13
@tk0miya 
Thanks for your reply.

> docstring is converted to signature if it looks like a signature

Can you provide some explanation on this.
I believe that correct flow should be that it identifies the signature and docstring (if present) separately in the first line?

**Comment by tk0miya** [comment] 2019-08-02 14:53
At present, `autodoc_docstring_signature` converts the whole of first line if it looks like a signature, not part of the line.

**Comment by dojutsu-user** [comment] 2019-08-02 15:02
@tk0miya 
I believe this can be considered as an improvement/bug?

**Comment by tk0miya** [comment] 2019-08-02 16:17
I don't think this is a bug. But improvement are welcome.

**Comment by tk0miya** [comment] 2020-04-26 02:30
Now I'm closing this because not a bug.
Thanks,

**Closed as completed by tk0miya** 2020-04-26 02:30 UTC
Labels: type:question, extensions:autodoc
