### ISSUE TITLE
v7.3.1 breaks the furo theme

### ISSUE THREAD

**Issue by walter-weinmann** [sphinx-doc/sphinx#12294] opened 2024-04-17 01:07 UTC
### Describe the bug

Theme error:
The 'furo' theme inherits from 'basic-ng', which is not a loaded theme. Loaded themes are: agogo, alabaster, basic, bizstyle, classic, default, epub, furo, haiku, nature, nonav, pyramid, scrolls, sphinxdoc, traditional

### How to Reproduce

sphinx-build -M html ${SPHINX_SOURCEDIR} ${SPHINX_BUILDDIR}

### Environment Information

```text
- rinohtype
      - sphinx
      - sphinx-autodoc-typehints
      - sphinx-basic-ng
```

### Sphinx extensions

```python
extensions = [
    "sphinx.ext.autodoc",  # Automatically document your Python modules
    "sphinx.ext.extlinks",
    "sphinx.ext.githubpages",
    "sphinx.ext.napoleon",  # Support for NumPy and Google style docstrings
    "myst_parser",  # Markdown support
]
```

**Comment by AA-Turner** [comment] 2024-04-17 01:29
Duplicate of #12292; please update to Sphinx 7.3.2.

A

**Closed as completed by AA-Turner** 2024-04-17 01:29 UTC
Labels: type:bug
