### ISSUE TITLE
HTML search does not provide all the results

### ISSUE THREAD

**Issue by MantasVaitkunas** [sphinx-doc/sphinx#2891] opened 2016-08-23 13:34 UTC
I did not have any problems till documentation became quite big. At the moment searchindex.js file size is 225.6kb

So now when I'm searching word "Satis" I get only 2 results. I should get at least 16.

I tried to copy document which was not displayed in the search results to new sphinx doc project with less files and search functionality worked perfectly.

Maybe someone had similar issues?

**Comment by tk0miya** [comment] 2016-08-24 11:49
Could you give me an example of docs?

I can't reproduce with the following steps:

```
$ echo Satis >> test.rst
$ make html
# search by "Satis"
```

**Comment by MantasVaitkunas** [comment] 2016-08-24 12:14
Unfortunately documentation is internal and I can't provide an example :(
I tried to reproduce an issue in the random documentation from readthedocs. Not sure if it's the same issue:
http://pop-php-framework.readthedocs.io/en/latest/search.html?q=methods&check_keywords=yes&area=default# It shows only 1 result from "Applications" page.
But this query should show this page too: http://pop-php-framework.readthedocs.io/en/latest/user_guide/images.html?highlight=method

**Comment by Blendify** [comment] 2016-08-24 22:04
We have a similar issue on our [site](https://www.blender.org/manual/) search for terms such as "Blender", or "3D View" all of which are included multiple time in the documentation.

We also have a task on our bug tracker for this:

https://developer.blender.org/T49126

**Comment by tobiasHeinke** [comment] 2016-08-24 22:41
To add some details:
The .docbuild file keys are not saved after full build and they vary.
The searchindex.js is only generated partially:
after full build: 40kB from 350kB; after normal build: 19kB. (only indices from the altered pages)
While normal build it throws the warning. "sphinx search index couldn't be loaded [...]".

But strangely, the parser gets a problem with underscores. 
Removing those makes the warning disappear. 

The files build with a minimal conf in a test environment without the warning.
Replacing it with the full conf makes the error appear. (returning to the minimal doesn't help).
This might be related to Opensearch. 
conf.py also contains: a template, math and video extensions.
In Sphinx 1.4.4 both test and normal docs work.

Sphinx: 1.4.5 and 1.46; Python: 3.52

**Comment by tk0miya** [comment] 2016-08-25 02:20
@MantasVaitkunas Thank you for example. I got it.

This comes from the keywords which is included in some section title does not match to the content part of the documents.
For example, the following case matched to Satis keyword in foo.rst.

```
$ echo Satis >> foo.rst
$ make html
# search by "Satis"  => matched to foo.rst
```

But, after adding new section including the keyword "Satis", foo.rst never matches on searching.

```
$ cat > bar.rst
Satis
=====
$ make clean html
# searcy by "Satis"  => matched only bar.rst
```

This behavior comes from the changes at #1067 and 054833a96f60ea1ae4b09d384b451066e552bff9.
It says 

> Modify the indexer to include the words in the section titles in a separate list. Remove these words from the regular list.

I don't know this is good way for searching. But, as a fact, this behavior confuses many people (including me).

**Comment by tk0miya** [comment] 2016-08-25 02:21
@tobiasHeinke It seems your problem is not related with this issue.
Please file a new issue and tell us your case in detail.

**Comment by TimKam** [comment] 2016-09-19 12:49
@tk0miya Is anybody working on a fix for this?
If not, I might have a look.

**Comment by tk0miya** [comment] 2016-09-21 07:05
@TimKam Maybe nobody works about this.
And I don't have enough time for Sphinx.

It would be great if you could help me :-)

**Comment by TimKam** [comment] 2016-09-28 09:33
@tk0miya Could you have a look at my PR? :-)

**Comment by tk0miya** [comment] 2016-10-10 15:44
Now #2971 is merged. Thank you for reporting.

**Closed as completed by tk0miya** 2016-10-10 15:44 UTC
Labels: html search
