### ISSUE TITLE
Misleading error message when using wrong format for LANG

### ISSUE THREAD

**Issue by hwansing** [sphinx-doc/sphinx#11749] opened 2023-11-10 19:21 UTC
### Describe the bug

When you have a translation for let's say pt-br (in source/locales/pt-br) and try to build it (with "make html LANGS=pt-br" for example), you get misleading output: 1. the build seems to be successful, while it is not (html files are build in build/pt-br/html, but they are completely in English) and 2. there are warnings " WARNING: reading error: <path-to-po-file> expected only letters, got 'pt-br' " which is not correct. 'pt_BR' is a valid value for LANG here, and using that succeeds to build the document for Brazilian Portuguese. So the build with LANGS=pt-br should fail completely and a message should say something "only letters and underscores are allowed for LANG.

### How to Reproduce

In a sphinx project, having a translation for the language 'pt-br', use "make html LANGS=pt-br".
(Simply renaming any existing directory like source/locales/pt to pt-br does the trick as well.)

### Environment Information

```text
This is on Sphinx 5.3 under Debian bookworm. 

Platform: linux (Linux-6.1.0-7-amd64-x86_64-with-glibc2.36)
Python version: 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0]
Python implementation: CPython
Sphinx version: 5.3.0
Jinia2 version: 3.1.2
```

### Sphinx extensions

```python
sphinx.ext.extlinks
```

**Comment by picnixz** [comment] 2023-12-24 18:21
I cannot reproduce this with 7.2.6. Note that we don't do backports because it would require too much work. By the way, I don't think we use `LANG`. If you want to translate your content we use `make -e SPHINXOPTS="-D language='...'" html` I think (check the docs for that).

Btw, I tried:

```
LANG=bad make html
```

which gives me an error (well a huge `locale.Error: unsupported locale setting` so not that nice). So technically, we do have the correct error message (and the reason is that we removed that custom internal setlocale thing in https://github.com/sphinx-doc/sphinx/commit/c7d7f2951d0c43280f78c84b65df11d207ea6177).

So for now, I'd say it works as intended (and we don't support older versions), so I'll close it.

**Closed as not planned by picnixz** 2023-12-24 18:21 UTC
