### ISSUE TITLE
Locale transform always uses rst parser

### ISSUE THREAD

**Issue by Bjwebb** [sphinx-doc/sphinx#2287] opened 2016-02-02 12:36 UTC
https://github.com/sphinx-doc/sphinx/blob/6b7b51a55aa0dc419d9fd8dae17bbec197bd2724/sphinx/transforms.py#L247

This causes a problem when trying to internationalize content intended for other parsers.

**Comment by shimizukawa** [comment] 2016-02-07 03:16
@Bjwebb please try sphinx `intl-supports-parsers` branch  with https://github.com/shimizukawa/recommonmark fork (that is already requested to merge by https://github.com/rtfd/recommonmark/pull/32 )

**Comment by Bjwebb** [comment] 2016-02-08 15:01
@shimizukawa Thanks, looks like it works for me.

**Comment by shimizukawa** [comment] 2016-02-08 15:14
@Bjwebb Thanks for your confirmation! I'll merge the branch into stable that will be shipped as sphinx-1.3.6.

**Comment by shimizukawa** [comment] 2016-02-08 15:19
Merged.

**Closed as completed by shimizukawa** 2016-02-08 15:19 UTC
Labels: type:bug, internals:environment, internals:internationalisation

**Comment by jpmckinney** [comment] 2019-11-19 21:33
@shimizukawa Has there been a regression here? With Sphinx 2.2.1 and recommonmark 0.6.0:

```bash
echo 'This is a `test`' > index.md
sphinx-build -a -v -b gettext -E -C -D extensions=recommonmark . outdir
grep 'test' outdir/index.pot
```

Outputs:

    msgid "This is a test"

I expected:


    msgid "This is a `test`"

**Comment by jpmckinney** [comment] 2019-11-19 23:03
Aha, I found it: commonmark (since 0.6.0) [sets the equivalent of `rawsource` to `None`](https://github.com/readthedocs/commonmark.py/commit/9553a37253f34297558540665daf9ad586230281#diff-3685c7caae4dbbc4a1b0eeb1042e89efR815-R816), such that `docutils.paragraph` nodes in recommonmark can't set `rawsource` correctly, such that `extract_messages` in Sphinx gets incorrect values…

Update: Link won't highlight lines as `inlines.py` is collapsed, but the relevant lines are:

```
        # allow raw string to be garbage collected
         block.string_content = None
```
