### ISSUE TITLE
Math is not HTML-encoded when :nowrap: is given (jsmath, mathjax)

### ISSUE THREAD

**Issue by lilisha100** [sphinx-doc/sphinx#3596] opened 2017-03-31 18:05 UTC
The problem mentioned here (#2226) still exists in the released 1.5.3.

In the mathax.py file in 1.5.3, from line 32 to line 33:

     if node['nowrap']:
              self.body.append(self.encode(node['latex']))

Codes to add math delimiters are missing. It should be:

    if node['nowrap']:
        self.body.append(self.builder.config.mathjax_display[0] +
                     self.encode(node['latex']) +
                     self.builder.config.mathjax_display[1])

### Environment info
- OS: <Unix/Linux/Mac/Win>
- Sphinx version: 1.5.3

**Comment by jfbu** [comment] 2017-03-31 20:43
<strike>Confirmed.</strike> Thanks for reporting, your fix appears to work in my brief testing. But this isn't part of Sphinx I am familiar with.

**edit** my initial impression was wrong. The problem #2226 was another one. But the reST snippet there is wrong, because it should have had the `\[..\]`. It is up to user when `:nowrap:` option is used to provide a math environment, which can be `\[..\]` or another one.

**Comment by jfbu** [comment] 2017-04-01 09:55
@lilisha100 I have looked more closely.

Sorry, but I think your fix is not the correct one and that there is no issue, but the user must use correct mark-up. Indeed this is what the documentation says [here](http://www.sphinx-doc.org/en/stable/ext/math.html#module-sphinx.ext.imgmath) with this example:

```
.. math::
   :nowrap:

   \begin{eqnarray}
      y    & = & ax^2 + bx + c \\
      f(x) & = & x^2 + 2xy + y^2
   \end{eqnarray}
```

Thus the at #2226 example should be marked-up this way:
```
.. math::
    :nowrap:

    \[a<b>c\]
```

If we patch the https://github.com/sphinx-doc/sphinx/blob/master/sphinx/ext/mathjax.py like you suggest we allow mark-up like this
```
.. math::
    :nowrap:

    a<b>c
```
which will work only for html output but not give expected result in other builders like LaTeX, because the math will not be suitably bracketed.

By the way the mark-up `\[\begin{eqnarray}...\end{eqnarray}\]` would be faulty in LaTeX and it works in MathJaX but the `\[..\]` isn't needed there.

**Comment by jfbu** [comment] 2017-04-01 10:10
Closing as this is not a bug. The documentation [here](http://www.sphinx-doc.org/en/stable/ext/math.html#directive-math) says that the math environment is to be inserted explicitly by user in the mark-up.

**Closed as completed by jfbu** 2017-04-01 10:10 UTC
Labels: type:question, markup, extensions:mathematics
