### ISSUE TITLE
Lack of float support for right-aligned SVG figures in HTML documents (maybe a missing CSS class)

### ISSUE THREAD

**Issue by jilljenn** [sphinx-doc/sphinx#3371] opened 2017-01-29 06:00 UTC
Subject: Lack of float support for right-aligned SVG figures in HTML documents (maybe a missing CSS class)

### Problem
- Whenever I have a right-aligned SVG figure in my HTML document, it lacks the `float: right` property, allowing text to flow around the figure.

#### Procedure to reproduce the problem

    .. figure:: /_static/riken.gif
       :align: right

    (Some text)

    .. image:: /_static/pix.svg
       :align: right

    (Some text)

#### Error logs / results
Yields the following layout (PIX is the SVG image).
![sphinx](https://cloud.githubusercontent.com/assets/1729581/22402225/a9ddc44e-e632-11e6-944f-17aef7753094.png)

The corresponding HTML for the GIF:

    <div class="figure align-right">
      <img alt="_images/riken.gif" src="_images/riken.gif">
    </div>

And for the SVG:

    <div align="right" class="align-right">
      <img alt="_images/pix.svg" src="_images/pix.svg">
    </div>

So, the `figure` class seems missing.

#### Expected results
The SVG figure should be in a `float: right` environment, as the GIF figure.

### Reproducible project / your project
- The code above. Sorry, I wanted to fix it myself, but I didn't find out where you added the `figure` class.

### Environment info
- OS: Mac OS 10.11.6
- Python version: 3.6
- Sphinx version: 1.5.2

**Comment by tk0miya** [comment] 2017-01-31 02:46
It seems you're using `image` directive for SVG image. Please use `figure` directive instead.
```
.. image:: /_static/pix.svg
   :align: right
```

Then you'll see right-aligned SVG image.

Input:
```
Image directive for SVG
-----------------------

.. image:: logo.svg
   :align: right

text text text text text text text text text text text text text text text text text text
text text text text text text text text text text text text text text text text text text
text text text text text text text text text text text text text text text text text text
text text text text text text text text text text text text text text text text text text

Figure directive for SVG
------------------------

.. figure:: logo.svg
   :align: right

text text text text text text text text text text text text text text text text text text
text text text text text text text text text text text text text text text text text text
text text text text text text text text text text text text text text text text text text
text text text text text text text text text text text text text text text text text text
```
Output:
![2017-01-31 11 44 02](https://cloud.githubusercontent.com/assets/748828/22450558/d54b9452-e7aa-11e6-95b7-2d06144e5669.png)

**Comment by tk0miya** [comment] 2017-02-11 17:17
Now I close this because it's not a bug.
Please reopen if you still have same problem.

Thanks,

**Closed as completed by tk0miya** 2017-02-11 17:17 UTC
Labels: type:question, markup
