### ISSUE TITLE
Sphinx not using the right Python version inside virtual environments

### ISSUE THREAD

**Issue by JonesKenzie** [sphinx-doc/sphinx#8910] opened 2021-02-19 10:53 UTC
**Describe the bug**
Hello there,

I've created a virtual environment using both `virtualenv` and `pipenv` and in the both cases it seems that `sphinx` is not able to figure out the correct Python version. I have installed Python 2.7 and Python 3.8 in my global environment.

The error shows up when I try to use `sphinx-apidoc` + `make html`. I'm on a Windows 10 machine. Because I'm using type annotations, I get this error:

```
(venv) C:\Users\eug\Documents\learning\learning-pdoc\docs>make html
Running Sphinx v1.8.5
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 3 source files that are out of date
updating environment: 3 added, 0 changed, 0 removed
reading sources... [100%] sample_package
WARNING: autodoc: failed to import module u'core' from module u'sample_package'; the following exception was raised:
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\sphinx\ext\autodoc\importer.py", line 154, in import_module
    __import__(modname)
  File "C:\Users\eug\Documents\learning\learning-pdoc\sample_package\core.py", line 4
    def sample_function2(a : Number, b : Number)->Number:
                           ^
SyntaxError: invalid syntax
```

As you can see I'm currently on the virtual environment (venv). Calling `python` by itself correctly calls the right version. In order to execute what I want I need to call:

```
python -m sphinx.cmd.build -M html . .
```
With is not ideal. Is there a way to fix this?

Thanks

**To Reproduce**
Create a virtual environment using Python 3.8.5 64-bits (either with `pipenv` or `virtualenv`). Install sphinx it's done
```
pipenv install sphinx
```

**Expected behavior**
Just want to generate the HTML files for type annotations for different versions of Python.

**Your project**

**Screenshots**

**Environment info**
- OS:Windows 10
- Python version: 3.8.5 64 bits
- Sphinx version: 1.8.5
- Sphinx extensions:  sphinx.ext.autodoc
- Extra tools:  pipenv / virtualenv

**Comment by tk0miya** [comment] 2021-02-24 15:46
I think you should use `pipenv run sphinx-build` instead of `sphinx-build`. Please rewrite your `Makefile` to invoke sphinx-build command via pipenv.

Anyway, this is not a bug of Sphinx itself. So I'm closing this.

**Closed as completed by tk0miya** 2021-02-24 15:46 UTC
Labels: type:question, api:cmdline

**Comment by mgeier** [comment] 2021-02-24 16:01
> In order to execute what I want I need to call:
> 
> ```
> python -m sphinx.cmd.build -M html . .
> ```
> 
> With is not ideal.

You can have it a bit shorter:

```
python -m sphinx . my-build-dir
```

It may not be ideal, but I prefer this over the `Makefile` solution, because it's actually platform-independent and you always know which Python version is involved.
