### ISSUE TITLE
The htmlhelp builder generates invalid hhc

### ISSUE THREAD

**Issue by char101** [sphinx-doc/sphinx#6229] opened 2019-03-31 03:01 UTC
**Describe the bug**
The htmlhelp builder generates invalid hhc.

**To Reproduce**
Build using the htmlhelp builder.

**Expected behavior**
The generated files compiled without problem.

**Screenshots**
This is a comparison between the content of hhc generated by sphinx 2.0.0 vs 1.8.2

![2019-03-31 09_59_46-Requestsdoc hhc and Requestsdoc hhc - Perforce P4Merge](https://user-images.githubusercontent.com/71255/55284192-c4e6b100-539b-11e9-94a4-1e018e37b768.png)

**Environment info**
- OS: Win 10
- Python version: [e.g. 3.7.1]
- Sphinx version: [e.g. 2.0.0]

As can be seen from the screenshot, the layout and the structure of the tags are different. The new one does not compile with Microsoft HtmlHelp compiler.

**Comment by tk0miya** [comment] 2019-04-04 17:30
Could you let me know the message of HtmlHelp compiler please?

**Comment by char101** [comment] 2019-04-05 01:04
Hi, here is the message:

HHC6000: Error: An internal file could not be created. Make certain there is enough disk space on the drive where you are compiling your file.

HHC5007: Error: Fatal navigational compilation error. This is likely the result of an invalid contents (.hhc) file.

Note that I don't have disk space problem.

Also while the CHM can be compiled using FPC [chmcmd](http://wiki.freepascal.org/chmcmd), the table of contents cannot be displayed when displaying the CHM (it is blank). So the problem is not just on the compilation phase, even when the `.hhc` can be embedded inside the CHM file, it cannot be rendered by htmlhelp.

**Comment by char101** [comment] 2019-04-05 01:05
IMO probably htmlhelp parses the `.hhc` using regular expression, not a HTML/XML parser, so exact format as generated by HTML Help Workshop is required instead of a valid HTML.

**Comment by tk0miya** [comment] 2019-04-06 04:48
OMG. I don't have windows PC on my local now. Could you check what character cause the error please?

**Comment by char101** [comment] 2019-04-06 05:19
Unfortunately htmlhelp does not provide such error. Also as I have previously written, I believe the contents of the hhc is not html or xml, it is just html look alike, so not it not a parsing error, it is simply that the accepted format should look just like what is generated by the native tool.

**Comment by tk0miya** [comment] 2019-04-07 09:16
Ah, sorry. My wording was wrong. I guess the error is caused by trailing slash on closing tag: `/>`. Could you check the removal goes well? If it is not working, I'll revert the change of hhc builder.
Thanks,

**Comment by char101** [comment] 2019-04-07 09:46
Actually that is one of the first thing I tried (removing the `/>`) and it still does not work. I also tried removing the `</li>`. I guess it is important to match exactly what is generated by Html Help Workshop.

**Comment by tk0miya** [comment] 2019-04-07 10:15
Thank you for info. I just push a change to make 1.8 compatible .hhc file: https://github.com/sphinx-doc/sphinxcontrib-htmlhelp/pull/2
Could you try this please?

**Comment by char101** [comment] 2019-04-10 00:58
I don't have a test environment. I think it would be easier to test it in your side by comparing the generated hhc with the result of sphinx 1.8.

**Comment by tk0miya** [comment] 2019-04-11 16:07
I just released new htmlhelp builder including the change now.
Could you check it please?

Thanks,

**Closed as completed by tk0miya** 2019-04-11 16:07 UTC
Labels: type:bug

**Comment by char101** [comment] 2019-04-12 05:50
I have successfully build the requests CHM documentation using sphinxcontrib-htmlhelp 1.0.2.

Thanks.

**Comment by tk0miya** [comment] 2019-04-13 06:50
Thank you for confirmation. Have a fun!
