### ISSUE TITLE
Sphinx unable to import modules

### ISSUE THREAD

**Issue by gvdb** [sphinx-doc/sphinx#2390] opened 2016-03-24 00:16 UTC
I've spent days trying to fix this to no avail. I've tried a few fixes mentioned on [StackOverflow](http://stackoverflow.com/questions/23531825/sphinx-is-not-able-to-import-anything) and issues mentioned here on [GitHub](https://github.com/sphinx-doc/sphinx/issues/2046) and none of the solutions have worked for me.

I've tried all the obvious things of appending to the PYTHONPATH and sys.path in the conf.py file, and ensuring there are `__init__.py` files in the appropriate locations, but Sphinx can't seem to find those Python files even though I can see them in the directories. I get over 200 of these warnings:

`/home/gvdb/doc/source/ATB.website.tabs.rst:363: WARNING: autodoc: failed to import module u'ATB.website.tabs'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/Sphinx-1.4a1-py2.6.egg/sphinx/ext/autodoc.py", line 507, in import_object
    __import__(self.modname)
ImportError: No module named ATB.website.tabs`

So the directory structure in that example is:
- ATB
  - website
    - tabs
      - *.py

Those directories and files all certainly exist, but Sphinx can't import them. I tried it where my doc/ directory is at the same level as ATB/ or inside it, but neither works.

I'm not sure if this is a bug in Sphinx or an error in how I'm using it, but I've exhausted my problem solving abilities on this and was hoping someone more expert might be able to provide some insight.

**Comment by gvdb** [comment] 2016-03-24 00:52
Of course, shortly after posting this, I found the solution to my problem.

The problem was what I was appending to my PYTHONPATH. I incorrectly thought adding `/home/gvdb/ATB/` would fix it. What I needed to add was `/home/gvdb/` so that it could "see" `ATB/`.

Sorry for clogging up the Issues list with something that isn't a bug.

**Comment by Henry0422** [comment] 2016-10-11 17:07
@gvdb Your comment is really useful. As a rookie of sphinx, I had the similar problem this morning. Now, I figured it out. Thx!

**Comment by mihaic** [comment] 2016-10-25 20:53
This should be closed as "not a bug" according to the comment of the bug reporter:
https://github.com/sphinx-doc/sphinx/issues/2390#issuecomment-200600938

**Closed as completed** 2016-10-25 23:32 UTC
Labels: extensions:autodoc

**Comment by shrinilthakkar** [comment] 2018-05-21 08:56
Had a similar problem and was stuck for a while. This post was a great help. Thanks a lot.

**Comment by api2001** [comment] 2018-07-04 10:11
Thanks so much - I also had this issue and could not solve in on my own:
For use of autodoc e.g. for a module *myCoolModule* make sure to add to conf.py:
```
import os
import sys
sys.path.insert(0, os.path.abspath('../source'))
```
where ../source is just the folder that *contains your module/code folder* you like to doc, example:

```
./doc
./doc/conf.py
./doc/index.rst
./doc/make.bat
./doc/Makefile
./source
./source/myCoolModule
./source/myCoolModule/myCoolScript.py
```

**Comment by zzfima** [comment] 2020-08-12 09:26
> Thanks so much - I also had this issue and could not solve in on my own:
> For use of autodoc e.g. for a module _myCoolModule_ make sure to add to conf.py:
> 
> ```
> import os
> import sys
> sys.path.insert(0, os.path.abspath('../source'))
> ```
> 
> where ../source is just the folder that _contains your module/code folder_ you like to doc, example:
> 
> ```
> ./doc
> ./doc/conf.py
> ./doc/index.rst
> ./doc/make.bat
> ./doc/Makefile
> ./source
> ./source/myCoolModule
> ./source/myCoolModule/myCoolScript.py
> ```

Thanks! This one is helps me:
`abspath('../source')`

**Comment by cycks** [comment] 2020-10-02 08:46
If the above suggestions do not work for you, try to use absolute imports instead of relative imports in your flask application.
