### ISSUE TITLE
Sphinx docker images with python 3.10 fail to build

### ISSUE THREAD

**Issue by smartmarketingreports** [sphinx-doc/sphinx#9920] opened 2021-12-01 10:06 UTC
### Describe the bug

The latest sphinxdoc/sphinx docker image fails html to build with the error:

File "/usr/local/lib/python3.10/site-packages/sphinx/util/typing.py", line 37, in <module>
    from types import Union as types_Union
ImportError: cannot import name 'Union' from 'types' (/usr/local/lib/python3.10/types.py)

This appears to be the bug documented [https://github.com/sphinx-doc/sphinx/issues/9562]. Supposedly fixed ?
Don't know whether the latest docker image would have picked up this fix or not... But it would seem it needs to?
Thanks

### How to Reproduce

```
$ git clone https://github.com/.../some_project
$ cd some_project
$ pip install -r requirements.txt
$ cd docs
$ make html SPHINXOPTS="-D language=de"
$ # open _build/html/index and see bla bla
```

### Expected behavior

Build docker image and install some sphinx source (i.e. rst files)
make html... displays the error

### Your project

not applicable

### OS

debian 10

### Python version

3.10

### Sphinx version

docker image tag 4.3.1

**Comment by JulienPalard** [comment] 2022-05-24 07:25
Do you still reproduce the issue?

It has been fixed by https://github.com/sphinx-doc/sphinx/pull/9513 and I successfully use Sphinx==4.5.0 with Python 3.10 (but without docker).

**Comment by tk0miya** [comment] 2022-05-29 09:40
Is it still happened in the "latest" image?
It seems you're using a bit old image. Could you try it again with 4.5.0, please?

**Comment by langemar** [comment] 2023-11-22 13:04
Hi,

this error, or at least a similar one, still persists as of today (11/22/2023).
I'm trying to build the pypy rpython docs with the latexpdf target using the [sphinxdoc/sphinx-latexpdf](https://hub.docker.com/layers/sphinxdoc/sphinx-latexpdf/latest/images/sha256-879a257535ed994a9cb02a2f1298ad24de34fd14807277aab25db30e275ed897?context=explore) docker container.

The source tarball I'm using is this: [https://downloads.python.org/pypy/pypy3.10-v7.3.13-src.tar.bz2](https://downloads.python.org/pypy/pypy3.10-v7.3.13-src.tar.bz2) .
And the docs I want to build are located in `rpython/doc` subdirectory of the tarball, given to the container as `./`

The command output is as follows:
```
# podman run --rm -v ./:/docs sphinxdoc/sphinx-latexpdf sh -c "cd /docs; pip3 install -r requirements.txt;make latexpdf"
Resolving "sphinxdoc/sphinx-latexpdf" using unqualified-search registries (/etc/containers/registries.conf.d/00-unqualified-search-registries.conf)
Trying to pull docker.io/sphinxdoc/sphinx-latexpdf:latest...
Getting image source signatures
Copying blob 67fa4b756060 done  
Copying blob 156c649741bc skipped: already exists  
Copying blob e9ffef1c8dcb skipped: already exists  
Copying blob 1f351811461e skipped: already exists  
Copying blob 0b86526d2e48 done  
Copying blob 648e0aadf75a skipped: already exists  
Copying blob 871212caeb51 done  
Copying blob 81f178b24f84 skipped: already exists  
Copying config 7b809423e7 done  
Writing manifest to image destination
Collecting sphinx-affiliates (from -r requirements.txt (line 1))
  Downloading sphinx_affiliates-0.2.1-py3-none-any.whl (10 kB)
Collecting sphinx_rtd_theme (from -r requirements.txt (line 2))
  Obtaining dependency information for sphinx_rtd_theme from https://files.pythonhosted.org/packages/18/01/76f40a18e9209bb098c1c1313c823dbbd001b23a2db71e7fd4eb5a48559c/sphinx_rtd_theme-1.3.0-py2.py3-none-any.whl.metadata
  Downloading sphinx_rtd_theme-1.3.0-py2.py3-none-any.whl.metadata (4.5 kB)
Collecting sphinx<4,>=1.8.5 (from sphinx-affiliates->-r requirements.txt (line 1))
  Downloading Sphinx-3.5.4-py3-none-any.whl (2.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 6.5 MB/s eta 0:00:00
Collecting docutils<0.19 (from sphinx_rtd_theme->-r requirements.txt (line 2))
  Downloading docutils-0.18.1-py2.py3-none-any.whl (570 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 570.0/570.0 kB 7.1 MB/s eta 0:00:00
Collecting sphinxcontrib-jquery<5,>=4 (from sphinx_rtd_theme->-r requirements.txt (line 2))
  Downloading sphinxcontrib_jquery-4.1-py2.py3-none-any.whl (121 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.1/121.1 kB 7.4 MB/s eta 0:00:00
Requirement already satisfied: sphinxcontrib-applehelp in /usr/local/lib/python3.11/site-packages (from sphinx<4,>=1.8.5->sphinx-affiliates->-r requirements.txt (line 1)) (1.0.6)
Requirement already satisfied: sphinxcontrib-devhelp in /usr/local/lib/python3.11/site-packages (from sphinx<4,>=1.8.5->sphinx-affiliates->-r requirements.txt (line 1)) (1.0.4)
Requirement already satisfied: sphinxcontrib-jsmath in /usr/local/lib/python3.11/site-packages (from sphinx<4,>=1.8.5->sphinx-affiliates->-r requirements.txt (line 1)) (1.0.1)
Requirement already satisfied: sphinxcontrib-htmlhelp in /usr/local/lib/python3.11/site-packages (from sphinx<4,>=1.8.5->sphinx-affiliates->-r requirements.txt (line 1)) (2.0.3)
Requirement already satisfied: sphinxcontrib-serializinghtml in /usr/local/lib/python3.11/site-packages (from sphinx<4,>=1.8.5->sphinx-affiliates->-r requirements.txt (line 1)) (1.1.7)
Requirement already satisfied: sphinxcontrib-qthelp in /usr/local/lib/python3.11/site-packages (from sphinx<4,>=1.8.5->sphinx-affiliates->-r requirements.txt (line 1)) (1.0.5)
Requirement already satisfied: Jinja2>=2.3 in /usr/local/lib/python3.11/site-packages (from sphinx<4,>=1.8.5->sphinx-affiliates->-r requirements.txt (line 1)) (3.1.2)
Requirement already satisfied: Pygments>=2.0 in /usr/local/lib/python3.11/site-packages (from sphinx<4,>=1.8.5->sphinx-affiliates->-r requirements.txt (line 1)) (2.16.1)
Collecting docutils<0.19 (from sphinx_rtd_theme->-r requirements.txt (line 2))
  Downloading docutils-0.16-py2.py3-none-any.whl (548 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 548.2/548.2 kB 7.1 MB/s eta 0:00:00
Requirement already satisfied: snowballstemmer>=1.1 in /usr/local/lib/python3.11/site-packages (from sphinx<4,>=1.8.5->sphinx-affiliates->-r requirements.txt (line 1)) (2.2.0)
Requirement already satisfied: babel>=1.3 in /usr/local/lib/python3.11/site-packages (from sphinx<4,>=1.8.5->sphinx-affiliates->-r requirements.txt (line 1)) (2.12.1)
Requirement already satisfied: alabaster<0.8,>=0.7 in /usr/local/lib/python3.11/site-packages (from sphinx<4,>=1.8.5->sphinx-affiliates->-r requirements.txt (line 1)) (0.7.13)
Requirement already satisfied: imagesize in /usr/local/lib/python3.11/site-packages (from sphinx<4,>=1.8.5->sphinx-affiliates->-r requirements.txt (line 1)) (1.4.1)
Requirement already satisfied: requests>=2.5.0 in /usr/local/lib/python3.11/site-packages (from sphinx<4,>=1.8.5->sphinx-affiliates->-r requirements.txt (line 1)) (2.31.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/site-packages (from sphinx<4,>=1.8.5->sphinx-affiliates->-r requirements.txt (line 1)) (65.5.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/site-packages (from sphinx<4,>=1.8.5->sphinx-affiliates->-r requirements.txt (line 1)) (23.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/site-packages (from Jinja2>=2.3->sphinx<4,>=1.8.5->sphinx-affiliates->-r requirements.txt (line 1)) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/site-packages (from requests>=2.5.0->sphinx<4,>=1.8.5->sphinx-affiliates->-r requirements.txt (line 1)) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/site-packages (from requests>=2.5.0->sphinx<4,>=1.8.5->sphinx-affiliates->-r requirements.txt (line 1)) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/site-packages (from requests>=2.5.0->sphinx<4,>=1.8.5->sphinx-affiliates->-r requirements.txt (line 1)) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/site-packages (from requests>=2.5.0->sphinx<4,>=1.8.5->sphinx-affiliates->-r requirements.txt (line 1)) (2023.7.22)
INFO: pip is looking at multiple versions of sphinxcontrib-applehelp to determine which version is compatible with other requirements. This could take a while.
Collecting sphinxcontrib-applehelp (from sphinx<4,>=1.8.5->sphinx-affiliates->-r requirements.txt (line 1))
  Obtaining dependency information for sphinxcontrib-applehelp from https://files.pythonhosted.org/packages/c0/0c/261c0949083c0ac635853528bb0070c89e927841d4e533ba0b5563365c06/sphinxcontrib_applehelp-1.0.7-py3-none-any.whl.metadata
  Downloading sphinxcontrib_applehelp-1.0.7-py3-none-any.whl.metadata (2.2 kB)
  Obtaining dependency information for sphinxcontrib-applehelp from https://files.pythonhosted.org/packages/57/57/1cdaff9321329139ffb0616b9907f2ddf46fa9a6a9488a93f049b2325472/sphinxcontrib_applehelp-1.0.5-py3-none-any.whl.metadata
  Downloading sphinxcontrib_applehelp-1.0.5-py3-none-any.whl.metadata (2.2 kB)
  Downloading sphinxcontrib_applehelp-1.0.4-py3-none-any.whl (120 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 120.6/120.6 kB 8.1 MB/s eta 0:00:00
INFO: pip is looking at multiple versions of sphinxcontrib-devhelp to determine which version is compatible with other requirements. This could take a while.
Collecting sphinxcontrib-devhelp (from sphinx<4,>=1.8.5->sphinx-affiliates->-r requirements.txt (line 1))
  Obtaining dependency information for sphinxcontrib-devhelp from https://files.pythonhosted.org/packages/c0/03/010ac733ec7b7f71c1dc88e7115743ee466560d6d85373b56fb9916e4586/sphinxcontrib_devhelp-1.0.5-py3-none-any.whl.metadata
  Downloading sphinxcontrib_devhelp-1.0.5-py3-none-any.whl.metadata (2.2 kB)
  Obtaining dependency information for sphinxcontrib-devhelp from https://files.pythonhosted.org/packages/30/68/7e7c2e823a50cc4d0835b962425924fe7006afa2bc7151a79c30b91fcf52/sphinxcontrib_devhelp-1.0.3-py3-none-any.whl.metadata
  Downloading sphinxcontrib_devhelp-1.0.3-py3-none-any.whl.metadata (2.2 kB)
  Downloading sphinxcontrib_devhelp-1.0.2-py2.py3-none-any.whl (84 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.7/84.7 kB 8.0 MB/s eta 0:00:00
INFO: pip is looking at multiple versions of sphinxcontrib-htmlhelp to determine which version is compatible with other requirements. This could take a while.
Collecting sphinxcontrib-htmlhelp (from sphinx<4,>=1.8.5->sphinx-affiliates->-r requirements.txt (line 1))
  Obtaining dependency information for sphinxcontrib-htmlhelp from https://files.pythonhosted.org/packages/28/7a/958f8e3e6abe8219d0d1f1224886de847ab227b218f4a07b61bc337f64be/sphinxcontrib_htmlhelp-2.0.4-py3-none-any.whl.metadata
  Downloading sphinxcontrib_htmlhelp-2.0.4-py3-none-any.whl.metadata (2.2 kB)
  Obtaining dependency information for sphinxcontrib-htmlhelp from https://files.pythonhosted.org/packages/57/41/ad44d14fd5273a7b20905fa4dd8444abf1795f6581666f6272e7d8cabf5a/sphinxcontrib_htmlhelp-2.0.2-py3-none-any.whl.metadata
  Downloading sphinxcontrib_htmlhelp-2.0.2-py3-none-any.whl.metadata (2.2 kB)
  Downloading sphinxcontrib_htmlhelp-2.0.1-py3-none-any.whl (99 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.8/99.8 kB 19.9 MB/s eta 0:00:00
INFO: pip is looking at multiple versions of sphinxcontrib-qthelp to determine which version is compatible with other requirements. This could take a while.
Collecting sphinxcontrib-qthelp (from sphinx<4,>=1.8.5->sphinx-affiliates->-r requirements.txt (line 1))
  Obtaining dependency information for sphinxcontrib-qthelp from https://files.pythonhosted.org/packages/1f/e5/1850f3f118e95581c1e30b57028ac979badee1eb29e70ee72b0241f5a185/sphinxcontrib_qthelp-1.0.6-py3-none-any.whl.metadata
  Downloading sphinxcontrib_qthelp-1.0.6-py3-none-any.whl.metadata (2.2 kB)
  Obtaining dependency information for sphinxcontrib-qthelp from https://files.pythonhosted.org/packages/8d/57/6edeb937dbc2858d980242ffc5913303c19774048b68654e5bee9556e146/sphinxcontrib_qthelp-1.0.4-py3-none-any.whl.metadata
  Downloading sphinxcontrib_qthelp-1.0.4-py3-none-any.whl.metadata (2.2 kB)
  Downloading sphinxcontrib_qthelp-1.0.3-py2.py3-none-any.whl (90 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.6/90.6 kB 8.0 MB/s eta 0:00:00
INFO: pip is looking at multiple versions of sphinxcontrib-serializinghtml to determine which version is compatible with other requirements. This could take a while.
Collecting sphinxcontrib-serializinghtml (from sphinx<4,>=1.8.5->sphinx-affiliates->-r requirements.txt (line 1))
  Obtaining dependency information for sphinxcontrib-serializinghtml from https://files.pythonhosted.org/packages/95/d6/2e0bda62b2a808070ac922d21a950aa2cb5e4fcfb87e5ff5f86bc43a2201/sphinxcontrib_serializinghtml-1.1.9-py3-none-any.whl.metadata
  Downloading sphinxcontrib_serializinghtml-1.1.9-py3-none-any.whl.metadata (2.3 kB)
  Obtaining dependency information for sphinxcontrib-serializinghtml from https://files.pythonhosted.org/packages/dc/85/ea34b6be0494eff8ae281107bb4a83f6c83066b358f2525a251dc852817c/sphinxcontrib_serializinghtml-1.1.8-py3-none-any.whl.metadata
  Downloading sphinxcontrib_serializinghtml-1.1.8-py3-none-any.whl.metadata (2.3 kB)
  Obtaining dependency information for sphinxcontrib-serializinghtml from https://files.pythonhosted.org/packages/82/a2/962548d13ceddff95eac7843c9ff37b451c02b69429007b93d6a10a353d3/sphinxcontrib_serializinghtml-1.1.6-py3-none-any.whl.metadata
  Downloading sphinxcontrib_serializinghtml-1.1.6-py3-none-any.whl.metadata (2.3 kB)
  Downloading sphinxcontrib_serializinghtml-1.1.5-py2.py3-none-any.whl (94 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.0/94.0 kB 8.1 MB/s eta 0:00:00
Downloading sphinx_rtd_theme-1.3.0-py2.py3-none-any.whl (2.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 6.5 MB/s eta 0:00:00
Installing collected packages: sphinxcontrib-serializinghtml, sphinxcontrib-qthelp, sphinxcontrib-htmlhelp, sphinxcontrib-devhelp, sphinxcontrib-applehelp, docutils, sphinx, sphinxcontrib-jquery, sphinx-affiliates, sphinx_rtd_theme
  Attempting uninstall: sphinxcontrib-serializinghtml
    Found existing installation: sphinxcontrib-serializinghtml 1.1.7
    Uninstalling sphinxcontrib-serializinghtml-1.1.7:
      Successfully uninstalled sphinxcontrib-serializinghtml-1.1.7
  Attempting uninstall: sphinxcontrib-qthelp
    Found existing installation: sphinxcontrib-qthelp 1.0.5
    Uninstalling sphinxcontrib-qthelp-1.0.5:
      Successfully uninstalled sphinxcontrib-qthelp-1.0.5
  Attempting uninstall: sphinxcontrib-htmlhelp
    Found existing installation: sphinxcontrib-htmlhelp 2.0.3
    Uninstalling sphinxcontrib-htmlhelp-2.0.3:
      Successfully uninstalled sphinxcontrib-htmlhelp-2.0.3
  Attempting uninstall: sphinxcontrib-devhelp
    Found existing installation: sphinxcontrib-devhelp 1.0.4
    Uninstalling sphinxcontrib-devhelp-1.0.4:
      Successfully uninstalled sphinxcontrib-devhelp-1.0.4
  Attempting uninstall: sphinxcontrib-applehelp
    Found existing installation: sphinxcontrib-applehelp 1.0.6
    Uninstalling sphinxcontrib-applehelp-1.0.6:
      Successfully uninstalled sphinxcontrib-applehelp-1.0.6
  Attempting uninstall: docutils
    Found existing installation: docutils 0.20.1
    Uninstalling docutils-0.20.1:
      Successfully uninstalled docutils-0.20.1
  Attempting uninstall: sphinx
    Found existing installation: Sphinx 7.1.2
    Uninstalling Sphinx-7.1.2:
      Successfully uninstalled Sphinx-7.1.2
Successfully installed docutils-0.16 sphinx-3.5.4 sphinx-affiliates-0.2.1 sphinx_rtd_theme-1.3.0 sphinxcontrib-applehelp-1.0.4 sphinxcontrib-devhelp-1.0.2 sphinxcontrib-htmlhelp-2.0.1 sphinxcontrib-jquery-4.1 sphinxcontrib-qthelp-1.0.3 sphinxcontrib-serializinghtml-1.1.5
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: pip install --upgrade pip
sphinx-build -b latex -d _build/doctrees   . _build/latex
Traceback (most recent call last):
  File "/usr/local/bin/sphinx-build", line 5, in <module>
    from sphinx.cmd.build import main
  File "/usr/local/lib/python3.11/site-packages/sphinx/cmd/build.py", line 25, in <module>
    from sphinx.application import Sphinx
  File "/usr/local/lib/python3.11/site-packages/sphinx/application.py", line 32, in <module>
    from sphinx.config import Config
  File "/usr/local/lib/python3.11/site-packages/sphinx/config.py", line 23, in <module>
    from sphinx.util import logging
  File "/usr/local/lib/python3.11/site-packages/sphinx/util/__init__.py", line 35, in <module>
    from sphinx.util import smartypants  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sphinx/util/smartypants.py", line 33, in <module>
    from sphinx.util.docutils import __version_info__ as docutils_version
  File "/usr/local/lib/python3.11/site-packages/sphinx/util/docutils.py", line 31, in <module>
    from sphinx.util.typing import RoleFunction
  File "/usr/local/lib/python3.11/site-packages/sphinx/util/typing.py", line 34, in <module>
    from types import Union as types_Union
ImportError: cannot import name 'Union' from 'types' (/usr/local/lib/python3.11/types.py)
make: *** [Makefile:106: latexpdf] Error 1
```

**Comment by JulienPalard** [comment] 2023-11-23 12:53
Looks like you're using Sphinx 3.5.4 (from april 2021), can you try with `sphinx>=4.5.0` (released in march 2022)?

I don't know how long Sphinx maintains its branches, but it feels like the Sphinx 3 branch is no longer maintained (as the last release on the 3 branch is from more than 3 years ago).

**Comment by langemar** [comment] 2023-11-23 15:33
Hi,

you're right @JulienPalard. I'm sorry, given my example, I can't use a newer version as sphinx-affiliates depends on a sphinx distribution `<4`. I haven't seen sphinx was downgraded while applying the requirements.txt .

Looking deeper into the matter it seems like the affiliates package is dead - so probably no update for the affiliates package will emerge to test with a newer version of sphinx.

best regrads

**Comment by JulienPalard** [comment] 2023-11-23 17:37
Feels like this issue can be closed.

**Comment by hugovk** [comment] 2023-11-23 17:59
> I can't use a newer version as sphinx-affiliates depends on a sphinx distribution `<4`.

They removed the upper cap in https://github.com/mattip/sphinx-affiliates/pull/3 but haven't released yet.

You could ask them for a new release, and use the Git version in the meantime.

**Closed as not planned** 2024-01-15 07:27 UTC
Labels: type:bug
