### ISSUE TITLE
Consistently failing Epub build

### ISSUE THREAD

**Issue by julienmalard** [sphinx-doc/sphinx#4292] opened 2017-12-12 16:36 UTC
Subject: Epub build failed for Tinamït project

### Problem
- Failed Epub build. Html and pdf seem to build correctly.

#### Procedure to reproduce the problem
Build on Read the docs:
```
python /home/docs/checkouts/readthedocs.org/user_builds/tinamit/envs/latest/bin/sphinx-build -T -b epub -d _build/doctrees-epub -D language=es . _build/epub
```

#### Error logs / results
```
Running Sphinx v1.5.6
making output directory...
loading translations [es]... done
loading pickled environment... not yet created
loading intersphinx inventory from https://docs.python.org/objects.inv...
intersphinx inventory has moved: https://docs.python.org/objects.inv -> https://docs.python.org/2/objects.inv
building [mo]: targets for 0 po files that are out of date
building [epub]: targets for 27 source files that are out of date
updating environment: 27 added, 0 changed, 0 removed
reading sources... [  3%] agradecimientos
reading sources... [  7%] desarrollo/des_bf
reading sources... [ 11%] desarrollo/des_mds
reading sources... [ 14%] desarrollo/des_trad
reading sources... [ 18%] desarrollo/desarrollo
reading sources... [ 22%] docu/BF
reading sources... [ 25%] docu/Conectado
reading sources... [ 29%] docu/Geog
reading sources... [ 33%] docu/MDS
reading sources... [ 37%] docu/Modelo
reading sources... [ 40%] docu/Unidades
reading sources... [ 44%] docu/docu
reading sources... [ 48%] docu/envolturasBF/DSSAT
reading sources... [ 51%] docu/envolturasBF/SAHYSMOD
reading sources... [ 55%] docu/envolturasBF/envolturasBF
reading sources... [ 59%] ejemplos/ejemplos
reading sources... [ 62%] ejemplos/salinidad_pk
reading sources... [ 66%] ejemplos/segali_ix
reading sources... [ 70%] ejemplos/sencillo
reading sources... [ 74%] index
reading sources... [ 77%] instal
reading sources... [ 81%] intro
reading sources... [ 85%] pubs
reading sources... [ 88%] uso/IGU
reading sources... [ 92%] uso/IPA
reading sources... [ 96%] uso/avanzado
reading sources... [100%] uso/uso

/home/docs/checkouts/readthedocs.org/user_builds/tinamit/checkouts/latest/docs/source/agradecimientos.rst:2: WARNING: Duplicate explicit target name: "sitio internet".
/home/docs/checkouts/readthedocs.org/user_builds/tinamit/checkouts/latest/docs/source/desarrollo/des_bf.rst:49: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/docs/checkouts/readthedocs.org/user_builds/tinamit/checkouts/latest/docs/source/desarrollo/des_bf.rst:63: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/docs/checkouts/readthedocs.org/user_builds/tinamit/checkouts/latest/docs/source/desarrollo/des_bf.rst:83: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/docs/checkouts/readthedocs.org/user_builds/tinamit/checkouts/latest/docs/source/desarrollo/des_trad.rst:4: WARNING: Duplicate explicit target name: "empezar ahora".
/home/docs/checkouts/readthedocs.org/user_builds/tinamit/checkouts/latest/docs/source/desarrollo/desarrollo.rst:4: WARNING: Duplicate explicit target name: "página oficial".
/home/docs/checkouts/readthedocs.org/user_builds/tinamit/checkouts/latest/docs/source/desarrollo/desarrollo.rst:4: WARNING: Duplicate explicit target name: "documentación completa".
/home/docs/checkouts/readthedocs.org/user_builds/tinamit/envs/latest/lib/python3.5/site-packages/tinamit-1.3.1-py3.5.egg/tinamit/BF.py:docstring of tinamit.BF.ModeloImpaciente.leer_egr:4: WARNING: Field list ends without a blank line; unexpected unindent.
/home/docs/checkouts/readthedocs.org/user_builds/tinamit/checkouts/latest/docs/source/instal.rst:2: WARNING: Duplicate explicit target name: "aquí".
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [  3%] agradecimientos

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/tinamit/envs/latest/lib/python3.5/site-packages/sphinx/cmdline.py", line 296, in main
    app.build(opts.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tinamit/envs/latest/lib/python3.5/site-packages/sphinx/application.py", line 333, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/tinamit/envs/latest/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/tinamit/envs/latest/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 322, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tinamit/envs/latest/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 360, in write
    self._write_serial(sorted(docnames), warnings)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tinamit/envs/latest/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 368, in _write_serial
    self.write_doc(docname, doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tinamit/envs/latest/lib/python3.5/site-packages/sphinx/builders/epub.py", line 416, in write_doc
    StandaloneHTMLBuilder.write_doc(self, docname, doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tinamit/envs/latest/lib/python3.5/site-packages/sphinx/builders/html.py", line 458, in write_doc
    self.handle_page(docname, ctx, event_arg=doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tinamit/envs/latest/lib/python3.5/site-packages/sphinx/builders/epub.py", line 509, in handle_page
    outfilename, event_arg)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tinamit/envs/latest/lib/python3.5/site-packages/sphinx/builders/html.py", line 820, in handle_page
    output = self.templates.render(templatename, ctx)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tinamit/envs/latest/lib/python3.5/site-packages/sphinx/jinja2glue.py", line 158, in render
    return self.environment.get_template(template).render(context)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tinamit/envs/latest/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tinamit/envs/latest/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tinamit/envs/latest/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tinamit/envs/latest/lib/python3.5/site-packages/sphinx/themes/basic/page.html", line 10, in top-level template code
    {%- extends "layout.html" %}
  File "/home/docs/checkouts/readthedocs.org/user_builds/tinamit/checkouts/latest/docs/source/_templates/layout.html", line 134, in top-level template code
    {% block menu %}
  File "/home/docs/checkouts/readthedocs.org/user_builds/tinamit/checkouts/latest/docs/source/_templates/layout.html", line 140, in block "menu"
    {% set global_toc = toctree(maxdepth=theme_navigation_depth|int, collapse=theme_collapse_navigation, includehidden=theme_includehidden) %}
  File "/home/docs/checkouts/readthedocs.org/user_builds/tinamit/envs/latest/lib/python3.5/site-packages/jinja2/filters.py", line 653, in do_int
    return int(value)
jinja2.exceptions.UndefinedError: 'theme_navigation_depth' is undefined

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/tinamit/envs/latest/lib/python3.5/site-packages/jinja2/filters.py", line 653, in do_int
    return int(value)
jinja2.exceptions.UndefinedError: 'theme_navigation_depth' is undefined
The full traceback has been saved in /tmp/sphinx-err-sdgm1eg_.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```
Link to failed build:
- https://readthedocs.org/projects/tinamit/builds/6398690/

#### Expected results
Successful Epub build for project.

### Reproducible project / your project
- https://readthedocs.org/projects/tinamit/

### Environment info
- OS: <Unix/Linux/Mac/Win/other with version> NA (Built on ReadtheDocs server)
- Python version: 3.5
- Sphinx version: 1.5.6
- <Extra tools e.g.: Browser, tex or something else> NA

**Comment by tk0miya** [comment] 2017-12-13 05:06
It seems the template of tinamit expects `theme_navigation_depth` as a template variable. I don't know where the variable is defiened. So please ask it to tinamit project or who modified the template.

**Comment by julienmalard** [comment] 2017-12-13 16:17
I am using ReadtheDocs (and their templates)...should I report this bug to them instead?

Thanks,
Julien Malard

**Comment by tk0miya** [comment] 2017-12-14 13:11
No, it is defined at `layout.html` on your repository.
Please refer here:
https://github.com/julienmalard/Tinamit/blob/master/docs/source/_templates/layout.html#L140

**Comment by julienmalard** [comment] 2017-12-14 14:51
Hello,


That is odd! I copied the layout.html directly from ReadTheDocs (RTD) and only modified a few lines to override left-to-right text alignment for projects in right-to-left scripts, but didn't change anything else. The line in question is actually also on the original RTD theme (https://github.com/rtfd/sphinx_rtd_theme/blob/master/sphinx_rtd_theme/layout.html#L136), and my other project built with the default theme (https://readthedocs.org/projects/tikon/builds/) has not had this problem.


<https://github.com/rtfd/sphinx_rtd_theme/blob/master/sphinx_rtd_theme/layout.html#L136>

Do you think I should report this to ReadtheDocs?

Thanks very much for your help,


Julien Malard

________________________________
દ્વારા: Takeshi KOMIYA <notifications@github.com>
મોકલ્યું: 14 ડિસેમ્બર 2017 08:11:53
પ્રતિ: sphinx-doc/sphinx
Cc: Julien Malard; Author
વિષય: Re: [sphinx-doc/sphinx] Consistently failing Epub build (#4292)


No, it is defined at layout.html on your repository.
Please refer here:
https://github.com/julienmalard/Tinamit/blob/master/docs/source/_templates/layout.html#L140

**Comment by tk0miya** [comment] 2017-12-15 16:07
No, it's not a bug. `sphinx_rtd_theme` behaves as a HTML theme and it adds some template variables.
But, on your case, you'd copied only `layout.html`. so it behaves as a HTML template.

Anyway, it is not a bug of Sphinx. So I close this.

**Closed as completed by tk0miya** 2017-12-15 16:07 UTC
Labels: type:question

**Comment by julienmalard** [comment] 2017-12-15 20:02
Thank you! Sorry for the trouble.

-Julien Malard

________________________________
દ્વારા: Takeshi KOMIYA <notifications@github.com>
મોકલ્યું: 15 ડિસેમ્બર 2017 11:07:13
પ્રતિ: sphinx-doc/sphinx
Cc: Julien Malard; Author
વિષય: Re: [sphinx-doc/sphinx] Consistently failing Epub build (#4292)


No, it's not a bug. sphinx_rtd_theme behaves as a HTML theme and it adds some template variables.
But, on your case, you'd copied only layout.html. so it behaves as a HTML template.

Anyway, it is not a bug of Sphinx. So I close this.
