### ISSUE TITLE
How to generate documentation using files from another directory?

### ISSUE THREAD

**Issue by AlexCPU7** [sphinx-doc/sphinx#5750] opened 2018-12-10 12:13 UTC
Subject: <what happen when you do on which document project>

### Problem
I cannot use the templates located in the directory above my Makefile. I do not understand, do you have this functionality?

#### Procedure to reproduce the problem
The structure of my project
```
apps
├── project_1
│    └── docs
│        └── index.rst
└── project_2
     └── docs
         └── index.rst
docs
├── Makefile
└── source
     ├── logs
     ├── conf.py
     └── index.rst
```
 Code in index.rst file:
```
Apps
====

.. toctree::
   :hidden:
   :maxdepth: 4

   ../../apps/project_1/docs/index
   ../../apps/project_2/docs/index

Indices and tables
==================

* :ref:'genindex'
* :ref:'modindex'
* :ref:'search'
```
#### Error logs / results
```
/storage/dev-project/docs/source/index.rst:9: WARNING: toctree contains reference to nonexisting document u'apps/project_1/docs/index'
/storage/dev-project/docs/source/index.rst:9: WARNING: toctree contains reference to nonexisting document u'apps/project_2/docs/index'
```

#### Expected results
I expected that the templates from other projects will be applied and compiled into a common document file.

### Reproducible project / your project
Sorry, I can not throw a link this is a closed project

### Environment info
- OS: Linux debian 9
- Python version: 2.7.13  
- Sphinx version: 1.8.2

**Comment by tk0miya** [comment] 2018-12-15 09:54
Unfortunately, there are no way. Sphinx expects all files are placed under source directory. Please copy  them or create symlink to source directory.
Thanks,

**Comment by tk0miya** [comment] 2019-01-13 14:19
I'm closing this because not a bug.
Thanks,

**Closed as completed by tk0miya** 2019-01-13 14:19 UTC
Labels: type:question
