### ISSUE TITLE
make latexpdf fails on table

### ISSUE THREAD

**Issue by tcaduser** [sphinx-doc/sphinx#4497] opened 2018-01-26 04:14 UTC
Subject: latexpdf fails on this table

### Problem

pdf compilation fails on this table.  If I remove one of the lines in the second row, it compiles fine.

#### Procedure to reproduce the problem

Run the attached example as part of a sphinx project.

```
make latexpdf
```

#### Error logs / results
It looks like the \hline from latex doesn't have any space to the first word in the next cell.  I can't find any way to add whitespace between \hline and the contents of the cell

```
(/usr/local/texlive/2015/texmf-dist/tex/latex/psnfss/ts1ptm.fd) [29] [30]
! Undefined control sequence.
<recently read> \hlinexxxxxxxxxxxxxxxx

l.1215 \end{tabulary}

?
```

Generated tex output.

```
\begin{tabulary}{\linewidth}[t]{|T|T|}
\hline
\sphinxstylethead{\sphinxstyletheadfamily 
xxxxxxxx xxxx
\unskip}\relax &\sphinxstylethead{\sphinxstyletheadfamily 
xxxxxxxx
\unskip}\relax \\
\hline
xxxxxxxxxxxxxxxx
&
xxxx xxxx
xxxxx xxx
xxxxxxxxx
\\
\hlinexxxxxxxxxxxxxxxx

xxxxxxxxxxxxxxxx

xxxxxxxxxxxxxxxx
&
xxxxxxx x
xx xxxxxx
xxxxxxxx
xxxxxxx x
xxxxxxxx.
\\
\hline
\end{tabulary}
```

- <public link of unexpected result if you have>

#### Expected results
<Describe what to actually do>

### Reproducible project / your project

```
.. table:: a title

  +------------------+-----------+
  | xxxxxxxx xxxx    | xxxxxxxx  |
  |                  |           |
  +==================+===========+
  |                  |           |
  | xxxxxxxxxxxxxxxx | xxxx xxxx |
  |                  | xxxxx xxx |
  |                  | xxxxxxxxx |
  +------------------+-----------+
  | xxxxxxxxxxxxxxxx | xxxxxxx x |
  |                  | xx xxxxxx |
  | xxxxxxxxxxxxxxxx | xxxxxxxx  |
  |                  | xxxxxxx x |
  | xxxxxxxxxxxxxxxx | xxxxxxxx. |
  |                  |           |
  +------------------+-----------+
```

### Environment info

- OS: Linux Redhat 6.9
- Python version: Anaconda Python 2.7.14
- Sphinx version: v 1.6.6
- <Extra tools e.g.: Browser, tex or something else>
   TeX Live 2017

AND

- OS: Mac OS X High Sierra
- Python version: Anaconda Python 2.7.14
- Sphinx version: v 1.6.3
- <Extra tools e.g.: Browser, tex or something else>
   TeX Live 2015

**Comment by jfbu** [comment] 2018-01-26 07:37
Thanks for reporting and for the test case, this is a duplicate of #4431 and it has been fixed in stable branch at d3058f4 (for 1.6.7 if the latter is released or for 1.7). The 1.7.0b1 did not get the patch but of course 1.7.0b2 will have it.

**Closed as completed by jfbu** 2018-01-26 07:37 UTC
Labels: type:bug, closed:duplicate, builder:latex
