### ISSUE TITLE
UnicodeDecodeError when building from Arch repo

### ISSUE THREAD

**Issue by RenaKunisaki** [sphinx-doc/sphinx#3777] opened 2017-05-20 20:11 UTC
Subject: Attempting to install python-sphinx package in Arch fails.

### Problem
- Installation fails with several UnicodeDecodeErrors.

#### Procedure to reproduce the problem
```
$ yaourt -S python-sphinx
```

#### Error logs / results
See attachment: [sphinx.log.txt](https://github.com/sphinx-doc/sphinx/files/1016479/sphinx.log.txt)

#### Expected results
Package builds and installs successfully.

### Environment info
- OS: Arch Linux AMD64
- Python version: 3.6.1
- Sphinx version: N/A

**Comment by tk0miya** [comment] 2017-05-21 00:55
What locale did you use? Our testing expects locales which allows UTF-8 encodings (for example, `C.UTF-8`).
Thanks,

**Comment by RenaKunisaki** [comment] 2017-05-21 04:43
`LANG=en_CA.UTF-8`

**Comment by tk0miya** [comment] 2017-05-30 15:56
I tried to reproduce this error using archlinux docker image. But I could not reproduce it.
I don't know what `yaourt` command is doing, and also don't know this investigation is correct or not.
Anyway, I need to know how to reproduce this.
```
$ docker run -it --rm base/archlinux /bin/bash
# cat >>/etc/pacman.conf
[archlinuxfr]
SigLevel = Never
Server = http://repo.archlinux.fr/$arch
# pacman --sync --refresh yaourt
(snip)
# yaourt -S python-sphinx
/usr/lib/yaourt/pacman.sh: line 19: sed: command not found
resolving dependencies...
looking for conflicting packages...

Packages (23) python-3.6.1-1  python-appdirs-1.4.3-1  python-babel-2.4.0-1  python-chardet-3.0.3-1  python-docutils-0.13.1-2
              python-imagesize-0.7.1-2  python-jinja-2.9.6-1  python-markupsafe-1.0-1  python-packaging-16.8-2
              python-pygments-2.2.0-1  python-pyparsing-2.2.0-1  python-pytz-2017.2-1  python-requests-2.14.2-1
              python-setuptools-1:35.0.2-1  python-six-1.10.0-3  python-snowballstemmer-1.2.1-2
              python-sphinx-alabaster-theme-0.7.10-1  python-sphinx_rtd_theme-0.2.4-1  python-sphinxcontrib-websupport-1.0.1-1
              python-sqlalchemy-1.1.10-1  python-urllib3-1.21.1-1  python-whoosh-2.7.4-2  python-sphinx-1.6.1-3

Total Download Size:    44.16 MiB
Total Installed Size:  190.94 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
 python-3.6.1-1-x86_64                                   33.2 MiB   982K/s 00:35 [##############################################] 100%
 python-pyparsing-2.2.0-1-any                            92.8 KiB   663K/s 00:00 [##############################################] 100%
 python-six-1.10.0-3-any                                 18.7 KiB   375K/s 00:00 [##############################################] 100%
 python-packaging-16.8-2-any                             29.5 KiB   985K/s 00:00 [##############################################] 100%
 python-appdirs-1.4.3-1-any                              14.0 KiB   699K/s 00:00 [##############################################] 100%
 python-setuptools-1:35.0.2-1-any                       261.3 KiB  1375K/s 00:00 [##############################################] 100%
 python-markupsafe-1.0-1-x86_64                          21.4 KiB   535K/s 00:00 [##############################################] 100%
 python-urllib3-1.21.1-1-any                            152.1 KiB   411K/s 00:00 [##############################################] 100%
 python-chardet-3.0.3-1-any                             150.1 KiB   320K/s 00:00 [##############################################] 100%
 python-requests-2.14.2-1-any                           154.2 KiB   441K/s 00:00 [##############################################] 100%
 python-jinja-2.9.6-1-any                               213.4 KiB   445K/s 00:00 [##############################################] 100%
 python-pygments-2.2.0-1-any                           1134.1 KiB   551K/s 00:02 [##############################################] 100%
 python-docutils-0.13.1-2-any                           642.8 KiB  2.24M/s 00:00 [##############################################] 100%
 python-sphinx_rtd_theme-0.2.4-1-any                    932.2 KiB  2.60M/s 00:00 [##############################################] 100%
 python-sphinx-alabaster-theme-0.7.10-1-any              13.9 KiB  0.00B/s 00:00 [##############################################] 100%
 python-pytz-2017.2-1-any                               158.6 KiB  2.21M/s 00:00 [##############################################] 100%
 python-babel-2.4.0-1-any                                 3.8 MiB  2.48M/s 00:02 [##############################################] 100%
 python-snowballstemmer-1.2.1-2-any                      87.5 KiB  4.27M/s 00:00 [##############################################] 100%
 python-imagesize-0.7.1-2-any                             5.0 KiB   501K/s 00:00 [##############################################] 100%
 python-sphinxcontrib-websupport-1.0.1-1-any             36.0 KiB   363K/s 00:00 [##############################################] 100%
 python-sqlalchemy-1.1.10-1-x86_64                     1267.5 KiB  2.75M/s 00:00 [##############################################] 100%
 python-whoosh-2.7.4-2-any                              591.7 KiB  3.63M/s 00:00 [##############################################] 100%
 python-sphinx-1.6.1-3-any                             1326.6 KiB  1820K/s 00:01 [##############################################] 100%
(23/23) checking keys in keyring                                                 [##############################################] 100%
(23/23) checking package integrity                                               [##############################################] 100%
(23/23) loading package files                                                    [##############################################] 100%
(23/23) checking for file conflicts                                              [##############################################] 100%
(23/23) checking available disk space                                            [##############################################] 100%
:: Processing package changes...
( 1/23) installing python                                                        [##############################################] 100%
Optional dependencies for python
    python-setuptools [pending]
    python-pip
    sqlite [installed]
    mpdecimal: for decimal
    xz: for lzma [installed]
    tk: for tkinter
( 2/23) installing python-pyparsing                                              [##############################################] 100%
( 3/23) installing python-six                                                    [##############################################] 100%
( 4/23) installing python-packaging                                              [##############################################] 100%
( 5/23) installing python-appdirs                                                [##############################################] 100%
( 6/23) installing python-setuptools                                             [##############################################] 100%
( 7/23) installing python-markupsafe                                             [##############################################] 100%
( 8/23) installing python-jinja                                                  [##############################################] 100%
( 9/23) installing python-pygments                                               [##############################################] 100%
(10/23) installing python-docutils                                               [##############################################] 100%
(11/23) installing python-sphinx_rtd_theme                                       [##############################################] 100%
(12/23) installing python-sphinx-alabaster-theme                                 [##############################################] 100%
(13/23) installing python-pytz                                                   [##############################################] 100%
(14/23) installing python-babel                                                  [##############################################] 100%
(15/23) installing python-snowballstemmer                                        [##############################################] 100%
Optional dependencies for python-snowballstemmer
    python-pystemmer: for improved performance
(16/23) installing python-imagesize                                              [##############################################] 100%
(17/23) installing python-urllib3                                                [##############################################] 100%
Optional dependencies for python-urllib3
    python-pysocks: SOCKS support
(18/23) installing python-chardet                                                [##############################################] 100%
(19/23) installing python-requests                                               [##############################################] 100%
Optional dependencies for python-requests
    python-pysocks: SOCKS proxy support
(20/23) installing python-sphinxcontrib-websupport                               [##############################################] 100%
(21/23) installing python-sqlalchemy                                             [##############################################] 100%
Optional dependencies for python-sqlalchemy
    python-psycopg2: connect to PostgreSQL database
(22/23) installing python-whoosh                                                 [##############################################] 100%
(23/23) installing python-sphinx                                                 [##############################################] 100%
Optional dependencies for python-sphinx
    texlive-latexextra: for generation of PDF documentation
    imagemagick: ext.imageconverter
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
```

Note:
```
# locale
LANG=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```

**Comment by RenaKunisaki** [comment] 2017-07-02 15:43
yaourt is a pacman wrapper, I'm not sure how to capture the commands but it should be the same as pacman.

```
~> locale
LANG=en_CA.UTF-8
LC_CTYPE="en_CA.UTF-8"
LC_NUMERIC="en_CA.UTF-8"
LC_TIME="en_CA.UTF-8"
LC_COLLATE="en_CA.UTF-8"
LC_MONETARY="en_CA.UTF-8"
LC_MESSAGES="en_CA.UTF-8"
LC_PAPER="en_CA.UTF-8"
LC_NAME="en_CA.UTF-8"
LC_ADDRESS="en_CA.UTF-8"
LC_TELEPHONE="en_CA.UTF-8"
LC_MEASUREMENT="en_CA.UTF-8"
LC_IDENTIFICATION="en_CA.UTF-8"
LC_ALL=

~> sudo locale
[sudo] password for rena: 
LANG=en_CA.UTF-8
LC_CTYPE="en_CA.UTF-8"
LC_NUMERIC="en_CA.UTF-8"
LC_TIME="en_CA.UTF-8"
LC_COLLATE="en_CA.UTF-8"
LC_MONETARY="en_CA.UTF-8"
LC_MESSAGES="en_CA.UTF-8"
LC_PAPER="en_CA.UTF-8"
LC_NAME="en_CA.UTF-8"
LC_ADDRESS="en_CA.UTF-8"
LC_TELEPHONE="en_CA.UTF-8"
LC_MEASUREMENT="en_CA.UTF-8"
LC_IDENTIFICATION="en_CA.UTF-8"
LC_ALL=
```

**Comment by polyzen** [comment] 2017-07-02 18:47
Do you have a reason for building it yourself? Otherwise, just install the package: `pacman -Syu python-sphinx`.

**Comment by RenaKunisaki** [comment] 2017-07-05 17:17
That works, thanks. I had been installing another package via yaourt which would pull sphinx in as a dependency and insist on building it locally too.

**Comment by tk0miya** [comment] 2018-03-06 16:02
I'm closing this now.
Please feel free to reopen if you still have this problem.
Thanks,

**Closed as completed by tk0miya** 2018-03-06 16:02 UTC
Labels: type:tests
