### ISSUE TITLE
ImportError: cannot import name 'get_app' from partially initialized module 'prompt_toolkit.application.current'

### ISSUE THREAD

**Issue by Socrats** [sphinx-doc/sphinx#9814] opened 2021-11-03 11:14 UTC
### Describe the bug

I am getting the following error when running Sphinx on a Python package with a C++/Pybind11 extension (so there is a mix of python and c++) files. 

The error only appears to occur when running on linux (on my macos everything works fine). I am using the latest version of sphinx and have the following extensions:

GitPython
PyGithub
requests
nbsphinx>=0.8.7
recommonmark>=0.7.1
sphinx_rtd_theme>=0.5.1
sphinx-autodoc-typehints>=1.12.0

This is the error message I get:

Exception occurred:
  File "/home/runner/.local/lib/python3.8/site-packages/prompt_toolkit/filters/app.py", line 6, in <module>
    from prompt_toolkit.application.current import get_app
ImportError: cannot import name 'get_app' from partially initialized module 'prompt_toolkit.application.current' (most likely due to a circular import) (/home/runner/.local/lib/python3.8/site-packages/prompt_toolkit/application/current.py)
The full traceback has been saved in /tmp/sphinx-err-j_we3eqt.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!

### How to Reproduce

```
$ git clone https://github.com/Socrats/EGTTools.git
$ git checkout develop
$ git submodule update --init --recursive
$ pip install --upgrade pip build wheel
$ python -m build
$ pip install -e .
$ python -m sphinx -M html docs docs/_build
```

### Your project

https://github.com/Socrats/EGTTools/tree/develop

### OS

Linux - Ubuntu 20.04.3 5 LTS

### Python version

3.8.12

### Sphinx version

3.2.1

### Sphinx extensions

sphinx.ext.napoleon, sphinx.ext.autodoc, sphinx.ext.autosummary, sphinx.ext.doctest, sphinx.ext.intersphinx, sphinx.ext.todo, sphinx.ext.coverage, sphinx.ext.mathjax, sphinx.ext.ifconfig, sphinx.ext.viewcode, sphinx.ext.githubpages, sphinx_autodoc_typehints, recommonmark, nbsphinx, pybind11_docstrings

**Comment by mgeier** [comment] 2021-11-03 19:37
This sounds a lot like https://github.com/spatialaudio/nbsphinx/issues/596.

**Comment by Socrats** [comment] 2021-11-04 08:00
> This sounds a lot like [spatialaudio/nbsphinx#596](https://github.com/spatialaudio/nbsphinx/issues/596).

That's it! Thanks a lot! Would it be reasonable to propose a warning message when including nbsphinx as an extension? Or I should just file a bug tracker on the nbsphinx project?

**Comment by mgeier** [comment] 2021-11-04 20:55
Which version of `prompt-toolkit` were you using (when the `InputError` happened)?

**Comment by Socrats** [comment] 2021-11-05 08:39
> Which version of `prompt-toolkit` were you using (when the `InputError` happened)?

The latest (3.0.22). And with `Sphinx 4`. The issue happened on the `ubuntu-latest` ` manylinux2010_x86_64` image in Github CI. On Mac with `promt-toolkit 3.0.21` and `Sphinx 3.2.1` I did not have any issues. So I suppose something broke with the new `promt-toolkit` version and its compatibility with `Sphinx 4`?

**Comment by tk0miya** [comment] 2021-12-22 18:04
It seems this is not a bug of Sphinx-core. Closing.

**Closed as completed by tk0miya** 2021-12-22 18:04 UTC
Labels: type:question
