### ISSUE TITLE
pip install sphinx error under the python3

### ISSUE THREAD

**Issue by brucelkx** [sphinx-doc/sphinx#2434] opened 2016-04-11 01:49 UTC
Exception occurred:
  File "conf.py", line 45, in <module>
    copyright = unicode(date.today().year) + u', Apple Inc'
NameError: name 'unicode' is not defined
The full traceback has been saved in /var/folders/7_/t87q5n0n327c2sh6670nrsmw0000gp/T/sphinx-err-0amfdez0.log, if you want to report the issue to the developers.

**Comment by tk0miya** [comment] 2016-04-11 03:46
It seems your `conf.py` is written for python2.
Could you attach the full traceback on `/var/folders/7_/t87q5n0n327c2sh6670nrsmw0000gp/T/sphinx-err-0amfdez0.log`?

**Comment by tk0miya** [comment] 2016-04-27 03:32
It seems not a bug of sphinx. So I close this now.
Please reopen if you get any more information about this issue.

Thanks,

**Closed as completed by tk0miya** 2016-04-27 03:32 UTC
Labels: type:question
