### ISSUE TITLE
Parsing Error in Compound.py

### ISSUE THREAD

**Issue by ZanderUF** [sphinx-doc/sphinx#6523] opened 2019-06-25 18:40 UTC
**Describe the bug**
I am using Breathe to connect Sphinx and Doxygen.  I am getting an exception error when trying to parse part of an XML file generated by Doxygen.  If this bug report should be put in a different spot I apologize.

**To Reproduce**
```
$ cd project_dir
$ sphinx-build -b html ./source ./build
```
Traceback (most recent call last):
  File "c:\program files (x86)\intelswtools\intelpython3\lib\site-packages\breathe\parser\__init__.py", line 84, in parse
    return self.cache[filename]
KeyError: 'P:/Edmonds/Zander/All_Previous_Versions_EFDCPlus/085_OMP/Working/Doxygen/docs_doxy/xml\\calpser_8f90.xml'

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "c:\program files (x86)\intelswtools\intelpython3\lib\site-packages\breathe\parser\compound.py", line 1067, in parse
    doc = minidom.parse(inFilename)
  File "c:\program files (x86)\intelswtools\intelpython3\lib\xml\dom\minidom.py", line 1958, in parse
    return expatbuilder.parse(file)
  File "c:\program files (x86)\intelswtools\intelpython3\lib\xml\dom\expatbuilder.py", line 911, in parse
    result = builder.parseFile(fp)
  File "c:\program files (x86)\intelswtools\intelpython3\lib\xml\dom\expatbuilder.py", line 207, in parseFile
    parser.Parse(buffer, 0)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 64, column 138
```

Line 64 of calpser_8f90.xml is:
`<codeline lineno="40"><highlight class="normal"><sp/><sp/><sp/><sp/><sp/><sp/ </highlight><highlight class="comment">!<sp/>***<sp/>CATMULL–ROM<sp/>SPLINE</highlight><highlight class="normal"></highlight></codeline>`

<codeline lineno="124"><highlight class="normal"><sp/><sp/><sp/><sp/></highlight><highlight class="comment">!<sp/>**<sp/><sp/>METHOD<sp/>1:<sp/>COURANT–FRIEDRICHS–LEWY</highlight><highlight class="normal"></highlight></codeline>

When I remove this line from the XML file the parsing error goes away and everything is built as expected.

**Expected behavior**
The XML will be parsed correctly.

**Environment info**
- OS: Windows 10
- Sphinx version: 2.1.2
- Python version: 3.6.8 (CPython)
- Docutils version: 0.14 
- Jinja2 version: 2.10.1

**Comment by tk0miya** [comment] 2019-06-28 14:24
It seems the error was raised from breathe extension. So this is not a bug of Sphinx.
Please ask this to their project.

I'm not good at breathe, but it seems the XML file you pasted is broken; the `sp` tag before highlight closer tag is not closed correctly:`<sp/><sp/ </highlight>`.
I don't know why such broken XML was generated, but this is also not a bug of breathe, I think.

**Comment by tk0miya** [comment] 2019-06-28 14:24
I'm closing this because not a bug of Sphinx.
Thanks,

**Closed as completed by tk0miya** 2019-06-28 14:24 UTC
Labels: type:bug
