### ISSUE TITLE
Quote before a link is misinterpreted

### ISSUE THREAD

**Issue by yves-chevallier** [sphinx-doc/sphinx#6615] opened 2019-07-30 13:00 UTC
**Describe the bug**

The following french text: 

```
l'élève, l'`île <https://en.wikipedia.org/wiki/Island>`__.
```

Is interpreted as: 

```
<p>l’élève, l”<a class="reference external" href="https://en.wikipedia.org/wiki/Island">île</a>.</p>
```

Where the `'` is replaced with `”` in the second case.

To reproduce this issue, just create a new project with the language `fr` and try to place a quote before a link. 

**Environment info**

Sphinx master branch

**Comment by jfbu** [comment] 2019-07-31 17:45
This is not a Sphinx but a Docutils issue.

Test file `test.rst`:

```rest
l'élève, l'`île <https://en.wikipedia.org/wiki/Island>`__.
```

Command:

```
rst2html.py --language=fr --smart-quotes -- test.rst test.html
```

output in html:

```html
<p>l’élève, l”<a class="reference external" href="https://en.wikipedia.org/wiki/Island">île</a>.</p>
```

Can you please raise issue upstream at [Docutils](https://sourceforge.net/p/docutils/bugs/)?

**Comment by jfbu** [comment] 2019-07-31 17:46
As work around, please use directly curly quote in source. edit: I mean use the apostrophe character `’` directly in source.

**Comment by yves-chevallier** [comment] 2019-08-01 12:48
Issue opened at Docutils [here](https://sourceforge.net/p/docutils/bugs/371/)

**Comment by tk0miya** [comment] 2020-11-12 18:02
I'm closing this now because this is not a bug of Sphinx itself.
Thanks,

**Closed as completed by tk0miya** 2020-11-12 18:02 UTC
Labels: type:question, docutils
