### ISSUE TITLE
should update CSS to reflect new docutils 0.17 HTML5 tags

### ISSUE THREAD

**Issue by drammock** [sphinx-doc/sphinx#9001] opened 2021-03-14 18:50 UTC
The [HTML5 writer in docutils 0.17](https://docutils.sourceforge.io/RELEASE-NOTES.html#release-0-17) writes the `.. sidebar::` directive as the HTML5 `aside` tag (used to be `div`). This means that the rule in `basic.css_t` for styling those elements no longer applies, since the rule is written for `div.sidebar` instead of `aside.sidebar`:

https://github.com/sphinx-doc/sphinx/blob/f7768d8282e2051596b5df54ecf144505cb8f4f5/sphinx/themes/basic/static/basic.css_t#L322-L331

According to the docutils changelog linked above, other tags now being output are `main`, `section`, `header`, `footer`, `figure`, and `figcaption`.  I haven't systematically checked for where / whether similar CSS mismatches are happening as a result, but I'd guess there are a few more besides the `div` -> `aside` issue that I ran into.

EDIT: crossref to https://github.com/mne-tools/mne-python/issues/9031 where there are screenshots of a sidebar directive that is failing to get styled properly.

**Comment by Daltz333** [comment] 2021-04-04 02:54
A ping on this. docutils 0.17 has just gotten published and now breaks generation

**Comment by mgeier** [comment] 2021-04-04 13:27
I've just created #9059, which hopefully fixes this issue.

@drammock 

> According to the docutils changelog linked above, other tags now being output are `main`, `section`, `header`, `footer`, `figure`, and `figcaption`. I haven't systematically checked for where / whether similar CSS mismatches are happening as a result, but I'd guess there are a few more besides the `div` -> `aside` issue that I ran into.

If you find more errors, can you please create a new issue?

**Comment by Blendify** [comment] 2021-04-05 03:58
See the rtd documentation here on how to pin a dependency: https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html#pinning-dependencies

**Comment by ericholscher** [comment] 2021-04-05 17:01
Another option for now is just to pin to docutils `<0.17`. We did this on the RTD theme, until we have a chance to fully test and implement the changes.

**Comment by return42** [comment] 2021-04-08 12:45
> Another option for now is just to pin to docutils <0.17

Another option I would vote for is to maintain a own fork and decouple docutils development from David Goodger: Each minor release brings new incompatibilities, each release of docutils cause problems in hundred of projects.

**Comment by tk0miya** [comment] 2021-04-08 13:12
I feel such a reaction is very hysteric and intolerant. If you'd like to get the docutils project better, please join the project and help them. (or please vote to decouple Sphinx development from me also)

**Comment by tk0miya** [comment] 2021-04-08 13:15
I merged #9059 to 3.5.x branch. So closing this now. Please file another issue if you find other troubles. Thanks,

**Closed as completed by tk0miya** 2021-04-08 13:15 UTC
Labels: type:bug, help wanted, html theme

**Comment by return42** [comment] 2021-04-08 13:33
> I feel such a reaction is very hysteric and intolerant.

Apologies my inappropriate comment .. but I'm annoyed that each minor release from docutils caused a cascade of problems.

>  If you'd like to get the docutils project better, please join the project

I had a look years ago ...the access to become team member is unusually difficult .. and personally I have a problem with sourceforge. / I know of some developers who would like to contribute to the project but don't, because the project management is a little bit idiosyncratic.

**Comment by ericholscher** [comment] 2021-04-08 14:20
I think the main goal here is more testing and communication, which is something everyone in the community can help and contribute to. Wearing my Read the Docs hat, we'd love to be able to work with sphinx & docutils to increase testing beta & development across the ecosystem, so hopefully we can catch some of these issues prior to them getting released. 

We can talk more about it over at #9056 perhaps, instead of this old issue, but I think there's some productive work to be done here.

**Comment by andredias** [comment] 2021-04-23 22:02
Disclaimer: I'm the author of [rst2html5](https://pypi.org/project/rst2html5/)

I'd like to suggest using it instead of docutils' rst2html5. It has been stable for years and produces better results than docutils. Please, see its README.
