### ISSUE TITLE
 Cyclic dependencies issue

### ISSUE THREAD

**Issue by linlinlinlin** [sphinx-doc/sphinx#2353] opened 2016-02-25 07:17 UTC
I am using `pipdeptree` to check my package dependency.

I found the output has

```
Warning!!! Cyclic dependencies found:
- sphinx-rtd-theme => sphinx => <ReqPackage("sphinx-rtd-theme")>
- Sphinx => sphinx-rtd-theme => sphinx => <ReqPackage("sphinx-rtd-theme")>
- sphinx => sphinx-rtd-theme => <ReqPackage("sphinx")>
```

**Comment by shimizukawa** [comment] 2016-02-25 07:53
Thanks for your reporting. The issue is fixed by #2087 and it will be shipped on sphinx-1.4 (alpha-1 has been released).

**Closed as completed by shimizukawa** 2016-02-25 07:53 UTC

**Comment by linlinlinlin** [comment] 2016-04-13 02:32
I have been upgrade to the latest version of Sphinx. But still have same issue.
What do I missing?

I am installed these package in my env.

```
Sphinx (1.4.1)
sphinx-rtd-theme (0.1.9)
sphinxcontrib-httpdomain (1.4.0)
```

**Comment by tk0miya** [comment] 2016-04-13 03:48
Really? Could you check it again at clean environment?

In my environment, sphinx-rtd-theme is not installed:

```
$ virtualenv foo
New python executable in /Users/tkomiya/work/tmp/doc/foo/bin/python2.7
Also creating executable in /Users/tkomiya/work/tmp/doc/foo/bin/python
Installing setuptools, pip, wheel...done.
$ . foo/bin/activate
(foo) $ pip list
pip (8.1.1)
setuptools (20.7.0)
wheel (0.29.0)
(foo) $ pip install Sphinx
Collecting Sphinx
  Using cached Sphinx-1.4.1-py2.py3-none-any.whl
Collecting babel!=2.0,>=1.3 (from Sphinx)
  Using cached Babel-2.3.3-py2.py3-none-any.whl
Collecting snowballstemmer>=1.1 (from Sphinx)
  Using cached snowballstemmer-1.2.1-py2.py3-none-any.whl
Collecting six>=1.4 (from Sphinx)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting Pygments>=2.0 (from Sphinx)
  Using cached Pygments-2.1.3-py2.py3-none-any.whl
Collecting docutils>=0.11 (from Sphinx)
Collecting Jinja2>=2.3 (from Sphinx)
  Using cached Jinja2-2.8-py2.py3-none-any.whl
Collecting imagesize (from Sphinx)
  Using cached imagesize-0.7.0-py2.py3-none-any.whl
Collecting alabaster<0.8,>=0.7 (from Sphinx)
  Using cached alabaster-0.7.7-py2.py3-none-any.whl
Collecting pytz>=0a (from babel!=2.0,>=1.3->Sphinx)
  Using cached pytz-2016.3-py2.py3-none-any.whl
Collecting MarkupSafe (from Jinja2>=2.3->Sphinx)
Installing collected packages: pytz, babel, snowballstemmer, six, Pygments, docutils, MarkupSafe, Jinja2, imagesize, alabaster, Sphinx
Successfully installed Jinja2-2.8 MarkupSafe-0.23 Pygments-2.1.3 Sphinx-1.4.1 alabaster-0.7.7 babel-2.3.3 docutils-0.12 imagesize-0.7.0 pytz-2016.3 six-1.10.0 snowballstemmer-1.2.1
(foo) $ pip list
alabaster (0.7.7)
Babel (2.3.3)
docutils (0.12)
imagesize (0.7.0)
Jinja2 (2.8)
MarkupSafe (0.23)
pip (8.1.1)
Pygments (2.1.3)
pytz (2016.3)
setuptools (20.7.0)
six (1.10.0)
snowballstemmer (1.2.1)
Sphinx (1.4.1)
wheel (0.29.0)
(foo) $
```

**Comment by shimizukawa** [comment] 2016-04-13 03:58
please check with `pipdeptree`.

```
$ pip install pipdeptree
```

With sphinx-1.3.6:

```
$ pip install sphinx==1.3.6
Successfully installed ... sphinx-1.3.6

$ pipdeptree -p sphinx
Warning!!! Cyclic dependencies found:
- sphinx-rtd-theme => sphinx => <ReqPackage("sphinx-rtd-theme")>
- sphinx => sphinx-rtd-theme => <ReqPackage("sphinx")>
------------------------------------------------------------------------
Sphinx==1.3.6
  - alabaster [required: >=0.7,<0.8, installed: 0.7.7]
  - babel [required: >=1.3,!=2.0, installed: 2.3.3]
    - pytz [required: >=0a, installed: 2016.3]
  - Pygments [required: >=2.0, installed: 2.1.3]
  - Jinja2 [required: >=2.3, installed: 2.8]
    - MarkupSafe [installed: 0.23]
  - sphinx-rtd-theme [required: >=0.1,<2.0, installed: 0.1.9]
    - sphinx [required: >=1.3, installed: 1.3.6]
      - alabaster [required: >=0.7,<0.8, installed: 0.7.7]
      - babel [required: >=1.3,!=2.0, installed: 2.3.3]
        - pytz [required: >=0a, installed: 2016.3]
      - Pygments [required: >=2.0, installed: 2.1.3]
      - Jinja2 [required: >=2.3, installed: 2.8]
        - MarkupSafe [installed: 0.23]
      - docutils [required: >=0.11, installed: 0.12]
      - six [required: >=1.4, installed: 1.10.0]
      - snowballstemmer [required: >=1.1, installed: 1.2.1]
  - docutils [required: >=0.11, installed: 0.12]
  - six [required: >=1.4, installed: 1.10.0]
  - snowballstemmer [required: >=1.1, installed: 1.2.1]
```

With sphinx-1.4.1:

```
$ pip install sphinx==1.4.1
Successfully installed imagesize-0.7.0 sphinx-1.4.1

$ pipdeptree -p sphinx
Sphinx==1.4.1
  - Jinja2 [required: >=2.3, installed: 2.8]
    - MarkupSafe [installed: 0.23]
  - Pygments [required: >=2.0, installed: 2.1.3]
  - six [required: >=1.4, installed: 1.10.0]
  - alabaster [required: >=0.7,<0.8, installed: 0.7.7]
  - imagesize [installed: 0.7.0]
  - babel [required: >=1.3,!=2.0, installed: 2.3.3]
    - pytz [required: >=0a, installed: 2016.3]
  - snowballstemmer [required: >=1.1, installed: 1.2.1]
  - docutils [required: >=0.11, installed: 0.12]
```

**Comment by linlinlinlin** [comment] 2016-04-13 05:34
Sorry. I found the problem in my environment. 
Because I am using `pew` as virtualenv tool.
It works well with pipdeptree check now.

**Comment by shimizukawa** [comment] 2016-04-13 06:02
Good to know! Thanks ;)
